### ISSUE TITLE
Buf: formatting not working anymore

### ISSUE THREAD

**Issue by Ganitzsh** [jose-elias-alvarez/null-ls.nvim#1002]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.7.2

### Operating System

macOS 12.4

### Minimal config

```
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir
if on_windows then
    temp_dir = vim.loop.os_getenv("TEMP")
else
    temp_dir = "/tmp"
end

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = {
	    require("null-ls").builtins.formatting.buf
        },
        debug = true,
    })
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "jose-elias-alvarez/null-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end
```

You also need to install https://github.com/bufbuild/buf

### Steps to reproduce

Open the following file:
```
syntax = "proto3";

package straudio.v1;

message AudioChunk {
     string name = 1;

  bytes data = 2;
}
```

run `:lua vim.lsp.buf.formatting()`

### Expected behavior

The file should get formatted 

### Actual behavior

Nothing happens

### Debug log

```
[TRACE Thu Aug 11 08:48:16 2022] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method textDocument/formatting
[TRACE Thu Aug 11 08:48:16 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_FORMATTING
[DEBUG Thu Aug 11 08:48:16 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:346: spawning command "buf" at /Users/<me>/Dev/audio-streamer with args { "format", "-w", "/tmp/null-ls_SP9h7H.proto" }
[TRACE Thu Aug 11 08:48:16 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:217: error output: Failure: failed to enumerate module files: open /private/tmp/.vnc-vncservice: permission denied

[TRACE Thu Aug 11 08:48:16 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:218: output: nil
[TRACE Thu Aug 11 08:48:16 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:222: ignoring stderr due to generator options
```

Not sure why it's trying to access a vnc file which is nowhere near the file I'm editing

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
This works for me, and I don't think it's an issue with null-ls. I have no idea what this error message means, but its presence is what's causing formatting to fail:

```
Failure: failed to enumerate module files: open /private/tmp/.vnc-vncservice: permission denied
```

Do you get the same error when you run the formatter from the command line? Either way I think you'll need to look into this on the `buf` side.

**Comment by Ganitzsh** [comment]
I've tried to run `buf` directly and it works fine. It worked fine in nvim until a moth ago or so. I checked other logs and I don't see anything wrong there. I've tried many configurations, and it doesn't fix the problem, I've looked everywhere and I'm running out of ideas.

**Comment by jose-elias-alvarez** [comment]
I'll mention that [looking at the commit history](https://github.com/jose-elias-alvarez/null-ls.nvim/commits/main/lua/null-ls/builtins/formatting/buf.lua), we haven't made any changes that should affect this (the only change we've made to the built-in definition was one that made it work in the first place, and there haven't been any changes to null-ls core in this area).

**Comment by Ganitzsh** [comment]
Thanks for the details! So according to `buf`'s maintainer the issue comes from the fact that `buf` attempts to read other proto files at the root of the target hence the open error. (https://github.com/bufbuild/buf/issues/1334#issuecomment-1213539045)

Is it possible to override the temp file location for a specific generator directly from the config? It'd allow me to work with `buf` while the mentioned issue (https://github.com/bufbuild/buf/issues/1035) is worked on?

**Comment by jose-elias-alvarez** [comment]
It's not currently possible to override the temporary directory, though from an architectural point of view it shouldn't be that hard to do so.

I don't plan on working on this myself, since I think having to use a temp file for formatters and linters is an unpleasant workaround, and if there's any chance of getting `stdin` support upstream, I think that's the way to go. I'm happy to review and consider merging a PR that doesn't add too much complexity in this area.

**Comment by Ganitzsh** [comment]
Okay thanks! I'll close this one as it is mostly resolved.

**Comment by kyle-mccarthy** [comment]
@Ganitzsh I was able to get this working correctly with the following:

```lua
null_ls.builtins.formatting.buf.with(
  {
    extra_args = function(params)
      local scan = require("plenary.scandir")

      local paths = scan.scan_dir(params.root, {search_pattern = "buf.yaml"})
      local config = paths[1]

      if config then
        return {"--config=" .. config, "--path=" .. params.bufname, "-o" .. params.temp_path}
      end

      return {}
    end,
    args = {"format"}
  }
)
```

@jose-elias-alvarez I can open a PR if you want. One thing I wasn't sure about is if to_temp_file and from_temp_file could be omitted and the bufname could be used for the output path. Also, when -o or -w aren't specified, it does write the output to stdout, can null-ls redirect it to the buffer?

**Comment by jose-elias-alvarez** [comment]
@kyle-mccarthy This seems like a reasonable workaround for now, but I would rather wait until we merge #1021.
