### ISSUE TITLE
Disable diagnosis in node_modules and git ignored files

### ISSUE THREAD

**Issue by LoganAtCrypto** [jose-elias-alvarez/null-ls.nvim#1010]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.7.2

### Operating System

MacBookPro18,1   Chip:	Apple M1 

### Minimal config
```lua
local null_ls_status_ok, null_ls = pcall(require, "null-ls")
if not null_ls_status_ok then
	return
end

-- https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md
local formatting = null_ls.builtins.formatting
local diagnostics = null_ls.builtins.diagnostics
local code_actions = null_ls.builtins.code_actions

-- https://github.com/prettier-solidity/prettier-plugin-solidity
null_ls.setup({
	debug = false,
	sources = {
		-- lua
		formatting.stylua,
		-- diagnostics.luacheck,
		-- python
		formatting.black.with({ extra_args = { "--fast" } }),
		diagnostics.flake8,
		-- javascript/typescript
		formatting.prettierd,
		code_actions.eslint_d,
		diagnostics.eslint_d.with({
			diagnostics_format = "[eslint] #{m}\n(#{c})",
		}),
		-- rust
		formatting.rustfmt,
		-- spell
		-- diagnostics.cspell,
		diagnostics.misspell,
	},
})
```
### Steps to reproduce

1. open a javascript project
2. go to definition of `ch` in `import ch from 'child_process`
3. The Diagnosis errors are showing up in the `child_process.d.ts` file

![Screen Shot 2022-08-15 at 13 23 10](https://user-images.githubusercontent.com/80801525/184581837-4f4504f2-308c-496c-9ec5-44203a4dd916.jpg)

### Expected behavior

should disable Diagnosis in `node_modules` files and git ignored files

### Actual behavior

Diagnosis are enabled in `node_modules` files and git ignored files

### Debug log

none

### Help

No

### Implementation help

none

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by LoganAtCrypto** [comment]
the same thing also happen in other languages, such as rust.

**Comment by jose-elias-alvarez** [comment]
There's no way that null-ls can know that it shouldn't create diagnostics for files listed in `.gitignore` or special directories like `node_modules`. All it's doing is spawning the underlying process and capturing its output, so if `eslint $FILE` generates diagnostics, then null-ls will pick those up and show them in Neovim. In this case, you'll have to configure those entries in a `.eslintignore` file, which (at least on my end) works as expected.

If you're running into a case where `eslint $FILE` doesn't generate diagnostics but null-ls does, please put together a minimal project that I can use to replicate the issue and investigate further.

**Comment by LoganAtCrypto** [comment]
Thank @jose-elias-alvarez for your reply! it works after i updated `.eslintignore`.

**Comment by ehaynes99** [comment]
Debatable whether a call like this is too expensive (~2.5ms on my machine), but this works well for me. This returns false for any file that is git ignored. The [-C option](https://git-scm.com/docs/git#Documentation/git.txt--Cltpathgt) makes git run as though that directory is the cwd.
* if the file is not in a git repo, the `output` value will contain error text
* if the file is tracked, the `output` value will be an empty string
* if the file is in a git repo but is ignored, the `output` value will be the filename, so negating that comparison returns makes `should_attach` return `false`.

```lua
null_ls.setup({
  -- ...
  should_attach = function(bufnr)
    local name = vim.api.nvim_buf_get_name(bufnr)
    local dir = vim.fs.dirname(name)
    local filename = vim.fs.basename(name)

    local command = string.format('git -C %s check-ignore %s', dir, filename)
    local output = vim.fn.trim(vim.fn.system(command))

    return not (output == filename)
  end,
})
```

**Comment by jose-elias-alvarez** [comment]
> It's debatable whether a call like this is too expensive, but this works well for me.

This is a pretty heavy-duty solution - it's about as accurate as we can get, but since `system()` is blocking, it could indeed be expensive. Thanks for posting this, though - it's great to have as a reference.

**Comment by illia-danko** [comment]
@ehaynes99 solution works for me. As I'm using my setup, for some reason `node_modules/` inside .eslintignore is not working, where plain cli `eslint .` does a job, which is strange. Probably some issue with a project path...
