### ISSUE TITLE
At startup getting error: attempt to index a boolean value

### ISSUE THREAD

**Issue by hesseltuinhof** [jose-elias-alvarez/null-ls.nvim#103]
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.5.0

### Steps to reproduce

I'm using paq as my plugin manager. Please consider the following minimal config:

```lua
local install_path = vim.fn.stdpath("data") .. "/site/pack/paqs/start/paq-nvim"

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.cmd("!git clone --depth 1 https://github.com/savq/paq-nvim.git " .. install_path)
end

-- load Paq
vim.cmd("packadd paq-nvim")

-- load plugins
require("paq"){
    "savq/paq-nvim";  -- Let Paq manage itself

    {"nvim-treesitter/nvim-treesitter", run="TSUpdate"};
    "neovim/nvim-lspconfig";
    "nvim-lua/plenary.nvim";

    "jose-elias-alvarez/null-ls.nvim";
}


vim.o.completeopt = "menuone,noselect"

local nvim_lsp = require("lspconfig")

local on_attach = function(client, bufnr)
    -- Disable LSP providing formatting
    client.resolved_capabilities.document_formatting = false
end

require("null-ls").config({
    debug = true,
    sources = {
        require("null-ls").builtins.formatting.yapf,
    }
})
require("lspconfig")["null-ls"].setup({
    on_attach = on_attach
})


local servers = { "pyright", "gopls", "julials", "texlab" }
for _, lsp in ipairs(servers) do
    nvim_lsp[lsp].setup {
        on_attach = on_attach,
        flags = {
            debounce_text_changes = 150,
        }
    }
end
```

### Expected behavior

At least being able to start Neovim without any errors.

### Actual behavior

At startup I get the following error:

```
Error detected while processing /home/peter/dev/nvim/init.lua:
E5113: Error while calling lua chunk: /home/peter/.config/nvim/init.lua:31: attempt to index a boolean value
```

### Debug log

Same error as in the *Actual behavior* section.

### Help

No

**Comment by jose-elias-alvarez** [comment]
I can't replicate this, and I don't think it's an issue on our end. Do you have another file anywhere in your config called `null-ls.lua`? The error you're getting makes me suspect that you're loading another module called `null-ls`, and since that module doesn't explicitly return anything, it returns `true`, which would explain `attempt to index a boolean value`.

**Comment by hesseltuinhof** [comment]
> Do you have another file anywhere in your config called null-ls.lua ?

:man_facepalming: 

(of course, I had an empty null-ls.lua flying around...)
