### ISSUE TITLE
Minimal config fails to properly run packer sync

### ISSUE THREAD

**Issue by skwde** [jose-elias-alvarez/null-ls.nvim#1041]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.7.2

### Operating System

centos7, macOS BigSur

### Minimal config

Your minimal config as in <https://raw.githubusercontent.com/jose-elias-alvarez/null-ls.nvim/main/scripts/minimal_init.lua>.

### Steps to reproduce

```sh
mkdir test-vim; cd test-vim
curl -fLO https://raw.githubusercontent.com/jose-elias-alvarez/null-ls.nvim/main/scripts/minimal_init.lua
nvim --clean -u minimal_init.lua
```

### Expected behavior

I can properly open nvim with the minimal config

### Actual behavior

It reports the error

```
Error executing vim.schedule lua callback: ...ack/packer/start/packer.nvim/lua/packer/plugin_utils.lua:87: Vim(call):E482
: Can't open file /path/to/manifest for writing: no such file or directory
stack traceback:
        [C]: in function 'cmd'
        ...ack/packer/start/packer.nvim/lua/packer/plugin_utils.lua:87: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Debug log

I don't get that far...

### Help

Yes, but I don't know how to start. I would need guidance

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
I also see this occasionally. I think it happens when [this logic](https://github.com/neovim/neovim/blob/79a194a27844e34112a9befe854df98df06159d5/runtime/plugin/rplugin.vim#L4) fails to resolve the manifest path correctly, making it default to a nonexistent fallback. Could you try #1061 and see if that helps?
