### ISSUE TITLE
Diagnostics shift text area to the right

### ISSUE THREAD

**Issue by tabcat** [jose-elias-alvarez/null-ls.nvim#1059]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

It would be nice if either the text area was always shifted to the right to fit the red E or if the red E could be disabled.

The undesirable behavior that this would be taking care of is the transition between the diagnostics being shown and when they are not after they have been fixed.
It's distracting to see all the text shift left or right when the diagnostics either pop up or go away. Just me?

### Help

No

### Implementation help

If this is simple to take care of I might be interested in making a PR but know 0 Lua.

**Comment by jose-elias-alvarez** [comment]
I'm not sure I fully understand the problem, but try checking out `:help signcolumn`. If I understand correctly, `vim.opt.signcolumn = "yes"` should take care of this.
