### ISSUE TITLE
Tidy diagnostics ignored because of system language

### ISSUE THREAD

**Issue by VPerrollaz** [jose-elias-alvarez/null-ls.nvim#1064]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.7.2

### Operating System

linux-mx

### Minimal config

Not a problem with the config.
See at the bottom for description and solution.

### Steps to reproduce

Won't reproduce unless the system is in french.

### Expected behavior

Diagnostics showing.

### Actual behavior

No diagnostic showing.

### Debug log

empty

### Help

Yes

### Implementation help

Actually tidy has language parameter to switch the output templates, see the difference on  some irrelevant file

```
$ tidy -quiet -errors index.html
Ligne: 50 Col: 11 - Avertissement:insertion implicite de <p>
Ligne: 50 Col: 11 - Avertissement:réduction des <p> vides

$ tidy -quiet -errors -lang en index.html
line 50 column 11 - Warning: inserting implicit <p>
line 50 column 11 - Warning: trimming empty <p>
```

So the parameters "-lang" "en" just need to be added in the file null-ls/builtins/diagnostics/tidy.lua
to the table common_args

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
Right, I guessed that changing the output format might cause unexpected issues like this. Mind putting in a PR?

**Comment by VPerrollaz** [comment]
Submitted #1065.
I checked on some files that the diagnostics now appear.
