### ISSUE TITLE
Remove spell from configure null-ls docs

### ISSUE THREAD

**Issue by alextes** [jose-elias-alvarez/null-ls.nvim#1096]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

When new users, such as myself, start using nvim (or my case migrate from vim) there's a lot going on.

You're copy pasting a lot to get basic functionality for coding work.

When pasting the example null-ls config, you paste in _spell_ as a source. As a coder, you may then spend some time rather annoyed at the bad suggestions `nvim-cmp` is throwing your way, and it may take a while to figure out null-ls hooks into the language server, which hooks into nvim-cmp, which gives text suggestions that most coders don't need.

This doesn't matter much, null-ls is still great when set up properly, but it may give people a slightly more pleasant and less confusing or frustrating experience setting up nvim, lsp, cmp, and null-ls for the first time.

What do others think? (:

Here are two threads of people running into the same issue:
* https://www.reddit.com/r/neovim/comments/wf5dsw/nvimcmplsp_how_to_remove_text_results_from/
* https://www.reddit.com/r/neovim/comments/v2ifpb/text_fields_on_lsp_auto_completion/

Thanks for a great plugin 💛 !

### Help

Yes

**Comment by jose-elias-alvarez** [comment]
I think that this is more of a lesson about users copy-pasting things from READMEs without fully understanding them, but yes, if this issue has come up multiple times, I'd be open to merging a PR that removes `spell` from the documentation.
