### ISSUE TITLE
Remove external dependencies from `built-in` `commitlint`.

### ISSUE THREAD

**Issue by kaiuri** [jose-elias-alvarez/null-ls.nvim#1097]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

`null-ls.nvim` has `commitlint` bultin. It does, however, have some external dependencies _i.e._ `@commitlint/config-conventional` and `commitlint-format-json`. Since `commitlint` can also read the current buffer with the `-e` option, provided with a config file `without` a `"parserPreset"` option. Although the output isn't `.json` we could parse it. 

Should we provide such a feature? It would make the `builtin` rely solely on `@commitlint/cli`.

### Help

Yes

### Implementation help

I need some help on how to write a custom `generator_opts.on_output` function without helpers. What type should this function return?

**Comment by jose-elias-alvarez** [comment]
Yes, this would be a welcome improvement. Check out [codespell](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting/codespell.lua) for an example of a source that parses output without helpers, though depending on the output format, [`from_lines`](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/cdef04dfad2d1a6d76f596ac63600e7430baaabe/lua/null-ls/helpers/diagnostics.lua#L92) may be useful here, too.

**Comment by kaiuri** [comment]
### Update

So, I composed a function that outputs valid `vim.diagnostics`, taking

```
⧗   input: uri
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

and outputting

```
{ {
    code = "[subject-empty]",
    col = 1,
    filename = "",
    message = "subject may not be empty ",
    row = 1,
    severity = 1,
    source = "commitlint"
  }, {
    code = "[type-empty]",
    col = 1,
    filename = "",
    message = "type may not be empty ",
    row = 1,
    severity = 1,
    source = "commitlint"
  } }
```

#### The functions

```lua
  ---@param line string
  ---@return integer|nil
  local function get_severity(line)
      local severities = {
          ['✖'] = vim.diagnostic.severity.ERROR,
          ['⚠'] = vim.diagnostic.severity.WARN,
          -- ['ⓘ'] = vim.diagnostic.severity.INFO -- this would be extra output if it was to be captured
      }
      for pattern, severity in pairs(severities) do
          local pos = { vim.regex("^" .. pattern):match_str(line) }
          if pos ~= nil then return severity end
      end
  end
  ```

```lua
  ---@return Diagnostic|nil
  local function on_output(line)
      -- ↓ makes sure we only parse lines that have actual error messages
      local valid_line = line:match(']$') and line
      if not valid_line then return nil
      else
          local severity = get_severity(valid_line)
          return severity
              and {
                  row = 1, -- `commitlint` does not output positions without an external `format` library
                  col = 1, -- ↑
                  source = "commitlint",
                  message = valid_line:match('%s%s%s(.*)%[.*'), -- gets only the message but not which rule
                  code = valid_line:match('%[.*%]'), -- gets which rule
                  severity = severity,
                  filename = ""
              } or nil
      end
  end
```

### Issues

`commitlint`'s `-e` file needs changes to be written before it can consider those. Piping the input was more straightforward, _e.g._

```lua
vim.fn.system((
[[#!/usr/bin/bash
cat <<EOF | commitlint -g ~/.commitlintrc.json
%s
EOF
]]):format(current_buffer_contents))
```

Any suggestions? Should the `builtin` _commitlint_ source be rewritten or an alternative one be added?
