### ISSUE TITLE
Customize diagnostics notifications

### ISSUE THREAD

**Issue by bandithedoge** [jose-elias-alvarez/null-ls.nvim#1098]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I have an LSP integration with nvim-notify set up and it works great, however, every time I edit a file with any diagnostic sources attached, I get a lot of diagnostic notifications at nearly every keystroke. Would it be possible to disable those notifications but keep the ones for errors, formatting and LSP progress?

### Help

No

**Comment by jose-elias-alvarez** [comment]
null-ls tries to behave as much like an actual LSP server as possible, and I’m not aware of any LSP servers that allow configuring progress notifications like this. Instead, they rely on the client or consumer to handle notifications as desired, and I think that’s the right approach here, too. 

I have no idea how nvim-notify works, but for example, this is one way to filter out messages using the default `vim.notify` handler:

```lua
local notify = vim.notify
vim.notify = function(message, …)
    if message:find(“message content I want to filter out goes here”) then
        return
    end
    notify(message, …)
end
