### ISSUE TITLE
E13: File exists (add ! to override)

### ISSUE THREAD

**Issue by henrychea** [jose-elias-alvarez/null-ls.nvim#1102]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.8.0-dev-812-gd1fb0dd8b

### Operating System

MacBook Pro (13-inch, M1, 2020) 12.5.1

### Minimal config

```
-- Use Null-Ls for formatting and diagnostics
local nstatus, null_ls = pcall(require, "null-ls")
if not nstatus then
	print("Null-ls not found")
	return
end

-- register any number of sources simultaneously
local my_sources = {
	-- Prettier formatter as daemon
	null_ls.builtins.formatting.prettierd,
	-- Eslint
	null_ls.builtins.diagnostics.eslint.with({
		diagnostics_format = "[eslint] #{m}\n(#{c})",
	}),
	-- Fish shell linter
	null_ls.builtins.diagnostics.fish,
	-- Prisma Object
	null_ls.builtins.formatting.prismaFmt,
	-- Ruby Rubocop
	null_ls.builtins.formatting.rubocop,
	null_ls.builtins.diagnostics.rubocop,
	-- Python black and pylint
	null_ls.builtins.formatting.black,
	null_ls.builtins.diagnostics.pylint,
	-- Lua formatter
	null_ls.builtins.formatting.stylua,
}

null_ls.setup({
	sources = my_sources,
})
```

### Steps to reproduce

Set up null-ls with some builtin linters and formatters.

### Expected behavior

Able to save normally

### Actual behavior

Always asks to overwrite on save, however if I remove the `null_ls.setup({})` function, there is no errors

### Debug log

[ERROR Thu Aug 11 19:28:05 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:180: command stylua is not executable (make sure it's installed and on your $PATH)

I do have stylua installed via homebrew

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by henrychea** [comment]
I am also able to get this error when opening a single .js file

![image](https://user-images.githubusercontent.com/40254517/189991011-6efbc2e9-7a52-41d5-b254-7e73d88624bb.png)

**Comment by jose-elias-alvarez** [comment]
You need to update to the latest Neovim master.

**Comment by henrychea** [comment]
Thanks for the tip, I've updated but now I got this new warning
```
[null-ls] failed to run generator: ...site/pack/packer/start/null-ls.nvim/lua/null-ls/loop.lua:157: failed to spawn command eslint: EACCES: permission denied
```

**Comment by jose-elias-alvarez** [comment]
The error message implies that the user who started the `neovim` process doesn’t have access to your global `eslint` executable. Can you open another issue and provide a full minimal reproduction?

**Comment by jose-elias-alvarez** [comment]
Or you can Google "npm EACCES: permission denied" and get more information, since I suspect that this is ultimately an issue with your local environment.

**Comment by ryanbas21** [comment]
FWIW, I am running into this issue as well. If I use any `builtins` in my setup, I get a E13 File Exists error when saving a file. I commented everything out of my config and slowly back and this was the cause. I have not figured out a solution. 

This happens on two computers. Even when I have typescript installed globally, and can go into a terminal and type `tsc`, null_ls seems to have an issue with it. (example) this happens in lua, typescript, any file that tries to load null_ls.

Both computers i am an admin on and both computers i've installed the package I am trying to use. I am on latest neovim HEAD and both computers are on mac OSX but i'm sure slightly different versions. NullLS logs and info don't provide any details into the failure.
Log: 
```
[TRACE Wed Sep 14 21:45:51 2022] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:110: starting null-ls client
[TRACE Wed Sep 14 21:46:49 2022] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:110: starting null-ls client
[TRACE Wed Sep 14 21:47:11 2022] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:110: starting null-ls client
[TRACE Wed Sep 14 22:08:07 2022] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:110: starting null-ls client
[TRACE Wed Sep 14 22:08:17 2022] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:110: starting null-ls client
[TRACE Wed Sep 14 22:15:11 2022] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:110: starting null-ls client
[TRACE Wed Sep 14 22:15:47 2022] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:110: starting null-ls client
[TRACE Thu Sep 15 06:22:23 2022] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:110: starting null-ls client
```

This happens when no sources are attached as well.

**Comment by henrychea** [comment]
Sorry I was a bit busy last two days, to fix this you need set permissions to your npm directory, something like `sudo chown -R $USER ~/.npm`

**Comment by jose-elias-alvarez** [comment]
@ryanbas21 There are two separate errors: the E13 error should be fixed by updating to the latest Neovim master, and the spawn failure error (which is the result of a different commit) requires fixing your permissions locally. It sounds like you are running into the former, but if you are on 0.8 and updating Neovim doesn’t take care of it, please open a separate issue.

**Comment by ryanbas21** [comment]
I had to completely uninstall neovim and reinstall.

**Comment by Pilotager** [comment]
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/49061023/190864816-d7e0500b-35b3-4811-8787-e554991425e5.png">


Hello, I also reported the problem of permissions, but I set permissions for npm

**Comment by jose-elias-alvarez** [comment]
The permissions problem is a separate issue, and one that I strongly believe is ultimately an issue with your local environment, not something we can act on here. If you are sure that it's a null-ls issue and can put together a full reproduction so I can investigate, please open another issue.
