### ISSUE TITLE
Insert mode lag?

### ISSUE THREAD

**Issue by jose-elias-alvarez** [jose-elias-alvarez/null-ls.nvim#111]
I've seen a few issues on LunarVim's repo that seem to be related to insert mode lag from null-ls diagnostics, such as [this one](https://github.com/LunarVim/LunarVim/issues/1223), which seems to have been solved by disabling Lua linting. On my end (using an underpowered Mac Mini currently), I haven't experienced any lag, even with slow sources like ESLint, and we haven't had any issues reported here. 

I did notice that attempting to spawn a command that didn't exist / wasn't on the user's `$PATH` caused lag, so in 6acbccff4214988aa6855b0fd9c24ad4397f6c62, I added a simple check to make sure the command is executable and also made it so the generator wouldn't run again if it threw an error. I wonder if these issues are related, but from what I understand, diagnostics have to be explicitly enabled in LunarVim, right?

Since I can't replicate these issues, I'd like to know more and see if they're still occurring, and I'm very open to any suggestions / fixes to improve performance. We're currently using the `debounce_text_changes` flag, which makes a big difference, but one idea is to simply avoid running generators in insert mode and send a synthetic `didChange` even when the user exits insert mode. 

cc @Tastyep @kylo252 @ other LunarVim people

**Comment by Tastyep** [comment]
On my side, I never had any performance issue, and my laptop isn't a beast either.
We also check that the builtins are executable, so I don't think it can be related.
I would definitely be in favor of running generators when leaving insert mode :+1:

**Comment by gegoune** [comment]
Forgive me my ignorance, but does null-ls use native handlers to display diagnostics? If so it should use user's value of `update_in_insert` from `vim.lsp.handlers['textDocument/publishDiagnostics']`.

**Comment by jose-elias-alvarez** [comment]
@Tastyep Thanks for the info! It must have been another issue, then, but it does seem to have been solved by disabling the linter.

@gegoune This came as a surprise to me too, but I recently learned that `update_in_insert` only controls the *display* of diagnostics and doesn't affect when Neovim sends `textDocument/didChange` notifications (which is what triggers null-ls updates). I can't remember where I first saw it, but [this post](https://www.reddit.com/r/neovim/comments/o0katt/update_in_insert_does_not_seems_to_work_correctly/) confirms it, and I tested it in null-ls with a simple counter and saw that it does indeed send notifications regardless of this option. 

A tentative idea is to store the notifications in state when in insert mode, then actually run the generators on `InsertLeave`. This wouldn't be too complex, since we can index the notification params by URI, and it would more or less eliminate the possibility that null-ls is causing insert mode lag (though it would be nice to have confirmation that it solves the issue users seem to be having).

**Comment by jose-elias-alvarez** [comment]
For reference: in #136 I tried an autocommand-based solution to avoid updating diagnostics in insert mode but found it problematic. I'm still open to other solutions, but since I don't have these issues locally, there's only so much I can do. 

The fact that I haven't experienced slowdown with *any* linter, no matter what I do, leads me to believe that users having these issues are using very slow setups. Raising the value of `debounce` is an option, but when just running a command causes system-wide slowdown, providing an LSP-like experience with updates on change may be out of reach.

**Comment by jose-elias-alvarez** [comment]
Going to close this for now, since we don't have any reports of the behavior here. Again, I'm happy to receive suggestions to improve performance or more detailed reports of issues so I can diagnose and reproduce what's going on.
