### ISSUE TITLE
Add diagnostics to npm-groovy-lint builtin

### ISSUE THREAD

**Issue by BonaBeavis** [jose-elias-alvarez/null-ls.nvim#1121]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

[Npm-groovy-lint](https://github.com/nvuillam/npm-groovy-lint) does also output diagnostics, which null-ls could use.

### Help

No

**Comment by joshzcold** [comment]
Closed by https://github.com/jose-elias-alvarez/null-ls.nvim/pull/1418
