### ISSUE TITLE
HLint Support

### ISSUE THREAD

**Issue by colin-heffernan** [jose-elias-alvarez/null-ls.nvim#1139]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

HLint gives source code suggestions for Haskell. I think it would fit under the Diagnostics section of Null-LS.

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

How would I test my contribution? I may have other questions along the way, as I've only ever contributed to one other project before.

**Comment by colin-heffernan** [comment]
It appears that HLint is a part of Haskell Language Server now. I'm not sure how necessary this is, so I'm closing it for now. If someone else wants it, though, I'm still willing to try to implement it.

**Comment by jose-elias-alvarez** [comment]
Agreed that the LSP solution is best, but thanks for opening the issue in case there's a demand for it in the future.
