### ISSUE TITLE
Being able to pass a function to `env` option when using `builtin.with({...})`.

### ISSUE THREAD

**Issue by UserIsntAvailable** [jose-elias-alvarez/null-ls.nvim#1151]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

The title says it all. I basically would like to have the same behavior that `args` and `extra_args` has, but with the `env` option.

### Help

Yes

### Implementation help

I went ahead, and read the [PR](https://github.com/jose-elias-alvarez/null-ls.nvim/pull/537) that implemented injecting environment variables. As far I can see, the only code changes that will need to be made will be at [generator_factory.lua](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/helpers/generator_factory.lua) and just implement something like:

```lua
-- Pretty much same code that `args`.

local resolved_env = env or {}
resolved_env = type(resolved_env) == "function" and resolved_env(params) or env

local spawn_opts = {
    env = resolved_env,
    ...
}
```

Of course, I will need to allow functions on the validate call, add tests, and update the docs, but I want to know if there is something else that will need to be changed. Thanks in advance.

**Comment by jose-elias-alvarez** [comment]
Seems fine, I can't think of anything your approach is missing (and if there is I'm sure it'll come up when writing the PR).
