### ISSUE TITLE
Error output: can't find the path , when using clang_format.

### ISSUE THREAD

**Issue by Muffeter** [jose-elias-alvarez/null-ls.nvim#1153]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

Nvim v0.8.0

### Operating System

windows11

### Minimal config

```Lua
local present, null_ls = pcall(require, "null-ls")

if not present then
   return
end

local b = null_ls.builtins

//custom.plugins.null-ls.lua

local sources = {

  b.formatting.clang_format,
}

null_ls.setup {
   debug = true,
   sources = sources,
}
```

### Steps to reproduce

<CR>fm

### Expected behavior

Complete the formatting on cpp files.

### Actual behavior

Stuck at fomatting 0%.
And there's nothing happened.
![image](https://user-images.githubusercontent.com/36598604/193780370-6140aaae-ab84-475a-ae02-c056f9fe63b2.png)

### Debug log

22/10/4 16:55:34] ...ta\site\pack\packer\opt\null-ls.nvim/lua\null-ls\rpc.lua:123: received LSP request for method textDocument/formatting
[TRACE 2022/10/4 16:55:34] ...\pack\packer\opt\null-ls.nvim/lua\null-ls\generators.lua:21: running generators for method NULL_LS_FORMATTING
[DEBUG 2022/10/4 16:55:34] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:321: spawning command "clang-format" at C:\Users\ALIENWARE\AppData\Local\nvim with args { "-assume-filename", "C:\\Users\\ALIENWARE\\AppData\\Local\\nvim\\lua\\custom\\plugins\\1.cpp" }
[TRACE 2022/10/4 16:55:34] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:209: error output: 系统找不到指定的路径。

[TRACE 2022/10/4 16:55:34] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:210: output: nil
[TRACE 2022/10/4 16:55:34] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:214: ignoring stderr due to generator options
[TRACE 2022/10/4 17:05:03] ...ta\site\pack\packer\opt\null-ls.nvim/lua\null-ls\rpc.lua:123: received LSP request for method textDocument/formatting
[TRACE 2022/10/4 17:05:03] ...\pack\packer\opt\null-ls.nvim/lua\null-ls\generators.lua:21: running generators for method NULL_LS_FORMATTING
[DEBUG 2022/10/4 17:05:03] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:321: spawning command "clang-format" at C:\Users\ALIENWARE\AppData\Local\nvim with args { "-assume-filename", "C:\\Users\\ALIENWARE\\AppData\\Local\\nvim\\lua\\custom\\plugins\\1.cpp" }
[TRACE 2022/10/4 17:05:03] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:209: error output: 系统找不到指定的路径。

[TRACE 2022/10/4 17:05:03] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:210: output: nil
[TRACE 2022/10/4 17:05:03] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:214: ignoring stderr due to generator options
[TRACE 2022/10/4 17:05:07] ...ta\site\pack\packer\opt\null-ls.nvim/lua\null-ls\rpc.lua:148: received LSP notification for method textDocument/didChange
[TRACE 2022/10/4 17:05:07] ...\pack\packer\opt\null-ls.nvim/lua\null-ls\generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG 2022/10/4 17:05:07] ...\pack\packer\opt\null-ls.nvim/lua\null-ls\generators.lua:24: no generators available
[TRACE 2022/10/4 17:05:07] ...ta\site\pack\packer\opt\null-ls.nvim/lua\null-ls\rpc.lua:148: received LSP notification for method textDocument/didSave
[TRACE 2022/10/4 17:05:07] ...\pack\packer\opt\null-ls.nvim/lua\null-ls\generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_SAVE
[DEBUG 2022/10/4 17:05:07] ...\pack\packer\opt\null-ls.nvim/lua\null-ls\generators.lua:24: no generators available
[TRACE 2022/10/4 17:05:09] ...ta\site\pack\packer\opt\null-ls.nvim/lua\null-ls\rpc.lua:123: received LSP request for method textDocument/formatting
[TRACE 2022/10/4 17:05:09] ...\pack\packer\opt\null-ls.nvim/lua\null-ls\generators.lua:21: running generators for method NULL_LS_FORMATTING
[DEBUG 2022/10/4 17:05:09] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:321: spawning command "clang-format" at C:\Users\ALIENWARE\AppData\Local\nvim with args { "-assume-filename", "C:\\Users\\ALIENWARE\\AppData\\Local\\nvim\\lua\\custom\\plugins\\1.cpp" }
[TRACE 2022/10/4 17:05:09] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:209: error output: 系统找不到指定的路径。

[TRACE 2022/10/4 17:05:09] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:210: output: nil
[TRACE 2022/10/4 17:05:09] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:214: ignoring stderr due to generator options
[TRACE 2022/10/4 17:05:10] ...ta\site\pack\packer\opt\null-ls.nvim/lua\null-ls\rpc.lua:123: received LSP request for method textDocument/formatting
[TRACE 2022/10/4 17:05:10] ...\pack\packer\opt\null-ls.nvim/lua\null-ls\generators.lua:21: running generators for method NULL_LS_FORMATTING
[DEBUG 2022/10/4 17:05:10] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:321: spawning command "clang-format" at C:\Users\ALIENWARE\AppData\Local\nvim with args { "-assume-filename", "C:\\Users\\ALIENWARE\\AppData\\Local\\nvim\\lua\\custom\\plugins\\1.cpp" }
[TRACE 2022/10/4 17:05:10] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:209: error output: 系统找不到指定的路径。

[TRACE 2022/10/4 17:05:10] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:210: output: nil
[TRACE 2022/10/4 17:05:10] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:214: ignoring stderr due to generator options
[TRACE 2022/10/4 17:05:20] ...ta\site\pack\packer\opt\null-ls.nvim/lua\null-ls\rpc.lua:148: received LSP notification for method textDocument/didChange
[TRACE 2022/10/4 17:05:20] ...\pack\packer\opt\null-ls.nvim/lua\null-ls\generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG 2022/10/4 17:05:20] ...\pack\packer\opt\null-ls.nvim/lua\null-ls\generators.lua:24: no generators available
[TRACE 2022/10/4 17:05:26] ...ta\site\pack\packer\opt\null-ls.nvim/lua\null-ls\rpc.lua:123: received LSP request for method textDocument/completion
[TRACE 2022/10/4 17:05:26] ...\pack\packer\opt\null-ls.nvim/lua\null-ls\generators.lua:21: running generators for method NULL_LS_COMPLETION
[DEBUG 2022/10/4 17:05:26] ...\pack\packer\opt\null-ls.nvim/lua\null-ls\generators.lua:24: no generators available
[DEBUG 2022/10/4 17:05:26] ...\pack\packer\opt\null-ls.nvim/lua\null-ls\completion.lua:16: received no completion results from generators
[TRACE 2022/10/4 17:05:27] ...ta\site\pack\packer\opt\null-ls.nvim/lua\null-ls\rpc.lua:148: received LSP notification for method textDocument/didChange
[TRACE 2022/10/4 17:05:27] ...\pack\packer\opt\null-ls.nvim/lua\null-ls\generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG 2022/10/4 17:05:27] ...\pack\packer\opt\null-ls.nvim/lua\null-ls\generators.lua:24: no generators available
[TRACE 2022/10/4 17:05:27] ...ta\site\pack\packer\opt\null-ls.nvim/lua\null-ls\rpc.lua:148: received LSP notification for method textDocument/didChange
[TRACE 2022/10/4 17:05:27] ...\pack\packer\opt\null-ls.nvim/lua\null-ls\generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG 2022/10/4 17:05:27] ...\pack\packer\opt\null-ls.nvim/lua\null-ls\generators.lua:24: no generators available
[TRACE 2022/10/4 17:05:30] ...ta\site\pack\packer\opt\null-ls.nvim/lua\null-ls\rpc.lua:123: received LSP request for method textDocument/formatting
[TRACE 2022/10/4 17:05:30] ...\pack\packer\opt\null-ls.nvim/lua\null-ls\generators.lua:21: running generators for method NULL_LS_FORMATTING
[DEBUG 2022/10/4 17:05:30] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:321: spawning command "clang-format" at C:\Users\ALIENWARE\AppData\Local\nvim with args { "-assume-filename", "C:\\Users\\ALIENWARE\\AppData\\Local\\nvim\\lua\\custom\\plugins\\1.cpp" }
[TRACE 2022/10/4 17:05:30] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:209: error output: 系统找不到指定的路径。

[TRACE 2022/10/4 17:05:30] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:210: output: nil
[TRACE 2022/10/4 17:05:30] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:214: ignoring stderr due to generator options

### Help

Yes, but I don't know how to start. I would need guidance

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by Muffeter** [comment]
I suspect that it's windows path that caused this situation.
Here's the code which define the path
```
//~/AppData\Local\nvim-data\site\pack\packer\opt\null-ls.nvim\lua\null-ls\builtins\formatting\clang_formatting.lua

local FORMATTING = methods.internal.FORMATTING
local RANGE_FORMATTING = methods.internal.RANGE_FORMATTING

return h.make_builtin({
    name = "clang_format",
    meta = {
        url = "https://www.kernel.org/doc/html/latest/process/clang-format.html",
        description = "Tool to format C/C++/… code according to a set of rules and heuristics.",
    },
    method = { FORMATTING, RANGE_FORMATTING },
    filetypes = { "c", "cpp", "cs", "java", "cuda" },
    generator_opts = {
        command = "clang-format",
        args = h.range_formatting_args_factory(
            { "-assume-filename", "$FILENAME" },
            "--offset",
            "--length",
            { use_length = true }
        ),
        to_stdin = true,
    },
    factory = h.formatter_factory,
})


```

And i cant figue out what "$FILENAME" is it and how nvim produce the value.

**Comment by jose-elias-alvarez** [comment]
`$FILENAME` is replaced by null-ls with the path to the current buffer. 

I'm going to need more information for me to investigate this. `clang-format` works well for me, and your log indicates that there is some error output, but it is in Chinese, so I can't read it.

**Comment by Muffeter** [comment]
> `$FILENAME` is replaced by null-ls with the path to the current buffer.
> 
> I'm going to need more information for me to investigate this. `clang-format` works well for me, and your log indicates that there is some error output, but it is in Chinese, so I can't read it.

the log code `[TRACE 2022/10/4 17:05:30] ...t\null-ls.nvim/lua\null-ls\helpers\generator_factory.lua:209: error output: 系统找不到指定的路径。`
means that "The specified path could not be found by the system"

**Comment by jose-elias-alvarez** [comment]
What happens when you run the command directly from the command line? I don't use Windows, but this is the equivalent command for Unix:

```sh
# assuming you are in the directory containing 1.cpp
cat 1.cpp | clang-format -assume-filename 1.cpp
```

**Comment by Muffeter** [comment]
> What happens when you run the command directly from the command line? I don't use Windows, but this is the equivalent command for Unix:
> 
> ```shell
> # assuming you are in the directory containing 1.cpp
> cat 1.cpp | clang-format -assume-filename 1.cpp
> ```

For windows , the code is 
`clang-format --assume-filename="~\1.cpp"`
But to my surpise, when i run the code in the `cmd.exe`, nothing appended.
The situation is the same in the `powershell`.

However after i changed `lspconfig.lua` , the clang-format works well.
```
local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities

local lspconfig = require "lspconfig"
//before is local servers = {"html", "cssls", "clangd", "lua"}
local servers = {"html", "cssls", "clangd", "sumneko_lua"}

for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    capabilities =  capabilities,
  }
end
```

I don't understand why this change made clang-format worked again.
But i think this issue should be closed, I will try to figure out why clang-format worked again!

Thanks for ur generous reply.
