### ISSUE TITLE
Look for prettier, eslint bin in node_modules then fallback to global

### ISSUE THREAD

**Issue by mcchrish** [jose-elias-alvarez/null-ls.nvim#116]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

A project-local version of prettier/eslint is a common practice rather than installing one version globally.

Since it's lsp, maybe it's possible to deduce the bin location using the workspace roots e.g. `${workspace root dir}/node_modules/.bin/prettier`. If not maybe it's possible to recursively look for it starting with `cwd` then up the directory tree.

If it's not found, then default to the globally installed one.

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I'm new to lua and still getting a hang of it. But changes probably starts here? https://github.com/jose-elias-alvarez/null-ls.nvim/blob/f5dc246c2edfd237ebcb0288250a18771019e810/lua/null-ls/builtins/formatting.lua#L361

**Comment by jose-elias-alvarez** [comment]
This kind of configuration is a little too language-specific to include directly into this project, but I can suggest two options to handle this:

1. Use [this plugin](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils), which has a null-ls integration with ESLint that will do what you want out-of-the-box; or
2. Manually set up a conditional source, e.g.:

```lua
local null_ls = require("null-ls")

-- you don't have to use these helpers and could do it yourself, too
local eslint = require("null-ls.helpers").conditional(function(utils)
    local project_local_bin = "node_modules/.bin/eslint"

    return null_ls.builtins.diagnostics.eslint.with({
        command = utils.root_has_file(project_local_bin) and project_local_bin or "eslint",
    })
end)

null_ls.config({ sources = { eslint } })
```

Let me know if either one of those works for you.

**Comment by bpinto** [comment]
If I may, you could also add `node_modules/.bin/` to your PATH so that running eslint inside vim or not has the same outcome.

**Comment by mcchrish** [comment]
I'm gonna try out both those options. I'm using TS on some projects and the first option is going to be handy. Meanwhile I probably will look at the manual setup as well since prettier can also be used for several other languages.

> If I may, you could also add `node_modules/.bin/` to your PATH so that running eslint inside vim or not has the same outcome.

That's interesting but would that make it harder for the setup to be portable?

I'm closing this feature request as it's concluded that it's not in the scope of this plugin.

**Comment by bpinto** [comment]
> That's interesting but would that make it harder for the setup to be portable?

I don't think so, it's a somewhat common practice, all that is needed is something like this:

```
export PATH="$PATH:./node_modules/.bin"
```

I use a slightly [different version](https://github.com/bpinto/dotfiles/blob/master/.config/fish/config.fish#L13) of this myself.

I think the approach depends on how you use your system, it may make sense to change $PATH if you see yourself using the binaries from the CLI, but if you don't, then I guess updating your vim setup might be easier.

**Comment by mcchrish** [comment]
For reference I found another solution using volta (a node/npm version manager). It handles switching the command version depending on the current directory. Which just sounds perfect for me.

https://docs.volta.sh/guide/understanding#managing-your-project

**Comment by Nargonath** [comment]
For those coming here for a way to switch between project local or global installation of a binary in your linter/formatter configuration, I have another solution to offer. I didn't like the idea of adding the `node_modules` path to my PATH since it brings a lot more executable in path. I created a `lua` function instead:

```lua
local function local_or_global(exe)
    local localExePath = './node_modules/.bin/' .. exe
    local localExe = vim.fn.glob(localExePath)

    if localExe == '' then return exe end

    return localExePath
end
```

Then you'd use it like this:

```lua
settings = {
    languages = {
        yaml = {
            {
                formatCommand = local_or_global('prettier') ..
                    ' --parser yaml --write',
                formatStdin = true
            }
        },
    }
}
```
