### ISSUE TITLE
In neovim 0.8.0+, stylua cannot be detected when specify condition .stylua.toml

### ISSUE THREAD

**Issue by winkee01** [jose-elias-alvarez/null-ls.nvim#1161]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.9.0-dev-5-g9353e2f7e

### Operating System

macOS 12.3

### Minimal config

```Lua
local null_ls = require('null-ls')

local function has_stylua_configured(_utils)
  return _utils.root_has_file({ ".stylua.toml", "stylua.toml", })
end

null_ls.setup({
  debug = true,
  debounce = 150,
  on_attach = function(client, bufnr)
    // ...
  end,
  sources = {
    -- (1) lua: stylua/luafomat
    null_ls.builtins.formatting.stylua.with({ condition = has_stylua_configured }),
  }
})
```
```


### Steps to reproduce

Open a `test.lua` in a directory that has `.stylua.toml` configured as below:

```
column_width = 120
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
```

### Expected behavior

Null-ls attached to my buffer, and shown in `:LspInfo`


### Actual behavior

null-ls wasn't detected in `:LspInfo`, meaning it was not attached to my buffer.

### Debug log

```
[DEBUG Thu Oct  6 09:14:10 2022] ...e/pack/packer/start/null-ls.nvim/lua/null-ls/sources.lua:48: not registering conditional source stylua
```

### Help

No

### Implementation help

_No response_

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by winkee01** [comment]
> I can't reproduce this. ~Can you put together a sample project? This may have to do with the directory structure of your project.~ Edit: I see that you specified the necessary directory structure, so I don't know what's going on.
> 
> Do you have the same issue on 0.8 stable? Is there a specific commit that broke this?

I didn't specify directory structure. you just need to open any `.lua` file that is in a directory that has `.stylua.toml` in it.

**Comment by jose-elias-alvarez** [comment]
I don't have the same issue, so I'm going to need more information if you want me to help you. 

> Do you have the same issue on 0.8 stable? Is there a specific commit that broke this?

**Comment by winkee01** [comment]
I spent a whole day debugging this, and find out that if it has problems working with this plugin **`notjedi/vim-rooter.lua`**, If I had this

```
{
  'notjedi/nvim-rooter.lua',
  config = function()
    require'nvim-rooter'.setup({
      rooter_patterns = {'.git', 'package.json', '_darcs', '.bzr', '.svn', 'Makefile'},
      trigger_patterns = { '*' },
      manual = false,
    })
  end
},
```

Then it will cause the problem, null-ls is not detected when `null_ls.builtins.formatting.stylua.with({ condition = has_stylua_configured })`.

If I had the below, then no problem
```
{
  'notjedi/nvim-rooter.lua',
  config = function()
    require'nvim-rooter'.setup({
      rooter_patterns = {'.git', 'package.json', '_darcs', '.bzr', '.svn', 'Makefile', '.stylua.toml'},
      trigger_patterns = { '*' },
      manual = false,
    })
  end
},
```

**So, is it an issue for `null-ls` or `nvim-rooter`?**

**Comment by jose-elias-alvarez** [comment]
This is 100% an nvim-rooter issue. null-ls depends on Neovim's `cwd`, so this is the equivalent of typing `:cd some-random-directory`.

For future reference: this is why I ask for a fully independent minimal config and not just a copy-pasted part of your own config.

**Comment by winkee01** [comment]
> 
> For future reference: this is why I ask for a fully independent minimal config and not just a copy-pasted part of your own config.

Totally agree, but sometimes it's so hard to chop down my config when it's too complicated.
