### ISSUE TITLE
Unclear message when eslint bin is not present

### ISSUE THREAD

**Issue by rmagatti** [jose-elias-alvarez/null-ls.nvim#118]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

This is less of a feature and more of a clarification thing.
If you don't have `eslint` installed and open, say, a `ts` file while having null-ls setup, it'll show you a message about wanting a binary but got `eslint`.
(sorry I didn't grab a screenshot)

Maybe that message could be improved to add a "is the specified binary installed?".

Either way, not a big deal, just thought I'd mention it.

### Help

No

**Comment by jose-elias-alvarez** [comment]
This is because of how `vim.validate` structures its error messages, but I agree that it could be clearer.

**Comment by jose-elias-alvarez** [comment]
I've separated the check and (hopefully) improved the message in f1a2eaba4f00b7ff2729aed48ea98585413c9f39.
