### ISSUE TITLE
Add pmd as a built-in

### ISSUE THREAD

**Issue by kmoschcau** [jose-elias-alvarez/null-ls.nvim#1194]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Add [pmd](https://pmd.github.io) as a built-in diagnostics tool.

I already have a rough version working in my own configs.

### Help

Yes

### Implementation help

PMD requires a config file/ruleset to be specified. It ships some configs in its JAR file, which can be loaded by specifying a classpath resolvable file in the JAR. Though likely users would want to specify different configs per project.

So what I would need help with is how I can read a vim variable (read from a local vimrc for example) and use that to compose the arguments for the executable on each run.

Finally, some performance tweaks might also be nice, since I did some involuntary performance tests as commented on #596.

**Comment by jose-elias-alvarez** [comment]
> Another thing: In theory PMD also supports finding things in multiple files, however that can end up being slow. Do you guys already have something like custom switches for builtins? Sure the user could add this on their on using .with, but I would like to add this behavior and just expose it with a simple boolean flag.

We will support a level of user configuration when #1160 is merged, but configuring a built-in to return results for multiple files requires using a [special flag](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/MAIN.md#multi-file-generators). I'd lean towards enabling multi-file support by default.
