### ISSUE TITLE
Add ability to root file match to conditional utils

### ISSUE THREAD

**Issue by lyonelz96** [jose-elias-alvarez/null-ls.nvim#1225]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

At the moment, when registering a source you can do something like this

```lua
null_ls.builtins.formatting.stylua.with({
        condition = function(utils)
            return utils.root_has_file({ "stylua.toml", ".stylua.toml" })
        end,
    }),
```
From what I understand you can also use the other Conditional Utils in utils.lua (has_file, root_has_file and root_matches).
There is a case I encountered where maybe doing string matching for a file would be a great addition to have.

For example in the case of prettier or eslint.

Prettier can have multiple types of configs: .prettierrc.yaml, .prettierrc.yml, .prettierrc.json, .prettierrc.js, .prettierrc.cjs etc...

You could theoretically use the root_has_file function like this:

```lua
null_ls.builtins.formatting.pretter.with({
        condition = function(utils)
            return utils.root_has_file({ 
               ".prettierrc.yaml", 
               ".prettierrc.yml", 
               ".prettierrc.json" 
            }) -- and so on
        end,
    }),
```

Usually eslint is used in conjunction with prettier and it's the same case there, eslint can have multiple types of config files.

So it would be nice to have something like this

```lua
null_ls.builtins.formatting.pretter.with({
        condition = function(utils)
            return utils.root_has_file_matches(".prettierrc.*")
        end,
    }),
```
Did a little research and came up with something:

Using table

```lua
root_has_file_matches(pattern)
	local user_data = vim.loop.fs_scandir(root)
	local data = vim.loop.fs_scandir_next(user_data)
	local data_tbl = {}

	while data do
		table.insert(data_tbl, data)
		data = vim.loop.fs_scandir_next(user_data)
	end

	for _, name in ipairs(data_tbl) do
		if name:match(pattern) then
			return true
		end
	end

	return false
end
```

Using single string

```lua
root_has_file_matches(pattern)
	local user_data = vim.loop.fs_scandir(root)
	local data = vim.loop.fs_scandir_next(user_data)
	local data_string = ''

	while data do
		data_string = data_string .. ' ' .. data
		data = vim.loop.fs_scandir_next(user_data)
	end

	if data_string:match(pattern) then
		return true
	end

	return false
end
```

Let me know what you think and if you like it I can work on a PR this week.

### Help

Yes

**Comment by jose-elias-alvarez** [comment]
Sure, this would be a welcome addition.
