### ISSUE TITLE
Codespell integration

### ISSUE THREAD

**Issue by vuki656** [jose-elias-alvarez/null-ls.nvim#123]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Would it be possible to implement [codespell](https://github.com/codespell-project/codespell)?

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

What would codespell need to provide in order to be compatible?

**Comment by jose-elias-alvarez** [comment]
I briefly played around with it and it's a little wonky when used from `stdin` but definitely possible to handle in the same way as the other built-in diagnostic sources we have. I can take a whack at it when I have a chance if nobody else has taken care of it.
