### ISSUE TITLE
dotenv-linter

### ISSUE THREAD

**Issue by zdufour-asp** [jose-elias-alvarez/null-ls.nvim#1252]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Would it be reasonable to add something like [dotenv-linter](https://github.com/dotenv-linter/dotenv-linter) to the null-ls builtins (for formatting & linting `.env` files)?

### Help

Yes

### Implementation help

your [CONTRIBUTING](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/CONTRIBUTING.md) is awesome. I think I can see a decent roadmap, but I still feel pretty noobish with lua, so I might have dumb questions (e.g. I still don't really get what the deal is with tables. They're dictionaries, AND lists?)

**Comment by jose-elias-alvarez** [comment]
Definitely reasonable, and I'm happy to proivde guidance on a PR. I would start by looking at existing linter sources and using one as a base.
