### ISSUE TITLE
Add tflint builtin

### ISSUE THREAD

**Issue by sblask** [jose-elias-alvarez/null-ls.nvim#1254]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

tflint is a linter for terraform I currently have this in my config and am testing it:

```lua
-- See https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/helpers/diagnostics.lua#L3
local tflint_severities = {
    ["error"] = 1,
    ["warning"] = 2,
    ["info"] = 3,
}
local tflint = {
    name = "tflint",
    method = null_ls.methods.DIAGNOSTICS_ON_SAVE,
    filetypes = { "terraform" },
    generator = null_ls.generator({
        command = "tflint",
        args = function(params)
            return {
                "--format",
                "json",
                vim.fs.dirname(params.bufname), -- tflint needs to run from repository root to load the right config
            }
        end,
        to_stdin = false,
        from_stderr = true,
        multiple_files = true,
        format = "json",
        check_exit_code = function(code, _stderr)
            return code == 0
        end,
        on_output = function(params)
            local rewritten_diagnostics = {}
            for _, diagnostic in ipairs(params.output.issues) do
                local rewritten_diagnostic = {
                    message = diagnostic.message,
                    row = 0,
                    col = 0,
                    source = "tflint",
                    severity = tflint_severities[diagnostic.rule.severity],
                    filename = params.bufname,
                }
                if diagnostic.range ~= nil then
                    rewritten_diagnostic.col = diagnostic.range.start.column
                    rewritten_diagnostic.end_col = diagnostic.range["end"].column
                    rewritten_diagnostic.row = diagnostic.range.start.line
                    rewritten_diagnostic.end_row = diagnostic.range["end"].line
                    if diagnostic.range.filename ~= "" then
                        rewritten_diagnostic.filename = diagnostic.range.filename
                    end
                end
                table.insert(rewritten_diagnostics, rewritten_diagnostic)
            end
            return rewritten_diagnostics
        end,
    }),
}
null_ls.register(tflint)
```

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I had a look at https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/test/spec/builtins/diagnostics_spec.lua but it's a bit unclear to me how it works

**Comment by gegoune** [comment]
You can use tflint directly with (or even without) lspconfig. Not sure if it's therefore needed in null-ls.

**Comment by sblask** [comment]
@gegoune there are many ways to run something. Before I ran tflint through Ale. The advantage of using null-ls is that there is one way of configuring something and the ability to use other lsp plugins to improve the experience.

**Comment by gegoune** [comment]
I am not sure I understand your advantage point. Doesn't lspconfig allow something to be configured? Not that I am arguing against it, just thought I would let you know that it is already very easily achievable via lspconfig.

**Comment by sblask** [comment]
Turns out I didn't understand what you meant, didn't know that tflint can act as language server. That is probably be a better alternative indeed.

**Comment by sblask** [comment]
For reference, I had to do this:

```
local lspconfig = require("lspconfig")
lspconfig["tflint"].setup({
    root_dir = lspconfig.util.root_pattern(".git", ".tflint.hcl"),
})
```

By default `root_pattern` has `".terraform"` first so it didn't load my `.tflint.hcl` which is one folder up from my Terraform code (tflint doesn't search for the config file but uses the one from the current working directory or none).
