### ISSUE TITLE
`gqq` command not working

### ISSUE THREAD

**Issue by jamestrew** [jose-elias-alvarez/null-ls.nvim#1259]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.9.0-dev-395+g3098064f3

### Dev Version?

- [X] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

archlinux 6.0.9-arch1-1

### Minimal Config

```Lua
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
  local path_sep = on_windows and "\\" or "/"
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      "nvim-lua/plenary.nvim",
      "jose-elias-alvarez/null-ls.nvim",

      "folke/tokyonight.nvim",
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  })
end

_G.load_config = function()
  vim.cmd([[colorscheme tokyonight]])

  local null_ls = require("null-ls")
  null_ls.setup({
    debug = true,
    sources = {
      null_ls.builtins.formatting.black,
      null_ls.builtins.formatting.gofmt,
    },
  })
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
  load_plugins()
  require("packer").sync()
  vim.cmd([[autocmd User PackerComplete ++once lua load_config()]])
else
  load_plugins()
  require("packer").sync()
  _G.load_config()
end
```

### Steps to Reproduce

1. open nvim with `nvim --clean -u minimal_init.lua`
2. create a random python file `:e /tmp/test.py` and enter a very long, oneline comment: `# this is a veery long comment this is a veery long commentthis is a veery long commentthis is a veery long commentthis is a veery long comment` 
3. with the cursor anywhere over the comment, in normal mode, hit `gqq`

This behavior can be seen for go file as well with the `gofmt` sources enabled (as is in the minimal_init.lua).

As for the formatting functionally, they appear to work correctly. Tested by writing some badly formatted code and running `:lua vim.lsp.buf.format()`

### Reproducibility Check

- [X] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

the long one line comment should be split into multiple lines via the builtin vim `gqq` formatting function.
eg.
```py
# this is a veery long comment this is a veery long commentthis is a veery long
# commentthis is a veery long commentthis is a veery long comment
```

This expected behavior can be observed by commenting out by commenting out the null-ls builtin formatting sources for whichever language you're testing. eg. comment out `null_ls.builtins.formatting.black` and repeat steps above and `gqq` will work as expected.

I've tried git bisecting both `null-ls` (going back to July 2022 commits) and neovim itself individually (v0.8.0 onwards) but was unable to find anything conclusive. I don't remember this issue always being present so I would've expected to find something within the periods I bisected. I'm interested with others can replicated what I'm experiencing.

### Actual Behavior

Nothing happens. The long oneline comment remains as is. As if the `gqq` command was eaten.

### Debug Log

[TRACE Sun 27 Nov 2022 05:19:51 PM EST] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:110: starting null-ls client
[TRACE Sun 27 Nov 2022 05:19:51 PM EST] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:123: received LSP request for method initialize
[TRACE Sun 27 Nov 2022 05:19:51 PM EST] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:148: received LSP notification for method initialized
[TRACE Sun 27 Nov 2022 05:19:51 PM EST] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:148: received LSP notification for method textDocument/didOpen
[TRACE Sun 27 Nov 2022 05:19:51 PM EST] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Sun 27 Nov 2022 05:19:51 PM EST] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:24: no generators available
[TRACE Sun 27 Nov 2022 05:20:23 PM EST] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:123: received LSP request for method shutdown
[TRACE Sun 27 Nov 2022 05:20:23 PM EST] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:148: received LSP notification for method exit

### Help

Yes

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by ner0-m** [comment]
I'm having similar issues. I didn't have time to test it properly. But in a markdown file, if any null-ls source is active and null-ls attached as a LSP (using `LspInfo`), reformatting using `gqq` in normal or `gq` in visual mode doesn't work anymore.

**Comment by jamestrew** [comment]
After a little more testing, I can confirm @ner0-m's claim that if any null-ls source is active on a buffer, `gqq` is broken.

Just tested the `gitsigns` source on a lua file with no other sources active and `gqq` still fails.

**Comment by jose-elias-alvarez** [comment]
See #1131. This is a default set by Neovim, and there's not much we can do about it, though there are some workarounds mentioned in that issue.
