### ISSUE TITLE
Stop Command for specific servers

### ISSUE THREAD

**Issue by pedro757** [jose-elias-alvarez/null-ls.nvim#1268]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Is there a command to stop a specific server? similar to `:LspStop <server_name>`with completion support.

![image](https://user-images.githubusercontent.com/30637426/205199646-8abcb0c0-4bf1-4c87-b2e5-1960f92740ab.png)

### Help

No

**Comment by jose-elias-alvarez** [comment]
This is being worked on in #1188.

**Comment by jose-elias-alvarez** [comment]
Closing as a duplicate.
