### ISSUE TITLE
ruff: built-ins for formatting and code actions

### ISSUE THREAD

**Issue by igorlfs** [jose-elias-alvarez/null-ls.nvim#1286]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Recently, a built-in for ruff has been added, but only for diagnostics. Given that ruff also supports code-actions and formatting, it'd be nice to have these capabilities as built-ins too! Ruff's documentation has a snippet to enable formatting with null-ls:
```lua
local null_ls = require("null-ls")
local methods = require("null-ls.methods")
local helpers = require("null-ls.helpers")

local function ruff_fix()
    return helpers.make_builtin({
        name = "ruff",
        meta = {
            url = "https://github.com/charliermarsh/ruff/",
            description = "An extremely fast Python linter, written in Rust.",
        },
        method = methods.internal.FORMATTING,
        filetypes = { "python" },
        generator_opts = {
            command = "ruff",
            args = { "--fix", "-e", "-n", "--stdin-filename", "$FILENAME", "-" },
            to_stdin = true
        },
        factory = helpers.formatter_factory
    })
end

null_ls.setup({
    sources = {
        ruff_fix(),
        null_ls.builtins.diagnostics.ruff,
    }
})
```
(taken from [here](https://github.com/charliermarsh/ruff#vim--neovim-unofficial))

### Help

No

**Comment by jose-elias-alvarez** [comment]
Formatting looks pretty straightforward - I think the snippet you posted is pretty much ready to go. Not sure about code actions, but as always, I'm happy to review and provide guidance on PRs.

**Comment by igorlfs** [comment]
Hey, ruff's developer made an LSP for ruff, which addresses the code actions issue. Given this alternative, I'll close the issue.

**Comment by tgy** [comment]
@igorlfs could you give details on how the LSP for ruff that you mention can be used alongside null-ls ? thanks!
