### ISSUE TITLE
Ruff diagnostics not working

### ISSUE THREAD

**Issue by joellidin** [jose-elias-alvarez/null-ls.nvim#1288]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.9.0-dev-488+g8b84a10db

### Dev Version?

- [X] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

Ubuntu 22.04

### Minimal Config

```Lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.g.loaded_remote_plugins = ""
vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = {
	    null_ls.builtins.diagnostics.ruff,
	},
        debug = true,
    })
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "jose-elias-alvarez/null-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },
            "neovim/nvim-lspconfig",
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end
```

### Steps to Reproduce

I don't know if I am being stupid but I can't get the linting from ruff to work. With the minimal setup below and with the python code:
```python
def foo(x):
    a = 1
```
I should get an diagnostic `local variable 'a' is assigned to but never used`, but I get nothing. If I change from `ruff` to `flake8` it works as intended.

### Reproducibility Check

- [X] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

I should get the diagnostic from ruff as well.

### Actual Behavior

Don't get the diagnostics.

### Debug Log

```
[TRACE fre  9 dec 2022 23:05:32] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:110: starting null-ls client
[TRACE fre  9 dec 2022 23:05:32] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:123: received LSP request for method initialize
[DEBUG fre  9 dec 2022 23:05:32] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:165: unable to notify client for method textDocument/didOpen (client not active): {
  textDocument = {
    uri = "file:///home/jlidin/Documents/test.py"
  }
}
[TRACE fre  9 dec 2022 23:05:32] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:148: received LSP notification for method initialized
[TRACE fre  9 dec 2022 23:05:32] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:148: received LSP notification for method textDocument/didOpen
[TRACE fre  9 dec 2022 23:05:32] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG fre  9 dec 2022 23:05:32] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:320: spawning command "ruff" at /home/jlidin/Documents with args { "-n", "-e", "--stdin-filename", "/home/jlidin/Documents/test.py", "-" }
[TRACE fre  9 dec 2022 23:05:32] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:204: error output: nil
[TRACE fre  9 dec 2022 23:05:32] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:205: output: def foo(x):
    a = 1

[TRACE fre  9 dec 2022 23:05:32] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:181: received diagnostics from source 1
[TRACE fre  9 dec 2022 23:05:32] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:182: {}
```

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation Help

I would love to help, but I know too little about plugin development overall. Moreover, I have tried to understand why this fails without success.

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
This is working for me on the latest version of `ruff` (0.0.173) and on Neovim 0.8.1:

<img width="452" alt="Screenshot 2022-12-10 at 1 47 39 PM" src="https://user-images.githubusercontent.com/54108223/206870683-83f7b318-1a46-476e-87ac-4a84b576ba2c.png">

Your output indicates that the linter is running correctly, but it's not detecting the error. In my case, I get the following output, which is then correctly parsed into a diagnostic:

```
[TRACE Sat Dec 10 13:46:58 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:204: error output: nil
[TRACE Sat Dec 10 13:46:58 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:205: output: Found 1 error(s).
test.py:2:5: F841 Local variable `a` is assigned to but never used
```

Have you tried updating `ruff` and verifying if it works directly from the command line?

**Comment by joellidin** [comment]
I am sorry about this. It worked directly from the command line. But the problem was that I had `fix = true` in a `pyproject.toml` because I was in a project. When removing this it works as expected. Thanks!
