### ISSUE TITLE
semgrep is run too aggressively

### ISSUE THREAD

**Issue by Integralist** [jose-elias-alvarez/null-ls.nvim#1299]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.8.1

### Dev Version?

- [X] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

macOS Ventura

### Minimal Config

```Lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
  local path_sep = on_windows and "\\" or "/"
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.g.loaded_remote_plugins = ""
vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
  local null_ls = require("null-ls")
  -- add only what you need to reproduce your issue
  null_ls.setup({
    sources = {
      require("null-ls").builtins.diagnostics.semgrep.with({
        args = { "--config", "auto", "-q", "--json", "$FILENAME" },
        timeout = 30000
      })
    },
    debug = true
  })
end

local function load_plugins()
  -- only add other plugins if they are necessary to reproduce the issue
  require("packer").startup({
    {
      "wbthomason/packer.nvim", {
        "jose-elias-alvarez/null-ls.nvim",
        requires = { "nvim-lua/plenary.nvim" },
        config = null_ls_config
      }
    },
    config = { package_root = package_root, compile_path = compile_path }
  })
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({
    "git", "clone", "https://github.com/wbthomason/packer.nvim",
    install_path
  })
  load_plugins()
  require("packer").sync()
else
  load_plugins()
  require("packer").sync()
end
```

### Steps to Reproduce

Open any `.go` file, but for the sake of example https://github.com/fastly/cli/blob/main/pkg/api/interface.go, and then just repeatedly go in and out of INSERT mode. You don't need to actually edit the file, just `o` and then `Esc` multiple times and check a process monitor like `htop` that can filter for the semgrep process and you'll see a new instance of semgrep spun up every time you enter INSERT mode.

### Reproducibility Check

- [X] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

I expected semgrep to run only when writing the buffer (and also when loading the buffer for the first time).

### Actual Behavior

Every time I enter INSERT, which is _a lot_ when editing a code file, and even without writing _any_ changes, each INSERT mode change causes semgrep to run.

I imagine this might be a simple change from [`method = DIAGNOSTICS`](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics/semgrep.lua#LL43C5-L43C26) to something like what is used by [staticcheck](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics/staticcheck.lua#L21) or [revive](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics/revive.lua#L19).

### Debug Log

N/A

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
> You don't need to actually edit the file, just o and then Esc multiple times and check a process monitor like htop that can filter for the semgrep process and you'll see a new instance of semgrep spun up every time you enter INSERT mode.

This does actually edit the file, since you're inserting a new line every time you press `o`. If you do the same with `i` (which doesn't edit the file) no change notifications are sent and so the source doesn't run. We do have logic in place to avoid running sources repeatedly when staying in insert mode but not for cases like this.

> I imagine this might be a simple change from [method = DIAGNOSTICS](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics/semgrep.lua#LL43C5-L43C26) to something like what is used by [staticcheck](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics/staticcheck.lua#L21) or [revive](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics/revive.lua#L19).

You can make this modification locally:

```lua
local null_ls = require("null-ls")

local semgrep = null_ls.builtins.diagnostics.semgrep.with({
    -- other options
    method = null_ls.methods.DIAGNOSTICS_ON_SAVE,
})
```

In #1291, the original author of the built-in mentioned that he doesn't see timeouts with the same source, so I don't know if it makes sense to change the method for everyone.

**Comment by Integralist** [comment]
I'm sorry, I didn't realise I could override that setting as well in my own configuration! That's great news 🙂 

OK will close then in that case 👍🏻
