### ISSUE TITLE
Provide vim help files

### ISSUE THREAD

**Issue by d12bb** [jose-elias-alvarez/null-ls.nvim#1304]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Having markdown in `doc/` is great for viewing in a browser, but not for using in Vim itself. Would be really nice if you could provide ones using the actual Vim help syntax.

### Help

No

**Comment by jose-elias-alvarez** [comment]
This is similar to #1057 - did you want to have access to all the documentation or just the built-in documentation? I'm unlikely to work on this myself, but this would have to be fully automated for me to consider it. See #949 for a potential approach.

**Comment by d12bb** [comment]
yeah, basically dupe. Searching for "help" inside hundreds of issues is hard :D Should have looked into the PRs though first, so sorry for that.

I like to have all the docs inside Vim, as it's where I potentially need it. No switching application, opening the right page (as gx obviously doesn't work for the partial urls used in plugin managers nowadays) etc. Autogenerated as in #949 would probably be more than sufficient.

Anyways, closing this as duplicate, I'll just follow the PR..
