### ISSUE TITLE
Offset encoding error appeared again on sumneko_lua 

### ISSUE THREAD

**Issue by ruanyouxing** [jose-elias-alvarez/null-ls.nvim#1305]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v 0.8.1

### Dev Version?

- [X] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

Arch Linux

### Minimal Config

```Lua
Null-ls config:
  null_ls.setup {
       on_init = function(new_client,_)
          new_client.offset_encoding = 'utf-8'
       end,
       sources = sources
}
(To avoid issue #428)
LSP config:
   capabilities.offsetEncoding = 'utf-8'
   require('lspconfig').clangd.setup {
     capabilities = capabitilities
  }
   require('lspconfig').sumneko_lua.setup {
     settings = {
      Lua = {
        diagnostics = { globals = { 'vim','packer_plugins' } },
        workspace = {
          library = {
            [vim.fn.expand '$VIMRUNTIME/lua'] = true,
            [vim.fn.expand '$VIMRUNTIME/lua/vim/lsp'= true,
          },
          maxPreload = 100000,
          preloadFileSize = 10000,
        },
        telemetry = { enable = false },
      },
    },
}
```

### Steps to Reproduce

Offset encoding error showed like #428 when I opened a .cpp file
Fixed with 
```lua 
    on_init = function(new_client,_)
      new_client.offset_encoding = 'utf-8'
    end
```
It's not showed when I open .cpp file anymore, but it showed again when I open a .lua file with that same error

### Reproducibility Check

- [X] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

No errors triggered

### Actual Behavior

Offset encoding error triggered when I edit a lua file

### Debug Log

It shows nothing

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
I believe lua-language-server uses utf-16, so if you set null-ls to utf-8, then you will see the incompatibility warning. Is this a new issue? Either way, this is not really possible for us to solve on our end for the same reasons described in #428. If you have two clients attached with different offset encodings, you'll see the warning.

**Comment by ruanyouxing** [comment]
got it, thanks
