### ISSUE TITLE
Support for Yarn PnP

### ISSUE THREAD

**Issue by ric980** [jose-elias-alvarez/null-ls.nvim#1319]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

ESLint diagnostics don't work with Yarn PnP out of the box. I have to constantly switch between these two configurations depending on my project:

Yarn PnP:

```
    null_ls.builtins.diagnostics.eslint.with {
      command = 'yarn',
      args = { 'eslint', '-f', 'json', '--stdin', '--stdin-filename', '$FILENAME' },
    },
```

Classic Yarn:
```
    null_ls.builtins.diagnostics.eslint
```

It's a workaround but still quite annoying. Any plans for Yarn PnP support?

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I have some basic Lua knowledge and many years of programming experience, but no knowledge of neovim and null_ls.

**Comment by jose-elias-alvarez** [comment]
We have [a command resolver](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/helpers/command_resolver.lua#L54) that simplifies the process a bit, though it's not out-of-the-box. 

I'm not sure if Yarn PnP usage is widespread enough to justify the overhead of trying to determine if a given Node project is using it automatically. For cases like this, I'd recommend registering two separate sources using [conditions](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md#condition) to determine whether they should be registered.

**Comment by ric980** [comment]
This command resolver is looking for Yarn PnP files. It looks for `.pnp.cjs`, and I have `.pnp.cjs` at the project root. Why is it not working out of the box? What else should I do so that the command resolver works for me?

**Comment by ric980** [comment]
I am trying to use conditions but cannot get them to work. This is my config file:

```lua
    -- Classic Yarn
    null_ls.builtins.diagnostics.eslint.with {
      condition = function(utils)
        return not utils.root_has_file '.pnp.cjs'
      end,
    },

    -- Yarn PnP
    null_ls.builtins.diagnostics.eslint.with {
      command = 'yarn',
      args = { 'eslint', '-f', 'json', '--stdin', '--stdin-filename', '$FILENAME' },
      condition = function(utils)
        return utils.root_has_file '.pnp.cjs'
      end,
    },
```

but the global `eslint` is still loaded, instead of loading it with `yarn`.

**Comment by ric980** [comment]
Ok, I got it working. This is my config file:

```
    -- Classic Yarn
    null_ls.builtins.diagnostics.eslint.with {
      condition = function(utils)
        return not utils.has_file '.pnp.cjs'
      end,
    },

    -- Yarn PnP
    null_ls.builtins.diagnostics.eslint.with {
      command = 'yarn',
      args = { 'eslint', '-f', 'json', '--stdin', '--stdin-filename', '$FILENAME' },
      condition = function(utils)
        return utils.has_file '.pnp.cjs'
      end,
    },
```

I am working on monorepos, so at the project root, there is no `.pnp.cjs` file. I guess project root means something with `.git` folder.

Thank you very much for your guidance.

**Comment by jose-elias-alvarez** [comment]
Glad you figured it out. For what it's worth, you can also customize root directory detection in your [config](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/CONFIG.md#options).
