### ISSUE TITLE
deno fmt is broken

### ISSUE THREAD

**Issue by brenol** [jose-elias-alvarez/null-ls.nvim#1322]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.8.1

### Dev Version?

- [ ] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

Ubuntu

### Minimal Config

```Lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.g.loaded_remote_plugins = ""
vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = {
            nls.builtins.formatting.deno_fmt,
        },
        debug = true,
    })
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "jose-elias-alvarez/null-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end
```

### Steps to Reproduce

 Save a Typescript, Javascript or any file that deno should format, but it does not happen.

I think the cause is (https://github.com/jose-elias-alvarez/null-ls.nvim/pull/1313/files), as I do not have `textwidth` set and I'm using `deno.json` in the root of the directory. 

Although I understand the motivation of the change made by @jceb, I think it goes against what deno own formatting does & the way null-ls works with other tools (AFAIK), where it respects all the default values of the tool, only bypassing values if the user customize it.

### Reproducibility Check

- [ ] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

The file is formatted.

### Actual Behavior

The file is not formatted.

### Debug Log

Could not get value from the minimal file, however, this was printed on my log when running save on file:
```
[DEBUG Thu 05 Jan 2023 02:53:50 PM -03] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:320: spawning command "deno" at /tmp/repro with args { "fmt", "-", "--ext", "tsx", "--options-line-width", "0", "--options-indent-width", "2" }
[TRACE Thu 05 Jan 2023 02:53:50 PM -03] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:204: error output: [0m[1m[31merror[0m: Invalid value "0" for '--options-line-width <options-line-width>': options-line-width should be a non zero integer

For more information try --help


Caused by:
    options-line-width should be a non zero integer
```

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by lucax88x** [comment]
also prettierd format stopped working, could be a hint?

**Comment by jose-elias-alvarez** [comment]
Yep, I think the fact that it doesn't work with the default `textwidth` value is an issue. We could either revert it completely or validate that `textwidth` and `shiftwidth` are set to non-zero values before adding them to the arguments list. @jceb What do you think?

**Comment by jose-elias-alvarez** [comment]
> also prettierd format stopped working, could be a hint?

I don't think this is related, since there haven't been any related changes. Please open a separate issue if you're still having problems and can verify that they're not replicable when using the CLI (I've had issues with prettierd not working in the past and stopped using it for that reason.)

**Comment by wjdwndud0114** [comment]
> also prettierd format stopped working, could be a hint?

Same thing happened to me - tried CLI and it was an issue with lock file. Try removing `~/.prettierd`

**Comment by jose-elias-alvarez** [comment]
For now I reverted 915558963709ea17c5aa246ca1c9786bfee6ddb4, since the fact that it's broken out-of-the-box (and in a pretty unclear way) is pretty bad.

> Although I understand the motivation of the change made by @jceb, I think it goes against what deno own formatting does & the way null-ls works with other tools (AFAIK), where it respects all the default values of the tool, only bypassing values if the user customize it.

In a perfect world we would be able to pass Neovim's relevant options to formatters, which would allow for something like #1325. In principle I'm in favor of changes like this, though I think this issue highlights the potential pitfalls of doing so.
