### ISSUE TITLE
Cpplint diagnostic - temp file causes unwanted warnings

### ISSUE THREAD

**Issue by mdvictor** [jose-elias-alvarez/null-ls.nvim#1351]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.8.1

### Dev Version?

- [ ] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

macOS Ventura 13.0.1

### Minimal Config

```Lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.g.loaded_remote_plugins = ""
vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = { null_ls.builtins.diagnostics.cpplint },
        debug = true,
    })
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "jose-elias-alvarez/null-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end
```

### Steps to Reproduce

1. Create a simple C header file, e.g:
```
class Test {
 public:
  void func();
};
```
2. Write an implementation so that a system header is after the `test.h` header:
```
#include "./test.h"

#include <string>

void Test::func() { std::string foo = "bar"; }
```

3. The warning `Found C++ system header after other header. Should be: .null-ls_528489_test.h, c system, c++ system, other.` appears.

### Reproducibility Check

- [X] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

The warning should not appear since the headers are in proper order (e.g: file header, c/cpp system and other headers). Cpplint sees the first include as a `other` header, which is incorrect.

### Actual Behavior

Since `null-ls` serves the generated temp file to `cpplint`, the linter returns the warning message, seeing `.null-ls_#######_test.h` as the correct file header.

### Debug Log

```
[TRACE Mon Jan 16 20:40:31 2023] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:97: starting null-ls client
[TRACE Mon Jan 16 20:40:31 2023] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:102: received LSP request for method initialize
[TRACE Mon Jan 16 20:40:31 2023] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:127: received LSP notification for method initialized
[TRACE Mon Jan 16 20:40:31 2023] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:127: received LSP notification for method textDocument/didOpen
[TRACE Mon Jan 16 20:40:31 2023] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Mon Jan 16 20:40:31 2023] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:320: spawning command "cpplint" at /Users/mdvictor/Workspace/repro-null-ls-err with args { "/Users/mdvictor/Workspace/repro-null-ls-err/.null-ls_814785_test.cpp" }
[TRACE Mon Jan 16 20:40:31 2023] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:204: error output: /Users/mdvictor/Workspace/repro-null-ls-err/.null-ls_814785_test.cpp:0:  No copyright message found.  You should have a line: "Copyright [year] <Copyright Owner>"  [legal/copyright] [5]
/Users/mdvictor/Workspace/repro-null-ls-err/.null-ls_814785_test.cpp:3:  Found C++ system header after other header. Should be: .null-ls_814785_test.h, c system, c++ system, other.  [build/include_order] [4]

[TRACE Mon Jan 16 20:40:31 2023] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:205: output: Done processing /Users/mdvictor/Workspace/repro-null-ls-err/.null-ls_814785_test.cpp
Total errors found: 2

[TRACE Mon Jan 16 20:40:31 2023] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:181: received diagnostics from source 1
[TRACE Mon Jan 16 20:40:31 2023] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:182: { {
    col = 0,
    end_col = 0,
    end_lnum = 0,
    lnum = 0,
    message = 'No copyright message found.  You should have a line: "Copyright [year] <Copyright Owner>"',
    row = "0",
    severity = 3,
    source = "cpplint"
  }, {
    col = 0,
    end_col = 0,
    end_lnum = 3,
    lnum = 2,
    message = "Found C++ system header after other header. Should be: .null-ls_814785_test.h, c system, c++ system, other.",
    row = "3",
    severity = 2,
    source = "cpplint"
  } }
```

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation Help

I've been looking into `lua/null-ls/builtins/diagnostics/cpplint.lua` and removing the `to_temp_file` option seems to fix it, in the sense that the warning does not appear anymore, but since the original file is being served to `cpplint` now, warnings, in general, appear or not only after the file is saved (and thus the new version served to `cpplint`). 

Or that is my understanding, at least. I don't have much experience with neither `nvim` nor `null-ls`. To fix the stale warnings,  I added:
```
       null_ls.builtins.diagnostics.cpplint.with({
               method = null_ls.methods.DIAGNOSTICS_ON_SAVE,
       })
```

So I get the latest `cpplint` messages on save, but I'm not sure that this is the best way.

I could try to fix this with some guidance, if possible. I'd say the first thing would be to remove the temp file option, after that I'm not sure.

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
See #1300. As you've identified, there's basically two solutions here:

1. Keep the current behavior, which uses a temp file to update diagnostics on change. Users can then either ignore the message or filter it out.
2. Change the linter to only run on save, in which case a temp file is no longer necessary, but behavior is less LSP-like.

I'd be open to a PR that filters out the message by default.

**Comment by mdvictor** [comment]
Thank you for your reply!

I should've checked the discussions better. Filtering seems to be the best option here.

I'll leave this issue open and try to push a PR with default filtering for that message soon.
