### ISSUE TITLE
For textlint, add dynamic code = `from_node_modules()`

### ISSUE THREAD

**Issue by sys9kdr** [jose-elias-alvarez/null-ls.nvim#1378]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

textlint is a node module. So I would like to add `dynamic_command = cmd_resolver.from_node_modules()`.

* https://github.com/jose-elias-alvarez/null-ls.nvim/blob/944c72a0a85b4a6affddda60d55eacf83075b718/lua/null-ls/builtins/formatting/textlint.lua
* https://github.com/jose-elias-alvarez/null-ls.nvim/blob/b287e9d124037a7ea5de8e3368a3b75274cec8b4/lua/null-ls/builtins/diagnostics/textlint.lua

### Help

Yes

**Comment by jose-elias-alvarez** [comment]
Sounds fine to me, should be a straightforward PR.

**Comment by jose-elias-alvarez** [comment]
Closed by #1396
