### ISSUE TITLE
Add support for mypy

### ISSUE THREAD

**Issue by Funk66** [jose-elias-alvarez/null-ls.nvim#139]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Mypy is conspicuously absent from the list of supported diagnostic tools. I was wondering whether there is a reason for that. It is supported by [nvim-lint](https://github.com/mfussenegger/nvim-lint/blob/c086009aaa6e73c0cf39432997790b317a875fca/lua/lint/linters/mypy.lua) and its implementation doesn't seem to be particularly troublesome.
Mypy has open issues to add support for [json formatting](https://github.com/python/mypy/issues/10816) and a full-fledged [language server](https://github.com/python/mypy/issues/10463), although I doubt that these are going to be implemented anytime soon.

### Help

Yes

### Implementation help

I can try to implement it myself, but I may need some help to make it work properly.

**Comment by jose-elias-alvarez** [comment]
I'm not familiar with `mypy`, but based on [this issue](https://github.com/python/mypy/issues/2119) it seems like it'll need some work to support linting a buffer's content (versus linting a file on disk). At the moment, all of the built-in diagnostic sources support linting on change, so I'd be hesitant to introduce a source that doesn't support it.

It seems that the [ALE source](https://github.com/dense-analysis/ale/blob/7d8fb2ba1716a744446b811fc278ecf30d4eb771/ale_linters/python/mypy.vim) has solved this issue, so we should probably use that as the base for the implementation (plus the patterns from nvim-lint). I'll have time to work on this myself in the second half of September but can review a PR before then.

**Comment by Funk66** [comment]
Oh, bugger. I thought I had an almost-working prototype, but you're right - this isn't as straightforward as I initially thought. I'll see if I can still open a PR in the coming weeks.
You may already know this, but for completeness I'll mention that mypy can run as a [daemon](https://mypy.readthedocs.io/en/stable/mypy_daemon.html). I'm not familiar with the internal workings of null-ls, but I assume that running a background process and interacting with it is going to be more complex.
Also, to provide additional context, mypy is the "official" static type checker for Python and pyright is - in my experience - not quite mature enough to replace it.

**Comment by jose-elias-alvarez** [comment]
From the documentation, it seems that the daemon might work well, since (if I understand correctly) it seems that we can interact with it as if it were a normal CLI program. I'd definitely give that a shot.
