### ISSUE TITLE
chktex failed to run generator

### ISSUE THREAD

**Issue by joellidin** [jose-elias-alvarez/null-ls.nvim#1390]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.9.0-dev-488+g8b84a10db

### Dev Version?

- [ ] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

Ubuntu 22.04

### Minimal Config

```Lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.g.loaded_remote_plugins = ""
vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = {
          null_ls.builtins.diagnostics.chktex,
        },
        debug = true,
    })
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "jose-elias-alvarez/null-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end
```

### Steps to Reproduce

With the following `test.tex` file:
```tex
\documentclass{article}
\begin{document}
:)
\end{document}
```
I get this error:
```
[null-ls] failed to run generator: ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:219: error in generator output: 3:2:1:Warning:10:Solo `)' found.
4:1:0:Warning:17:Number of `(' doesn't match the number of `)'!
```
when running `nvim --clean -u minimal_init.lua test.tex`. The diagnostic is clearly in the error, but I don't know how to fix the error in generator output. Is there something I have missed?

### Reproducibility Check

- [X] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

To get the normal `null-ls` diagnostics.

### Actual Behavior

`null-ls` errors.

### Debug Log

```
[TRACE ons  8 feb 2023 17:33:47] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:205: output: nil
[WARN  ons  8 feb 2023 17:33:47] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:94: failed to run generator: ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:219: error in generator output: 3:2:1:Warning:10:Solo `)' found.
4:1:0:Warning:17:Number of `(' doesn't match the number of `)'!
```

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by patrick96** [comment]
I have the same issue on Ubuntu 22.10. I have tracked it down to the following: The newest version of chktex has an exit code of `2` when there are warnings and an exit code of `3` if there are errors. However, null-ls does not recognize these error codes, locally I have applied the following patch:

```patch
diff --git a/lua/null-ls/builtins/diagnostics/chktex.lua b/lua/null-ls/builtins/diagnostics/chktex.lua
index c25c664..808bb0a 100644
--- a/lua/null-ls/builtins/diagnostics/chktex.lua
+++ b/lua/null-ls/builtins/diagnostics/chktex.lua
@@ -22,7 +22,7 @@ return h.make_builtin({
         },
         format = "line",
         check_exit_code = function(code)
-            return code <= 1
+            return code <= 3
         end,
         on_output = h.diagnostics.from_pattern(
             [[(%d+):(%d+):(%d+):(%w+):(%d+):(.+)]],
```

Also, Ubuntu does not yet have the newest version of chktex, but it seems the debian package (and as a consequence the ubuntu package) have backported some of those changes to version 1.7.6

**Comment by jose-elias-alvarez** [comment]
The patch seems like a good solution, especially if it works across versions. PR welcome!
