### ISSUE TITLE
Do we need a helper to generate lsp edits from diff?

### ISSUE THREAD

**Issue by black-desk** [jose-elias-alvarez/null-ls.nvim#1395]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I would like to add a new buildin for `git clang-format` which is a python wrapper of clang-format. It only format the lines which change.

Unlike other formators, this command seems not output the formatted content to stdout. By defalut, it just change the files on disk.  But it have a option `--diff`, which print the changes should make.

So I would like to add a helper to generate edits from diff then add a `git clang-format` buildin.

### Help

Yes

### Implementation help

I will have a try first. If I need any help, I will just comment below.

**Comment by black-desk** [comment]
I found git-clang-format cannot change the arguments send to git, which means that we cannot make git assume the file content as the content in buffer. So it will be more difficult to add that `git clang-format` builtin as I tought before.

**Comment by black-desk** [comment]
I found a way to implement git clang-format like builtin, so I close this.

**Comment by evelez7** [comment]
> I found a way to implement git clang-format like builtin, so I close this.

@black-desk care to share how you implemented this? I am also interested in getting git clang-format on my lvim.

**Comment by black-desk** [comment]
Check it here: https://github.com/black-desk/dotfiles/commit/b57e72629a40c74b70bceab49e99736538165994

But I am not using it right now because of some performance issue. It seems to be very slow.
