### ISSUE TITLE
Switch to Plenary jobs to spawn processes?

### ISSUE THREAD

**Issue by jose-elias-alvarez** [jose-elias-alvarez/null-ls.nvim#140]
The current implementation of `loop.spawn` is working well, but it's caused mysterious issues in the past (e.g. #84), and offloading the task to Plenary would reduce the maintenance burden here. We'd also benefit from future improvements to Plenary, like async jobs. 

The `loop` module is pretty isolated, so this should be a pretty straightforward change. I want to investigate how other plugins are using Plenary jobs and make sure that they have all the features we need (timeouts are the only thing I'm unsure about).

**Comment by gegoune** [comment]
gitsigns has or will shortly, not sure if PR got merged yet, move away from plenary jobs to their own implementation. Might be worth checking their reasoning.

**Comment by jose-elias-alvarez** [comment]
Wow, interesting – I see the logic in [this issue](https://github.com/lewis6991/gitsigns.nvim/pull/341), and honestly I feel like a lot of what's there also applies to null-ls. I definitely have to think about this more.

**Comment by jose-elias-alvarez** [comment]
My conclusion is that the current implementation isn't ideal for null-ls (and is somewhat buggy), but I'm hopeful that async jobs will be an improvement, so I'm closing this for now to revisit later.
