### ISSUE TITLE
Ignore fixable rules for linters

### ISSUE THREAD

**Issue by sQVe** [jose-elias-alvarez/null-ls.nvim#1441]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Hey 👋,

I've been playing around with the `filter` option for `eslint_d`, since I'm trying to filter out all rules that are fixable. I'm running a very extensive ESLint config, and rules that are fixable just adds noise to the linting.

The `diagnostic` table, provided to the filter function has the following keys: `message`, `end_col`, `end_row`, `code`, `severity`, `row`, and `col`. One way to filter out fixable rules would be to have a massive table with the `code` of all the rules that I want to ignore. This isn't really feasible though, and a better solution would be if the `diagnostic` table would provide information if the rule is fixable or not. 

According to this issue https://github.com/eslint/eslint/issues/8949#issuecomment-315583596, it should be doable.

Would love some more insights here 🙏🏼 

### Help

No

**Comment by jose-elias-alvarez** [comment]
Our ESLint diagnostics don't currently provide this info but it should be a pretty straightforward change. When [processing and returning the diagnostic](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/7899b6d58af65d849cbb0497dc1d918a18dcd164/lua/null-ls/builtins/formatting/eslint.lua#L36) we have access to all of the JSON properties ESLint provides, so we'd want to make it available under the `user_data` key (see #622 for discussion).

**Comment by sQVe** [comment]
@jose-elias-alvarez Alright, sounds great 🎉 

I could give this a try, if you do not have time or ability to prioritize it, if you could provide some guidance and pointers on how you would like to start this. The only diagnostics builtin using the `user_data` is current `cspell`, and that is using the `from_patterns` helper rather than the `from_json`. I'm a bit unsure how I best would populate `user_data` with `fix` information.

**Comment by jose-elias-alvarez** [comment]
This is how I would do it (not really tested):

```lua
local handle_eslint_output = function(params)
    params.messages = params.output and params.output[1] and params.output[1].messages or {}
    if params.err then
        table.insert(params.messages, { message = params.err })
    end

    local parser = h.diagnostics.from_json({
        attributes = {
            severity = "severity",
            _fix = "fix", -- prefix with _ to make sure it's deleted after
        },
        severities = {
            h.diagnostics.severities["warning"],
            h.diagnostics.severities["error"],
        },
        adapters = {
            {
                user_data = function(entries)
                    return {
                        fixable = not not entries._fix,
                    }
                end,
            },
        },
    })

    return parser({ output = params.messages })
end
```
