### ISSUE TITLE
null-ls/utils/init.lua:282: attempt to index field 'fs' (a nil value)

### ISSUE THREAD

**Issue by Karhdo** [jose-elias-alvarez/null-ls.nvim#1450]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.7.0

### Dev Version?

- [X] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

MacOS

### Minimal Config

```Lua
local null_ls_status_ok, null_ls = pcall(require, "null-ls")
if not null_ls_status_ok then
	return
end

local formatting = null_ls.builtins.formatting
-- local diagnostics = null_ls.builtins.diagnostics

local sources = {
	formatting.prettier.with({ extra_args = { "--single-quote", "--tab-width 4", "--print-width 200" } }),
	formatting.black.with({ extra_args = { "--fast" } }),
	formatting.stylua,
}

null_ls.setup({
	debug = false,
	sources = sources,
	on_attach = function(client)
		-- Format on save
		if client.resolved_capabilities.document_formatting then
			vim.cmd([[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()]])
		end
	end,
})
```

### Steps to Reproduce

local null_ls_status_ok, null_ls = pcall(require, "null-ls")
if not null_ls_status_ok then
	return
end

local formatting = null_ls.builtins.formatting
-- local diagnostics = null_ls.builtins.diagnostics

local sources = {
	formatting.prettier.with({ extra_args = { "--single-quote", "--tab-width 4", "--print-width 200" } }),
	formatting.black.with({ extra_args = { "--fast" } }),
	formatting.stylua,
}

null_ls.setup({
	debug = false,
	sources = sources,
	on_attach = function(client)
		-- Format on save
		if client.resolved_capabilities.document_formatting then
			vim.cmd([[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()]])
		end
	end,
})

### Reproducibility Check

- [X] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

local null_ls_status_ok, null_ls = pcall(require, "null-ls")
if not null_ls_status_ok then
	return
end

local formatting = null_ls.builtins.formatting
-- local diagnostics = null_ls.builtins.diagnostics

local sources = {
	formatting.prettier.with({ extra_args = { "--single-quote", "--tab-width 4", "--print-width 200" } }),
	formatting.black.with({ extra_args = { "--fast" } }),
	formatting.stylua,
}

null_ls.setup({
	debug = false,
	sources = sources,
	on_attach = function(client)
		-- Format on save
		if client.resolved_capabilities.document_formatting then
			vim.cmd([[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()]])
		end
	end,
})

### Actual Behavior

local null_ls_status_ok, null_ls = pcall(require, "null-ls")
if not null_ls_status_ok then
	return
end

local formatting = null_ls.builtins.formatting
-- local diagnostics = null_ls.builtins.diagnostics

local sources = {
	formatting.prettier.with({ extra_args = { "--single-quote", "--tab-width 4", "--print-width 200" } }),
	formatting.black.with({ extra_args = { "--fast" } }),
	formatting.stylua,
}

null_ls.setup({
	debug = false,
	sources = sources,
	on_attach = function(client)
		-- Format on save
		if client.resolved_capabilities.document_formatting then
			vim.cmd([[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()]])
		end
	end,
})

### Debug Log

local null_ls_status_ok, null_ls = pcall(require, "null-ls")
if not null_ls_status_ok then
	return
end

local formatting = null_ls.builtins.formatting
-- local diagnostics = null_ls.builtins.diagnostics

local sources = {
	formatting.prettier.with({ extra_args = { "--single-quote", "--tab-width 4", "--print-width 200" } }),
	formatting.black.with({ extra_args = { "--fast" } }),
	formatting.stylua,
}

null_ls.setup({
	debug = false,
	sources = sources,
	on_attach = function(client)
		-- Format on save
		if client.resolved_capabilities.document_formatting then
			vim.cmd([[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()]])
		end
	end,
})

### Help

Yes

### Implementation Help

local null_ls_status_ok, null_ls = pcall(require, "null-ls")
if not null_ls_status_ok then
	return
end

local formatting = null_ls.builtins.formatting
-- local diagnostics = null_ls.builtins.diagnostics

local sources = {
	formatting.prettier.with({ extra_args = { "--single-quote", "--tab-width 4", "--print-width 200" } }),
	formatting.black.with({ extra_args = { "--fast" } }),
	formatting.stylua,
}

null_ls.setup({
	debug = false,
	sources = sources,
	on_attach = function(client)
		-- Format on save
		if client.resolved_capabilities.document_formatting then
			vim.cmd([[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()]])
		end
	end,
})

### Requirements

- [x] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
0.7.0 is not a supported version. You’ll need to update to 0.8 or greater (the latest stable release is 0.8.3). If you’re on macOS then you should easily be able to do so via Homebrew.
