### ISSUE TITLE
Shellcheck builtin not showing the messasge code

### ISSUE THREAD

**Issue by itaranto** [jose-elias-alvarez/null-ls.nvim#1463]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.8.3

### Dev Version?

- [X] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

Arch Linux

### Minimal Config

```Lua
-
```

### Steps to Reproduce

- Create the following file:

```sh
#!/bin/sh

ls ${some_var}
```
- Open it with Neovim

### Reproducibility Check

- [ ] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

- The diagnostic message should contain both the message: `Double quote to prevent globbing and word splitting`  and the shellcheck code: `SC2086`.

### Actual Behavior

- The diagnostic message is: `Double quote to prevent globbing and word splitting`

### Debug Log

-

### Help

Yes

### Implementation Help

It looks like the builting is parsing shellcheck output as JSON:

```lua
on_output = function(params)
            local parser = h.diagnostics.from_json({
                attributes = { code = "code" },
                severities = {
                    info = h.diagnostics.severities["information"],
                    style = h.diagnostics.severities["hint"],
                },
            })

            return parser({ output = params.output.comments })
        end,
```

I don't know how diagnostic builtins work but I tried running:

```shellcheck --format json1 --source-path=. --external-sources - < test.sh > output.json```

and the contents of `output.json` do have the shellcheck code:

```json
{
  "comments": [
    {
      "file": "-",
      "line": 3,
      "endLine": 3,
      "column": 4,
      "endColumn": 15,
      "level": "warning",
      "code": 2154,
      "message": "some_var is referenced but not assigned.",
      "fix": null
    },
    {
      "file": "-",
      "line": 3,
      "endLine": 3,
      "column": 4,
      "endColumn": 15,
      "level": "info",
      "code": 2086,
      "message": "Double quote to prevent globbing and word splitting.",
      "fix": {
        "replacements": [
          {
            "column": 4,
            "endColumn": 4,
            "endLine": 3,
            "insertionPoint": "afterEnd",
            "line": 3,
            "precedence": 7,
            "replacement": "\""
          },
          {
            "column": 15,
            "endColumn": 15,
            "endLine": 3,
            "insertionPoint": "beforeStart",
            "line": 3,
            "precedence": 7,
            "replacement": "\""
          }
        ]
      }
    }
  ]
}
```

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
You can [configure the source to show the code](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md#diagnostics-format). This isn’t done out-of-the-box for consistency with Neovim’s default display of LSP diagnostics, which do not show codes.

**Comment by itaranto** [comment]
> You can [configure the source to show the code](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md#diagnostics-format). This isn’t done out-of-the-box for consistency with Neovim’s default display of LSP diagnostics, which do not show codes.

OK, that's good to know.

Thanks for pointing me out to the right direction.
