### ISSUE TITLE
Using GCC as a source of diagnostics?

### ISSUE THREAD

**Issue by IndianBoy42** [jose-elias-alvarez/null-ls.nvim#148]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I think that GCC  would be nice to use gcc as a source of diagnostics. Some of my c++ projects (particularly embedded projects) aren't that compatible with clang, and thus clangd sometimes doesn't work super well. Just using the GCC error messages would be great. 

### Help

Yes

### Implementation help

The main hard part is probably parsing the output of GCC, I guess we would have to use `-fdiagnostics-format=json`. Also we should look for `compile_commands.json` or `compile_flags.txt`, or maybe just run `cmake --build` or `make/ninja` and get the output

**Comment by jose-elias-alvarez** [comment]
If it can output to JSON, it should be pretty straightforward to parse the output. I'm not at all familiar with the C++ ecosystem, so I can't do this on my own, but I can review / provide help with a PR for anyone who's interested in putting it together.

**Comment by jose-elias-alvarez** [comment]
I believe [this file](https://github.com/dense-analysis/ale/blob/f0887d3e6178482255f11aa378124aef3699245f/ale_linters/cpp/cc.vim) and [this file](https://github.com/dense-analysis/ale/blob/f0887d3e6178482255f11aa378124aef3699245f/autoload/ale/handlers/gcc.vim) contain what ALE uses to spawn and parse GCC for C++ files (though like I said, I'm not familiar with the ecosystem, so I could be wrong). Not sure why they're not using the JSON option, but it could be a good place to start.

**Comment by IndianBoy42** [comment]
I am starting on this work, I have one question, is there a builtin method for searching the working directory for things like `compile_commands.json` or cmake build directories?

**Comment by jose-elias-alvarez** [comment]
nvim-lspconfig has [a bunch of useful utils](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/util.lua) for handling paths, so I imagine there's something there we can use (we have it as a dependency here, so we're free to use them unconditionally).

**Comment by IndianBoy42** [comment]
So implementing this from scratch myself was quite hard, mainly to handle the project stuff, but recently I found [gccdiags](https://gitlab.com/andrejr/gccdiag) that can handle that for me. I just have to parse the output, they have some examples for `efm` and `diagnostic-languageserver`, I wonder if there is a straightforward translation from that?

**Comment by jose-elias-alvarez** [comment]
Yes, definitely. We'd just have to convert the diagnostic-languageserver regexes to their Lua equivalents and feed the lines to the [`from_pattern` helper](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/43dc39f704558ca4445ffbd89777dbe5367c2dd1/lua/null-ls/helpers.lua#L584). There's a bunch of built-ins using the helper that should serve as examples.

**Comment by jose-elias-alvarez** [comment]
Great! Feel free to open a PR whenever.

**Comment by jose-elias-alvarez** [comment]
Closed by #393.
