### ISSUE TITLE
Eslint_d: failed to decode json: Expected value but found invalid token at character 1

### ISSUE THREAD

**Issue by ltsfran** [jose-elias-alvarez/null-ls.nvim#1496]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.8.3

### Dev Version?

- [ ] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

macOS

### Minimal Config

```Lua
local formatting = null_ls.builtins.formatting -- to setup formatters
local diagnostics = null_ls.builtins.diagnostics -- to setup linters
local code_actions = null_ls.builtins.code_actions

local eslint_config = {
	prefer_local = "node_modules/.bin",
	condition = function(utils)
		return utils.root_has_file({
			".eslintrc",
			".eslintrc.js",
			".eslintrc.cjs",
			".eslintrc.yaml",
			".eslintrc.yml",
			".eslintrc.json",
		})
	end,
}

-- to setup format on save
local augroup = vim.api.nvim_create_augroup("LspFormatting", {})

-- configure null_ls
null_ls.setup({
	-- setup formatters & linters
	sources = {
		--  to disable file types use
		--  "formatting.prettier.with({disabled_filetypes = {}})" (see null-ls docs)
		-- formatting.prettier, -- js/ts formatter
		formatting.stylua, -- lua formatter
		formatting.eslint_d.with(eslint_config),
		diagnostics.eslint_d.with(eslint_config),
		code_actions.eslint_d.with(eslint_config),
...
```

### Steps to Reproduce

download attached config.
Find a tsx repo with an eslint configuration.
Open a tsx file

### Reproducibility Check

- [ ] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

I want to handle rules in base my .eslintrc.cjs config. It works with diagnostics.eslint but its a little slow. So I want to config the same with eslint_d but it doesnt work.

### Actual Behavior

Failed to decode json: Expected value but found invalid token at character 1
.eslintrc.js Bufnr[1]

### Debug Log

![Screenshot 2023-04-05 at 17 46 57](https://user-images.githubusercontent.com/38477522/230228245-f764859c-1062-4b1b-a8d1-68818a1e0d88.png)

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
So this works with vanilla `eslint` but not `eslint_d`? Have you tried running it from the command line?

**Comment by ltsfran** [comment]
Currently this is my config with builtins.eslint
![Screenshot 2023-04-05 at 18 20 38](https://user-images.githubusercontent.com/38477522/230232785-ef3e159d-25f1-4f13-bf9e-88a663a9562a.png)
And it works
![Screenshot 2023-04-05 at 18 21 11](https://user-images.githubusercontent.com/38477522/230232863-73cd2077-bfc8-489f-868e-d3af5ea7d343.png)
But when I do the same with eslint_d
![Screenshot 2023-04-05 at 18 23 36](https://user-images.githubusercontent.com/38477522/230233140-d98b7338-f376-4d5e-b356-612eb1f54816.png)
![Screenshot 2023-04-05 at 18 23 47](https://user-images.githubusercontent.com/38477522/230233196-64f988e9-385f-4c2f-9328-123803afcd2e.png)

**Comment by ltsfran** [comment]
In other projects it has worked without any problem, only in this one when I wanted to use a file with CJS extension it failed.

**Comment by ltsfran** [comment]
This is my repository https://github.com/ltsfran/portfolio

**Comment by jose-elias-alvarez** [comment]
`eslint_d` diagnostics in your project work on my end. Try [enabling debug mode](https://github.com/jose-elias-alvarez/null-ls.nvim#how-do-i-enable-debug-mode-and-get-debug-output) and see if there's any output from `eslint_d`. It can also help to run `eslint_d stop` from the command line when switching projects.

**Comment by ltsfran** [comment]
These are my logs
<img width="1680" alt="Screenshot 2023-04-06 at 12 16 34" src="https://user-images.githubusercontent.com/38477522/230449694-c4492d80-e831-4d10-be68-1efbde6e8551.png">
I just start to manage neovim, so I dont know what happened, but now it works with `eslint_d`.

**Comment by jose-elias-alvarez** [comment]
Looks like the same error that came up in #1484. If this an issue with `eslint_d` only and if it's replicable from the command line, then there's nothing we can do here. Since you say it's working, I'm going to close this for now.
