### ISSUE TITLE
Support ruby-lsp

### ISSUE THREAD

**Issue by luizkowalski** [jose-elias-alvarez/null-ls.nvim#1504]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Hey 👋🏻 
Any chance that null-ls could also support Shopify's [ruby-lsp](https://github.com/Shopify/ruby-lsp)?

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by jose-elias-alvarez** [comment]
This is an actual language server, so it's not something we would support here. [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#ruby_ls) already has a configuration, so that's where you'll want to set it up.

**Comment by luizkowalski** [comment]
oh yeah, sorry, that makes sense...getting started with neovim now, still getting some things right hahaha
thanks!
