### ISSUE TITLE
Range Formatting

### ISSUE THREAD

**Issue by AndreM222** [jose-elias-alvarez/null-ls.nvim#1508]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.9.0

### Dev Version?

- [X] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

windows

### Minimal Config

```Lua
vnoremap <S-f> <Cmd>lua vim.lsp.buf.format()<CR> --using prettier for js
```

### Steps to Reproduce

select with visual and try to use the format binding for range formatting

### Reproducibility Check

- [x] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

to format only selected lines

### Actual Behavior

formats everything

### Debug Log

none

### Help

Yes

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
I can't reproduce this - given your mapping and the following JavaScript file:

```javascript
console.log("hi") // no semicolon
console.log("hi") 
console.log("hi")
```

Selecting the second line in either visual or visual line mode and triggering the mapping only adds a semicolon to the second line. If you're sure this is a problem, can you please use a full minimal reproduction, including a standalone config + a file I can replicate the issue on?

**Comment by AndreM222** [comment]
```
-- Binding

nnoremap <S-f> <Cmd>lua vim.lsp.buf.format({ timeout_ms = 2000 })<CR>
vnoremap <S-f> <Cmd>lua vim.lsp.buf.format({ timeout_ms = 2000 })<CR>

-- Setup

local status, null_ls = pcall(require, "null-ls")
if (not status) then return end

null_ls.setup({
    border = 'single',
    sources = {
        -- Formatting
        null_ls.builtins.formatting.prettier.with({
        extra_args = function(params)
            return params.options
                and params.options.tabSize
                and {
                    "--tab-width",
                    params.options.tabSize,
                    "--trailing-comma none",
                    "--no-semi",
                    "--arrow-parens avoid",
                    "--single-quote",
                }
        end,
    }),
        null_ls.builtins.formatting.clang_format.with({
            extra_args = { "--style=Microsoft" }
        }),
        null_ls.builtins.formatting.autopep8,
        null_ls.builtins.formatting.latexindent,

        -- Diagnostics
        null_ls.builtins.diagnostics.eslint_d.with({
            diagnostics_format = '[eslint] #{m}\n(#{c})'
        }),
    },
})

```

**Comment by jose-elias-alvarez** [comment]
I still can't replicate this. Please add a minimal reproduction *according to the template* or I cannot help.

**Comment by AndreM222** [comment]
![Screenshot 2023-05-15 222357](https://github.com/jose-elias-alvarez/null-ls.nvim/assets/98118238/1937a5b5-402a-4233-af83-f78cdb3bf965)
![Screenshot 2023-05-15 222417](https://github.com/jose-elias-alvarez/null-ls.nvim/assets/98118238/96283fc6-bcf1-435f-a413-c28a868c024e)

btw also the linter spams a lot. is there any way to prevent it. this probably is something I should investigate with vim notify but does not hurt to ask.
