### ISSUE TITLE
Support passing detected LSP project root to external command

### ISSUE THREAD

**Issue by disrupted** [jose-elias-alvarez/null-ls.nvim#151]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I am currently in the process of migrating my configuration from EFM to null-ls. 

Some formatting providers need to know the project root to work correctly. For example `isort` needs it do distinguish between local and external imports. EFM has the variable `$ROOT` for this:
https://github.com/disrupted/dotfiles/blob/3efca0ac29500410cc34f6e85cd98c2df1a940a5/.config/nvim/lua/efm/isortd.lua#L4

It would be useful to have the same `$ROOT` arg available in null-ls in addition to the existing ones (`$FILENAME`, `$FILEEXT`, `$TEXT`).

### Help

Yes

**Comment by dsully** [comment]
This is great. Another approach would be to have "rootMarkers" that could be applied to each source like efm-langserver does.

That would allow me to specify `setup.cfg` for Python, which is one directory level deeper than my `.git`

**Comment by jose-elias-alvarez** [comment]
> This is great. Another approach would be to have "rootMarkers" that could be applied to each source like efm-langserver does.
> 
> That would allow me to specify `setup.cfg` for Python, which is one directory level deeper than my `.git`

If you're talking about passing a specific project root as an argument based on a root marker, this is already possible by modifying `args` or `extra_args`:

```lua
local my_modified_source = require("null-ls").builtins.diagnostics.not_a_real_source.with({
    extra_args = function(params)
        local root = require("lspconfig.util").root_pattern("root-marker")(params.bufname)
        return { "--root-dir", root }
    end,
})
```

I still support adding a `$ROOT` "shortcut", since I imagine it's a common case.
