### ISSUE TITLE
HTML linting support

### ISSUE THREAD

**Issue by imSafdarAwan** [jose-elias-alvarez/null-ls.nvim#153]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

need the support for the html we have linting for the css but not for the html

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

i am not a more experienced in the development i just know how to write the js that means i am  a front end developer if i could help you anyway i am ready to do so but as you know i just know js

**Comment by vuki656** [comment]
[This](https://github.com/htmlhint/HTMLHint) could potentially be used

**Comment by jose-elias-alvarez** [comment]
Which linter are you using for CSS? If HTMLHint works for you, it should be simple to add support, since it supports linting via `stdin` and seems to have a [JSON output format](https://htmlhint.com/docs/user-guide/usage/options#format).

**Comment by polyzen** [comment]
Doesn't look like we have any CSS linters yet, but stylelint would be the best choice. efm did not support HTMLHint, but I've been meaning to port rstcheck, stylelint, and yamllint over.

**Comment by imSafdarAwan** [comment]
> Which linter are you using for CSS? If HTMLHint works for you, it should be simple to add support, since it supports linting via `stdin` and seems to have a [JSON output format](https://htmlhint.com/docs/user-guide/usage/options#format).

but how can i link the html hint with null-ls
mainly thats the prob it does not recognizes the html hint

**Comment by vuki656** [comment]
> mainly thats the prob it does not recognizes the html hint

What have you tried?

**Comment by imSafdarAwan** [comment]
> > mainly thats the prob it does not recognizes the html hint
> 
> What have you tried?

it only wors by using an external linter like ale or syntastic but why would i need to install an external 
linter when lsp is there for it

**Comment by gegoune** [comment]
CSS linter stylelint has LSP implementation available right through lspconfig. Works really well. 

https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#stylelint_lsp

FYI

**Comment by polyzen** [comment]
Note: HTMLHint has not worked with a config file for over a year now:
https://github.com/htmlhint/HTMLHint/issues/504

**Comment by jose-elias-alvarez** [comment]
We added stylelint support in #188, so I'm going to close this issue. Feel free to open another if there is a specific linter you want supported.
