### ISSUE TITLE
`yamllint` diagnostic is not respecting rule specific ignore path

### ISSUE THREAD

**Issue by budimanjojo** [jose-elias-alvarez/null-ls.nvim#1531]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.9.0

### Dev Version?

- [X] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

Linux x86_64

### Minimal Config

```Lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.g.loaded_remote_plugins = ""
vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = {
            null_ls.builtins.diagnostics.yamllint
        },
        debug = true,
    })
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "jose-elias-alvarez/null-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end
```

### Steps to Reproduce

- Have `minimal_init.lua` like above.
- Have a file named `test.sops.yaml` and put this inside the file:
  ```
  ---
  hello:
      welcome: home
  ```
- Have another file named `.yamllint.yaml` and put this inside the file:
  ```
  ---
  extends: default
  rules:
    indentation:
      spaces: 2
      indent-sequences: consistent
      ignore: |
        *.sops.yaml
  ```
- Run `nvim --clean -u minimal_init.lua test.sops.yaml`.

### Reproducibility Check

- [X] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

There should be no diagnostic error. I run this command which match what `null-ls` use to run `yamllint` which returns no error:
`yamllint --format parsable test.sops.yaml`.

### Actual Behavior

It will show the diagnostic error: `wrong indentation: expected 2 but found 4` although I have specified `yamllint` to ignore `*.sops.yaml`. 

### Debug Log

Nothing

### Help

Yes, but I don't know how to start. I would need guidance

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
The issue is that null-ls is using `stdin`, so the equivalent command is actually this:

```sh
cat test.sops.yaml | yamllint --format parsable -
```

That command also reports an error. The ideal solution would be for `yamllint` to do one of the following:

1. Attempt to resolve a config file from the `cwd` in which the command is spawned
2. Add an `--stdin-filepath` flag to allow specifying the path to the actual file that `stdin` represents

Other than that there's not much we can do. We could change the whole source to use a temp file instead, but that has its own downsides.

**Comment by budimanjojo** [comment]
Thanks! I'll open an issue to `yamllint` side and close this.
