### ISSUE TITLE
rome linter 

### ISSUE THREAD

**Issue by maximyurevich** [jose-elias-alvarez/null-ls.nvim#1549]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

rome check diagnostic tool https://docs.rome.tools/linter/

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I tried to implement, but I don't know how to work with output

**Comment by jose-elias-alvarez** [comment]
Duplicate of #1511
