### ISSUE TITLE
Add filetype astro to prettier, prettierd, eslint, eslint_d

### ISSUE THREAD

**Issue by dobbbri** [jose-elias-alvarez/null-ls.nvim#1552]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Add filetype astro to prettier, prettierd, eslint, eslint_d

### Help

No

**Comment by jose-elias-alvarez** [comment]
I don't know about ESLint, but for Prettier, I can see that Astro [requires a plugin](https://github.com/withastro/prettier-plugin-astro). Our policy in the past has been to not include default filetypes that require this kind of additonal setup. The recommended approach is instead to use [the `extra_filetypes` config option](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md#filetypes).
