### ISSUE TITLE
Diagnostics cleared with multiple_files

### ISSUE THREAD

**Issue by nmrtv** [jose-elias-alvarez/null-ls.nvim#1555]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.10.0-dev-319+g5825d2f6c Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Dev Version?

- [ ] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

Manjaro Linux 22.1.1

### Minimal Config

```Lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
	local path_sep = on_windows and "\\" or "/"
	local result = table.concat({ ... }, path_sep)
	return result
end

vim.g.loaded_remote_plugins = ""
vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
	local null_ls = require("null-ls")
	-- add only what you need to reproduce your issue
	null_ls.setup({
		sources = {
			null_ls.builtins.diagnostics.mypy,
		},
		debug = true,
	})
end

local function load_plugins()
	-- only add other plugins if they are necessary to reproduce the issue
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			{
				"jose-elias-alvarez/null-ls.nvim",
				requires = { "nvim-lua/plenary.nvim" },
				config = null_ls_config,
			},
		},
		config = {
			package_root = package_root,
			compile_path = compile_path,
		},
	})
end

if vim.fn.isdirectory(install_path) == 0 then
	vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
	load_plugins()
	require("packer").sync()
else
	load_plugins()
	require("packer").sync()
end
```

### Steps to Reproduce

1. Install mypy (e.g. `pip install mypy`).
2. Create file `bad.py`:
```python
a: int = "something"
```
3. Create file `good.py`:
```python
a: int = 123
```
4. Open neovim.
5. Open file with diagnostics `:e bad.py`.
6. Open file without diagnostics `:split good.py`.

### Reproducibility Check

- [X] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

Diagnostics inside the first buffer should remain visible.

### Actual Behavior

Diagnostics in the first buffer disappear after opening another buffer without diagnostics.

### Debug Log

[TRACE 2023 m. gegužės 12 d. 14:14:04] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:97: starting null-ls client
[TRACE 2023 m. gegužės 12 d. 14:14:04] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:102: received LSP request for method initialize
[TRACE 2023 m. gegužės 12 d. 14:14:04] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:127: received LSP notification for method initialized
[TRACE 2023 m. gegužės 12 d. 14:14:04] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:127: received LSP notification for method textDocument/didOpen
[TRACE 2023 m. gegužės 12 d. 14:14:04] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG 2023 m. gegužės 12 d. 14:14:04] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:320: spawning command "mypy" at /home/hipis/tmp/nullls-test with args { "--hide-error-codes", "--hide-error-context", "--no-color-output", "--show-absolute-path", "--show-column-numbers", "--show-error-codes", "--no-error-summary", "--no-pretty", "--shadow-file", "/home/hipis/tmp/nullls-test/bad.py", "/home/hipis/tmp/nullls-test/.null-ls_814785_bad.py", "/home/hipis/tmp/nullls-test/bad.py" }
[TRACE 2023 m. gegužės 12 d. 14:14:05] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:204: error output: nil
[TRACE 2023 m. gegužės 12 d. 14:14:05] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:205: output: /home/hipis/tmp/nullls-test/bad.py:1:10: error: Incompatible types in assignment (expression has type "str", variable has type "int")  [assignment]

[TRACE 2023 m. gegužės 12 d. 14:14:05] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:181: received diagnostics from source 1
[TRACE 2023 m. gegužės 12 d. 14:14:05] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:182: { {
    bufnr = 1,
    code = "assignment",
    col = 9,
    end_col = 0,
    end_lnum = 1,
    filename = "/home/hipis/tmp/nullls-test/bad.py",
    lnum = 0,
    message = 'Incompatible types in assignment (expression has type "str", variable has type "int")',
    row = "1",
    severity = 1,
    source = "mypy"
  } }
[TRACE 2023 m. gegužės 12 d. 14:14:11] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:127: received LSP notification for method textDocument/didOpen
[TRACE 2023 m. gegužės 12 d. 14:14:11] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG 2023 m. gegužės 12 d. 14:14:11] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:320: spawning command "mypy" at /home/hipis/tmp/nullls-test with args { "--hide-error-codes", "--hide-error-context", "--no-color-output", "--show-absolute-path", "--show-column-numbers", "--show-error-codes", "--no-error-summary", "--no-pretty", "--shadow-file", "/home/hipis/tmp/nullls-test/good.py", "/home/hipis/tmp/nullls-test/.null-ls_728967_good.py", "/home/hipis/tmp/nullls-test/good.py" }
[TRACE 2023 m. gegužės 12 d. 14:14:12] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:204: error output: nil
[TRACE 2023 m. gegužės 12 d. 14:14:12] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:205: output: nil
[TRACE 2023 m. gegužės 12 d. 14:14:12] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:181: received diagnostics from source 1
[TRACE 2023 m. gegužės 12 d. 14:14:12] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:182: {}

### Help

Yes

### Implementation Help

The problem is with the `multiple_files` argument, when an empty `diagnostics` table is received. In this case diagnostics don't have bufnr and are cleared for other buffers in the function `handle_multiple_file_diagnostics`.

The solution is to check for an empy table in `handle_diagnostics`:
```lua
local handle_diagnostics = function(id, diagnostics, bufnr, multiple_files)
    local namespace = get_namespace(id)
    if multiple_files and next(diagnostics) ~= nil then
        handle_multiple_file_diagnostics(namespace, diagnostics)
    else
        handle_single_file_diagnostics(namespace, diagnostics, bufnr)
    end
end
```

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
See #577 for context on this behavior. I agreed with the original logic that dropping diagnostics is worse than the behavior you observed, but I'm happy to explore other solutions.

**Comment by nmrtv** [comment]
Well, in that case, null-ls is completely unusable with mypy. The problem is not only that diagnostics work only in the current buffer, but even after switching to another buffer, it stops working. Because when I switch from the buffer 1, to the buffer 2, diagnostics for 1 are gone until I restart neovim or change something there. Completely unreliable and useless.

**Comment by tgy** [comment]
mypy diagnostics only show up as an error message on my side

they don't show up as line by line underline diagnostic errors :/
