### ISSUE TITLE
vim runtime error 

### ISSUE THREAD

**Issue by imkerberos** [jose-elias-alvarez/null-ls.nvim#157]
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

VimR - SNAPSHOT-20210703.151310

### Steps to reproduce

open any file with lsp started.

### Expected behavior

Open file correctly.

### Actual behavior

Error executing vim.schedule lua callback: ...imView.bundle/Contents/Resources/runtime/lua/vim/uri.lua:116: attempt to index local 'uri' (a nil value)

### Debug log

null-ls log: /Users/I553461/.cache/nvim/null-ls.log
Detected filetype: go

5 source(s) active for this buffer:

Formatting: golines, goimports, gofmt
Diagnostics: codespell, misspell

### Help

No

### Implementation help

problem occurs after commit: 2e39b373d80acd60964bbe0f9a0e8781c3a7d2bd.

**Comment by jose-elias-alvarez** [comment]
I don't know about VimR, but what version of Neovim are you using? #156 describes how users on the Neovim master branch need to do a clean rebuild to handle the change from that commit (0.5 should continue working as usual).

**Comment by imkerberos** [comment]
Thank you. It's just the same as #156.
