### ISSUE TITLE
Add support for typst

### ISSUE THREAD

**Issue by pythops** [jose-elias-alvarez/null-ls.nvim#1585]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Support for [typst](https://github.com/typst/typst) 
Here is the lsp https://github.com/nvarner/typst-lsp

### Help

No

**Comment by jose-elias-alvarez** [comment]
It looks like the language server is [already supported via nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#typst_lsp). Unless there's a reason to prefer the CLI, that should be the preferred solution for linting / formatting / whatever else it supports.
