### ISSUE TITLE
After :PaqInstall I've been asked to GitHub login and my entire nvim crashes...

### ISSUE THREAD

**Issue by 205g0** [jose-elias-alvarez/null-ls.nvim#17]
Pretty much the title... 😶

Relevant config line which triggered `Username for 'https://github.com':` and the crash:
```
...
paq {'jose-elias-alvarez/null-ls.nvim'}
...

**Comment by jose-elias-alvarez** [comment]
Sorry, I'm not able to replicate this on my end with a minimal config for paq. To be clear, null-ls doesn't do anything special at all in terms of plugin management / installation (it's just a regular Git repository), so I think this is an issue on the plugin manager's side.

[This issue](https://github.com/savq/paq-nvim/issues/4) on the paq repo seems to describe a similar situation, so I'd take a look there. I also see this in their README, which could be relevant:

> NOTICE: Calling the paq function per package is deprecated. Users should now pass a list to the 'paq-nvim' module instead.

**Comment by 205g0** [comment]
Thanks for doing my homework haha... and yes, that was the issue. Closing.

Not related but since I just rewrite my init.vim to lua coming from coc, what will be the leading package manager in lua land? Paq seems to be more terse and Packer more mature is my first, uneducated guess.

**Comment by jose-elias-alvarez** [comment]
I think that’s accurate. Packer can handle quite a lot, including features like Luarocks dependencies that most people won’t use, so if your needs are simple you might want to go with something more lightweight.
