### ISSUE TITLE
Using multiple diagnostics sources on a same filtype seems to only report the last registred

### ISSUE THREAD

**Issue by gbprod** [jose-elias-alvarez/null-ls.nvim#172]
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.5.0

### Steps to reproduce

Add two diagnostics sources for the same filetype (eg. psalm and phpstan for php).

    null_ls.register(null_ls.builtins.diagnostics.phpstan)
    null_ls.register(null_ls.builtins.diagnostics.psalm)

When editing a file, only the last diagnostic source is displayed

### Expected behavior

Both sources should be displayed

### Actual behavior

Only the last registred source is displayed

### Debug log

```
null-ls log: /home/gilles/.cache/nvim/null-ls.log
Detected filetype: php

2 source(s) active for this buffer:

Diagnostics: psalm, phpstan
```

```
[DEBUG jeu. 09 sept. 2021 10:13:35] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: received LSP notification for method textDocument/didChange
[DEBUG jeu. 09 sept. 2021 10:13:35] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG jeu. 09 sept. 2021 10:13:35] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: spawning command ./vendor/bin/phpstan with args:
[DEBUG jeu. 09 sept. 2021 10:13:35] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: { "analyze", "--error-format", "json", "--no-progress", "/tmp/lua_SJ8fiz.php" }
[DEBUG jeu. 09 sept. 2021 10:13:35] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: spawning command ./vendor/bin/psalm with args:
[DEBUG jeu. 09 sept. 2021 10:13:35] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: { "--output-format=json", "--no-progress", "/tmp/lua_oAbIYy.php" }
[DEBUG jeu. 09 sept. 2021 10:13:36] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: error output: [{"severity":"error","line_from":38,"line_to":38,"type":"TooFewArguments","message":"Too few arguments for method Mediapa
\\Application\\Offers\\OffersGroupRepository::bysluginstorage saw 1","file_name":"..\/..\/..\/..\/..\/..\/..\/..\/tmp\/lua_oAbIYy.php","file_path":"\/tmp\/lua_oAbIYy.php","snippet":"        $result = $this->bySlugInStorage($slug);","se
bySlugInStorage","from":1026,"to":1041,"snippet_from":1001,"snippet_to":1049,"column_from":26,"column_to":41,"error_level":-1,"shortcode":25,"link":"https:\/\/psalm.dev\/025","taint_trace":null,"other_references":null}]

[DEBUG jeu. 09 sept. 2021 10:13:36] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: output: nil
[DEBUG jeu. 09 sept. 2021 10:13:36] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: error output: Note: Using configuration file /home/gilles/workspace/new-stack/mediapart/projects/baseadmin/basetunnel/phpstan.neon.

[DEBUG jeu. 09 sept. 2021 10:13:36] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: output: {"totals":{"errors":0,"file_errors":1},"files":{"/tmp/lua_SJ8fiz.php":{"errors":1,"messages":[{"message":"Method Mediapart\\Bas
cation\\Offers\\OffersGroupRepository::bySlugInStorage() invoked with 1 parameter, 2 required.","line":38,"ignorable":true}]}},"errors":[]}
[DEBUG jeu. 09 sept. 2021 10:13:36] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: received diagnostics from generators
[DEBUG jeu. 09 sept. 2021 10:13:36] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: { {
    code = 25,
    col = 26,
    end_col = 41,
    end_row = 38,
    message = "Too few arguments for method Mediapart\\Basetunnel\\Application\\Offers\\OffersGroupRepository::bysluginstorage saw 1",
    range = {
      end = {
        character = 40,
        line = 37
      },
      start = {
        character = 25,
        line = 37
      }
    },
    row = 38,
    severity = 1,
    source = "./vendor/bin/psalm"
  } }
```

### Help

Yes

**Comment by jose-elias-alvarez** [comment]
Hmm, that’s strange, in my experience this shouldn’t be a problem. I can see that both sources are running and the output looks correct, so I wonder what’s going on.

I won’t have time to test this out directly for about a week, but could you verify that both sources run correctly when registered individually? Also, does the order you register the sources matter (that is, if you register `phpstan` first, do you see those diagnostics)?

**Comment by gbprod** [comment]
> I won’t have time to test this out directly for about a week, but could you verify that both sources run correctly when registered individually? 

Yes, individually, sources run correctly

> Also, does the order you register the sources matter (that is, if you register `phpstan` first, do you see those diagnostics)?

It depends, sometimes I see no diagnostics but most of times I see only diagnostics of the last registred diagnostic.

> Edit: also, if both sources seem to be working normally when registered on their own, could you try adding the line `params = vim.deepcopy(params)` right below [this line](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/5d82f9c50cd89e2a0c63ca761024f764225c1d1e/lua/null-ls/helpers.lua#L159) and see if that makes a difference?

That makes the job ! I can see both diagnostics when adding the `deepcopy`.
I've tried to add this [here](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/5d82f9c50cd89e2a0c63ca761024f764225c1d1e/lua/null-ls/generators.lua#L21) but it does not works. 

Would you like me to create a PR ?

**Comment by vinicius507** [comment]
Sometimes when I'm editing files only one is reported in the virtual text, but when I open up `trouble.nvim` to check LSP Diagnostics, everything shows up. It might be related to this issue.

**Comment by gbprod** [comment]
I've you tried #179 ? Does it fix this issue ?

**Comment by vinicius507** [comment]
> I've you tried #179 ? Does it fix this issue ?

Haven't tried it yet, I'm going to try it later and report.

**Comment by vinicius507** [comment]
#179 does not seem to fix this issue, I think I misunderstood the context. I'll be opening up an issue reporting this behavior.
