### ISSUE TITLE
Errors when opening a bash script with multiple sources (output type leaking from one to the other?)

### ISSUE THREAD

**Issue by Gelio** [jose-elias-alvarez/null-ls.nvim#174]
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.6.0-dev+223-g384a43fe7

### Steps to reproduce

1. Install and enable `misspell` and `shellcheck` built-ins
2. Open a bash file, for example:

```sh
#!/bin/bash

set -euo pipefail

npm i -g bash-language-server
mispell
```

### Expected behavior

There is no error and the `mispell` word on the last line is detected as a misspell.

### Actual behavior

There's an error in `:messages`:

```
Error executing vim.schedule lua callback: vim/shared.lua:64: s: expected string, got table
stack traceback:
        vim/shared.lua:64: in function 'gsplit'
        vim/shared.lua:111: in function 'split'
        ...e/pack/packer/start/null-ls.nvim/lua/null-ls/helpers.lua:83: in function 'line_output_wrapper'
        ...e/pack/packer/start/null-ls.nvim/lua/null-ls/helpers.lua:198: in function 'handler'
        ...site/pack/packer/start/null-ls.nvim/lua/null-ls/loop.lua:62: in function 'cb'
        vim.lua:277: in function <vim.lua:277>
```

The error reappears each time I make some edits to the file, so probably there's something wrong with parsing the input.

Note that the error is only shown when there are misspell diagnostics for the file. When the file is valid, there's no error.

### Debug log

It says the debug log is at `/home/voreny/.cache/nvim/null-ls.log` but

```
14:31 $ cat /home/voreny/.cache/nvim/null-ls.log
cat: /home/voreny/.cache/nvim/null-ls.log: No such file or directory
```

`:NullLsInfo` gives:
```
null-ls log: /home/voreny/.cache/nvim/null-ls.log
Detected filetype: sh

2 source(s) active for this buffer:

Diagnostics: misspell, shellcheck
```

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

It may be related to https://github.com/jose-elias-alvarez/null-ls.nvim/issues/172, since both sources are running on the same type, and they expect different output type (json vs string). Maybe the output type is leaking from one source to the other?

**Comment by jose-elias-alvarez** [comment]
Yes, I agree that it could be related to the other issue. Could you try the fix I suggested there? If the issue is that the output is leaking, that might help.

**Comment by Gelio** [comment]
Good idea. With that line added, the problem is gone and I see the diagnostic from misspell, as expected, and `:messages` are empty.

Let me know if you'd like me to create a PR from that change. I'm not doing that yet as IMO that's a hacky way to solve it and maybe there is a better place to use `deepcopy` than at the beginning of the function :smile:

**Comment by jose-elias-alvarez** [comment]
Also, could you open up another issue for the log issue? Not sure what’s going on there but I want to look into it when I have a chance.

**Comment by Gelio** [comment]
> We definitely need to make the objects unique to prevent this issue and other unwanted interactions. A better place to use `deepcopy` might be [in this loop](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/5d82f9c50cd89e2a0c63ca761024f764225c1d1e/lua/null-ls/generators.lua#L21) to make sure each generator gets a unique copy. If that works, I’m happy to review a PR if you’re up for it.

Actually, I believe I don't have enough knowledge of this plugin and time right now to explore it, so my changes would be more of a shotgun debugging than actual quality changes. I'll leave it up to you, if you don't mind :slightly_smiling_face: 

> Also, could you open up another issue for the log issue? Not sure what’s going on there but I want to look into it when I have a chance.

Sure, I'll do that in a second

**Comment by jose-elias-alvarez** [comment]
No worries, thanks for looking into it. I’ll have the fix ready as soon as I can.

**Comment by Gelio** [comment]
Great, thanks!

Here's the issue about the log being missing: https://github.com/jose-elias-alvarez/null-ls.nvim/issues/175

**Comment by jose-elias-alvarez** [comment]
#198 should take care of the leaking issue.

**Comment by Gelio** [comment]
Great, thank you!
