### ISSUE TITLE
null-ls log is not created

### ISSUE THREAD

**Issue by Gelio** [jose-elias-alvarez/null-ls.nvim#175]
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.6.0-dev+223-g384a43fe7

### Steps to reproduce

Not sure, exactly. I have null-ls configured and working well with multiple sources.

1. Invoke `:NullLsInfo`
2. Try to read the null-ls log that is shown in the popup

### Expected behavior

The log file is there and contains some data.

### Actual behavior

The file listed in the path for null-ls log in `:NullLsInfo` does not exist.

`:NullLsInfo` gives:
```
null-ls log: /home/voreny/.cache/nvim/null-ls.log
Detected filetype: sh

2 source(s) active for this buffer:

Diagnostics: misspell, shellcheck
```

and then

```
14:31 $ cat /home/voreny/.cache/nvim/null-ls.log
cat: /home/voreny/.cache/nvim/null-ls.log: No such file or directory
```

There are other files in `~/.cache/nvim`:

```
16:02 $ ls -al ~/.cache/nvim
.rw-rw-r--  314 voreny  8 wrz 09:43 log
.rw-rw-r-- 257k voreny  9 wrz 15:12 lsp.log
.rw-rw-r--  58k voreny  7 wrz 08:04 packer.nvim.log

```

e.g.
```
16:02 $ tail ~/.cache/nvim/lsp.log
[ START ] 2021-09-09T14:50:09+0200 ] LSP logging initiated
[ START ] 2021-09-09T14:50:40+0200 ] LSP logging initiated
[ START ] 2021-09-09T14:50:44+0200 ] LSP logging initiated
[ START ] 2021-09-09T15:06:54+0200 ] LSP logging initiated
[ START ] 2021-09-09T15:07:20+0200 ] LSP logging initiated
[ START ] 2021-09-09T15:07:53+0200 ] LSP logging initiated
[ START ] 2021-09-09T15:08:05+0200 ] LSP logging initiated
[ START ] 2021-09-09T15:08:16+0200 ] LSP logging initiated
[ START ] 2021-09-09T15:07:26+0200 ] LSP logging initiated
[ START ] 2021-09-09T15:12:38+0200 ] LSP logging initiated
```

### Debug log

This is what the issue is about - it's missing :smile: 

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

```
16:02 $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

**Comment by jose-elias-alvarez** [comment]
Thanks for the info! The way the log path is generated is dead simple, and logging is handled entirely through Plenary’s log module, so this is either a misunderstanding of how that module works or an issue with the module itself. I’ll investigate when I have access to a computer again.

**Comment by bpinto** [comment]
Have you enabled debug mode?

**Comment by Gelio** [comment]
> Have you enabled debug mode?

No, I did not :crying_cat_face: 

---

 think this is one of the most embarrassing issues I have created. Of course, after enabling debug mode, `null-ls.log` is created as expected:

```
09:03 $ cat ~/.cache/nvim/null-ls.log
[DEBUG pią, 10 wrz 2021, 09:03:46] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: received LSP request for method initialize
[DEBUG pią, 10 wrz 2021, 09:03:46] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: received LSP notification for method initialized
[DEBUG pią, 10 wrz 2021, 09:03:46] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: received LSP notification for method textDocument/didOpen
[DEBUG pią, 10 wrz 2021, 09:03:46] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG pią, 10 wrz 2021, 09:03:46] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: spawning command shellcheck with args:
[DEBUG pią, 10 wrz 2021, 09:03:46] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: { "--format", "json", "-" }
[DEBUG pią, 10 wrz 2021, 09:03:46] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: spawning command misspell with args:
[DEBUG pią, 10 wrz 2021, 09:03:46] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: {}
[DEBUG pią, 10 wrz 2021, 09:03:46] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: error output: nil
[DEBUG pią, 10 wrz 2021, 09:03:46] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: output: []

[DEBUG pią, 10 wrz 2021, 09:03:46] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: error output: nil
[DEBUG pią, 10 wrz 2021, 09:03:46] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: output: nil
[DEBUG pią, 10 wrz 2021, 09:03:49] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: received LSP request for method shutdown
[DEBUG pią, 10 wrz 2021, 09:03:49] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:51: received LSP notification for method exit
```

I'll close the issue. Thank you @bpinto 

---

A side note: to avoid such confusion for other users of the plugin, I suggest 2 changes:
1. Change `:NullLsInfo` to show a message about enabling debug mode instead of the path to `null-ls.log` when debug mode is not enabled.

    This way it would be clearer that debug mode has to be enabled to see the log and that the log file is not created automatically.

2. Add information about enabling debug mode to the bug issue template in GitHub.

**Comment by jose-elias-alvarez** [comment]
Thank you for checking this out! I agree with both of your suggestions and will implement them shortly.
