### ISSUE TITLE
Silence subsequent errors if executable was not found

### ISSUE THREAD

**Issue by andersevenrud** [jose-elias-alvarez/null-ls.nvim#189]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

It would be nice to have an option that silences subsequent errors in the cases where an executable is not found.

Right now I'm getting spammed with the following when I don't have "luacheck" in my PATH:

```
Error executing vim.schedule lua callback: ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...e/pack/packer/start/null-ls.nvim/lua/null-ls/helpers.lua:149: command luacheck is not exec
utable (make sure it's installed and on your $PATH)
```

In addition to this error, vim expects me to press a key to resume normal operation. This gets annoying fast!

I have looked at the docs and issues, and I don't see any way to solve this myself unless I'm missing something very obvious (like a vim setting) :thinking: 

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by jose-elias-alvarez** [comment]
Are you using the same setup across multiple machines? One way to handle this would be to use `condition`:

```lua
local null_ls = require("null-ls")

local sources = {
    null_ls.builtins.formatting.stylua.with({
        condition = function()
            return vim.fn.executable("stylua") > 0
        end,
    }),
}
```

**Comment by andersevenrud** [comment]
Ah, of course. This didn't cross my mind when I was setting this up. Thanks!
