### ISSUE TITLE
Provide diagnostics for closed files in workspace

### ISSUE THREAD

**Issue by cblessing24** [jose-elias-alvarez/null-ls.nvim#194]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Provide diagnostics for all files in the current workspace irrespective of whether they are open in neovim or not.

Currently null-ls only provides diagnostics for files that are open in neovim as far as I know. I think providing diagnostics for closed files as well would be very useful for checking all diagnostics in the current workspace via telescope for example. Other language servers (e.g. pyright) have this functionality already.

### Help

No

**Comment by jose-elias-alvarez** [comment]
Sure, it's possible to implement something like this if a source supports it, though it would take some extra work, since the current diagnostics framework is set up to handle one buffer at a time. Is there a specific source you have in mind (e.g. a CLI program that can provide diagnostics for an entire project at once)? I know ESLint supports this, so I could try to put together a prototype when I have time.

**Comment by cblessing24** [comment]
I mainly use flake8, mypy and pylint to lint my Python code. Maybe flake8 would be a good place to start because it is already supported?

**Comment by jose-elias-alvarez** [comment]
Got it. For reference, how does pyright handle workspace diagnostics? Is it a separate command?

**Comment by cblessing24** [comment]
Honestly, I am not sure. I guess it just publishes diagnostics for all python files in the workspace instead of just the open ones over the protocol.

**Comment by jryom** [comment]
Just to chime in, `tsc` might be another good use for this. It's what [`coc-tsserver` uses to provide diagnostics for TypeScript project](https://github.com/neoclide/coc-tsserver/blob/68bb4634f345b70c8b2e8c48294dd3619eb5b810/package.json#L97-L101), using the `--watch` flag to update on workspace changes.

Would be nice to be able to configure something similar via `null-ls`.

**Comment by jose-elias-alvarez** [comment]
@jryom Could you try out #351 and let me know what you think? Unfortunately the architecture of null-ls makes it impossible to get output from a continuously-running process the way `coc-tsserver` does, so the experience is definitely worse, but I'd like to know if you think it's useful enough to justify supporting it in spite of the limitations I describe there.

**Comment by jose-elias-alvarez** [comment]
This feature is now supported in #376, which I plan on merging once null-ls fully migrates to Neovim 0.6.0.
