### ISSUE TITLE
failed to get info: buffer is not attached

### ISSUE THREAD

**Issue by horseinthesky** [jose-elias-alvarez/null-ls.nvim#195]
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.6.0-dev+259-g1c5833cb0

### Steps to reproduce

Install:
```
use {
  "neovim/nvim-lspconfig",
  requires = {
    {
      "glepnir/lspsaga.nvim",
      after = "nvim-lspconfig",
      config = function()
        require "config.lspsaga"
      end,
    },
    {
      "jose-elias-alvarez/null-ls.nvim",
      module = "null-ls",
    },
  },
  event = "BufReadPre",
  config = function()
    require "lsp"
  end,
}
```

`require "lsp"` runs
```
local lspconfig = require "lspconfig"
<other stuff>
local nls = require "null-ls"
nls.config {
  debug = true,
  debounce = 150,
  save_after_format = false,
  sources = {
    nls.builtins.formatting.prettier,
    nls.builtins.formatting.stylua,
    nls.builtins.code_actions.gitsigns,
    nls.builtins.formatting.isort,
    nls.builtins.formatting.black,
    nls.builtins.diagnostics.flake8,
  },
}

nls.setup {}
```

### Expected behavior

`null-ls` attached to the buffer and able to lint and format.

### Actual behavior

`null-ls` is not attached to the buffer.

Other lsp servers are attached fine.

### Debug log

null-ls: failed to get info: buffer is not attached

### Help

No

**Comment by jose-elias-alvarez** [comment]
I think the issue is that you are not calling `require("lspconfig")["null-ls"].setup` anywhere. The `nls.setup` method you are using is deprecated and won't work do anything if you have already called `nls.config`. 

Could you take a look at the [config documentation](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/CONFIG.md) and see if setting up the `lspconfig` integration solves your issue?

**Comment by horseinthesky** [comment]
> Could you take a look at the [config documentation](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/CONFIG.md) and see if setting up the `lspconfig` integration solves your issue?

Sorry. My bad.

With the following config everything works like a charm:
```
local nls = require "null-ls"
nls.config {
  diagnostics_format = "[#{s}] #{c}: #{m}",
  sources = {
    nls.builtins.code_actions.gitsigns,
    nls.builtins.formatting.prettier,
    nls.builtins.formatting.stylua.with {
      extra_args = { "--config-path", vim.fn.expand "~/.config/stylua/stylua.toml" },
    },
    nls.builtins.formatting.isort.with {
      extra_args = { "-l", "100" },
    },
    nls.builtins.formatting.black.with {
      extra_args = { "-l", "100" },
    },
    nls.builtins.diagnostics.flake8.with {
      extra_args = { "--ignore", "E501,W503" },
    },
    -- nls.builtins.diagnostics.mypy.with {
    --   extra_args = {
    --     "--show-column-numbers",
    --     "--ignore-missing-imports",
    --     "--disable-error-code",
    --     "name-defined",
    --     "--cache-dir",
    --     "/dev/null",
    --   },
    -- },
  },
}

lspconfig["null-ls"].setup {}
```
