### ISSUE TITLE
Code Action RPC error

### ISSUE THREAD

**Issue by vanhtuan0409** [jose-elias-alvarez/null-ls.nvim#197]
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.5.0

### Steps to reproduce

1. Enable null-ls builtin `code_actions.gitsign`
2. Trigger `Blame line` action by calling `vim.lsp.buf.code_action()`

Note: I have 2 LSP servers attached. 1 is Null-ls, the other is Gopls.

### Expected behavior

Action is performed and no error message. Wonder if 2 LSP servers attached is causing issue

### Actual behavior

Blame line popup appears but an error message is shown at the status line

![2021-09-16_21-55](https://user-images.githubusercontent.com/8175932/133635377-2d36e397-853e-46ec-929f-a46aaed9abd8.png)

### Debug log

![2021-09-16_21-58](https://user-images.githubusercontent.com/8175932/133635657-6fdfebaa-538b-4974-8cfe-1e5b71898e30.png)

### Help

No

**Comment by jose-elias-alvarez** [comment]
I can't reproduce this with the language servers I regularly use (`lua-language-server` and `tsserver`). Can you check if it happens with other language servers, too? If not I can try to set up `gopls` and investigate.

**Comment by vanhtuan0409** [comment]
Tested with tsserver and no error shown. Seems like it gopls issue. Tks you anyway :D

**Comment by vanhtuan0409** [comment]
Seems like nvim lsp client also sends request to gopls. Gopls then return error because it cannot handle NULLL_LS_CODE_ACTION command.

Do you know a way that we can mitigate this issue or supress the error msg?

**Comment by vanhtuan0409** [comment]
current builtin behaviour is to send code action command to all attached server.
therefore, `NULL_LS_CODE_ACTION` is accidentally sent to gopls, which answered with an error response. Default lsp handlers will logs any error response if exists
https://github.com/neovim/neovim/blob/v0.5.0/runtime/lua/vim/lsp/handlers.lua#L438
can override default `workspace/executeCommand` to supress error message as follow

```lua
local default_exe_handler = vim.lsp.handlers["workspace/executeCommand"]
vim.lsp.handlers["workspace/executeCommand"] = function(err, result, ctx, config)
  -- supress NULL_LS error msg
  local prefix = "NULL_LS"
  if err and err.message:sub(1, #prefix) == prefix then
    return
  end
  return default_exe_handler(err, result, ctx, config)
end
```

I will close the ticket but leave my workaround here in case anyone need it

**Comment by jose-elias-alvarez** [comment]
Thank you for looking into this! I'm going to re-open it since I'd like to see if I can improve the behavior (I can see that other servers log an error, which isn't ideal either).

**Comment by n3wborn** [comment]
Maybe I'm wrong but I've just [opened an issue](https://github.com/lewis6991/gitsigns.nvim/issues/386) on gitsigns repo today about code_actions not working on nightly. I prefer mentioning it just in case this could be related to this issue.
