### ISSUE TITLE
Avoid updating diagnostics in insert mode, part 2

### ISSUE THREAD

**Issue by jose-elias-alvarez** [jose-elias-alvarez/null-ls.nvim#199]
#136 documents my first failed attempt to implement this. Since then, I've come up with the idea to handle this in the RPC module, where we could check the current mode, store notifications in state, and unconditionally flush any stored notifications on `InsertLeave`. This allows us to leave the diagnostics module untouched and could potentially be expanded to other methods in the future.

Remaining potential issues:
- Checking the current mode could be unreliable if there is a delay between changing the text and receiving the notification
- Making sure that editing the text and exiting insert mode doesn't trigger a double notification

I'll start prototyping this and open a PR soon.

**Comment by p00f** [comment]
Is this relevant? https://gitlab.com/yorickpeterse/nvim-dd
