### ISSUE TITLE
Telescope code actions are broken

### ISSUE THREAD

**Issue by jose-elias-alvarez** [jose-elias-alvarez/null-ls.nvim#201]
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.6.0-dev+279-g9d5d72c38

### Steps to reproduce

1. Install the latest version of Telescope
2. Get code actions using `:Telescope lsp_code_actions`
3. Select a null-ls code action

### Expected behavior

The code action is applied. 

### Actual behavior

Neovim throws an error:

```
E5108: Error executing lua ...acker/start/telescope.nvim/lua/telescope/builtin/lsp.lua:262: attempt to index field 'arguments' (a nil value)
```

### Debug log

N/A

### Help

Yes

### Implementation help

This is caused by nvim-telescope/telescope.nvim#738. Fixing this on our end is simple, but I want to get verification that Telescope's behavior is in line with the LSP spec to see if it should be fixed upstream instead.

**Comment by jose-elias-alvarez** [comment]
Fixed by nvim-telescope/telescope.nvim#1274.

**Comment by ggsalas** [comment]
I think I have this issue. When I try to execute actions in a tsx file I see 
```E5108: Error executing lua [string ":lua"]:1: attempt to call field 'lsp_code_actions' (a nil value)                                                                                               
stack traceback:                                                                                                                                                                                   
        [string ":lua"]:1: in main chunk                                                                                                                                                           
Press ENTER or type command to continue  ```

I'm runing neovim 0.7 and I have updated all my plugins.

**Comment by jose-elias-alvarez** [comment]
@ggsalas Can you open an issue and put together a reproduction? I don't use Telescope anymore.

**Comment by fitrh** [comment]
@ggsalas https://github.com/nvim-telescope/telescope.nvim/commit/e7e90466de0571d39fe642cdfec1c577451b8be1

**Comment by jose-elias-alvarez** [comment]
Oh yeah, nice catch, looks like they're recommending using the standard code actions handler + `vim.ui.select`, which makes sense.
