### ISSUE TITLE
null-ls cannot prompt user input in code action

### ISSUE THREAD

**Issue by vanhtuan0409** [jose-elias-alvarez/null-ls.nvim#205]
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.5.0

### Steps to reproduce

1. Setup a new **async** generator from scratch, serving code action with
2. Return action func with prompt user input

```
{
  title = "my action",
  action = function()
    local input = vim.fn.input("Ask for input: ")
    print(input)
  end,
}
```

### Expected behavior

User get prompted for input
Code continue to executed after prompt

### Actual behavior

User get prompted for input
Seems like `vim.fn.input` does not return. Nothing is printed. Execution stopped without any logs (debug = true)

### Debug log

None

### Help

No

**Comment by jose-elias-alvarez** [comment]
I was able to get input from `vim.fn.input` in a code with the following:

```lua
local test_code_action = {
    method = require("null-ls.methods").internal.CODE_ACTION,
    generator = {
        fn = function(params, done)
            return done({
                {
                    title = "Replace line",
                    action = function()
                        local input = vim.fn.input("New line content: ")
                        vim.api.nvim_buf_set_lines(params.bufnr, params.row - 1, params.row, false, { input })
                    end,
                },
            })
        end,
        async = true,
    },
    filetypes = {},
}
require("null-ls").register(test_code_action)
```

Does this work on your end? Making async sources from scratch is a little finicky, but I think this should be okay.

**Comment by vanhtuan0409** [comment]
tested again and everything is working find now :D I don't know what changed, maybe plenary got some updates.
