### ISSUE TITLE
highlight about Diagnostic not work with nightly neovim

### ISSUE THREAD

**Issue by PangPangPangPangPang** [jose-elias-alvarez/null-ls.nvim#207]
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.6.0-dev+331-gaba397991

### Steps to reproduce

Common lsp_install config

### Expected behavior

Same highlight with other lsp server like tsserver

### Actual behavior

other lsp use highlight currently, but null_ls not.
other lsp:
![image](https://user-images.githubusercontent.com/8207475/134626960-a34bba4c-8392-49c7-ae41-e4cca5fe53a1.png)
null-ls:
![image](https://user-images.githubusercontent.com/8207475/134627141-1603c3eb-2c0d-4e4f-ad86-5d47e49aaba2.png)

### Debug log

[DEBUG Fri Sep 24 14:16:48 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: received LSP request for method shutdown
[DEBUG Fri Sep 24 14:16:48 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: received LSP notification for method exit
[DEBUG Fri Sep 24 14:16:53 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: received LSP request for method initialize
[DEBUG Fri Sep 24 14:16:53 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: received LSP notification for method initialized
[DEBUG Fri Sep 24 14:16:53 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: received LSP notification for method textDocument/didOpen
[DEBUG Fri Sep 24 14:16:53 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG Fri Sep 24 14:16:53 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: spawning command eslint_d with args:
[DEBUG Fri Sep 24 14:16:53 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: { "-f", "json", "--stdin", "--stdin-filename", "/Users/max/frontend/the-cat/packages/newCat/src/pages/authorManage/userBuiltForumReview/index.tsx" }
[DEBUG Fri Sep 24 14:16:53 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: spawning command codespell with args:
[DEBUG Fri Sep 24 14:16:53 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: { "-" }
[DEBUG Fri Sep 24 14:16:53 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: error output: nil
[DEBUG Fri Sep 24 14:16:53 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: output: nil
[DEBUG Fri Sep 24 14:16:53 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: error output: nil
[DEBUG Fri Sep 24 14:16:53 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: output: [{"filePath":"/Users/max/frontend/the-cat/packages/newCat/src/pages/authorManage/userBuiltForumReview/index.tsx","messages":[{"ruleId":"@typescript-eslint/no-explicit-any","severity":1,"message":"Unexpected any. Specify a different type.","line":15,"column":25,"nodeType":"TSAnyKeyword","messageId":"unexpectedAny","endLine":15,"endColumn":28,"suggestions":[{"messageId":"suggestUnknown","fix":{"range":[783,786],"text":"unknown"},"desc":"Use `unknown` instead, this will force you to explicitly, and safely assert the type is correct."},{"messageId":"suggestNever","fix":{"range":[783,786],"text":"never"},"desc":"Use `never` instead, this is useful when instantiating generic type parameters that you don't need to know the type of."}]},{"ruleId":"@typescript-eslint/no-explicit-any","severity":1,"message":"Unexpected any. Specify a different type.","line":16,"column":46,"nodeType":"TSAnyKeyword","messageId":"unexpectedAny","endLine":16,"endColumn":49,"suggestions":[{"messageId":"suggestUnknown","fix":{"range":[842,845],"text":"unknown"},"desc":"Use `unknown` instead, this will force you to explicitly, and safely assert the type is correct."},{"messageId":"suggestNever","fix":{"range":[842,845],"text":"never"},"desc":"Use `never` instead, this is useful when instantiating generic type parameters that you don't need to know the type of."}]},{"ruleId":"@typescript-eslint/no-explicit-any","severity":1,"message":"Unexpected any. Specify a different type.","line":23,"column":43,"nodeType":"TSAnyKeyword","messageId":"unexpectedAny","endLine":23,"endColumn":46,"suggestions":[{"messageId":"suggestUnknown","fix":{"range":[1180,1183],"text":"unknown"},"desc":"Use `unknown` instead, this will force you to explicitly, and safely assert the type is correct."},{"messageId":"suggestNever","fix":{"range":[1180,1183],"text":"never"},"desc":"Use `never` instead, this is useful when instantiating generic type parameters that you don't need to know the type of."}]},{"ruleId":"react-hooks/exhaustive-deps","severity":1,"message":"React Hook useCallback has a missing dependency: 'queryData'. Either include it or remove the dependency array.","line":37,"column":6,"nodeType":"ArrayExpression","endLine":37,"endColumn":8,"suggestions":[{"desc":"Update the dependencies array to be: [queryData]","fix":{"range":[1893,1895],"text":"[queryData]"}}]}],"errorCount":0,"warningCount":4,"fixableErrorCount":0,"fixableWarningCount":0,"source":"import React, { useState, useCallback } from 'react';\nimport { useSelectedRowKeys } from '@common/hooks/selectedRowKeys';\nimport { useMount } from '@common/hooks';\nimport { RootState, Dispatch } from 'store';\nimport EditColumnTable from '@components/editColumnTable';\nimport { Form, Row, Col, Button, Space, Pagination, message, Dropdown, Menu } from 'antd';\nimport { connect } from 'react-redux';\nimport formItems, { columnConfig } from './userBuiltForumConfig';\nimport { UserBuiltForumItem, UserBuiltForumModalProps, UserBuiltForumStatus } from './models/userBuiltForumItem';\nimport Style from './userBuiltForum.scss';\nimport { ColumnsType } from 'antd/lib/table';\nimport { table_helper } from '@common/utils/table_helper';\n\ninterface UserBuiltForumProps {\n  refreshData: (query?: any) => void;\n  handleExport: ({ query, config }: { query: any; config: ColumnsType<UserBuiltForumItem> }) => void;\n  queryData: (page: number) => void;\n  modifyStatus: ({ record, status }: { record: UserBuiltForumItem; status: UserBuiltForumStatus }) => void;\n  changePageSize: (size: number) => void;\n  userBuiltForumState: UserBuiltForumModalProps;\n}\n\nfunction UserBuiltForumContainer<Values = any>(props: UserBuiltForumProps) {\n  const { refreshData, queryData, modifyStatus, changePageSize, handleExport } = props;\n  const [form] = Form.useForm();\n  const [modifyColumn, setModifyColumn] = useState<boolean>(false);\n  const { userBuiltForumState } = props;\n  const [selectedRowKeys, setSelectedRowKeys, rowSelection, getExportSelected, onCopyFIDs] = useSelectedRowKeys<UserBuiltForumItem>('forum_id', userBuiltForumState);\n  const config: ColumnsType<UserBuiltForumItem> = columnConfig({\n    modifyStatus: (record: UserBuiltForumItem, status: UserBuiltForumStatus) => {\n      modifyStatus({ record, status });\n    },\n  });\n\n  const onChangePage = useCallback((page: number) => {\n    queryData(page);\n  }, []);\n\n  const clearAndRefresh = (query?: Values) => {\n    setSelectedRowKeys([]);\n    refreshData(query);\n  };\n\n  useMount(() => {\n    clearAndRefresh();\n  });\n\n  const onExport = async () => {\n    handleExport({ query: form.getFieldsValue(), config });\n  };\n\n  const onExportSelected = async () => {\n    const exportItems = getExportSelected();\n    if (exportItems === undefined) {\n      return;\n    }\n    const modifyConfig = config.filter(item => item.title !== 'Forum');\n    modifyConfig.unshift({ title: 'Forum Name', dataIndex: 'forum_name' });\n    modifyConfig.unshift({ title: 'Forum', dataIndex: 'forum_id' });\n    table_helper.exportToCsv(exportItems, modifyConfig, 'user_built_data');\n    message.success('Export success!');\n  };\n  const onFinish = (query?: Values) => {\n    clearAndRefresh(query);\n  };\n\n  const menu = (\n    <Menu>\n      <Menu.Item>\n        <a target=\"_blank\" onClick={onExport}>\n          Export Batch Items\n        </a>\n      </Menu.Item>\n      <Menu.Item>\n        <a target=\"_blank\" onClick={onExportSelected}>\n          {`Export Selected Items(${selectedRowKeys.length})`}\n        </a>\n      </Menu.Item>\n    </Menu>\n  );\n\n  return (\n    <Form form={form} className=\"ant-advanced-search-form\" onFinish={onFinish}>\n      <div className={Style.antAdvancedCard}>\n        <Row gutter={24} justify=\"start\">\n          {formItems(form)}\n        </Row>\n        <Row justify=\"end\">\n          <Col span={24} style={{ textAlign: 'right' }}>\n            <Button\n              style={{ margin: '0 8px' }}\n              onClick={() => {\n                form.resetFields();\n              }}\n            >\n              Clear\n            </Button>\n            <Button\n              style={{ margin: '0 8px' }}\n              onClick={() => {\n                setModifyColumn(true);\n              }}\n            >\n              Custom Column\n            </Button>\n            <Button style={{ margin: '0 8px' }} htmlType=\"submit\" type=\"primary\">\n              Search\n            </Button>\n            <Button style={{ margin: '0 8px' }} type=\"primary\" onClick={onCopyFIDs}>\n              {`Copy Selected FIDs(${selectedRowKeys.length})`}\n            </Button>\n            <Dropdown overlay={menu} placement=\"bottomCenter\">\n              <Button style={{ margin: '0 8px' }} type=\"primary\">\n                {`Export(${selectedRowKeys.length})`}\n              </Button>\n            </Dropdown>\n          </Col>\n        </Row>\n      </div>\n      <Space />\n      <div className={Style.antAdvancedCard}>\n        <EditColumnTable<UserBuiltForumItem>\n          rowKey=\"forum_id\"\n          rowSelection={rowSelection}\n          showEdit={modifyColumn}\n          storeKey={'user_built_forum'}\n          columns={config}\n          dataSource={userBuiltForumState.list}\n          loading={userBuiltForumState.loading}\n          scroll={{ x: 2300 }}\n          pagination={false}\n          style={{ paddingBottom: '10px' }}\n        />\n        <Pagination\n          pageSize={userBuiltForumState.pageSize}\n          current={userBuiltForumState.currentPage}\n          total={userBuiltForumState.total}\n          onChange={onChangePage}\n          onShowSizeChange={(_, size) => {\n            changePageSize(size);\n            clearAndRefresh();\n          }}\n        />\n      </div>\n    </Form>\n  );\n}\nconst mapState = (state: RootState) => ({\n  userBuiltForumState: state.userBuiltForumModel,\n});\n\nconst mapDispatch = (dispatch: Dispatch) => ({\n  refreshData: dispatch.userBuiltForumModel.refreshData,\n  handleExport: dispatch.userBuiltForumModel.handleExport,\n  queryData: dispatch.userBuiltForumModel.queryData,\n  modifyStatus: dispatch.userBuiltForumModel.modifyStatus,\n  changePageSize: dispatch.userBuiltForumModel.changePageSize,\n});\n\nexport default connect(mapState, mapDispatch)(UserBuiltForumContainer);\n","usedDeprecatedRules":[]}]
[DEBUG Fri Sep 24 14:16:53 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: received diagnostics from generators
[DEBUG Fri Sep 24 14:16:53 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: { {
    code = "@typescript-eslint/no-explicit-any",
    col = 25,
    end_col = 28,
    end_row = 15,
    message = "Unexpected any. Specify a different type.",
    range = {
      end = {
        character = 27,
        line = 14
      },
      start = {
        character = 24,
        line = 14
      }
    },
    row = 15,
    severity = 2,
    source = "eslint_d"
  }, {
    code = "@typescript-eslint/no-explicit-any",
    col = 46,
    end_col = 49,
    end_row = 16,
    message = "Unexpected any. Specify a different type.",
    range = {
      end = {
        character = 48,
        line = 15
      },
      start = {
        character = 45,
        line = 15
      }
    },
    row = 16,
    severity = 2,
    source = "eslint_d"
  }, {
    code = "@typescript-eslint/no-explicit-any",
    col = 43,
    end_col = 46,
    end_row = 23,
    message = "Unexpected any. Specify a different type.",
    range = {
      end = {
        character = 45,
        line = 22
      },
      start = {
        character = 42,
        line = 22
      }
    },
    row = 23,
    severity = 2,
    source = "eslint_d"
  }, {
    code = "react-hooks/exhaustive-deps",
    col = 6,
    end_col = 8,
    end_row = 37,
    message = "React Hook useCallback has a missing dependency: 'queryData'. Either include it or remove the dependency array.",
    range = {
      end = {
        character = 7,
        line = 36
      },
      start = {
        character = 5,
        line = 36
      }
    },
    row = 37,
    severity = 2,
    source = "eslint_d"
  } }

### Help

No

**Comment by gegoune** [comment]
Perhaps this: https://github.com/neovim/neovim/issues/14090#issuecomment-921312955 ?

**Comment by jose-elias-alvarez** [comment]
Are you doing anything to customize the highlight groups? Everything seems to be working normally on my end, and I don't think any of the recent changes to the diagnostic API should cause this. I'd need more information to reproduce the issue.

**Comment by PangPangPangPangPang** [comment]
> Are you doing anything to customize the highlight groups? Everything seems to be working normally on my end, and I don't think any of the recent changes to the diagnostic API should cause this. I'd need more information to reproduce the issue.

Sorry I don`t know how to debug. Maybe you can find some clues from my dotfile ?
https://github.com/PangPangPangPangPang/mxvim/blob/master/neovim_config/lua/lsp/lsp_nullls.lua
https://github.com/PangPangPangPangPang/mxvim/blob/master/neovim_config/lua/config/_lsp_config.lua

**Comment by PangPangPangPangPang** [comment]
> Perhaps this: [neovim/neovim#14090 (comment)](https://github.com/neovim/neovim/issues/14090#issuecomment-921312955) ?

Thank you for replying but I don't think this is the reason.
I have replaced it with the new one and diagnostic of tsserver works fine.

**Comment by jose-elias-alvarez** [comment]
At a glance, you have quite a few custom highlight groups defined. I'd start by commenting out the highlight-related parts of your config and see what's causing the issue. The breakage is almost definitely related to the linked Neovim issue. 

As far as I know, null-ls highlighting works as expected with default settings, since I don't do any highlight customization and am unable to reproduce this. I'd need more detailed reproduction steps to see if this is an issue on our end.

**Comment by PangPangPangPangPang** [comment]
Sorry，nightly neovim change all 'Warning' to 'Warn' and I I ignored them.
