### ISSUE TITLE
Add builtin for Stylelint

### ISSUE THREAD

**Issue by mrjones2014** [jose-elias-alvarez/null-ls.nvim#227]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I use `stylelint` (https://stylelint.io)  for additional linting of CSS and SCSS files. Would love to have a built in source for it.

### Help

Yes

### Implementation help

Here's what I've got so far to try to make a custom source for stylelint. When I run `:NullLsInfo` it shows `stylelint` source is active, but it is not printing the params table so I can't figure out how to properly parse the output.

```lua
    -- stylelint is not built-in
    {
      name = 'stylelint',
      method = null_ls.methods.DIAGNOSTICS, -- null_ls is defined above as local null_ls = require('null-ls')
      filetypes = { 'scss', 'sass', 'css' },
      generator = null_ls.generator({
        command = './node_modules/.bin/stylelint',
        args = { '--formatter', 'json', '--stdin-filename', '%filepath' },
        format = 'json',
        check_exit_code = function(code)
          return code == 0
        end,
        on_output = function(params)
          print(vim.inspect(params))
          --[[ local parser = require('null-ls.helpers').diagnostics.from_json({
            attributes = {},
          })

          return parser({ output = params.output }) ]]
        end,
      }),
    },
```

**Comment by polyzen** [comment]
https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#stylelint
https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#stylelint-1

**Comment by mrjones2014** [comment]
@polyzen Whoops, my bad, I made a typo when I did cmd+f to search that page! thanks!
