### ISSUE TITLE
[Bug]: `markdownlint` as formatter don't work properly

### ISSUE THREAD

**Issue by younger-1** [jose-elias-alvarez/null-ls.nvim#233]
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.5

### Steps to reproduce

Good situation(autofix available): If all the lint problems found by `markdownlint` as linter can be fixed by using `markdownlint --fix <file>`, that is the output of `markdownlint --fix <file>` is empty, `null-ls` will fix all these problem by using `markdownlint` as formatter.

Bad situation(autofix not available): Once there is a lint problem doesn't have autofix provided by `markdownlint`, `null-ls` will not format the file at all even there are other problems which autofix is avaiable. The expected behavior can be achieved by the command `markdownlint --fix <file>` which will fix all problems with autofix and output problems which doesn't have autofix.

1. config and register `markdownlint` as formatter and linter for markdown file
2. open the file `demo.md` with following content:
3. try to format the file with `null-ls`

```md
# Tools

## SSH

#### Links (autofix not available)

https://github.com/sshuttle/sshuttle (autofix available with `markdownlint`)
```

### Expected behavior

The `demo.md` has two problem, one is `#### Links` which has `MD001/heading-increment` problem and the autofix not available for it, another is the last line which has `MD034/no-bare-urls` problem and autofix is available.

The file should be formatted as the following after formatting by `null-ls`, which is done right with shell command `markdownlint --fix demo.md --config <markdownlint.json>`.

```md
# Tools

## SSH

#### Links (autofix not available)

<https://github.com/sshuttle/sshuttle> (autofix available with `markdownlint`)
```

### Actual behavior

The `demo.md` doesn't get formatted

### Debug log

```log
null-ls log: /home/young/.cache/nvim/null-ls.log
Detected filetype: markdown

2 source(s) active for this buffer:

Formatting: markdownlint
Diagnostics: markdownlint
```

### Help

No

**Comment by jose-elias-alvarez** [comment]
Thanks for the excellent reproduction steps! 1c482001bd3dc044f973efc474919b33a9994e5a seems to fix the issue. Can you try updating and let me know?

**Comment by younger-1** [comment]
Good job! It works as expected. Thank you!
