### ISSUE TITLE
Sequential formatting creates undo history for intermediate results

### ISSUE THREAD

**Issue by disrupted** [jose-elias-alvarez/null-ls.nvim#234]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

When using multiple formatters (like isort and black for Python), the intermediate formatting results are applied to the buffer creating unwanted history entries in the undo tree.

I found this comment from Jose mentioning the issue with a potential solution, so figured I would open an issue for keeping track of it

> I think it's possible if we use a temporary buffer. [...] I can see that one advantage is to avoid creating 2 separate undo steps. I'll look into it, but I think we can consider it as a future improvement.

https://github.com/jose-elias-alvarez/null-ls.nvim/pull/93#issuecomment-894927671

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

haven't worked with temporary buffers, but it seems like an interesting approach

**Comment by jose-elias-alvarez** [comment]
For reference, the approach I had in mind was:

1. Load the current buffer's content into a new buffer;
2. Sequentially apply the edits to the temporary buffer without diffing them;
3. After all edits have been applied, diff the temporary buffer against the original buffer;
4. Apply the diffed edits to the original buffer; and
5. Unload the temporary buffer.

This would require shuffling around the formatting logic and would also require some work to make the experience seamless (for example, I think we'd have to save and restore the user's previous buffer) but it should be possible.

**Comment by jose-elias-alvarez** [comment]
I played around with this and found that it's more complicated than I expected. Even if everything goes as I described, there's a ton of edge cases / possible bad interactions, so I don't plan on working on this.
