### ISSUE TITLE
[Feature]: show the fully resolved command for a provider

### ISSUE THREAD

**Issue by kylo252** [jose-elias-alvarez/null-ls.nvim#264]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Store the fully resolved command as a string/list similar to `client.cmd`. This is useful for debugging purposes mostly. It would also allows a streamlined method that can be used in `NullLsInfo` for example.

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

Example:

```lua
local sources = {
    null_ls.builtins.formatting.shfmt.with({
        extra_args = { "-i", "2", "-ci" }
      })
  }
```

now if I try this `lua print(vim.inspect((require("null-ls.builtins.formatting")["shfmt"]))`

```lua
{
  _opts = {
    args = <function 1>, -- we need the results of this somwehere
    command = "shfmt",
    on_output = <function 2>,
    suppress_errors = true,
    to_stdin = true
  },
  filetypes = { "sh" },
  method = "NULL_LS_FORMATTING",
  name = "shfmt",
  with = <function 3>,
  <metatable> = {
    __index = <function 4>
  }
}
```

Related: #106

**Comment by jose-elias-alvarez** [comment]
6306fd47af803062f31709e82a46139f97f9b03d makes it so that `_last_args` and `_last_command` are set whenever the generator runs. Combined with `get_sources`, which was added in 0b196b3b2c395f0d822fc79eb9024d462cceb702, `:lua print(vim.inspect(require("null-ls").get_source("shfmt")))` will give you the following output:

```lua
{ {
    filetypes = {
      sh = true
    },
    generator = {
      async = true,
      fn = <function 1>,
      opts = {
       -- set when the generator runs for the first time, nil otherwise
        _last_args = { "-filename", "/Users/jose/test.sh", "-i", "2", "-ci" },
        _last_command = "shfmt",
        args = <function 2>,
        command = "shfmt",
        ignore_stderr = true,
        on_output = <function 3>,
        to_stdin = true
      }
    },
    id = 9,
    methods = {
      NULL_LS_FORMATTING = true
    },
    name = "shfmt"
  } }
```
