### ISSUE TITLE
Execute rubocop via bundler

### ISSUE THREAD

**Issue by strayer** [jose-elias-alvarez/null-ls.nvim#270]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

The projects I'm using usually include rubocop installed via bundler. This requires executing rubocop via `bundle exec rubocop` since simply running `rubocop` will most likely not use the currect rubocop version.

Right now I'm configuring null-ls like this:

```lua
require("null-ls").config({
  sources = {
    require("null-ls").builtins.diagnostics.rubocop.with({
      command = "bundle",
      args = { "exec", "rubocop", "-f", "json", "--stdin", "$FILENAME" }
    }),
    require("null-ls").builtins.formatting.rubocop.with({
      command = "bundle",
      args = {"exec", "rubocop", "--auto-correct", "-f", "quiet", "--stderr", "--stdin", "$FILENAME" }
    }),
  },
})
```

But this is pretty verbose and duplicates the args that are already set by null-ls (making updates annoying if null-ls updates something there).

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

Not sure if there should maybe just be a separate builtin like `builtins.diagnostics.rubocop_bundler` or if this can be somehow integrated in the existing builtins. I may be able to open a PR with some guidance which way would fit the style of null-ls.

**Comment by jose-elias-alvarez** [comment]
You could try extending the existing args:

```lua
require("null-ls").config({
    sources = {
        require("null-ls").builtins.diagnostics.rubocop.with({
            command = "bundle",
            args = vim.list_extend({ "exec", "rubocop" }, require("null-ls").builtins.diagnostics.rubocop._opts.args),
        }),
    },
})
```

I'm not opposed to including it as a separate built-in (I'm not sure there's a good way to incorporate it into the existing built-in) but if the above workaround works, I think this might be best as a user config option, especially since binstubs seem like a great solution.

**Comment by jose-elias-alvarez** [comment]
I looked into allowing `commands` to be a list as part of #349 but found that it adds too much complexity for such a small (and in my opinion cosmetic) improvement. The assumption that `command` is a string runs deep, and there's a surprising number of edge cases, so I'm going to close this.
