### ISSUE TITLE
Formatting for multiple (different language) buffers not working

### ISSUE THREAD

**Issue by danjenson** [jose-elias-alvarez/null-ls.nvim#277]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.5.1

### null-ls config

```lua
	use({
		"jose-elias-alvarez/null-ls.nvim",
		after = "nvim-lspconfig",
		config = function()
			local x = require("null-ls")
			x.config({
				-- format on save set in autocmds
				sources = {
					-- [web] shell: sudo npm i -g prettierd
					x.builtins.formatting.prettierd,
					-- [markdown] shell: sudo npm i -g write-good
					x.builtins.diagnostics.write_good,
					-- [R] R: install.packages('formatR')
					x.builtins.formatting.format_r,
					-- [rust] shell: rustup component add rustfmt [--toolchain nightly]
					x.builtins.formatting.rustfmt,
					-- [lua] shell: cargo install stylua
					x.builtins.formatting.stylua,
					-- [lua] shell: sudo luarocks install luacheck [lanes]
					x.builtins.diagnostics.luacheck,
					-- [python] shell: pip install yapf
					x.builtins.formatting.yapf,
				},
			})
		end,
	})
```

### Steps to reproduce

Open an html buffer, i.e. `index.html`, format on save works fine, then open another buffer, i.e. `main.py` -- formatting on save doesn't work. This is in my`autocmds.lua` file:
```lua
vim.cmd('autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()')
```

### Expected behavior

Different languages in separate buffers are formatted according to their respective formatters.

### Actual behavior

Only the file type for the first buffer opened is active.

### Debug log

N/A - no errors

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I would need to understand where the entry point is for each buffer.

**Comment by jose-elias-alvarez** [comment]
Feel free to reopen this with more info if you're still having problems.
