### ISSUE TITLE
Show error messages when command failed?

### ISSUE THREAD

**Issue by wookayin** [jose-elias-alvarez/null-ls.nvim#280]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I wish there were some way to display error messages when underlying command (e.g., formatter) failed. Currently, when something goes wrong and the formatter fails, nothing happens silently.

For example, I had an older version of `isort` (or in case `isort` is not installed -- which I think is a very common failure case) which exited with non-zero-exit code, after the formatting request `:lua vim.lsp.buf.formatting_sync()`.

By turning on the debug mode I was able to see the log message and figured out why the formatter was failing.
```
[DEBUG Sat Oct 23 18:39:25 2021] .../.vim/plugged/null-ls.nvim/lua/null-ls/utils.lua:51: error output: /usr/local/miniconda3/lib/python3.7/site-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
Traceback (most recent call last):
  File "/usr/local/miniconda3/bin/isort", line 11, in <module>
    sys.exit(main())
  File "/usr/local/miniconda3/lib/python3.7/site-packages/isort/main.py", line 343, in main
    SortImports(file_=file_, write_to_stdout=True, **arguments)
TypeError: type object got multiple values for keyword argument 'write_to_stdout'
```

To make troubleshooting even more convenient, can we detect such failure cases when the prettier/linter program has failed? If we could get the error message without turning on the debug mode, that'd be even better. Thanks!

**Comment by jose-elias-alvarez** [comment]
I don't have any bright ideas about how to solve this in a consistent way, and I think that showing errors of this type in a log (vs. showing them immediately) is consistent with general Neovim LSP behavior. Feel free to reopen this if you have any ideas.
