### ISSUE TITLE
Formatter and FormattingOptions (e.g., tabSize)

### ISSUE THREAD

**Issue by wookayin** [jose-elias-alvarez/null-ls.nvim#310]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

LSP formatting APIs, such as`vim.lsp.buf.formatting_sync(formattingOptions, timeout)`, are following LSP specification as per the following:

https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#formattingOptions

where FormattingOptions look like:
```typescript
interface FormattingOptions {
	tabSize: uinteger;
	insertSpaces: boolean;
	trimTrailingWhitespace?: boolean;
	insertFinalNewline?: boolean;
	trimFinalNewlines?: boolean;
	[key: string]: boolean | integer | string;
}
```

It looks like that null-ls.nvim is not aware of such FormattingOptions; e.g., they are never passed to underlying formatter command-line programs.

For example, I hoped that `vim.lsp.buf.formatting_sync({tabSize = 2})` should result in formatting (e.g., yapf for python) but with a specifically intended tab size, but these arguments are simply ignored. This would be useful when one is using non-standard indent size (e.g., tabsize = 2 in python following Google's convention) where `tabsize,indentsize,shiftwidth` are all set to 2.

It'd be great to support other source-specific options in some ways.

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#formattingOptions

**Comment by jose-elias-alvarez** [comment]
It's simple to capture these additional options, but handling them isn't that straightforward because different formatters accept them in different ways:

```sh
stylua --indent-width 2
prettier --tab-width 2
# doesn't support this at all
black
```

We could add a table to translate between `FormattingOptions` and the formatter's argument structure, but then the concern would be creating an uneven experience when using more opinionated formatters that don't expose these options. Let me know what you think.

**Comment by jose-elias-alvarez** [comment]
Working on a recent refactor made me realize that updating our current built-ins with support for this would be a monumental task, and as I mentioned I wouldn't be happy with the inherent lack of consistency this would bring. In 8226c3aa67e4f4477528b8528624c1b6c4f26b58 I made a small change to expose these options and make it possible for users to dynamically set arguments based on these options, which I think is the best we'll get.
