### ISSUE TITLE
File with CRLF (line endings) breaks eslint_d

### ISSUE THREAD

**Issue by Keep-Simple** [jose-elias-alvarez/null-ls.nvim#312]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.5.1

### null-ls config

// from [LunarVim](https://www.lunarvim.org/languages/#at-a-glance)

local linters = require "lvim.lsp.null-ls.linters"
linters.setup {
  {
    exe = "eslint_d",
    filetypes = { "typescript", "javascript", "javascriptreact", "typescriptreact" },
  },
}

### Steps to reproduce

1. Setup eslint_d / eslint inside neovim config
2. Create a file with CRLF (windows file endings, \r\n)
3. File should be in the project folder with eslint config
4. Inside eslint config have this inside [rules](https://eslint.org/docs/rules/linebreak-style) - linebreak-style: ["error", "windows"]
5. Open file and see errors

### Expected behavior

No errors must be shown, as the file contains correct line endings.

### Actual behavior

 But for some reason, eslint says that line ending is LF (UNIX one)
![image](https://user-images.githubusercontent.com/59699238/140197400-2d2f7b62-2322-46a0-9457-6e7230be1bae.png)

### Debug log

probable fine (?)

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by jose-elias-alvarez** [comment]
Currently null-ls is hardcoded to split content piped to `stdin` with `\n`. Is there some way to know what type of line endings a file has? Based on [this line](https://github.com/neovim/neovim/blob/f26b391317281d0520056eaa8312cf25e654149f/runtime/lua/vim/lsp.lua#L274), Neovim itself should have the same issue with the ESLint language server, too (unless that server includes some kind of workaround).

**Comment by Keep-Simple** [comment]
Seems like a similar issue
https://github.com/w0rp/ale/issues/823

**Comment by jose-elias-alvarez** [comment]
Great find, very helpful! Can you try #313 and see if that makes a difference?
