### ISSUE TITLE
Broken built-ins? Check here!

### ISSUE THREAD

**Issue by jose-elias-alvarez** [jose-elias-alvarez/null-ls.nvim#321]
In 5005297ee3ac3b01209c5eaecd1bd66a9abd18a4 I modularized all of our current built-ins to provide a small performance boost and better prepare for future additions. This was a pretty big refactor, and I did most of it manually, so it's possible that I broke something in the process.

If I broke a built-in source you're using or if you notice anything else wrong, please post here and I'll fix it ASAP.

**EDIT**: A side effect of this commit is that nonexistent built-ins are no longer silently ignored. If you see errors, please try updating to the latest version of the plugin – it'll warn you about these so you can fix / remove them. If this doesn't fix your error, post here or open up another issue.

**Comment by IndianBoy42** [comment]
Could this error message be related to this problem?

```
2021-11-09T12:41:39 ERROR packer.nvim: Error running config for null-ls.nvim: ...te/pack/packer/start/null-ls.nvim/lua/null-ls/config.lua:90: filetypes: expected table, got nil
```

My config is:
```
local diagnostics_format = "[#{c}] #{m} (#{s})"

  local formatters = null.builtins.formatting
  local diagnostics = null.builtins.diagnostics
  local code_actions = null.builtins.code_actions
  local hover = null.builtins.hover

  null.config {
    diagnostics_format = diagnostics_format,
    sources = {
      -- Formatters
      formatters.stylua,
      formatters.prettierd,
      -- formatters.rustfmt,
      formatters.shfmt,
      formatters.black, -- yapf, autopep8
      formatters.isort,
      -- formatters.clang_format,
      -- formatters.uncrustify,
      formatters.cmake_format,
      formatters.elm_format,
      formatters.fish_indent,
      formatters.fnlfmt,
      -- formatters.json_tool,
      formatters.nixfmt,
      formatters.yamllint,

      -- -- Diagnostics
      -- -- diagnostics.chktex, -- vimtex?
      -- diagnostics.selene, -- lua linter
      -- diagnostics.luacheck, -- lua linter
      -- diagnostics.eslint,
      -- diagnostics.hadolint,
      diagnostics.cppcheck,
      diagnostics.flake8,
      -- diagnostics.pylint,
      -- diagnostics.hadolint,
      -- -- diagnostics.luacheck,
      diagnostics.write_good,
      -- diagnostics.proselint,
      -- diagnostics.vale, -- lets install vale-linter
      -- -- diagnostics.misspell,
      diagnostics.markdownlint,

      -- Code Actions
      -- code_actions.gitsigns, -- TODO: reenable when I can lower the priority
      code_actions.proselint,

      -- Hover Info
      hover.dictionary
      -- hover.dictionary.with {
      --   generator = {},
      --   filetypes = { "txt", "markdown", "tex" },
      -- },
    },
  }
  require("lspconfig")["null-ls"].setup {}
```

**Comment by jose-elias-alvarez** [comment]
@IndianBoy42 I think your issue is that `yamllint` is a diagnostics source, not a formatter. Removing it or changing it to `diagnostics.yamllint` makes your config work on my end. 

This seems to be the same issue mentioned in #322. These sources weren't working to begin with, but erroring out like this isn't good behavior either, so I'll go ahead and add a warning message.

**Comment by mrjones2014** [comment]
@jose-elias-alvarez when using `require('null-ls').builtins.code_actions.gitsigns`, I'm getting the following notification:

>Autostart for null-ls failed: matching root directory not detected.

but it actually didn't fail, if I run `:LspInfo` it shows its attached and `autostart true`, but I only have a subset of the Gitsigns code actions that were there previously.

Any other info I can provide that would be useful here?

**Comment by jose-elias-alvarez** [comment]
@mrjones2014 Are you overriding the server's settings somewhere? `autostart` should always be set to `false` since null-ls manages attaching to buffers manually. I don't know why that would affect the availability of the actions but I'd start there.

**Comment by mrjones2014** [comment]
Ah, yeah, I had set `autostart = true` for `null-ls`, thanks!

**Comment by mrjones2014** [comment]
@jose-elias-alvarez that didn't seem to fix the issue though

**Comment by jose-elias-alvarez** [comment]
@mrjones2014 Check out the setup instructions again and make sure your config is okay, and if you're sure it is, open an issue with minimal reproduction steps.

**Comment by kabouzeid** [comment]
proselint is broken for me. First it works, but after a few edits I get the following warning and diagnostics aren't updated anymore.

proselint 0.13.0
nvim 0.6.1
null-ls latest commit as of now

```
[null-ls] [WARN  22:35:26] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:49: failed to run generator: ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:64: failed to decode json: Expected v
alue but found invalid token at character 1
```

**Comment by jose-elias-alvarez** [comment]
@kabouzeid Could you open a separate issue and follow the instructions in the template? This is an older issue meant to handle problems caused by a specific refactor.

**Comment by kabouzeid** [comment]
Will do, sorry
