### ISSUE TITLE
Completion support for non-alphanumeric characters in match

### ISSUE THREAD

**Issue by oncomouse** [jose-elias-alvarez/null-ls.nvim#327]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

The new completion support is very cool. I'm trying to port an omnifunc I use to look up BibTeX citations in Markdown documents. BibTeX citations start with the @ symbol, so I need to check if `params.word_to_complete` contains an @, which it doesn't [because the regex uses \k](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/2e6a9ba1702f5d59c55d3ca627de6c96f816a76b/lua/null-ls/utils.lua#L125), which doesn't match @.

As far as I'm concerned that's fine. @ isn't a word character, but it would be nice to have line and line_to_cursor, [which are values generated along with word_to_complete](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/2e6a9ba1702f5d59c55d3ca627de6c96f816a76b/lua/null-ls/utils.lua#L123-L124).

Would that be possible? 

### Help

Yes

### Implementation help

Easiest fix would be to add `line` and `line_to_cursor` to `params` in `make_params`, but is there anything else that would need doing? Or some better way to do this?

**Comment by jose-elias-alvarez** [comment]
Exposing those would be a simple solution (or we could ask sources to get the current line themselves, but since we already have it we might as well expose it). I wonder if there's another solution we could use here to keep things flexible? @Furkanzmc

**Comment by Furkanzmc** [comment]
I'm not sure what's being asked here. Is there a problem with the word we use to match or a problem with the completion items?

If it's the first one, `iskeyword` option can be used to change what kind of words are matched. We are already expanding `\k` in our regex so changing the option for the desired file type could solve this problem. 

Am I getting the problem right?

**Comment by jose-elias-alvarez** [comment]
You're right – if I understand correctly I think setting `iskeyword` should handle this case (a big advantage of using Vim regular expressions here, so good call on that!).

**Comment by Furkanzmc** [comment]
@oncomouse Do you have a specific case that's not working for you? Maybe we can start with that and see what's not working correctly.

**Comment by oncomouse** [comment]
@Furkanzmc let me try `iskeyword`. That sounds like what's causing my problem. I'll check this evening and if that's the issue, I'll close this.

**Comment by oncomouse** [comment]
Adding `@-@` to `iskeyword` added the BibTeX keys to completion results, and I learned something about how vim's regex works. Thanks!
