### ISSUE TITLE
Formatting broken on latest Neovim master

### ISSUE THREAD

**Issue by jose-elias-alvarez** [jose-elias-alvarez/null-ls.nvim#328]
neovim/neovim@2ecf0a4c6183bba1c65d440711038f040d355fef removed `vim.lsp.util.compute_diff` (which we probably shouldn't have been relying on in the first place) and replaced it with [`vim.sync.compute_diff`](https://github.com/neovim/neovim/blob/2ecf0a4c6183bba1c65d440711038f040d355fef/runtime/lua/vim/lsp/sync.lua#L336). Unfortunately, `vim.sync.compute_diff` isn't a drop-in replacement, since it doesn't automatically calculate start and end line indexes when they're undefined. 

I think the best solution is to borrow some code from `vim.lsp.util.compute_diff` and use it as the basis for an independent `compute_diff` function that will work independently and across versions.

**Comment by jose-elias-alvarez** [comment]
Should be closed by #313 (tested on `NVIM v0.6.0-dev+569-g2ecf0a4c6` and 0.5.1).

**Comment by hituzi-no-sippo** [comment]
Hi.

Thank you for create this great tool.

Would you please tell me why you can't replace it with `vim.lsp.sync.compute_diff` ?

I have changed the code as follows:

```diff
diff --git a/lua/null-ls/formatting.lua b/lua/null-ls/formatting.lua
index 8e837c1..3025a2a 100644
--- a/lua/null-ls/formatting.lua
+++ b/lua/null-ls/formatting.lua
@@ -1,6 +1,9 @@
+local sync = require("vim.lsp.sync")
+
 local log = require("null-ls.logger")
 local methods = require("null-ls.methods")
 local u = require("null-ls.utils")
+local client = require("null-ls.client")

 local api = vim.api
 local lsp = vim.lsp
@@ -68,8 +71,7 @@ M.handler = function(method, original_params, handler)
         end

         local after_each = function(edits)
-            local ok, err =
-                pcall(lsp.util.apply_text_edits, edits, temp_bufnr, require("null-ls.client").get_offset_encoding())
+            local ok, err = pcall(lsp.util.apply_text_edits, edits, temp_bufnr, client.get_offset_encoding())
             api.nvim_buf_set_option(temp_bufnr, "buflisted", false) -- apply_text_edits sets buflisted to true
             if not ok then
                 handle_err(err)
@@ -78,14 +80,23 @@ M.handler = function(method, original_params, handler)

         local callback = function()
             local ok, err = pcall(function()
-                local edits = require("null-ls.diff").compute_diff(
-                    u.buf.content(bufnr),
-                    u.buf.content(temp_bufnr),
+                local prev_lines = u.buf.content(bufnr)
+                local curr_lines = u.buf.content(temp_bufnr)
+                local edits = sync.compute_diff(
+                    prev_lines,
+                    curr_lines,
+                    0,
+                    #prev_lines,
+                    #curr_lines,
+                    client.get_offset_encoding(),
                     u.get_line_ending(bufnr)
                 )
-                local is_actual_edit = not (edits.newText == "" and edits.rangeLength == 0)
+                local is_actual_edit = edits.text ~= ""

                 if is_actual_edit then
+                    edits.newText = edits.text
+
                     log:debug("received edits from generators")
                     log:trace(vim.inspect(edits))
                 end
```

After running the above code, I think the following two issues are the cause of the lack of replacement in compute_diff.

- It is not possible to determine if two buffers are exactly the same with only `sync.compute_diff`.
   Using `vim.deep_equal` can determine if they are the same, but performance will be worse.
- Can't use only `sync.compute_diff` to extract only the changed parts of two buffers.
  In the return table ([TextDocumentContentChangeEvent](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentContentChangeEvent)) of `sync.compute_diff`, the value of `text` is the text in the range listed in `range`.

If null-ls knew the exact start and end rows of the change, this would solve two problems. However, the current null-ls cannot get the exact start and end lines of the change.

I have read this issue and #313 , but I'm not sure if I am right.

Thank you.

**Comment by jose-elias-alvarez** [comment]
@hituzi-no-sippo I don't remember the exact issue since it's been so long, but I believe the fundamental problem is the same one you noticed:

> Unfortunately, `vim.sync.compute_diff` isn't a drop-in replacement, since it doesn't automatically calculate start and end line indexes when they're undefined.

That made it more convenient to just copy-paste the old `vim.lsp.util.compute_diff` and use that instead. 

Is there an advantage to using `sync.compute_diff` instead? I'm not sure it's worth the trouble. To my knowledge, the only issue with the current implementation is that it only returns one `TextDocumentContentChangeEvent` (vs. returning multiple changes) but as far as I can tell, that's the same for `sync.compute_diff`.
