### ISSUE TITLE
Linter name in diagnostics

### ISSUE THREAD

**Issue by stephan-hesselmann-by** [jose-elias-alvarez/null-ls.nvim#33]
It would be cool to have the option to prefix diagnostics with the linter name. That way diagnostics from multiple linting sources can be distinguished from each other. Efm added a similar feature recently: https://github.com/mattn/efm-langserver/pull/148

**Comment by gegoune** [comment]
It already exists in null-ls, you need to update your diagnostic handler on nvim side. null-ls provides `source` field, have a look here https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics.lua

**Comment by stephan-hesselmann-by** [comment]
Thanks I wasn't aware of that. Could you give me a hint on what I have to do on neovim side to override the handler?

**Comment by gegoune** [comment]
https://github.com/neovim/nvim-lspconfig/wiki/UI-customization#show-source-in-diagnostics

**Comment by stephan-hesselmann-by** [comment]
Perfect thanks a lot :)
