### ISSUE TITLE
It's not possible to provide completion items that doesn't start with the completion word

### ISSUE THREAD

**Issue by Furkanzmc** [jose-elias-alvarez/null-ls.nvim#331]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

When Neovim processes the completion items returned from LSPs, it excludes the results that do not start with the word that's being completed.

For example, I have a completion source that I use to do mnemonics based completion.

```
def get_something() 

gs<TAB> -> This would result in get_something showing up in completion list
```

I use this source as part of my `completefunc`. If I include this source in null-ls, then I don't see the result because `get_something` does not start with `gs`.

I looked in Neovim's source code for this and was not able to find a workaround to it. This requires some investigation, or maybe a solution already exists but I'm unaware of it.

### Help

Yes

**Comment by jose-elias-alvarez** [comment]
Possibly related to neovim/neovim#13854.

**Comment by jose-elias-alvarez** [comment]
@Furkanzmc Do you think this is something we can handle here? Since this is how Neovim completion currently works, I don't know if we can provide a plugin-agnostic solution, and if I understand correctly I think that the linked Neovim PR would solve this precise issue.

**Comment by Furkanzmc** [comment]
I only logged this issue so we are aware of it.

IMO, the best we should attempt to do is provide a small snippet for a `completefuncfilter` once it is merged. We should leave any possible solutions to the completion plugins. If we try to solve this problem then it might open the door to other fixes that should be handled by a completion plugin. I think it's best to keep the scope very focused. We wouldn't expect `clangd` to solve this problem, and neither should we.

**Comment by jose-elias-alvarez** [comment]
Closing this as it's not really actionable from our end.
