### ISSUE TITLE
builtins are not working properly luacheck is not giving the lintig and the stylelint is not formatting 

### ISSUE THREAD

**Issue by imSafdarAwan** [jose-elias-alvarez/null-ls.nvim#342]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

tried in both nvim-5.1 and nvim-nightly

### null-ls config

```lua
local vim = vim
local on_attach = require("lsp.lsp_util").on_attach
--=======================================================
--                      null-ls
--=======================================================
local null_ls = require("null-ls")
local builtins = null_ls.builtins
local sources = {
	builtins.formatting.stylua,
	builtins.diagnostics.luacheck,
	builtins.formatting.black.with({ extra_args = { "--fast" } }),
	builtins.diagnostics.flake8,
	builtins.diagnostics.eslint_d.with({
		condition = function(utils)
			return utils.root_has_file(".eslintrc.json")
		end,
	}),
	builtins.formatting.eslint_d,
	builtins.formatting.stylelint,
	builtins.formatting.clang_format,
	builtins.diagnostics.stylelint,
	-- builtins.diagnostics.htmlhint,
	builtins.formatting.prettier_d_slim.with({
		-- filetypes = { "html", "json", "css", "scss", "less", "yaml", "markdown" },
		filetypes = { "html", "json", "yaml", "markdown" },
	}),

	builtins.code_actions.gitsigns,
}
null_ls.config({
	debug = true,
	sources = sources,
})
require("lspconfig")["null-ls"].setup({ on_attach = on_attach, autostart = true })

local helpers = require("null-ls.helpers")

-- local htmlhint = helpers.make_builtin({
-- 	method = null_ls.methods.DIAGNOSTICS,
-- 	filetypes = { "html" },
-- 	generator_opts = {
-- 		command = "htmlhint",
-- 		args = { "--format", "json" },
-- 		to_stdin = true,
-- 		from_stderr = true,
-- 		format = "json",
-- 		-- on_output = function(params)
-- 		-- 	local parser = helpers.diagnostics.from_json({
-- 		-- 		attributes = {
-- 		-- 			severity = "type",
-- 		-- 			code = "source",
-- 		-- 		},
-- 		-- 		severities = {
-- 		-- 			ERROR = helpers.diagnostics.severities["error"],
-- 		-- 			WARNING = helpers.diagnostics.severities["warning"],
-- 		-- 		},
-- 		-- 	})
-- 		-- 	params.messages = params.output
-- 		-- 			and params.output.files
-- 		-- 			and params.output.files["STDIN"]
-- 		-- 			and params.output.files["STDIN"].messages
-- 		-- 		or {}
-- 		--
-- 		-- 	return parser({ output = params.messages })
-- 		-- end,
-- 		on_output = function(params)
-- 			local diagnostics = {}
-- 			local severities = { error = 1, warning = 2, suggestion = 4 }
-- 			for _, diagnostic in ipairs(params.output["stdin." .. vim.fn.fnamemodify(params.bufname, ":e")]) do
-- 				table.insert(diagnostics, {
-- 					row = diagnostic.Line,
-- 					col = diagnostic.Span[1],
-- 					end_col = diagnostic.Span[2] + 1,
-- 					code = diagnostic.Check,
-- 					message = diagnostic.Message,
-- 					severity = severities[diagnostic.Severity],
-- 				})
-- 			end
-- 			return diagnostics
-- 		end,
-- 	},
-- 	factory = helpers.generator_factory,
-- })

-- FIXME: read the htmlhint output json format and compare it to csshint or something like that and
-- figure out how to output the htmlhint json to the lsp client
local htmlhint = helpers.make_builtin({
	method = null_ls.methods.DIAGNOSTICS,
	filetypes = { "html" },
	generator_opts = {
		command = "htmlhint",
		args = { "--format", "json" },
		to_stdin = true,
		from_stderr = true,
		format = "json",
		on_output = function(params)
			local diagnostics = {}
			for _, diagnostic in ipairs(params.output[1].messages) do
				--[[
                --{
                  col = 1,
                  evidence = "<!--comment--><!DOCTYPE html>",
                  line = 1,
                  message = "Doctype must be declared first.",
                  raw = "<!--comment-->",
                  rule = {
                    description = "Doctype must be declared first.",
                    id = "doctype-first",
                    link = "https://github.com/thedaviddias/HTMLHint/wiki/doctype-first"
                  },
                  type = "error"
                } --]]
				print(vim.inspect(diagnostic))
			end
			return diagnostics
		end,
	},
	factory = helpers.generator_factory,
})

-- return { {
--     row, -- number, optional (defaults to first line)
--     col, -- number, optional (defaults to beginning of line)
--     end_row, -- number, optional (defaults to row)
--     end_col, -- number, optional (defaults to end of line),
--     source, -- string, optional (defaults to "null-ls")
--     code, -- number, optional
--     message, -- string
--     severity, -- 1 (error), 2 (warning), 3 (information), 4 (hint)
-- } }

null_ls.register(htmlhint)
```

### Steps to reproduce

NOTE: i have upgraded to new distro today every thing works fine but only problem is with the styleint and luacheck

### Expected behavior

format the docuemt like other formatters 

### Actual behavior

stylelint is not formatting the document and the luacheck is not giving dignostics but both of them are attached to the null_ls

### Debug log

[DEBUG و 00:13:53 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: not registering conditional source eslint_d
[DEBUG و 00:13:55 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: not registering conditional source eslint_d
[DEBUG و 00:14:12 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: not registering conditional source eslint_d
[DEBUG و 00:14:53 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: not registering conditional source eslint_d
[DEBUG و 00:15:21 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: not registering conditional source eslint_d
[DEBUG و 00:15:25 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: not registering conditional source eslint_d
[DEBUG و 00:17:56 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: not registering conditional source eslint_d
[DEBUG و 00:18:09 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: not registering conditional source eslint_d
[DEBUG و 00:18:09 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received LSP request for method initialize
[DEBUG و 00:18:10 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received LSP notification for method initialized
[DEBUG و 00:18:10 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received LSP notification for method textDocument/didOpen
[DEBUG و 00:18:10 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG و 00:18:11 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received diagnostics from generators
[DEBUG و 00:18:11 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: {}
[DEBUG و 00:18:22 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received LSP request for method shutdown
[DEBUG و 00:18:22 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received LSP notification for method exit
[DEBUG و 00:18:23 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: not registering conditional source eslint_d
[DEBUG و 00:18:23 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received LSP request for method initialize
[DEBUG و 00:19:41 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received LSP notification for method initialized
[DEBUG و 00:19:41 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received LSP notification for method textDocument/didOpen
[DEBUG و 00:19:41 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG و 00:19:41 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received LSP request for method textDocument/codeAction
[DEBUG و 00:19:41 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: running generators for method NULL_LS_CODE_ACTION
[DEBUG و 00:19:41 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received diagnostics from generators
[DEBUG و 00:19:41 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: {}
[DEBUG و 00:19:41 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received code actions from generators
[DEBUG و 00:19:41 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: {}
[DEBUG و 00:19:41 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received LSP request for method shutdown
[DEBUG و 00:19:41 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received LSP notification for method exit
[DEBUG و 00:20:01 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: not registering conditional source eslint_d
[DEBUG و 00:20:07 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: not registering conditional source eslint_d
[DEBUG و 00:20:16 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: not registering conditional source eslint_d
[DEBUG و 00:20:16 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received LSP request for method initialize
[DEBUG و 00:20:32 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received LSP notification for method initialized
[DEBUG و 00:20:32 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received LSP notification for method textDocument/didOpen
[DEBUG و 00:20:32 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG و 00:20:32 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received diagnostics from generators
[DEBUG و 00:20:32 ت 13 نومبر 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: {}

### Help

No

**Comment by imSafdarAwan** [comment]
## stylelint
![image](https://user-images.githubusercontent.com/87114084/141615568-eab16dcf-d55b-4c53-802f-bc66b15b49a2.png)
## luacheck 
![image](https://user-images.githubusercontent.com/87114084/141615611-f9b3647c-3423-4661-9e4c-9c0bab314ec2.png)
in the luacheck image it should give me warinig on vim because the vim variable is not defined anywhere i am defining the 
``lua local vim = vim```
to avoid other warning's

**Comment by jose-elias-alvarez** [comment]
If they worked for you before but aren't working on a new distro, odds are that this is an issue with your environment. I don't see anything relevant in your logs but I would try running `luacheck` and `stylelint` directly from the command line and make sure they do what you expect. I also can't do anything about this without a minimal reproduction / better debug output.

**Comment by imSafdarAwan** [comment]
> If they worked for you before but aren't working on a new distro, odds are that this is an issue with your environment. I don't see anything relevant in your logs but I would try running `luacheck` and `stylelint` directly from the command line and make sure they do what you expect. I also can't do anything about this without a minimal reproduction / better debug output.

sorry brother unfortunatly i have added the .stylintrc in my project root dir and the .stylentrc had some invalid syntax so it was giving me the linting but didn't work for formatting as you said use command line to check they are working or not and i did so the problem with luacheck was that it was getting problem with lua53 from the binaries ```/usr/bin/ ``` i have opened an issue on their repo because i couldn't figure out the problem but thanks for your response that was very helpful

**Comment by jose-elias-alvarez** [comment]
Great, glad you were able to figure out what was going wrong.
