### ISSUE TITLE
Stylua ignores the given argument list.

### ISSUE THREAD

**Issue by cjnucette** [jose-elias-alvarez/null-ls.nvim#35]
Hi, I have the following configuration:
```lua
local null_ls = require("null-ls")
null_ls.setup({
on_attach = function()
		vim.cmd([[
      augroup lsp_format_on_save
        autocmd! * <buffer>
        autocmd BufWritePost <buffer> lua vim.lsp.buf.formatting()
      augroup END
    ]])
	end,
	save_after_formatting = true,
	sources = {
		null_ls.builtins.formatting.prettier.with({
			filetypes = { "html", "css", "json", "markdown", "yaml" },
		}),
		null_ls.builtins.formatting.stylua.with({
			filetypes = { "lua" },
			command = "stylua",
			arguments = { "--indent-width", "2", "--indent-type",  "Spaces", "-" },
		}),
	},
})
```
It is working, but `stylua` ignores the arguments list. If you look in the code pasted above, it has tabs instead of spaces.

**Comment by gegoune** [comment]
It's args, not arguments.

**Comment by cjnucette** [comment]
Thanks, that's it.
I think the documentation should be more clear in this case. Not only the options does not reflect this but also are written in a capitalized manner. <https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md>
