### ISSUE TITLE
Add support for Godot

### ISSUE THREAD

**Issue by jovandeginste** [jose-elias-alvarez/null-ls.nvim#368]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I have no idea how to start, but this vim-plugin seems to be a great resource:

https://github.com/habamax/vim-godot

They explain how to add it to regular vim/neovim, but of course it would be great to have it built-in in null-ls... 

### Help

No

### Implementation help

I would like to help, but I have no knowledge of lua, vim-script or lsp... I can copy-paste and alter values inside quotes :wink:

**Comment by jose-elias-alvarez** [comment]
I'm totally unfamiliar with this and am unlikely to work on it myself, but for reference for future contributors, which features would you specifically be interested in supporting here? I think the commands could be ported but folding and highlighting are better handled in Vimscript.

**Comment by jovandeginste** [comment]
Your question is confusing me, probably due to my ignorance here... I thought there was a language server involved, and null-ls basically manages these?

**Comment by jose-elias-alvarez** [comment]
Looking briefly at the plugin it doesn't seem to have any LSP functionality. null-ls doesn't really manage language servers – it's more about converting what non-language servers do into a language-friendly format. For example, instead of separate commands like `:GodotRunCurrent`, null-ls could provide this as a code action.

**Comment by Orgil** [comment]
godot engine has built-in lsp server so configure it same as others. It does work well.

**Comment by jovandeginste** [comment]
> godot engine has built-in lsp server so configure it same as others. It does work well.

Is that something I can easily do, or is this something that can be easily added to `null-ls`?

**Comment by mjlbach** [comment]
It's easy. There's no point in null-ls support. Consult the lspconfig documentation.

**Comment by jovandeginste** [comment]
Easy is a relative thing, but I'll look into it! Thanks everyone :heart:

**Comment by jose-elias-alvarez** [comment]
Closing this as there is an LSP solution.
