### ISSUE TITLE
null-ls stopped working

### ISSUE THREAD

**Issue by ichirou2910** [jose-elias-alvarez/null-ls.nvim#372]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.6.0-dev+622-gfd6df7481

### null-ls config

```lua
local ok, null_ls = pcall(require, "null-ls")

if not ok then
    return
end

local builtins = null_ls.builtins

local sources = {
    builtins.markdownlint,
    builtins.formatting.prettierd.with({
        filetypes = { "html", "json", "markdown", "scss", "css" },
    }),
    builtins.diagnostics.eslint.with({ command = "eslint_d" }), -- Lua

    builtins.formatting.stylua,

    builtins.formatting.shfmt,
    builtins.diagnostics.shellcheck.with({ diagnostics_format = "#{m} [#{c}]" }),
}

local M = {}
M.setup = function()
    null_ls.config({ sources = sources })
    require("lspconfig")["null-ls"].setup {
        on_attach = function()
            vim.cmd([[autocmd BufWritePost <buffer> lua vim.lsp.buf.formatting()]])
        end
    }
end
return M

```

### Steps to reproduce

Open a file of configured types (lua, md, sh...)

### Expected behavior

null-ls works normally

### Actual behavior

null-ls doesnt work and doesnt show up in LspInfo
![image](https://user-images.githubusercontent.com/51302893/142995631-151b2b4f-038f-439e-afb8-8ca42f02ce95.png)

### Debug log

[WARN  Tue 23 Nov 2021 03:19:59 PM +07] ...site/pack/packer/start/null-ls.nvim/lua/null-ls/info.lua:31: failed to get info: buffer is not attached

### Help

No

**Comment by ichirou2910** [comment]
From what I saw in the log, null-ls didn't attach itself to the buffer, but I cant understand why it didnt. Things was working fine for me before. I updated both neovim and the plugins yesterday and null-ls just stopped working.

**Comment by jose-elias-alvarez** [comment]
I think the issue is `builtins.markdownlint`, which should be `builtins.diagnostics.markdownlint`. Fixing that makes your config work for me. 

Trying to register a `nil` source unfortunately causes source registration to fail in a way that's hard to catch (and impossible to avoid if we want to keep source order).

**Comment by momofor** [comment]
I have the right base configuration with the only source being clang_format. but I still get an error saying that cmd is a nil value in the rpc.lua file.

**Comment by jose-elias-alvarez** [comment]
@momofor Can you open a separate discussion or issue with your config? From the sound of it it's not related to this issue.

**Comment by ichirou2910** [comment]
> I think the issue is builtins.markdownlint, which should be builtins.diagnostics.markdownlint. Fixing that makes your config work for me.

Thanks! It works fine now!

> though I'll try to think of a solution to make this kind of issue easier to debug

Yes, I was going to request that too. Would be great to know exactly what went wrong.
