### ISSUE TITLE
Cannot call setup function with recent changes

### ISSUE THREAD

**Issue by jacksonludwig** [jose-elias-alvarez/null-ls.nvim#38]
I updated my plugins today and noticed that when trying to run the following config:
```typescript
require("null-ls").config {}
require("lspconfig")["null-ls"].setup {}
```
I get the following error:
```
packer.nvim: Error running config for nvim-lspconfig: ...site/pack/packer/start/null-ls.nvim/lua/null-ls/init.lua:31: attempt to call field 'setup' (a nil value)
```
Is this on my end or am I calling this incorrectly? I have lspconfig to installed and have been using this plugin for a while now along with your ts-utils plugin.

Thanks for any help you can provide.

**Comment by vinicius507** [comment]
Had the same problem while running `null-ls` like this and attached to `clangd` at the same time. Removing either of them made the other method work.

**Comment by vinicius507** [comment]
Also, in config you need to specify your sources.

**Comment by jacksonludwig** [comment]
Thanks, however I'm still a bit confused as I was following the ts-utils readme which states to do the following:
```lua
local nvim_lsp = require("lspconfig")

-- enable null-ls integration (optional)
require("null-ls").setup {}

nvim_lsp.tsserver.setup {
    on_attach = function(client, bufnr)
        -- disable tsserver formatting if you plan on formatting via null-ls
        client.resolved_capabilities.document_formatting = false

        local ts_utils = require("nvim-lsp-ts-utils")

        -- defaults
        ts_utils.setup {
            debug = false,
            disable_commands = false,
            enable_import_on_completion = false,

-- more config below....
```
This worked before recent updates, and I'm not sure how to adapt it at the moment

**Comment by jose-elias-alvarez** [comment]
Are you running `setup` twice? That's the only way I can get this to trigger an error – otherwise, both the old method and the new method are working for me. The config in the ts-utils readme is meant for users who aren't otherwise using null-ls, so there's no need to call `setup` if you have already set up null-ls (via either method) elsewhere.

**Comment by MurdeRMelodY** [comment]
I've been having the same issues since recent update. Am I doing something wrong?
`require("packer").startup(function(use)
  use { "wbthomason/packer.nvim" }

  use {
    "jose-elias-alvarez/null-ls.nvim",
    requires = {
      { "nvim-lua/plenary.nvim" },
      { "neovim/nvim-lspconfig" }
    },
    config = function()
      require("null-ls").config {
        sources = {
          require("null-ls").builtins.formatting.stylua,
        }
      }
      require("lspconfig")["null-ls"].setup {
        on_attach = function()
          vim.cmd([[autocmd BufWritePost <buffer> lua vim.lsp.buf.formatting()]])
        end
      }
    end
  }
end)
`

**Comment by MurdeRMelodY** [comment]
`require("packer").startup(function(use)
  use { "wbthomason/packer.nvim" }

  use {
    "jose-elias-alvarez/null-ls.nvim",
    requires = {
      { "nvim-lua/plenary.nvim" },
      { "neovim/nvim-lspconfig" }
    },
    config = function()
      require("null-ls").config {
        sources = {
          require("null-ls").builtins.formatting.stylua,
        }
      }
      require("lspconfig")["null-ls"].setup {
        on_attach = function()
          vim.cmd([[autocmd BufWritePost <buffer> lua vim.lsp.buf.formatting()]])
        end
      }
    end
  }
end)
`

**Comment by MurdeRMelodY** [comment]
```lua
require("packer").startup(function(use)
  use { "wbthomason/packer.nvim" }

  use {
    "jose-elias-alvarez/null-ls.nvim",
    requires = {
      { "nvim-lua/plenary.nvim" },
      { "neovim/nvim-lspconfig" }
    },
    config = function()
      require("null-ls").config {
        sources = {
          require("null-ls").builtins.formatting.stylua,
        }
      }
      require("lspconfig")["null-ls"].setup {
        on_attach = function()
          vim.cmd([[autocmd BufWritePost <buffer> lua vim.lsp.buf.formatting()]])
        end
      }
    end
  }
end)

```

**Comment by jacksonludwig** [comment]
@jose-elias-alvarez Thanks for the info. I'm not calling setup multiple times though. It seems using the original config from the ts-utils readme (e.g. `require("null-ls").setup {}`) or it's updated version (e.g. calling `require"null-ls".config{}` and `require"lspconfig"["null-ls"].setup{}`) results in the same error.

**Comment by jacksonludwig** [comment]
Thanks, after making sure I only call it once, it works correctly. 

However, I do get the same error when ever I have to re-source my plugins (e.g. `:PackerSync` or `:PackerCompile`), which I did not encounter before. This means that I have to restart neovim when I run either of these commands or else null-ls will not function.

**Comment by folke** [comment]
@jacksonludwig you should always restart neovim after running packer sync or packer compile. It might have worked previously, but plugins will definitely break if you don't restart :)
