### ISSUE TITLE
Better sources discoverability

### ISSUE THREAD

**Issue by kylo252** [jose-elias-alvarez/null-ls.nvim#383]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

It was possible to get a list of available sources even when they weren't registered, but somewhere between #332 and #321 that ability got removed. It may have never been intended to work that way from the beginning, but it was useful nevertheless. 

Before: 
![image](https://user-images.githubusercontent.com/59826753/143680979-6ebce372-de93-4a80-8aef-de913a2b3503.png)

That list is now always empty for non-registered sources, which isn't really that helpful.

### Help

Yes

### Implementation help

There are two options available:
- expose the config so that one can require it without setting up the source, see https://github.com/neovim/nvim-lspconfig/pull/1479
- create a static table that contains metadata about the available sources, see https://github.com/williamboman/nvim-lsp-installer/pull/159

**Comment by jose-elias-alvarez** [comment]
The specific commit that removed this was d78734baeeedae8e73c76680726dfae57ed82d09. You can require a built-in without setting it up, actually (it’s only set up once you register it) but the only way I can think of to get a list of all available buiIt-ins would be to scan the file system. 

If it’s useful, I wouldn’t be opposed to a solution like the one you put together for lsp-installer.

**Comment by kylo252** [comment]
Implemented in #397 🚀
