### ISSUE TITLE
Environment Variables for Run Command

### ISSUE THREAD

**Issue by cenk1cenk2** [jose-elias-alvarez/null-ls.nvim#385]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Hello @jose-elias-alvarez,

Thank you for expanding this beautiful plugin and for your work on it. It does much more than I would imagine at the initial state of the plugin. 

I would like to kindly ask you that since `null-ls` is checking for whether the command is executable or not, how can I add environment variables to do the command. I have scanned through the code based and already tried the approach to append the environment variables at the beginning of the command but there is no avail since it checks with `vim.executable` to whether this given command is executable or not.

I have a case where I would like to have the environment variable `PRETTIERD_DEFAULT_CONFIG` for `prettierd` to have default configuration because some of the company repositories do not have a `prettierrc` file.

Is there any way that can be implemented as a parameter to the current formatter/linter/code-action provider etc. just like a `environment` entry in the configuration with `prettierd.with`.

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by jose-elias-alvarez** [comment]
Thank you for the kind words! We have a way to handle this currently using `extra_args`:

```lua
local prettierd = require("null-ls.builtins").formatting.prettierd.with({
    extra_args = function(params)
        return params.root:find("project-without-prettierrc", 1, true) and { "--config", "/path/to/global/prettierrc" }
    end,
})
```

Unfortunately, this works for vanilla `prettier` but not `prettierd`, which apparently doesn't support the `--config` flag:

```
Error: Only a single file path is supported
```

If the `extra_args` solution seems good to you, I'd recommend opening an upstream issue so that this works as expected with `prettierd`. Otherwise, we could definitely allow passing environment variables to processes via `with` as you suggested.

**Comment by cenk1cenk2** [comment]
Thank you for the answer. I could easily create a merge request to prettierd since it is already in Typescript.

But do you think that supporting generally the environment variables can be in the beneficial?

I can also use that time to create a pull request to you, if you can give me a minor guidence.

Thanks for the quick answer on the issue.

**Comment by jose-elias-alvarez** [comment]
Sure, we haven't received requests for it before but it seems like a sensible addition. I think it should be pretty simple. We'd need to add an `env` key to the [`opts` table](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/2af1e1e7cce44fb07cd2508db2cc29cd120107ca/lua/null-ls/helpers.lua#L103-L119), pass it to [`loop.spawn`](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/2af1e1e7cce44fb07cd2508db2cc29cd120107ca/lua/null-ls/helpers.lua#L303) in the `spawn_args` table, then pass it to [`uv.spawn`](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/2af1e1e7cce44fb07cd2508db2cc29cd120107ca/lua/null-ls/loop.lua#L98).

**Comment by cenk1cenk2** [comment]
Thank you for this detailed guidence, I will give it a go hopefully this weekend.
