### ISSUE TITLE
Calling vim.lsp.buf.formatting() results in error

### ISSUE THREAD

**Issue by DanielWeidinger** [jose-elias-alvarez/null-ls.nvim#390]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.6.0

### null-ls config

local lspconfig = require'lspconfig'
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
local null_ls = require("null-ls")

null_ls.config({
    sources = {
        null_ls.builtins.formatting.stylua,
        null_ls.builtins.formatting.prettier_d_slim,
        null_ls.builtins.code_actions.gitsigns,
        -- null_ls.builtins.completion.spell,
    },
})

lspconfig["null-ls"].setup({
    on_attach = on_attach,
    capabilities=capabilities
})

### Steps to reproduce

Run vim.lsp.buf.formatting() on a buffer which is included in the sources

### Expected behavior

Formatting of the buffer

### Actual behavior

Error and no formatting

### Debug log

[WARN  Mi 01 Dez 2021 17:39:20] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:45: failed to run generator: ...daniel/.vim/plugged/null-ls.nvim/lua/null-ls/helpers.lua:167: command stylua is not executable (make sure it's installed and on your $PATH)
[TRACE Mi 01 Dez 2021 18:47:11] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method initialize
[TRACE Mi 01 Dez 2021 18:47:11] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method initialized
[TRACE Mi 01 Dez 2021 18:47:11] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didOpen
[TRACE Mi 01 Dez 2021 18:47:11] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Mi 01 Dez 2021 18:47:11] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available
[TRACE Mi 01 Dez 2021 18:47:11] ...el/.vim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:117: received diagnostics from generators
[TRACE Mi 01 Dez 2021 18:47:11] ...el/.vim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:118: {}
[TRACE Mi 01 Dez 2021 18:47:26] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method initialize
[TRACE Mi 01 Dez 2021 18:47:26] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method initialized
[TRACE Mi 01 Dez 2021 18:47:26] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didOpen
[TRACE Mi 01 Dez 2021 18:47:26] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Mi 01 Dez 2021 18:47:26] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available
[TRACE Mi 01 Dez 2021 18:47:26] ...el/.vim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:117: received diagnostics from generators
[TRACE Mi 01 Dez 2021 18:47:26] ...el/.vim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:118: {}
[TRACE Mi 01 Dez 2021 18:47:28] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didChange
[TRACE Mi 01 Dez 2021 18:47:28] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG Mi 01 Dez 2021 18:47:28] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available
[TRACE Mi 01 Dez 2021 18:47:28] ...el/.vim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:117: received diagnostics from generators
[TRACE Mi 01 Dez 2021 18:47:28] ...el/.vim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:118: {}
[TRACE Mi 01 Dez 2021 18:47:28] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didSave
[TRACE Mi 01 Dez 2021 18:47:28] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS_ON_SAVE
[DEBUG Mi 01 Dez 2021 18:47:28] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available
[TRACE Mi 01 Dez 2021 18:47:28] ...el/.vim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:117: received diagnostics from generators
[TRACE Mi 01 Dez 2021 18:47:28] ...el/.vim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:118: {}
[TRACE Mi 01 Dez 2021 18:47:28] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method textDocument/formatting
[TRACE Mi 01 Dez 2021 18:47:28] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_FORMATTING
[DEBUG Mi 01 Dez 2021 18:47:28] ...daniel/.vim/plugged/null-ls.nvim/lua/null-ls/helpers.lua:302: spawning command [prettier_d_slim] with args { "--stdin", "--stdin-filepath", "/home/daniel/Desktop/Codl-Homepage/src/templates/blog-post.tsx" }
[TRACE Mi 01 Dez 2021 18:47:28] ...daniel/.vim/plugged/null-ls.nvim/lua/null-ls/helpers.lua:184: error output: nil
[TRACE Mi 01 Dez 2021 18:47:28] ...daniel/.vim/plugged/null-ls.nvim/lua/null-ls/helpers.lua:185: output: import React from "react";
import styled from "styled-components";
import { graphql } from "gatsby";
import Layout from "../layouts/MainLayout";
import { SEO } from "../components/basic/SEO";
import { TextBlock } from "../components/blog/BlogComponents";
import MetaInfo from "../components/blog/MetaInfo";

const Content = styled.div`
	display: flex;
	flex-direction: column;
	width: 100%;
	min-height: 100%;
	margin-top: calc(var(--navbar-height) / 2);
`;

const BlogHeader = styled.h2`
	font-size: 3.5em;
	font-weight: 500;

	margin: 0;
	margin-bottom: 0.2em;
`;

const HeadingWrapper = styled.div`
	margin: 0 5vw;
	width: 100%;
	display: flex;
	flex-direction: column;
	justify-content: baseline;

	@media screen and (max-width: 950px) {
		margin: 0;
		width: 95%;
	}
`;

export const HeaderDivider = styled.div`
	margin: 3em 0;
	opacity: 0.2;
	font-weight: 600;
	font-size: 2.8em;
`;

export default function BlogPost({ data }) {
	const post = data.markdownRemark;
	return (
		<Layout>
			<Content>
				<SEO
					title={post.frontmatter.title}
					description={data.excerpt}
				/>
				<HeadingWrapper>
					<BlogHeader>{post.frontmatter.title}</BlogHeader>
					<MetaInfo
						author={post.frontmatter.author}
						date={post.frontmatter.date}
					/>
				</HeadingWrapper>
				<TextBlock
					dangerouslySetInnerHTML={{
						__html: post.html
					}}
				/>
			</Content>
		</Layout>
	);
}

export const query = graphql`
	query BlogQuery($slug: String!) {
		markdownRemark(fields: { slug: { eq: $slug } }) {
			html
			excerpt
			frontmatter {
				title
				author
				date(fromNow: true)
			}
		}
	}
`;

[DEBUG Mi 01 Dez 2021 18:47:28] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/formatting.lua:55: received edits from generators
[TRACE Mi 01 Dez 2021 18:47:28] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/formatting.lua:56: { {
    col = 1,
    end_col = 1,
    end_row = 80,
    row = 1,
    text = 'import React from "react";\nimport styled from "styled-components";\nimport { graphql } from "gatsby";\nimport Layout from "../layouts/MainLayout";\nimport { SEO } from "../components/basic/SEO";\nimport { TextBlock } from "../components/blog/BlogComponents";\nimport MetaInfo from "../components/blog/MetaInfo";\n\nconst Content = styled.div`\n\tdisplay: flex;\n\tflex-direction: column;\n\twidth: 100%;\n\tmin-height: 100%;\n\tmargin-top: calc(var(--navbar-height) / 2);\n`;\n\nconst BlogHeader = styled.h2`\n\tfont-size: 3.5em;\n\tfont-weight: 500;\n\n\tmargin: 0;\n\tmargin-bottom: 0.2em;\n`;\n\nconst HeadingWrapper = styled.div`\n\tmargin: 0 5vw;\n\twidth: 100%;\n\tdisplay: flex;\n\tflex-direction: column;\n\tjustify-content: baseline;\n\n\t@media screen and (max-width: 950px) {\n\t\tmargin: 0;\n\t\twidth: 95%;\n\t}\n`;\n\nexport const HeaderDivider = styled.div`\n\tmargin: 3em 0;\n\topacity: 0.2;\n\tfont-weight: 600;\n\tfont-size: 2.8em;\n`;\n\nexport default function BlogPost({ data }) {\n\tconst post = data.markdownRemark;\n\treturn (\n\t\t<Layout>\n\t\t\t<Content>\n\t\t\t\t<SEO\n\t\t\t\t\ttitle={post.frontmatter.title}\n\t\t\t\t\tdescription={data.excerpt}\n\t\t\t\t/>\n\t\t\t\t<HeadingWrapper>\n\t\t\t\t\t<BlogHeader>{post.frontmatter.title}</BlogHeader>\n\t\t\t\t\t<MetaInfo\n\t\t\t\t\t\tauthor={post.frontmatter.author}\n\t\t\t\t\t\tdate={post.frontmatter.date}\n\t\t\t\t\t/>\n\t\t\t\t</HeadingWrapper>\n\t\t\t\t<TextBlock\n\t\t\t\t\tdangerouslySetInnerHTML={{\n\t\t\t\t\t\t__html: post.html\n\t\t\t\t\t}}\n\t\t\t\t/>\n\t\t\t</Content>\n\t\t</Layout>\n\t);\n}\n\nexport const query = graphql`\n\tquery BlogQuery($slug: String!) {\n\t\tmarkdownRemark(fields: { slug: { eq: $slug } }) {\n\t\t\thtml\n\t\t\texcerpt\n\t\t\tfrontmatter {\n\t\t\t\ttitle\n\t\t\t\tauthor\n\t\t\t\tdate(fromNow: true)\n\t\t\t}\n\t\t}\n\t}\n`;\n'
  } }
[TRACE Mi 01 Dez 2021 18:49:46] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didClose
[TRACE Mi 01 Dez 2021 18:49:46] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method shutdown
[TRACE Mi 01 Dez 2021 18:49:46] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method exit
[TRACE Mi 01 Dez 2021 18:49:52] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didClose
[TRACE Mi 01 Dez 2021 18:49:52] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method shutdown
[TRACE Mi 01 Dez 2021 18:49:52] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method exit
[TRACE Mi 01 Dez 2021 18:49:57] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method initialize
[TRACE Mi 01 Dez 2021 18:49:57] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method initialized
[TRACE Mi 01 Dez 2021 18:49:57] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didOpen
[TRACE Mi 01 Dez 2021 18:49:57] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Mi 01 Dez 2021 18:49:57] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available
[TRACE Mi 01 Dez 2021 18:49:57] ...el/.vim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:117: received diagnostics from generators
[TRACE Mi 01 Dez 2021 18:49:57] ...el/.vim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:118: {}
[TRACE Mi 01 Dez 2021 18:49:59] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didChange
[TRACE Mi 01 Dez 2021 18:49:59] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG Mi 01 Dez 2021 18:49:59] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available
[TRACE Mi 01 Dez 2021 18:49:59] ...el/.vim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:117: received diagnostics from generators
[TRACE Mi 01 Dez 2021 18:49:59] ...el/.vim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:118: {}
[TRACE Mi 01 Dez 2021 18:49:59] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didSave
[TRACE Mi 01 Dez 2021 18:49:59] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS_ON_SAVE
[DEBUG Mi 01 Dez 2021 18:49:59] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available
[TRACE Mi 01 Dez 2021 18:49:59] ...el/.vim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:117: received diagnostics from generators
[TRACE Mi 01 Dez 2021 18:49:59] ...el/.vim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:118: {}
[TRACE Mi 01 Dez 2021 18:49:59] /home/daniel/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method textDocument/formatting
[TRACE Mi 01 Dez 2021 18:49:59] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_FORMATTING
[DEBUG Mi 01 Dez 2021 18:49:59] ...daniel/.vim/plugged/null-ls.nvim/lua/null-ls/helpers.lua:302: spawning command [prettier_d_slim] with args { "--stdin", "--stdin-filepath", "/home/daniel/Desktop/Codl-Homepage/src/templates/blog-post.tsx" }
[TRACE Mi 01 Dez 2021 18:49:59] ...daniel/.vim/plugged/null-ls.nvim/lua/null-ls/helpers.lua:184: error output: nil
[TRACE Mi 01 Dez 2021 18:49:59] ...daniel/.vim/plugged/null-ls.nvim/lua/null-ls/helpers.lua:185: output: import React from "react";
import styled from "styled-components";
import { graphql } from "gatsby";
import Layout from "../layouts/MainLayout";
import { SEO } from "../components/basic/SEO";
import { TextBlock } from "../components/blog/BlogComponents";
import MetaInfo from "../components/blog/MetaInfo";

.... some code ....

[DEBUG Mi 01 Dez 2021 18:49:59] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/formatting.lua:55: received edits from generators
[TRACE Mi 01 Dez 2021 18:49:59] ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/formatting.lua:56: { {
    col = 1,
    end_col = 1,
    end_row = 79,
    row = 1,
    text = 'import React from "react";\nimport styled from "styled-components";\nimport { graphql } from "gatsby";\nimport Layout from "../layouts/MainLayout";\nimport { SEO } from "../components/basic/SEO";\nimport { TextBlock } from "../components/blog/BlogComponents";\nimport MetaInfo from "../components/blog/MetaInfo";\n\nconst Content = styled.div`\n\tdisplay: flex;\n\tflex-direction: column;\n\twidth: 100%;\n\tmin-height: 100%;\n\tmargin-top: calc(var(--navbar-height) / 2);\n`;\n\nconst BlogHeader = styled.h2`\n\tfont-size: 3.5em;\n\tfont-weight: 500;\n\n\tmargin: 0;\n\tmargin-bottom: 0.2em;\n`;\n\nconst HeadingWrapper = styled.div`\n\tmargin: 0 5vw;\n\twidth: 100%;\n\tdisplay: flex;\n\tflex-direction: column;\n\tjustify-content: baseline;\n\n\t@media screen and (max-width: 950px) {\n\t\tmargin: 0;\n\t\twidth: 95%;\n\t}\n`;\n\nexport const HeaderDivider = styled.div`\n\tmargin: 3em 0;\n\topacity: 0.2;\n\tfont-weight: 600;\n\tfont-size: 2.8em;\n`;\n\nexport default function BlogPost({ data }) {\n\tconst post = data.markdownRemark;\n\treturn (\n\t\t<Layout>\n\t\t\t<Content>\n\t\t\t\t<SEO\n\t\t\t\t\ttitle={post.frontmatter.title}\n\t\t\t\t\tdescription={data.excerpt}\n\t\t\t\t/>\n\t\t\t\t<HeadingWrapper>\n\t\t\t\t\t<BlogHeader>{post.frontmatter.title}</BlogHeader>\n\t\t\t\t\t<MetaInfo\n\t\t\t\t\t\tauthor={post.frontmatter.author}\n\t\t\t\t\t\tdate={post.frontmatter.date}\n\t\t\t\t\t/>\n\t\t\t\t</HeadingWrapper>\n\t\t\t\t<TextBlock\n\t\t\t\t\tdangerouslySetInnerHTML={{\n\t\t\t\t\t\t__html: post.html\n\t\t\t\t\t}}\n\t\t\t\t/>\n\t\t\t</Content>\n\t\t</Layout>\n\t);\n}\n\nexport const query = graphql`\n\tquery BlogQuery($slug: String!) {\n\t\tmarkdownRemark(fields: { slug: { eq: $slug } }) {\n\t\t\thtml\n\t\t\texcerpt\n\t\t\tfrontmatter {\n\t\t\t\ttitle\n\t\t\t\tauthor\n\t\t\t\tdate(fromNow: true)\n\t\t\t}\n\t\t}\n\t}\n`;\n'
  } }

### Help

No

**Comment by jose-elias-alvarez** [comment]
Your log is confusing since it seems to mix results from several sources. What exactly is the error you are seeing? If it's the `stylua` error, then the message is pretty clear (you need to have the executable installed and available on your `$PATH`). Other than that, your config is working properly on my end, so I'm not sure what the issue is.

**Comment by DanielWeidinger** [comment]
Sorry, I kinda forgot to include the actual error I'm getting within nvim:

Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:330: bufnr: expected number, got nil                                                                              
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:608: in function 'validate'
        /usr/share/nvim/runtime/lua/vim/lsp/util.lua:330: in function 'apply_text_edits'
        /home/daniel/.config/nvim/plugins/lsp/lsp.lua:10: in function 'handler'
        ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/formatting.lua:70: in function 'apply_edits'
        ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/formatting.lua:94: in function 'callback'
        ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:90: in function 'callback'
        ...iel/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:69: in function 'callback'
        ...el/.vim/plugged/plenary.nvim/lua/plenary/async/async.lua:21: in function 'callback_or_next'
        ...el/.vim/plugged/plenary.nvim/lua/plenary/async/async.lua:40: in function 'saved_callback'
        .../.vim/plugged/plenary.nvim/lua/plenary/async/control.lua:115: in function 'tx'
        ...iel/.vim/plugged/plenary.nvim/lua/plenary/async/util.lua:66: in function 'callback'
        ...el/.vim/plugged/plenary.nvim/lua/plenary/async/async.lua:21: in function 'callback_or_next'
        ...el/.vim/plugged/plenary.nvim/lua/plenary/async/async.lua:40: in function <...el/.vim/plugged/plenary.nvim/lua/plenary/async/async.lua:39>

**Comment by jose-elias-alvarez** [comment]
That's pretty peculiar – I understand the trace, but we've never seen this error reported before, and I can't understand how it could happen in the first place. Does this happen when formatting other files / with other sources, too?

**Comment by DanielWeidinger** [comment]
Yes, I get the same error on Lua(stylua) and Typescript(prettier) files. Haven't tried other sources, though.

**Comment by jose-elias-alvarez** [comment]
No idea about this one. I'd suggest updating Neovim and making sure you're on the latest version of null-ls, but other than that I don't know how it's possible for `bufnr` to be `nil` in this situation.  

For reference, your trace (after adjusting for a small fix that shouldn't make a difference here) references [this line](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/c6221e93531504ad19f622bd8f3bae859b31fcf0/lua/null-ls/formatting.lua#L73). `bufnr` is resolved [here](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/c6221e93531504ad19f622bd8f3bae859b31fcf0/lua/null-ls/utils.lua#L37-L50) and should be defined in every case. Figuring this out would require either a reliable reproduction (which might be tough, since as I mentioned your config works fine on my end) or some deep debugging in the null-ls code.

**Comment by DanielWeidinger** [comment]
I did some investigation on the two code-samples you provided, and in both cases `bufnr` is not `nil`. So it seems the issue stems from the native lsp functionality, specifically at: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:330: in function 'apply_text_edits'.

**Comment by jose-elias-alvarez** [comment]
That's even stranger. The path to `apply_text_edits` should go through [this handler](https://github.com/neovim/neovim/blob/73b35ef10f95536874bfa147c44f62c4fea08f0f/runtime/lua/vim/lsp/handlers.lua#L219), so I'm not sure why `bufnr` would be undefined by the time it gets [here](https://github.com/neovim/neovim/blob/73b35ef10f95536874bfa147c44f62c4fea08f0f/runtime/lua/vim/lsp/util.lua#L329).

**Comment by shihanng** [comment]
Apologies if this is unrelated and only adds noise, but I would like to share my findings.

I decided to try out null-ls this morning and have received the exact same error as posted in this issue.

<details>
<summary>
Error message below
</summary>

```Error detected while processing BufWritePre Autocommands for "<buffer=1>":
Error executing vim.schedule lua callback: ...lls/neovim/0.6.0/share/nvim/runtime/lua/vim/lsp/util.lua:330: bufnr: expected number, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:608: in function 'validate'
        ...lls/neovim/0.6.0/share/nvim/runtime/lua/vim/lsp/util.lua:330: in function 'apply_text_edits'
        ...ihanng/.config/nvim/lua/lsp_setups/default_on_attach.lua:7: in function 'handler'
        ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:70: in function 'apply_edits'
        ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:99: in function 'callback'
        ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:90: in function 'callback'
        ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:69: in function 'callback'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:21: in function 'callback_or_next'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:40: in function 'saved_callback'
        .../packer/start/plenary.nvim/lua/plenary/async/control.lua:115: in function 'tx'
        ...ack/packer/start/plenary.nvim/lua/plenary/async/util.lua:66: in function 'callback'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:21: in function 'callback_or_next'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:40: in function <...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:39>
        [C]: in function 'wait'
        ...installs/neovim/0.6.0/share/nvim/runtime/lua/vim/lsp.lua:996: in function 'request_sync'
        ...alls/neovim/0.6.0/share/nvim/runtime/lua/vim/lsp/buf.lua:180: in function 'formatting_sync'
        [string ":lua"]:1: in main chunk
vim.lsp.buf.formatting_sync: timeout
```
</details>

In my config file, I have this code that assigns custom format function to `vim.lsp.handlers["textDocument/formatting"]` which is from https://www.reddit.com/r/neovim/comments/jvisg5/lets_talk_formatting_again/.

```lua
local format_async = function(err, _, result, _, bufnr)
    if err ~= nil or result == nil then
        return
    end
    if not vim.api.nvim_buf_get_option(bufnr, "modified") then
        local view = vim.fn.winsaveview()
        vim.lsp.util.apply_text_edits(result, bufnr)
        vim.fn.winrestview(view)
        if bufnr == vim.api.nvim_get_current_buf() then
            vim.api.nvim_command("noautocmd :update")
        end
    end
end

vim.lsp.handlers["textDocument/formatting"] = format_async
```

I was able to mitigate my issue by removing the above from my config.

**Comment by DanielWeidinger** [comment]
@shihanng Thank you! This was indeed the issue. 
@jose-elias-alvarez Thank you for the fast replies and the help.

**Comment by jose-elias-alvarez** [comment]
Thank you @shihanng for the hint! 

FYI the signature for that `format_async` handler is outdated since Neovim 0.5.1. I believe it should continue to work if you update it to the following (though you might run into strange issues if you register multiple formatting sources, but let me know):

```lua
local format_async = function(err, result, ctx)
    if err ~= nil or result == nil then
        return
    end

    local bufnr = ctx.bufnr
    if not vim.api.nvim_buf_get_option(bufnr, "modified") then
        local view = vim.fn.winsaveview()
        vim.lsp.util.apply_text_edits(result, bufnr)
        vim.fn.winrestview(view)
        if bufnr == vim.api.nvim_get_current_buf() then
            vim.api.nvim_command("noautocmd :update")
        end
    end
end

vim.lsp.handlers["textDocument/formatting"] = format_async
```

**Comment by shihanng** [comment]
@jose-elias-alvarez Thank you for the snippet above.
I tested it out and it did not give any error plus the formatting was completed as expected.

I also tried with multiple formatting sources (with efm-language-server enabled) just for curiosity and it indeed has some strange behavior: I had to run format multiple times to get the result. However, I believe this should be raised as a separate issue if there is a need in the future.

Thank you for the snippet again!

**Comment by beauwilliams** [comment]
> Apologies if this is unrelated and only adds noise, but I would like to share my findings.
> 
> I decided to try out null-ls this morning and have received the exact same error as posted in this issue.
> Error message below
> 
> In my config file, I have this code that assigns custom format function to `vim.lsp.handlers["textDocument/formatting"]` which is from https://www.reddit.com/r/neovim/comments/jvisg5/lets_talk_formatting_again/.
> 
> ```lua
> local format_async = function(err, _, result, _, bufnr)
>     if err ~= nil or result == nil then
>         return
>     end
>     if not vim.api.nvim_buf_get_option(bufnr, "modified") then
>         local view = vim.fn.winsaveview()
>         vim.lsp.util.apply_text_edits(result, bufnr)
>         vim.fn.winrestview(view)
>         if bufnr == vim.api.nvim_get_current_buf() then
>             vim.api.nvim_command("noautocmd :update")
>         end
>     end
> end
> 
> vim.lsp.handlers["textDocument/formatting"] = format_async
> ```
> 
> I was able to mitigate my issue by removing the above from my config.

Thank you. I have been having this issue too.

**Comment by beauwilliams** [comment]
I made fn this to check for 0.5.1+ and set the correct async formatter

```lua
-- async formatting
-- https://www.reddit.com/r/neovim/comments/jvisg5/lets_talk_formatting_again/
-- NOTE: This is 0.5.1+ only
local format_async = function(err, result, ctx)
	if err ~= nil or result == nil then
		return
	end

	local bufnr = ctx.bufnr
	if not vim.api.nvim_buf_get_option(bufnr, 'modified') then
		local view = vim.fn.winsaveview()
		vim.lsp.util.apply_text_edits(result, bufnr)
		vim.fn.winrestview(view)
		if bufnr == vim.api.nvim_get_current_buf() then
			vim.api.nvim_command('noautocmd :update')
		end
	end
end

-- NOTE: This is 0.5 only
local format_async_legacy = function(err, _, result, _, bufnr)
	if err ~= nil or result == nil then
		return
	end
	if not vim.api.nvim_buf_get_option(bufnr, 'modified') then
		local view = fn.winsaveview()
		vim.lsp.util.apply_text_edits(result, bufnr)
		fn.winrestview(view)
		vim.api.nvim_command('noautocmd :update')
	end
end

local get_async_format_fn = function()
	if utils.hasVersion("0.5.1") then
		return format_async
	elseif utils.hasVersion("0.5") then
		return format_async_legacy
	end
end

vim.lsp.handlers['textDocument/formatting'] = get_async_format_fn()
```
