### ISSUE TITLE
Add `:checkhealth` support for checking if configured sources are executable

### ISSUE THREAD

**Issue by datwaft** [jose-elias-alvarez/null-ls.nvim#392]
### Issues

- [x] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I usually use `:checkhealth` to check if I all lspconfig executables `cmd` are executable.

_e.g._

```markdown
lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: clangd: configuration checked.
  - ERROR: arduino_language_server: The given command "arduino-language-server" is not executable.
  - INFO: cmake: configuration checked.
  - INFO: pyright: configuration checked.
  - ERROR: r_language_server: The given command "R" is not executable.
  - INFO: null-ls: configuration checked.
```

It would be helpful if I could do the same with null-ls, so that I could check if I have installed every executable that the plugin is configured to use.

This is useful if I am setting a new environment, or if I am not sure I have everything properly installed.

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I would like to help, but I don't have any experience implementing similar functionality.

**Edit:** `:help health-dev-lua` has the essentials of how to implement this functionality. I would still need help with how to get the executables for each configured source and how to check if the executables are executables.

**Comment by jose-elias-alvarez** [comment]
Sure, this could be a good idea. You could do it by using [`sources.get`](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/c69a7dc52a9c316a9e4e80e1aa2455777b5a7855/lua/null-ls/sources.lua#L80) with an empty query to get all registered sources, then using [`utils.is_executable`](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/c69a7dc52a9c316a9e4e80e1aa2455777b5a7855/lua/null-ls/utils.lua#L92) (or just `vim.fn.executable`) to check each commands. There's a few quirks you'd have to handle:  

1. Not all sources have a `command` defined
2. `command` can be a function
3. `command` could fail to resolve in the current directory but could resolve correctly when using an option like `only_local`

**Comment by datwaft** [comment]
Opened the pull request #396.
