### ISSUE TITLE
Rubocop

### ISSUE THREAD

**Issue by thevan96** [jose-elias-alvarez/null-ls.nvim#400]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Linter ruby by rubocop in two case:
- Run command: rubocop
- Run command with local project: bundle exec rubocop
I want option config like ale
https://github.com/dense-analysis/ale/blob/master/doc/ale-ruby.txt

### Help

No

**Comment by jose-elias-alvarez** [comment]
We don't have a dedicated config option for this case, but there are 2 possible solutions mentioned in #270.

**Comment by benjamineskola** [comment]
As-yet untested but could you achieve this using the [`conditional` helper](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#conditional-registration)?

(Commands in question taken from #270.)

```lua
local nls = require("null-ls")

nls.config({
    sources = {
        require("null-ls.helpers").conditional(function(utils)
            return utils.root_has_file("Gemfile")
                    and nls.builtins.formatting.rubocop.with({
                        command = "bundle",
                        args = vim.list_extend(
                            { "exec", "rubocop" },
                            require("null-ls").builtins.diagnostics.rubocop._opts.args
                        ),
                    })
                or nls.builtins.formatting.rubocop
        end),
    },
})
```

**Comment by thevan96** [comment]
> As-yet untested but could you achieve this using the [`conditional` helper](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#conditional-registration)?
> 
> (Commands in question taken from #270.)
> 
> ```lua
> local nls = require("null-ls")
> 
> nls.config({
>     sources = {
>         require("null-ls.helpers").conditional(function(utils)
>             return utils.root_has_file("Gemfile")
>                     and nls.builtins.formatting.rubocop.with({
>                         command = "bundle",
>                         args = vim.list_extend(
>                             { "exec", "rubocop" },
>                             nls.builtins.formatting.rubocop._opts.args
>                         ),
>                     })
>                 or nls.builtins.formatting.rubocop
>         end),
>     },
> })
> ```


I visited dotfile of your, your solution work but formatting not working, no response

**Comment by jose-elias-alvarez** [comment]
> > As-yet untested but could you achieve this using the [`conditional` helper](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#conditional-registration)?
> > (Commands in question taken from #270.)
> > ```lua
> > local nls = require("null-ls")
> > 
> > nls.config({
> >     sources = {
> >         require("null-ls.helpers").conditional(function(utils)
> >             return utils.root_has_file("Gemfile")
> >                     and nls.builtins.formatting.rubocop.with({
> >                         command = "bundle",
> >                         args = vim.list_extend(
> >                             { "exec", "rubocop" },
> >                             nls.builtins.formatting.rubocop._opts.args
> >                         ),
> >                     })
> >                 or nls.builtins.formatting.rubocop
> >         end),
> >     },
> > })
> > ```
> 
> I visited dotfile of your, your solution work but formatting not working, no response

I don't work with Ruby, but this solution is working for me (i.e. it spawns `bundle exec rubocop` when there is a file named `Gemfile` in the root directory and spawns `rubocop` if not). You mentioned linters in your original post, so try changing `formatting` to `diagnostics` in the example if that's what you want.

From what I gather, there's a few different ways to solve this (the cleanest being [binstubs](https://bundler.io/man/bundle-binstubs.1.html)). I don't plan on adding language-/linter-specific config options to the core, so I'm going to close this. If you're having issues with formatting, follow the instructions [here](https://github.com/jose-elias-alvarez/null-ls.nvim#something-isnt-working-what-do-i-do) and open an issue if you're convinced it's a null-ls issue and are able to put together a minimal reproduction.

**Comment by kassio** [comment]
this snippet is not working in the last version of the plugin:
`attempt to call field 'conditional' (a nil value)`. Was anyone here able to update to the last version?

**Comment by jose-elias-alvarez** [comment]
@kassio Apologies, the `conditional` helper was removed recently. It's pretty simple to replicate the same behavior (which is why it was removed):

```lua
local null_ls = require("null-ls")

local conditional = function(fn)
    local utils = require("null-ls.utils").make_conditional_utils()
    return fn(utils)
end

null_ls.setup({
    sources = {
        conditional(function(utils)
            return utils.root_has_file("Gemfile")
                    and null_ls.builtins.formatting.rubocop.with({
                        command = "bundle",
                        args = vim.list_extend({ "exec", "rubocop" }, null_ls.builtins.formatting.rubocop._opts.args),
                    })
                or null_ls.builtins.formatting.rubocop
        end),
    },
})
```

**Comment by goetzc** [comment]
> @kassio Apologies, the `conditional` helper was removed recently. It's pretty simple to replicate the same behavior (which is why it was removed):

This sounds like a great and very handy default option, for any language, use the specific package manager. If there is a `Gemfile`, make use of it. Same with others, like `package.json`, `Cargo.toml`, etc., try to use the respective/default/de-facto package manager.

**Comment by jose-elias-alvarez** [comment]
@goetzc The [`condition` helper](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md#condition) still exists and should handle the case you describe.
