### ISSUE TITLE
Allow specifying diagnostics format as function

### ISSUE THREAD

**Issue by rliebz** [jose-elias-alvarez/null-ls.nvim#403]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

## Feature

Having a function that takes a `diagnostic` as input and returns a format string would allow more flexibility than the current `diagnostics_format` parameter provides. This could be done by allowing `diagnostics_format` to be a function instead of a string.

For example:

```lua
diagnostics_format = function(diagnostic)
  if diagnostic.code then
    return string.format("[%s] %s (%s)", diagnostic.code, diagnostic.message, diagnostic.source)
  end
  
  return string.format("%s (%s)", diagnostic.message, diagnostic.source)
end
```

This would also more closely match the pattern used by `vim.diagnostic.config` to pass `virtual_text.format`.

## Use Case

For me, the problem this solves is that some linters provide a `code` while others do not. I would like to have formats that differ based on whether or not that code exists. For example, for a linter `my-linter` with code `E123` I might want the following:

```
[E123] An error was detected (my-linter)
```

If the linter does not provide error codes, however, this would produce an unhelpful `[]` at the start of the message:

```
[] An error was detected (my-linter)
```

Whereas I would prefer to omit the brackets when the error code is not available.

```
An error was detected (my-linter)
```

Note that while the example provided was based on the example in `CONFIG.md`, the flexibility to come up with arbitrary patterns based on the presence/absence of an error is desirable:
```
[my-linter: E123] An error was detected
[my-linter] An error was detected
```

## Alternatives

1. This behavior can be achieved today by passing a custom `diagnostics_format` to each built-in diagnostic. However, this requires a configuration on a per-diagnostic basis, rather than being able to set it once globally. 
2. The message format could be extended to support more advanced string templating. [This is how ale tackles the same issue](https://github.com/dense-analysis/ale/blob/master/doc/ale.txt#L1027-L1051). That said, this would likely be more work on this repo for less flexibility to the users. 

### Help

Yes

**Comment by jose-elias-alvarez** [comment]
I could have sworn that the new diagnostics API had a way to handle this, but I can't find anything in [the code](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/diagnostic.lua). I mentioned in #39 that users could override the handler to do this themselves, but it seems like the option has been removed.

Anyways, I think allowing `diagnostics_format` to be a function is a good idea. Alternatively (or in addition) we could be a little smarter about how we format diagnostics to remove surrounding characters, since I imagine the `code` case in your description is pretty common. I won't have time to work on this myself for a bit but would welcome a PR.

**Comment by rliebz** [comment]
It's possible to get formatting through [the diagnostic API](https://github.com/neovim/neovim/blob/master/runtime/doc/diagnostic.txt#L351-L361) ([implementation](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/diagnostic.lua#L123-L134)), but the core component that's missing for me is the diagnostic "code", since that's not part of [the built-in definition of a diagnostic](https://github.com/neovim/neovim/blob/master/runtime/doc/diagnostic.txt#L42-L50). 

I opened up a PR with a potential implementation (#406), when you get the chance, feel free to let me know what you think!

**Comment by kylo252** [comment]
> I could have sworn that the new diagnostics API had a way to handle this

@jose-elias-alvarez, It does.
 
> but the core component that's missing for me is the diagnostic "code", since that's not part of [the built-in definition of a 

You must have been doing something wrong, it already works fine for me.

![image](https://user-images.githubusercontent.com/59826753/145368214-d8677e18-ff1a-4b89-96b5-3ebe1f5ca8da.png)

Here's my configuration

```lua
  local config = {
    virtual_text = false,
    signs = signs,
    underline = true,
    update_in_insert = true,
    severity_sort = true,
    float = {
      focusable = false,
      style = "minimal",
      border = "rounded",
      source = "always",
      header = "",
      prefix = "",
      format = function(d)
        local t = vim.deepcopy(d)
        if d.code then
          t.message = string.format("%s [%s]", t.message, t.code):gsub("1. ", "")
        end
        return t.message
      end,
    },
  }

  vim.diagnostic.config(config)
```

**Comment by rliebz** [comment]
@kylo252 Thanks for the quick feedback. I didn't realize that extra properties passed through to the built-in diagnostic API would also be available as part of the format function. Since they are, you're absolutely right, this is unnecessary.
