### ISSUE TITLE
null-ls server not starting

### ISSUE THREAD

**Issue by MurdeRMelodY** [jose-elias-alvarez/null-ls.nvim#41]
Since the most recent updates, I've been this issue. Am I doing something wrong?
```lua
require("packer").startup(function(use)
  use { "wbthomason/packer.nvim" }

  use {
    "jose-elias-alvarez/null-ls.nvim",
    requires = {
      { "nvim-lua/plenary.nvim" },
      { "neovim/nvim-lspconfig" }
    },
    config = function()
      require("null-ls").config {
        sources = {
          require("null-ls").builtins.formatting.stylua,
        }
      }
      require("lspconfig")["null-ls"].setup {
        on_attach = function()
          vim.cmd([[autocmd BufWritePost <buffer> lua vim.lsp.buf.formatting()]])
        end
      }
    end
  }
end)
```

**Comment by folke** [comment]
Do you get any kind of error?

Could you post your full `plugins.lua`?

**Comment by folke** [comment]
I just tested with your minimal example, and everything seems to work as expected

**Comment by MurdeRMelodY** [comment]
> Do you get any kind of error?
> 
> Could you post your full `plugins.lua`?

Nope. I don't get any errors. My plugins config is split up into different files:

'plugins/dev.lua'
```lua
local config = function(plugin)
  return string.format(
    [[require("plugins.dev.%s.config")]],
    plugin
  )
end

dev["neovim/nvim-lspconfig"] = {
  config = config("lspconfig")
}

dev["jose-elias-alvarez/null-ls.nvim"] = {
  requires = {
    { "nvim-lua/plenary.nvim" },
    { "neovim/nvim-lspconfig" }
  },
  config = config("null_ls"),
}
```

'plugins/dev/null_ls/config.lua'
```lua
require("null-ls").config({
  sources = { require("null-ls").builtins.formatting.stylua }
})

require("lspconfig")["null-ls"].setup({
  on_attach = function(client, bufnr)
    vim.cmd([[autocmd BufWritePost <buffer> lua vim.lsp.buf.formatting()]])
  end
})
```

**Comment by MurdeRMelodY** [comment]
> > Do you get any kind of error?
> > Could you post your full `plugins.lua`?
> 
> Nope. I don't get any errors. My plugins config is split up into different files:
> 
> 'plugins/dev.lua'
> 
> ```lua
> local config = function(plugin)
>   return string.format(
>     [[require("plugins.dev.%s.config")]],
>     plugin
>   )
> end
> 
> dev["neovim/nvim-lspconfig"] = {
>   config = config("lspconfig")
> }
> 
> dev["jose-elias-alvarez/null-ls.nvim"] = {
>   requires = {
>     { "nvim-lua/plenary.nvim" },
>     { "neovim/nvim-lspconfig" }
>   },
>   config = config("null_ls"),
> }
> ```
> 
> 'plugins/dev/null_ls/config.lua'
> 
> ```lua
> require("null-ls").config({
>   sources = { require("null-ls").builtins.formatting.stylua }
> })
> 
> require("lspconfig")["null-ls"].setup({
>   on_attach = function(client, bufnr)
>     vim.cmd([[autocmd BufWritePost <buffer> lua vim.lsp.buf.formatting()]])
>   end
> })
> ```

calling `vim.lsp.buf.formatting()` manually doesn't work either and `LspInfo` shows no available servers

**Comment by folke** [comment]
Did you run `PackerInstall`? And restart nvim before and after your changes?

**Comment by MurdeRMelodY** [comment]
> Did you run `PackerSync`? And restart nvim before and after your changes?

Yeah it's working now. thanks a lot.
```lua
require("null-ls").config({
  sources = { require("null-ls").builtins.formatting.stylua },
})

require("lspconfig")["null-ls"].setup({
  on_attach = function(_, _)
    vim.cmd("autocmd BufWritePost <buffer> lua vim.lsp.buf.formatting()")
  end,
  root_dir = vim.loop.cwd,
})
```

**Comment by MurdeRMelodY** [comment]
Sorry this is probably unrelated to this plugin but I encountered something strange in `LspInfo`.
![2021-07-22-002828_1094x418_scrot](https://user-images.githubusercontent.com/63958167/126568467-2b2863a1-70ea-44c2-85c5-9468265e562b.png)
Is this normal?

**Comment by jose-elias-alvarez** [comment]
Not sure about this one, does it also happen when you comment out null-ls from your config? If not I'd look into your lua-language-server config, since it looks like the autocommands that spawn a server when you open a Lua file might be getting duplicated (though I can't say for sure). 

For `root_dir`, we're currently using `Makefile` and `.git` as root markers, so it won't work out of the box on files that don't have those markers in their root directories. We might tweak these in the future, but not running on any random file unless specified by the user is consistent with actual LSP behavior, so I think your solution makes sense.

**Comment by folke** [comment]
@jose-elias-alvarez for null-ls you can probably fallback to `dirname` in https://github.com/jose-elias-alvarez/null-ls.nvim/blob/2c2aec89bb85cc38e9fd6f83a93bb748ae462a01/lua/null-ls/lspconfig.lua#L15

So:

```lua
config_def.root_dir = function(fname)
  return util.root_pattern('.git')(fname) or util.path.dirname(fname)
end
```

@MurdeRMelodY That Sumneko issue is unrelated to null-ls and has to do with the fact that the root_dir cannot be detected there and the default fallback right now is also `dirname`. @mjlbach has a PR to show a prompt in this case where you can choose the root dir if it can not be detected.

**Comment by MurdeRMelodY** [comment]
thanks a lot. closing.
