### ISSUE TITLE
Per filetype settings for prettier

### ISSUE THREAD

**Issue by ranebrown** [jose-elias-alvarez/null-ls.nvim#42]
Using the builtin prettier formatter is there a way to change settings per filetype? E.g. set `--tab-width 4` for markdown and 2 for everything else?

**Comment by jose-elias-alvarez** [comment]
Yes! We recently added (still poorly-documented) support for setting arguments dynamically. This should get you started:

```lua
null_ls.builtins.formatting.prettier.with({
    args = function(params)
        return params.ft == "markdown" and { "$FILENAME", "--tab-width", "4" } or { "$FILENAME" }
    end,
})
```

**Comment by ranebrown** [comment]
Nice! That works, thanks!
