### ISSUE TITLE
stylint can't be initialized

### ISSUE THREAD

**Issue by mortezadadgar** [jose-elias-alvarez/null-ls.nvim#426]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.6.0

### null-ls config

local null_ls = require "null-ls"
null_ls.setup {
	debug = true,
	sources = {
		null_ls.builtins.formatting.prettier.with {
			extra_args = { "--tab-width", "4" },
		},
		null_ls.builtins.formatting.goimports,
		null_ls.builtins.diagnostics.shellcheck,
		null_ls.builtins.diagnostics.golangci_lint,
		null_ls.builtins.diagnostics.stylelint
	},
}

### Steps to reproduce

1) install stylelint `sudo npm install -g --save-dev stylelint stylelint-config-standard`
2) create a standard stylelint config file according to [doc](https://github.com/stylelint/stylelint/blob/main/docs/user-guide/get-started.md#linting-css) in project root directory
3) open a css file
4) null-ls print this error `[null-ls] [WARN  19:10:07] .../pack/packer/opt/null-ls.nvim/lua/null-ls/.../stylelint.lua:19: Expected value but found invalid token at character 1`

### Expected behavior

-

### Actual behavior

-

### Debug log

[TRACE Mon 13 Dec 2021 07:07:09 PM +0330] ...site/pack/packer/opt/null-ls.nvim/lua/null-ls/client.lua:74: starting null-ls client
[TRACE Mon 13 Dec 2021 07:07:09 PM +0330] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:117: received LSP request for method initialize
[DEBUG Mon 13 Dec 2021 07:07:09 PM +0330] ...site/pack/packer/opt/null-ls.nvim/lua/null-ls/client.lua:125: unable to notify client for method textDocument/didOpen (client not active): {
  textDocument = {
    uri = "file:///home/*/workspace/*/*/css/style.css"
  }
}
[TRACE Mon 13 Dec 2021 07:07:09 PM +0330] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method initialized
[TRACE Mon 13 Dec 2021 07:07:09 PM +0330] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didOpen
[TRACE Mon 13 Dec 2021 07:07:09 PM +0330] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Mon 13 Dec 2021 07:07:09 PM +0330] ...ite/pack/packer/opt/null-ls.nvim/lua/null-ls/helpers.lua:303: spawning command [stylelint] with args { "--formatter", "json", "--stdin-filename", "/home/*/workspace/*/*/css/style.css" }
[TRACE Mon 13 Dec 2021 07:07:09 PM +0330] ...ite/pack/packer/opt/null-ls.nvim/lua/null-ls/helpers.lua:185: error output: Error: Could not find "stylelint-config-standard". Do you need a `configBasedir`?
    at module.exports (/usr/lib64/node_modules/stylelint/lib/utils/configurationError.js:11:49)
    at getModulePath (/usr/lib64/node_modules/stylelint/lib/utils/getModulePath.js:27:9)
    at loadExtendedConfig (/usr/lib64/node_modules/stylelint/lib/augmentConfig.js:225:21)
    at extendConfig (/usr/lib64/node_modules/stylelint/lib/augmentConfig.js:196:30)
    at augmentConfigBasic (/usr/lib64/node_modules/stylelint/lib/augmentConfig.js:52:26)
    at augmentConfigFull (/usr/lib64/node_modules/stylelint/lib/augmentConfig.js:102:30)
    at Object.transform (/usr/lib64/node_modules/stylelint/lib/getConfigForFile.js:46:37)
    at run (/usr/lib64/node_modules/stylelint/node_modules/cosmiconfig/dist/Explorer.js:42:49)
    at async cacheWrapper (/usr/lib64/node_modules/stylelint/node_modules/cosmiconfig/dist/cacheWrapper.js:16:18)
    at async cacheWrapper (/usr/lib64/node_modules/stylelint/node_modules/cosmiconfig/dist/cacheWrapper.js:16:18)

[TRACE Mon 13 Dec 2021 07:07:09 PM +0330] ...ite/pack/packer/opt/null-ls.nvim/lua/null-ls/helpers.lua:186: output: nil
[WARN  Mon 13 Dec 2021 07:07:09 PM +0330] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:39: failed to run generator: ...l-ls.nvim/lua/null-ls/builtins/diagnostics/stylelint.lua:19: Expected value but found invalid token at character 1
[TRACE Mon 13 Dec 2021 07:07:21 PM +0330] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:117: received LSP request for method shutdown
[TRACE Mon 13 Dec 2021 07:07:21 PM +0330] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method exit

### Help

No

**Comment by mortezadadgar** [comment]
installing stylelint-config-standard locally return another error

<details>
<summary>Details</summary>

[TRACE Mon 13 Dec 2021 07:23:09 PM +0330] ...site/pack/packer/opt/null-ls.nvim/lua/null-ls/client.lua:74: starting null-ls client
[TRACE Mon 13 Dec 2021 07:23:09 PM +0330] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:117: received LSP request for method initialize
[DEBUG Mon 13 Dec 2021 07:23:09 PM +0330] ...site/pack/packer/opt/null-ls.nvim/lua/null-ls/client.lua:125: unable to notify client for method textDocument/didOpen (client not active): {
  textDocument = {
    uri = "file:///home/morteza/workspace/Html-css/acme/css/style.css"
  }
}
[TRACE Mon 13 Dec 2021 07:23:09 PM +0330] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method initialized
[TRACE Mon 13 Dec 2021 07:23:09 PM +0330] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didOpen
[TRACE Mon 13 Dec 2021 07:23:09 PM +0330] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Mon 13 Dec 2021 07:23:09 PM +0330] ...ite/pack/packer/opt/null-ls.nvim/lua/null-ls/helpers.lua:303: spawning command [stylelint] with args { "--formatter", "json", "--stdin-filename", "/home/morteza/workspace/Html-css/acme/css/style.css" }
[TRACE Mon 13 Dec 2021 07:23:09 PM +0330] ...ite/pack/packer/opt/null-ls.nvim/lua/null-ls/helpers.lua:185: error output: [{"source":"/home/morteza/workspace/Html-css/acme/css/style.css","deprecations":[],"invalidOptionWarnings":[],"parseErrors":[],"errored":true,"warnings":[{"line":24,"column":12,"rule":"color-hex-length","severity":"error","text":"Expected \"#ffffff\" to be \"#fff\" (color-hex-length)"},{"line":31,"column":12,"rule":"color-hex-length","severity":"error","text":"Expected \"#ffffff\" to be \"#fff\" (color-hex-length)"},{"line":44,"column":12,"rule":"color-hex-length","severity":"error","text":"Expected \"#ffffff\" to be \"#fff\" (color-hex-length)"},{"line":68,"column":12,"rule":"color-hex-length","severity":"error","text":"Expected \"#cccccc\" to be \"#ccc\" (color-hex-length)"},{"line":75,"column":12,"rule":"color-hex-length","severity":"error","text":"Expected \"#ffffff\" to be \"#fff\" (color-hex-length)"},{"line":92,"column":12,"rule":"color-hex-length","severity":"error","text":"Expected \"#ffffff\" to be \"#fff\" (color-hex-length)"},{"line":131,"column":12,"rule":"color-hex-length","severity":"error","text":"Expected \"#ffffff\" to be \"#fff\" (color-hex-length)"},{"line":133,"column":5,"rule":"comment-empty-line-before","severity":"error","text":"Expected empty line before comment (comment-empty-line-before)"},{"line":2,"column":20,"rule":"font-family-no-missing-generic-family-keyword","severity":"error","text":"Unexpected missing generic font family (font-family-no-missing-generic-family-keyword)"},{"line":80,"column":1,"rule":"no-descending-specificity","severity":"error","text":"Expected selector \"#showcase h1\" to come before selector \"header #branding h1\" (no-descending-specificity)"},{"line":20,"column":1,"rule":"selector-class-pattern","severity":"error","text":"Expected class selector to be kebab-case"},{"line":40,"column":5,"rule":"shorthand-property-no-redundant-values","severity":"error","text":"Unexpected longhand value '0 20px 0 20px' instead of '0 20px' (shorthand-property-no-redundant-values)"},{"line":81,"column":18,"rule":"unit-no-unknown","severity":"error","text":"Unexpected unknown unit \"x\" (unit-no-unknown)"},{"line":2,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":3,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":4,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":5,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":10,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":11,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":12,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":16,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":17,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":21,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":22,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":23,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":24,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":25,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":30,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":31,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":32,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":33,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":34,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":35,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":39,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":40,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":44,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":45,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":46,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":50,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":54,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":58,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":59,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":64,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":68,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":69,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":74,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":75,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":76,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":77,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":81,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":82,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":86,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":91,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":92,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":93,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":94,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":98,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":102,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":103,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":107,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":108,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":109,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":114,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":118,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":119,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":120,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":124,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":128,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":129,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":130,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":131,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":132,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":133,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":137,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":142,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":138,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":139,"column":9,"rule":"indentation","severity":"error","text":"Expected indentation of 4 spaces (indentation)"},{"line":140,"column":9,"rule":"indentation","severity":"error","text":"Expected indentation of 4 spaces (indentation)"},{"line":141,"column":9,"rule":"indentation","severity":"error","text":"Expected indentation of 4 spaces (indentation)"},{"line":144,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":146,"column":5,"rule":"indentation","severity":"error","text":"Expected indentation of 2 spaces (indentation)"},{"line":145,"column":9,"rule":"indentation","severity":"error","text":"Expected indentation of 4 spaces (indentation)"}]}]
[TRACE Mon 13 Dec 2021 07:23:09 PM +0330] ...ite/pack/packer/opt/null-ls.nvim/lua/null-ls/helpers.lua:186: output: nil
[WARN  Mon 13 Dec 2021 07:23:09 PM +0330] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:39: failed to run generator: ...l-ls.nvim/lua/null-ls/builtins/diagnostics/stylelint.lua:19: Expected value but found invalid token at character 1


</details>

**Comment by jose-elias-alvarez** [comment]
I wasn't able to replicate your specific error, but I think the Stylelint built-in was relying on the behavior of `vim.fn.json_decode` when decoding strings. 319ceacc82eb5c8f79edd3a046d16b7d6ff3dfe3 should handle errors properly, so could you try updating the plugin and see if it helps?

**Comment by mortezadadgar** [comment]
Thanks for quick response, now I'm getting this on screen error 
![image](https://user-images.githubusercontent.com/27911493/145858722-6086a2de-3bfd-41b3-a990-397c64bb872f.png)

**Comment by jose-elias-alvarez** [comment]
Looks like Stylelint is annoying and outputs valid output *and* errors to `stderr`. Could you update and try again?

**Comment by mortezadadgar** [comment]
thanks stylelint works now tough I have to install stylelint-config-standard for every project do you have any idea why stylelint-config-standard couldn't be installed globally?

**Comment by jose-elias-alvarez** [comment]
No idea, it actually does work when installed globally on my end, which is why I wasn't able to replicate your exact error. Maybe it has to do with permissions? I install global npm modules without `sudo`, so that could be related.

**Comment by mortezadadgar** [comment]
thanks I had to write .stylelintrc.json like this
`
{
  "extends": "/usr/lib64/node_modules/stylelint-config-standard/node_modules/stylelint-config-recommended"
}
`
