### ISSUE TITLE
transition from lspconfig

### ISSUE THREAD

**Issue by danjenson** [jose-elias-alvarez/null-ls.nvim#429]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.6.0

### null-ls config

see reproduction step

### Steps to reproduce

Remove:
```lua
	use({
		"jose-elias-alvarez/null-ls.nvim",
		after = "nvim-lspconfig",
		config = function()
			local x = require("null-ls")
			local b = x.builtins
			x.setup({
				-- format on save set in autocmds
				sources = {
					-- [web] shell: sudo npm i -g prettierd
					b.formatting.prettierd,
					-- [markdown] shell: sudo npm i -g write-good
					b.diagnostics.write_good,
					-- [R] R: install.packages('formatR')
					b.formatting.format_r,
					-- [rust] shell: rustup component add rustfmt [--toolchain nightly]
					b.formatting.rustfmt,
					-- [lua] shell: cargo install stylua
					b.formatting.stylua,
					-- [lua] shell: sudo luarocks install luacheck; sudo luarocks install lanes
					b.diagnostics.luacheck,
					-- [python] shell: pip install yapf
					b.formatting.yapf,
				},
			})
                        -- COMMENTED OUT / REMOVED REFERENCE TO lspconfig
			-- local on_attach = function(client)
			-- 	if client.resolved_capabilities.document_formatting then
			-- 		vim.cmd("autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()")
			-- 	end
			-- end
			-- require("lspconfig")["null-ls"].setup({ on_attach = on_attach })
		end,
	})

	use({
		"williamboman/nvim-lsp-installer",
		after = "null-ls.nvim",
		config = function()
			local lsp_installer = require("nvim-lsp-installer")
			lsp_installer.on_server_ready(function(server)
                                -- ADDED HERE, BUT DOESN'T WORK
				local on_attach = function(client)
					if client.resolved_capabilities.document_formatting then
						vim.cmd("autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()")
					end
				end
				server:setup({ on_attach = on_attach })
			end)
		end,
	})
```

### Expected behavior

autocommand for formatting would work.

### Actual behavior

Nothing happens on save.

### Debug log

[TRACE Mon Dec 13 10:05:12 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didSave
[DEBUG Mon Dec 13 10:05:12 2021] ...pack/packer/opt/null-ls.nvim/lua/null-ls/diagnostics.lua:141: buffer unchanged; ignoring didSave notification
[TRACE Mon Dec 13 10:05:23 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didChange
[TRACE Mon Dec 13 10:05:23 2021] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG Mon Dec 13 10:05:23 2021] ...ite/pack/packer/opt/null-ls.nvim/lua/null-ls/helpers.lua:303: spawning command [luacheck] with args { "--formatter", "plain", "--codes", "--ranges", "--filename", "/data/repos/conf/void/dots/config/nvim/init.lua", "-" }
[TRACE Mon Dec 13 10:05:23 2021] ...ite/pack/packer/opt/null-ls.nvim/lua/null-ls/helpers.lua:185: error output: /data/repos/conf/void/dots/config/nvim/init.lua:6:1-3: (W112) mutating non-standard global variable 'vim'
/data/repos/conf/void/dots/config/nvim/init.lua:106:7-9: (W113) accessing undefined variable 'vim'

[TRACE Mon Dec 13 10:05:23 2021] ...ite/pack/packer/opt/null-ls.nvim/lua/null-ls/helpers.lua:186: output: nil
[TRACE Mon Dec 13 10:05:23 2021] ...pack/packer/opt/null-ls.nvim/lua/null-ls/diagnostics.lua:155: received diagnostics from source 6
[TRACE Mon Dec 13 10:05:23 2021] ...pack/packer/opt/null-ls.nvim/lua/null-ls/diagnostics.lua:156: { {
    code = "112",
    col = 0,
    end_col = 3,
    end_lnum = 5,
    lnum = 5,
    message = "mutating non-standard global variable 'vim'",
    row = "6",
    severity = 2,
    source = "luacheck"
  }, {
    code = "113",
    col = 6,
    end_col = 9,
    end_lnum = 105,
    lnum = 105,
    message = "accessing undefined variable 'vim'",
    row = "106",
    severity = 2,
    source = "luacheck"
  } }
[TRACE Mon Dec 13 10:05:23 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didSave
[TRACE Mon Dec 13 10:05:23 2021] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS_ON_SAVE
[DEBUG Mon Dec 13 10:05:23 2021] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available
[TRACE Mon Dec 13 10:06:54 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didSave
[DEBUG Mon Dec 13 10:06:54 2021] ...pack/packer/opt/null-ls.nvim/lua/null-ls/diagnostics.lua:141: buffer unchanged; ignoring didSave notification
[TRACE Mon Dec 13 10:06:56 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didSave
[DEBUG Mon Dec 13 10:06:56 2021] ...pack/packer/opt/null-ls.nvim/lua/null-ls/diagnostics.lua:141: buffer unchanged; ignoring didSave notification
[TRACE Mon Dec 13 10:06:56 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:117: received LSP request for method shutdown
[TRACE Mon Dec 13 10:06:56 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method exit
[TRACE Mon Dec 13 10:06:58 2021] ...site/pack/packer/opt/null-ls.nvim/lua/null-ls/client.lua:74: starting null-ls client
[TRACE Mon Dec 13 10:06:58 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:117: received LSP request for method initialize
[DEBUG Mon Dec 13 10:06:58 2021] ...site/pack/packer/opt/null-ls.nvim/lua/null-ls/client.lua:125: unable to notify client for method textDocument/didOpen (client not active): {
  textDocument = {
    uri = "file:///home/danj/setup.py"
  }
}
[TRACE Mon Dec 13 10:06:58 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method initialized
[TRACE Mon Dec 13 10:06:58 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didOpen
[TRACE Mon Dec 13 10:06:58 2021] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Mon Dec 13 10:06:58 2021] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available
[TRACE Mon Dec 13 10:07:00 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didSave
[TRACE Mon Dec 13 10:07:00 2021] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS_ON_SAVE
[DEBUG Mon Dec 13 10:07:00 2021] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available
[TRACE Mon Dec 13 10:07:04 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didChange
[TRACE Mon Dec 13 10:07:04 2021] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG Mon Dec 13 10:07:04 2021] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available
[TRACE Mon Dec 13 10:07:04 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didSave
[TRACE Mon Dec 13 10:07:04 2021] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS_ON_SAVE
[DEBUG Mon Dec 13 10:07:04 2021] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available
[TRACE Mon Dec 13 10:07:34 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didSave
[DEBUG Mon Dec 13 10:07:34 2021] ...pack/packer/opt/null-ls.nvim/lua/null-ls/diagnostics.lua:141: buffer unchanged; ignoring didSave notification
[TRACE Mon Dec 13 10:07:35 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didSave
[DEBUG Mon Dec 13 10:07:35 2021] ...pack/packer/opt/null-ls.nvim/lua/null-ls/diagnostics.lua:141: buffer unchanged; ignoring didSave notification
[TRACE Mon Dec 13 10:07:40 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:117: received LSP request for method shutdown
[TRACE Mon Dec 13 10:07:40 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method exit
[TRACE Mon Dec 13 10:07:43 2021] ...site/pack/packer/opt/null-ls.nvim/lua/null-ls/client.lua:74: starting null-ls client
[TRACE Mon Dec 13 10:07:43 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:117: received LSP request for method initialize
[DEBUG Mon Dec 13 10:07:43 2021] ...site/pack/packer/opt/null-ls.nvim/lua/null-ls/client.lua:125: unable to notify client for method textDocument/didOpen (client not active): {
  textDocument = {
    uri = "file:///data/repos/conf/void/dots/config/nvim/init.lua"
  }
}
[TRACE Mon Dec 13 10:07:43 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method initialized
[TRACE Mon Dec 13 10:07:43 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didOpen
[TRACE Mon Dec 13 10:07:43 2021] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Mon Dec 13 10:07:43 2021] ...ite/pack/packer/opt/null-ls.nvim/lua/null-ls/helpers.lua:303: spawning command [luacheck] with args { "--formatter", "plain", "--codes", "--ranges", "--filename", "/data/repos/conf/void/dots/config/nvim/init.lua", "-" }
[TRACE Mon Dec 13 10:07:43 2021] ...ite/pack/packer/opt/null-ls.nvim/lua/null-ls/helpers.lua:185: error output: /data/repos/conf/void/dots/config/nvim/init.lua:6:1-3: (W112) mutating non-standard global variable 'vim'
/data/repos/conf/void/dots/config/nvim/init.lua:106:7-9: (W113) accessing undefined variable 'vim'

[TRACE Mon Dec 13 10:07:43 2021] ...ite/pack/packer/opt/null-ls.nvim/lua/null-ls/helpers.lua:186: output: nil
[TRACE Mon Dec 13 10:07:43 2021] ...pack/packer/opt/null-ls.nvim/lua/null-ls/diagnostics.lua:155: received diagnostics from source 6
[TRACE Mon Dec 13 10:07:43 2021] ...pack/packer/opt/null-ls.nvim/lua/null-ls/diagnostics.lua:156: { {
    code = "112",
    col = 0,
    end_col = 3,
    end_lnum = 5,
    lnum = 5,
    message = "mutating non-standard global variable 'vim'",
    row = "6",
    severity = 2,
    source = "luacheck"
  }, {
    code = "113",
    col = 6,
    end_col = 9,
    end_lnum = 105,
    lnum = 105,
    message = "accessing undefined variable 'vim'",
    row = "106",
    severity = 2,
    source = "luacheck"
  } }
[TRACE Mon Dec 13 10:07:44 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didSave
[TRACE Mon Dec 13 10:07:44 2021] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS_ON_SAVE
[DEBUG Mon Dec 13 10:07:44 2021] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available
[TRACE Mon Dec 13 10:07:46 2021] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didSave
[DEBUG Mon Dec 13 10:07:46 2021] ...pack/packer/opt/null-ls.nvim/lua/null-ls/diagnostics.lua:141: buffer unchanged; ignoring didSave notification

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by danjenson** [comment]
I reverted to the version that uses `lspconfig` and it looks like this is no longer throwing the error message?

**Comment by danjenson** [comment]
There was no error, it just wasn't autoformatting. The documentation on the front page says to add `on_attach` to each of the language servers, so I was trying to do that in `nvim-lsp-installer`, but this is much eaiser.

**Comment by jose-elias-alvarez** [comment]
You're right, that bit of documentation needs to be updated. Thanks!
