### ISSUE TITLE
Enable `condition` when using `make_builtin`

### ISSUE THREAD

**Issue by iDuuck** [jose-elias-alvarez/null-ls.nvim#433]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

While setting up my nvim to use `null-ls` instead of `Neoformat` (btw, [super stoked about this](https://twitter.com/n___vc/status/1470691079976628226)), I saw, that there might be a problem with eslint_d, when there is no actual eslint configuration in the project (see below).

<img width="633" alt="Screenshot 2021-12-14 at 11 14 29" src="https://user-images.githubusercontent.com/325241/145978765-41d47f50-fc93-4bb4-8b8d-f71fb9173bae.png">

When we are having an eslint configuration in the project, we are not having the problem with the error above.

---

**My proposal** would be to implement something that we can use when registering/making the builtin, and not only when using the source.

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by jose-elias-alvarez** [comment]
I'm not sure I understand the request completely. We currently have [conditional source registration](https://github.com/vuki656/nvim-config/blob/f0ef7bd443feadaeb4f398bdc919f38df1da49a7/lua/plugins/formatter-linter.lua#L49) which can be used to avoid registering a source if a config file isn't present. I've personally used it to handle the ESLint case you describe, but am I misunderstanding what you want here?

**Comment by jose-elias-alvarez** [comment]
This is supported as of 742739910ef5ef93efcaed32a5b875d7833b42af.
