### ISSUE TITLE
Disable null-ls formatting from `on_attach`

### ISSUE THREAD

**Issue by axieax** [jose-elias-alvarez/null-ls.nvim#436]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Condition: LSP server (e.g. gopls) has formatting capabilities but no formatting source has been specifically enabled for Go filetypes from null-ls, except for `null_ls.builtins.formatting.trim_whitespace` which has `filetypes = {}`. I want to be able to disable null's formatting capabilities, specifically for this source, when this condition is satisfied (if LSP supports formatting but null does not specifically):
```lua
function default_on_attach(client, bufnr)
  -- documentFormatting
  local name = client.name
  print(name)
  local is_null = name == "null-ls"
  local ls_can_format = client.resolved_capabilities.document_formatting
  print("ls_can_format", ls_can_format)
  local null_can_format = require("lsp.null").use_null_formatting()
  print("null_can_format", null_can_format)

  -- prefer null-ls for formatting if available
  if (not is_null and null_can_format) or (is_null and not null_can_format) then
    -- disable formatting
    print("formatting disabled")
    client.resolved_capabilities.document_formatting = false
    client.resolved_capabilities.document_range_formatting = false
  else
    -- use client for formatting
    print("formatting enabled")
    vim.cmd("autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()")
  end
end
```
Please note that my language servers and null both use the same `on_attach` function above. It seems that disabling formatting for LSP servers doesn't work for null-ls in the same way. My full config can be found [here](https://github.com/axieax/dotconfig). 

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

Not sure if `client.resolved_capabilities.document_formatting = false` and `client.resolved_capabilities.document_range_formatting = false` can be used to target null-ls.

**Comment by jose-elias-alvarez** [comment]
Yes, modifying `resolved_capabilities` works. I don't know what `require("lsp.null").use_null_formatting()` does, but I think there's something weird about your condition. This is what I tried to use and it works as expected:

```lua
local null_ls = require("null-ls")
local null_ls_sources = require("null-ls.sources")

local on_attach = function(client, bufnr)
    local name = client.name
    local ls_can_format = client.resolved_capabilities.document_formatting
    print("ls_can_format", ls_can_format)

    local is_null = name == "null-ls"
    local null_can_format = #vim.tbl_filter(function(source)
        return null_ls_sources.is_available(
            source,
            vim.api.nvim_buf_get_option(bufnr, "filetype"),
            null_ls.methods.FORMATTING
        )
    end, null_ls_sources.get({})) > 0
    print("null_can_format", null_can_format)

    if (not is_null and null_can_format) or (is_null and not null_can_format) then
        print("formatting disabled", name)
        client.resolved_capabilities.document_formatting = false
        client.resolved_capabilities.document_range_formatting = false
    else
        print("formatting enabled", name)
        vim.cmd("autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()")
    end
end
```

I'd try to simplify it and try to figure out where it's going wrong. You could also solve the specific issue at hand by setting `disabled_filetypes = { "go"}` for the formatter.

**Comment by axieax** [comment]
```lua
function M.default_on_attach(client, bufnr)
  local name = client.name
  local is_null = name == "null-ls"
  local filetype = vim.api.nvim_buf_get_option(bufnr, "filetype")
  local ls_can_format = client.resolved_capabilities.document_formatting
  local null_can_format = require("lsp.null").use_null_formatting(filetype)

  print(name)
  print("ls_can_format", ls_can_format)
  print("null_can_format", null_can_format)

  -- prefer null-ls for formatting if available
  if (not is_null and null_can_format) or (is_null and not null_can_format) then
    -- disable formatting
    print("formatting disabled")
    client.resolved_capabilities.document_formatting = false
    client.resolved_capabilities.document_range_formatting = false
  else
    -- use client for formatting
    print("formatting enabled")
    vim.cmd("autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()")
  end
end

-- from lsp.null
function M.use_null_formatting(filetype)
  local null_ls = require("null-ls")
  local null_ls_sources = require("null-ls.sources")

  local sources = null_ls_sources.get({})
  for _, source in ipairs(sources) do
    if
      source.name ~= "trim_whitespace"
      and null_ls_sources.is_available(source, filetype, null_ls.methods.FORMATTING)
    then
      return true
    end
  end
  return false
end
```
Thanks for the quick response. This is what I've got so far. As can be seen below, the logic is working as expected (wanting to disable formatting for null-ls but enable for gopls).

![image](https://user-images.githubusercontent.com/62098008/146056650-6014ff26-45eb-44fe-bfc6-0eddba3573fb.png)

However, as can be seen below, it seems that null-ls' formatting capabilities have not be disabled appropriately (although the image above says that it should have). The expected behaviour is that no prompt appears since gopls is the only lsp server with formatting capabilities. 

![image](https://user-images.githubusercontent.com/62098008/146056850-4a892408-2624-4280-bf61-a2c6c0013479.png)

Also, I realise that I could manually find and disable filetypes for trim_whitespace, but thought it would be nicer to automate this process.

**Comment by axieax** [comment]
Oo thanks for the thorough investigation!! I've managed to override the `client.supports_method` directly below by doing the following. However, do you think it will be better to do a conditional return check for `client.resolved_capabilities.document_formatting == false` at the beginning by default to prevent others from falling down a similar rabbit hole?

```lua
-- prefer null-ls for formatting if available
if not is_null and null_can_format then
  -- disable formatting for ls
  print("formatting disabled for ls")
  client.resolved_capabilities.document_formatting = false
  client.resolved_capabilities.document_range_formatting = false
elseif is_null and not null_can_format then
  -- disable formatting for null-ls
  print("formatting disabled for null")
  client.supports_method = function(--[[ method ]])
    return false
  end
else
  -- use client for formatting
  print("formatting enabled")
  vim.cmd("autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()")
end

```

**Comment by TonioGela** [comment]
I read the conversation and as far as I understood setting `client.resolved_capabilities.document_formatting == false` (plus the range one) will now make null-ls the default method to format code, i.e for hls
```lua
-- Non lsp-installer servers
lspconfig.hls.setup({
    on_attach = function(client)
        -- This will use null-ls formatting capabilities
        client.resolved_capabilities.document_formatting = true
        client.resolved_capabilities.document_range_formatting = true
    end
})
```
but how about disabling null-ls just for that specific one?
