### ISSUE TITLE
condition `root_has_file` multiple inputs

### ISSUE THREAD

**Issue by aspeddro** [jose-elias-alvarez/null-ls.nvim#449]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Maybe `root_has_file` should accept multiple arguments?

```lua
null_ls.setup {
  debug = true,
  sources = {
    formatting.stylua.with {
      condition = function(utils)
        return utils.root_has_file({'stylua.toml', '.stylua.toml'})
        -- or utils.root_has_some_file({ ... })
      end,
    },
  },
}
```

### Help

No

**Comment by jose-elias-alvarez** [comment]
Sure, this is a sensible option to add. PR welcome!

**Comment by aspeddro** [comment]
I will open a PR to implement `root_has_some_file`

**Comment by jose-elias-alvarez** [comment]
Rather than another method, I think it would be intuitive for `root_has_file` to accept either a table (indicating multiple files) or a string (indicating a single file).
