### ISSUE TITLE
Unable to get null-ls format working when using packer lazy load

### ISSUE THREAD

**Issue by shubham-cpp** [jose-elias-alvarez/null-ls.nvim#453]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+727-g326e74571 Build type: Release

### null-ls config

<details>
  <summary>Full null-ls config is here</summary>
  
```lua
local null_ls = require("null-ls")
local b = null_ls.builtins
local sources = {
    -- Html,css,json
    b.formatting.prettierd,
    -- [java|type]script(react)?
    -- b.formatting.fixjson,
    b.diagnostics.eslint_d,
    b.formatting.eslint_d,
    b.code_actions.eslint_d,
    -- C/C++
    b.formatting.clang_format,
    b.diagnostics.cppcheck,
    -- Lua
    b.diagnostics.luacheck.with({
        extra_args = { "--globals", "vim", "describe" },
    }),
    b.formatting.stylua,
    -- Python
    b.formatting.isort,
    b.formatting.yapf,
    b.diagnostics.flake8,
    -- Bash,zsh
    b.formatting.shfmt.with({ extra_args = { "-i", "2", "-ci" } }),
    b.diagnostics.shellcheck,
    -- Vim
    b.diagnostics.vint,
    -- Yaml
    b.diagnostics.yamllint,
    -- Misc
    b.code_actions.gitsigns,
    b.hover.dictionary,
}
null_ls.setup({
    on_attach = require("config.lsp.utils").on_attach,
    sources = sources,
    diagnostics_format = "[#{c}] #{m} (#{s})",
    debug=true
})
```

</details>

## Packer config
<details>
  <summary>Click to expand!</summary>

```lua
use({
	"hrsh7th/nvim-cmp",
	event = "InsertEnter",
	config = get_config("cmp"),
})

use({ "hrsh7th/cmp-nvim-lua", after = "nvim-cmp" })
use({ "hrsh7th/cmp-nvim-lsp", after = "cmp-nvim-lua" })
use({ "hrsh7th/cmp-buffer", after = "cmp-nvim-lua" })
use({ "hrsh7th/vim-vsnip", after = "cmp-buffer" })
use({ "hrsh7th/cmp-vsnip", after = "vim-vsnip" })
use({ "rafamadriz/friendly-snippets", after = "cmp-vsnip" })
use({ "hrsh7th/cmp-path", after = "friendly-snippets" })

use({ "neovim/nvim-lspconfig", config = get_config("lsp"), after = "nvim-lsp-installer" })
use({ "williamboman/nvim-lsp-installer", after = "cmp-nvim-lsp" })
use("b0o/schemastore.nvim")
use({
	"jose-elias-alvarez/null-ls.nvim",
	requires = { "nvim-lua/plenary.nvim"},
    after="nvim-lspconfig",
    config = get_config("lsp.nulls")
})
```

</details>

As you can see null-ls will load after nvim-lspconfig.

### Expected behavior

Null-ls format to work as intended.

### Actual behavior

`:LspInfo` output

```
  
 Language client log: /home/shubham/.cache/nvim/lsp.log
 Detected filetype:   lua
 
 2 client(s) attached to this buffer: 
 
 Client: sumneko_lua (id: 1, pid: 81427, bufnr: [1])
 	filetypes:       lua
 	autostart:       true
 	root directory:  /home/shubham/Documents/dotfiles
 	cmd:             /home/shubham/.local/share/nvim/lsp_servers/sumneko_lua/extension/server/bin/Linux/lua-language-server
 
 Client: null-ls (id: 2, pid: 5001, bufnr: [1, 82])
 	filetypes:       markdown, less, yaml, html, css, scss, javascript, typescript, javascriptreact, typescriptreact, json, vue, graphql, java, c, cs, cpp, lua, python, sh, vim, text
 	autostart:       false
 	root directory:  /home/shubham/Documents/dotfiles
 	cmd:             nvim
 
 Configured servers list: tsserver, tailwindcss, emmet_language_server, bashls, vimls, yamlls, pyright, html, jsonls, cssls, sumneko_lua, gopls, clangd, null-ls

```

the null-ls doesn't autostart but is attached to current file 

### Debug log

```vim
[TRACE Thursday 16 December 2021 12:16:37 PM] ...site/pack/packer/opt/null-ls.nvim/lua/null-ls/client.lua:82: starting null-ls client
[TRACE Thursday 16 December 2021 12:16:37 PM] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:117: received LSP request for method initialize
[DEBUG Thursday 16 December 2021 12:16:37 PM] ...site/pack/packer/opt/null-ls.nvim/lua/null-ls/client.lua:133: unable to notify client for method textDocument/didOpen (client not active): {
  textDocument = {
    uri = "file:///home/shubham/Documents/dotfiles/.config/nvim/lua/config/lsp/nulls.lua"
  }
}
[TRACE Thursday 16 December 2021 12:16:37 PM] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method initialized
[TRACE Thursday 16 December 2021 12:16:37 PM] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didOpen
[TRACE Thursday 16 December 2021 12:16:37 PM] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Thursday 16 December 2021 12:16:37 PM] ...ite/pack/packer/opt/null-ls.nvim/lua/null-ls/helpers.lua:306: spawning command [luacheck] with args { "--formatter", "plain", "--codes", "--ranges", "--filename", "/home/shubham/Documents/dotfiles/.config/nvim/lua/config/lsp/nulls.lua", "--globals", "vim", "describe", "-" }
[TRACE Thursday 16 December 2021 12:16:37 PM] ...ite/pack/packer/opt/null-ls.nvim/lua/null-ls/helpers.lua:188: error output: Usage: luacheck ([--config <config>] | [--no-config])
       ([--default-config <default_config>] | [--no-default-config])
       [-h] [-g] [-u] [-r] [-a] [-s] [--no-self] [--std <std>] [-c]
       [-d] [-t] [-m] [--max-line-length <length>]
       [--no-max-line-length] [--max-code-line-length <length>]
       [--no-max-code-line-length] [--max-string-line-length <length>]
       [--no-max-string-line-length]
       [--max-comment-line-length <length>]
       [--no-max-comment-line-length]
       [--max-cyclomatic-complexity <complexity>]
       [--no-max-cyclomatic-complexity] [--filename <filename>]
       [-j <jobs>] [--formatter <formatter>] [-q] [--codes] [--ranges]
       [--no-color] [-v] <file> [<file>] ...
       ([--cache [<cache>]] | [--no-cache])
       [--ignore <patt> [<patt>] ...] [--enable <patt> [<patt>] ...]
       [--only <patt> [<patt>] ...] [--globals [<name>] ...]
       [--read-globals [<name>] ...] [--new-globals [<name>] ...]
       [--new-read-globals [<name>] ...] [--not-globals [<name>] ...]
       [--exclude-files <glob> [<glob>] ...]
       [--include-files <glob> [<glob>] ...]

Error: missing argument 'files'

[TRACE Thursday 16 December 2021 12:16:37 PM] ...ite/pack/packer/opt/null-ls.nvim/lua/null-ls/helpers.lua:189: output: nil
[TRACE Thursday 16 December 2021 12:16:37 PM] ...pack/packer/opt/null-ls.nvim/lua/null-ls/diagnostics.lua:155: received diagnostics from source 7
[TRACE Thursday 16 December 2021 12:16:37 PM] ...pack/packer/opt/null-ls.nvim/lua/null-ls/diagnostics.lua:156: {}
[TRACE Thursday 16 December 2021 12:18:19 PM] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didOpen
[TRACE Thursday 16 December 2021 12:18:19 PM] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Thursday 16 December 2021 12:18:19 PM] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available
[TRACE Thursday 16 December 2021 12:18:19 PM] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didClose
[TRACE Thursday 16 December 2021 12:18:19 PM] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didOpen
[TRACE Thursday 16 December 2021 12:18:19 PM] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Thursday 16 December 2021 12:18:19 PM] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available
[TRACE Thursday 16 December 2021 12:18:29 PM] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didClose
[TRACE Thursday 16 December 2021 12:18:38 PM] ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:142: received LSP notification for method textDocument/didOpen
[TRACE Thursday 16 December 2021 12:18:38 PM] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Thursday 16 December 2021 12:18:38 PM] .../pack/packer/opt/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available

```

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by shubham-cpp** [comment]
the commit with `1ce59e3596ad6d4a33121aeb2e760c4a9772d63e` seems to work. Later I'll test few more commits where this problem started

**Comment by jose-elias-alvarez** [comment]
First: No need to load after `lspconfig`, since the integration was removed and the two plugins are now independent. I'd try removing that first, since in #488, removing `after = "nvim-lspconfig"` solved a separate issue. 

Second, null-ls `autostart` will always show as `false`, since it uses its own mechanism to attach to buffers, so that's not indicative of a problem, I think. 

Third, it's strange that 1ce59e3596ad6d4a33121aeb2e760c4a9772d63e is causing issues, since if you look at the diff, it didn't make any changes to null-ls runtime code (it's a separate script that generates metadata).

I don't really use lazy loading because it causes unpredictable issues like this, but if you're able to investigate and figure out what's going on, let me know.

**Comment by GreatestOfAllTimee** [comment]
This also happened to me. It seems like some filetypes can't be format (already tested with and without lazyload). This happened after latest null-ls update. Did it work after remove null-ls from lazyload?

**Comment by shubham-cpp** [comment]
> No need to load after lspconfig

Tried that too but didn't work

> but if you're able to investigate and figure out 

Will definitely look into it this weekend

**Comment by shubham-cpp** [comment]
@GreatestOfAllTimee, no actually. I just put the commit has using packer to download specific null-ls and that works as expected. Commit has is 1ce59e3

**Comment by GreatestOfAllTimee** [comment]
> @GreatestOfAllTimee, no actually. I just put the commit has using packer to download specific null-ls and that works as expected. Commit has is [1ce59e3](https://github.com/jose-elias-alvarez/null-ls.nvim/commit/1ce59e3596ad6d4a33121aeb2e760c4a9772d63e) (I'm still lazy loading the plugin using specified commit hash)

How you do you download with a specific commit ?

**Comment by jose-elias-alvarez** [comment]
Again, it's *really* strange that that commit would cause any issues. If you have a chance, a full minimal reproduction with an isolated config like [this one](https://gist.github.com/jose-elias-alvarez/b7c6d2d07f585fcf98b5dbb061c26a48) would help us get to the bottom of this.

**Comment by jose-elias-alvarez** [comment]
@GreatestOfAllTimee You can see the instructions [here](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/344#issue-1053024141) to pin to a commit, though if you're able to bisect and find the commit that broke this, it would be a big help.

**Comment by GreatestOfAllTimee** [comment]
Sadly after reinstall with commit [1ce59e](https://github.com/jose-elias-alvarez/null-ls.nvim/commit/1ce59e3596ad6d4a33121aeb2e760c4a9772d63e) still can't get it done. I don't why this happen, I will get around to find out why.

**Comment by GreatestOfAllTimee** [comment]
> > @GreatestOfAllTimee, no actually. I just put the commit has using packer to download specific null-ls and that works as expected. Commit has is [1ce59e3](https://github.com/jose-elias-alvarez/null-ls.nvim/commit/1ce59e3596ad6d4a33121aeb2e760c4a9772d63e) (I'm still lazy loading the plugin using specified commit hash)
> 
> How you do you download with a specific commit ?


**Video reference which work only with certain filetype** : 

https://user-images.githubusercontent.com/73665622/146435701-4ead37a0-0585-47a1-ba11-9f9553513ccd.mp4

**Comment by jose-elias-alvarez** [comment]
Thanks for the video, but since I'm not experiencing this myself, I need a full minimal reproduction + logs to figure it out.

**Comment by astridlyre** [comment]
This is also affecting me. I reverted to commit `1ce59e3596ad6d4a33121aeb2e760c4a9772d63e` and the problem went away.

**Comment by jose-elias-alvarez** [comment]
Please try downloading [this minimal config](https://gist.github.com/jose-elias-alvarez/8c13e18a0f52a6abd8cc4fc955d06248) and running it with `nvim --clean -u minimal_init.lua`. This works fine for me on the latest version of null-ls, both on the latest Neovim master and on 0.6.0 stable.

If this works for you, then there's another issue somewhere in your configs. I'm not terribly interested in investigating lazy-loading issues because they're complicated and I don't do it myself. If the minimal config doesn't work, please bisect and provide logs, or else there's nothing I can do here.

**Comment by shubham-cpp** [comment]
ok will test this and let you know

**Comment by shubham-cpp** [comment]
Your minimal config work even after applying the lazying load(I just put `event="InsertEnter"` inside `null-ls.nvim` block) but doesn't work if I do the same with my config. Maybe its an issue from my end. 
Should I temporarily close this issue and reopen later after checking my configs properly?

**Comment by jose-elias-alvarez** [comment]
Thanks for testing it, let's keep the issue open since it seems like a few other people are having similar issues.

**Comment by astridlyre** [comment]
Okay, so I did a refactor of my config and tried the latest commit, it's working now for me.

**Comment by shubham-cpp** [comment]
@jose-elias-alvarez fixed the issue. My custom `on_attach()` function was causing the issue. The issue my from my end, apologies for my naiveness

**Comment by GreatestOfAllTimee** [comment]
> @jose-elias-alvarez fixed the issue. My custom `on_attach()` function was causing the issue. The issue my from my end, apologies for my naiveness

Can you share your config file ? I still have this issue. Poor me

**Comment by shubham-cpp** [comment]
> Can you share your config file 

Haven't pushed the changes to github yet will do in sometime

**Comment by shubham-cpp** [comment]
@GreatestOfAllTimee  

1. Look at [plugins.lua](https://github.com/shubham-cpp/dotfiles/blob/387d52d81aa088efb4a1e77a2201e79970c6f1c4/.config/nvim/lua/plugins.lua#L40)
2. Then [null-ls.lua](https://github.com/shubham-cpp/dotfiles/blob/387d52d81aa088efb4a1e77a2201e79970c6f1c4/.config/nvim/lua/config/lsp/nulls.lua#L35)

**Comment by GreatestOfAllTimee** [comment]
> @GreatestOfAllTimee
> 
>     1. Look at [plugins.lua](https://github.com/shubham-cpp/dotfiles/blob/387d52d81aa088efb4a1e77a2201e79970c6f1c4/.config/nvim/lua/plugins.lua#L40)
> 
>     2. Then [null-ls.lua](https://github.com/shubham-cpp/dotfiles/blob/387d52d81aa088efb4a1e77a2201e79970c6f1c4/.config/nvim/lua/config/lsp/nulls.lua#L35)

FIXED! I just realized without `on_attach` also can BUT cannot be used using lazyload. Thank you so much for your guide, and I thanks to [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) for the awesome plugin.
