### ISSUE TITLE
Error when running `:LspRestart` on buffers using null-ls

### ISSUE THREAD

**Issue by rouge8** [jose-elias-alvarez/null-ls.nvim#459]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.6.0

### null-ls config

```lua
null_ls = require('null-ls')
null_ls.setup({
  diagnostics_format = "[#{c}] #{m} (#{s})",
  sources = {
    null_ls.builtins.diagnostics.flake8,
    null_ls.builtins.diagnostics.yamllint,
  },
})
```

Version: d5ad64919848c19e8d105e3620c7241747ee23cc

### Steps to reproduce

1. Edit a Python or YAML file.
2. Run `:LspRestart`.

### Expected behavior

Attached LSPs (e.g. pyright) restart and null-ls continues working.

### Actual behavior

An error is displayed and formatting and diagnostics from null-ls stop working:

```
Error executing vim.schedule lua callback: /Users/andy/.vim/plugged/nvim-lspconfig/lua/lspconfig.lua:58: attempt to call field 'launch' (a nil value)
stack traceback:
	/Users/andy/.vim/plugged/nvim-lspconfig/lua/lspconfig.lua:58: in function 'fn'
	vim.lua:415: in function 'cb'
	vim.lua:285: in function <vim.lua:285>
```

This is weird because the error suggests it's from [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig), but it only happens when I'm using null-ls.

### Debug log

```
[WARN  Thu Dec  2 23:26:50 2021] ...ndy/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:45: failed to run generator: ...s/andy/.vim/plugged/null-ls.nvim/lua/null-ls/helpers.lua:167: command flake8 is not executable (make sure it's installed and on your $PATH)
[TRACE Thu Dec 16 17:00:41 2021] ...rs/andy/.vim/plugged/null-ls.nvim/lua/null-ls/client.lua:84: starting null-ls client
[TRACE Thu Dec 16 17:00:41 2021] /Users/andy/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:118: received LSP request for method initialize
[DEBUG Thu Dec 16 17:00:42 2021] ...rs/andy/.vim/plugged/null-ls.nvim/lua/null-ls/client.lua:135: unable to notify client for method textDocument/didOpen (client not active): {
  textDocument = {
    uri = "file:///Users/andy/.dotfiles.public/t.yaml"
  }
}
[TRACE Thu Dec 16 17:00:42 2021] /Users/andy/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method initialized
[TRACE Thu Dec 16 17:00:42 2021] /Users/andy/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method textDocument/didOpen
[TRACE Thu Dec 16 17:00:42 2021] ...ndy/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:9: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Thu Dec 16 17:00:42 2021] ...s/andy/.vim/plugged/null-ls.nvim/lua/null-ls/helpers.lua:306: spawning command [yamllint] with args { "--format", "parsable", "-" }
[TRACE Thu Dec 16 17:00:42 2021] ...s/andy/.vim/plugged/null-ls.nvim/lua/null-ls/helpers.lua:188: error output: nil
[TRACE Thu Dec 16 17:00:42 2021] ...s/andy/.vim/plugged/null-ls.nvim/lua/null-ls/helpers.lua:189: output: nil
[TRACE Thu Dec 16 17:00:42 2021] ...dy/.vim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:155: received diagnostics from source 3
[TRACE Thu Dec 16 17:00:42 2021] ...dy/.vim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:156: {}
[TRACE Thu Dec 16 17:00:43 2021] /Users/andy/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:118: received LSP request for method shutdown
[TRACE Thu Dec 16 17:00:43 2021] /Users/andy/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method exit
```

### Help

No

**Comment by jose-elias-alvarez** [comment]
Yep, I'm able to reproduce this. You can see [here](https://github.com/neovim/nvim-lspconfig/blob/64bd3b95345f2dbedc83a3d9a472662c48b3e940/lua/lspconfig.lua#L58) that it attempts to call `configs["null-ls"].launch()`, which throws the error you're seeing. The issue is that calling `:LspRestart` without any arguments enters [this path](https://github.com/neovim/nvim-lspconfig/blob/64bd3b95345f2dbedc83a3d9a472662c48b3e940/lua/lspconfig/util.lua#L391), which returns all active clients. 

That means that `:LspRestart` should throw the same error when the user is using a client that isn't supported by lspconfig, but I'd be surprised if that situation hasn't come up before. I'll see if I can put together a minimal reproduction / PR upstream.

**Comment by shubham-cpp** [comment]
@jose-elias-alvarez just a suggestion, since null-ls no longer depends on lspconfig wouldn't it be better if null-ls had its own function/command to restart?

**Comment by jose-elias-alvarez** [comment]
@shubham-cpp Since it runs in memory, null-ls doesn't really have the same concept of restarting. You can already force diagnostics to refresh with `:w | e` (like a real server). Is there another use case for restarting that you have in mind?

**Comment by shubham-cpp** [comment]
Sometimes eslint_d fails to update properly so I just restart the server, but the `:w|e` is something I didn't know about

**Comment by bellini666** [comment]
Hey guys,

I'm seeing this error too. The main issue with this is that sometimes I have to restart `pyright` when working on a python project (it sometimes fails t understand new files), and because of this error null-ls stops working.

So, either way I have to fully restart neovim, either to fix pyright or after to fix null-ls that stopped working after `:LspRestart`

Are there any workarounds for this?

**Comment by jose-elias-alvarez** [comment]
I opened an issue upstream at neovim/nvim-lspconfig#1582. The ideal solution is that `:LspRestart` will completely ignore clients not managed by nvim-lspconfig (so `:LspRestart` wouldn't affect null-ls at all), but it'll take a little time to put together and merge a fix.

In the meantime, 80e1c2942f70bfdf16886a64692f274ef7356010 should help. I don't often use `:LspRestart`, but could you give that a shot?

**Comment by rouge8** [comment]
https://github.com/jose-elias-alvarez/null-ls.nvim/commit/80e1c2942f70bfdf16886a64692f274ef7356010 works for me!

**Comment by bellini666** [comment]
https://github.com/jose-elias-alvarez/null-ls.nvim/commit/80e1c2942f70bfdf16886a64692f274ef7356010 works for me too! Hopefully it is fixed soon upstream :)

But thanks for working it around!

**Comment by kylo252** [comment]
@jose-elias-alvarez, that pseudo launch to forcing the client to attach to way too many buffers. Check `:LspInfo` before and after. It's not checking the filetype correctly 😢

**Comment by jose-elias-alvarez** [comment]
@kylo252 I don't immediately see any bad behavior, but I changed it a bit so that it only tries to add listed buffers in case that was an issue. Either way, this is fundamentally an issue with an external command.

**Comment by jose-elias-alvarez** [comment]
The upstream issue is now closed and I've removed the workaround here.

**Comment by milanglacier** [comment]
> The upstream issue is now closed and I've removed the workaround here. `:LspRestart` will now ignore null-ls completely. As I mentioned, restarting the null-ls client is mostly meaningless. If the goal is to force a refresh of diagnostics, `:w | e` will do the trick.

I found that `:w | e` to refresh directory won't work if I changes the working directory.
Say, I'm working on project A and jump to files in project B, but the root directory of null-ls doesn't change to project B,
and the diagnostics due to wrong root path won't refresh since I can't change the root path of null-ls.
