### ISSUE TITLE
When opening a second buffer: Error executing vim.schedule lua callback: [...]/null-ls/init.lua:31: attempt to call field 'setup' (a nil value)

### ISSUE THREAD

**Issue by fnune** [jose-elias-alvarez/null-ls.nvim#46]
![null-ls-bug-second-buffer](https://user-images.githubusercontent.com/16181067/126749172-0216b85c-81f2-46a6-bc24-c93d97c26004.gif)

See the GIF above:

- When opening a first buffer, `null-ls` doesn't throw any errors and my LSP features work great.
- When opening a second buffer (regardless of through a split window, or just a second buffer), `null-ls` throws this error:

```
Error executing vim.schedule lua callback: [...]/null-ls/init.lua:31: attempt to call field 'setup' (a nil value)
```

---

My config:

```lua
local lsp_status = require('lsp-status')
lsp_status.register_progress()
local nvim_lsp = require('lspconfig')
local on_attach = function(client, bufnr)
  require("null-ls").setup {}
  require("nvim-lsp-ts-utils").setup { eslint_enable_diagnostics = true, eslint_bin = "eslint_d" }
  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

  lsp_status.on_attach(client, bufnr)

  -- Mappings.
  local opts = { noremap=true, silent=true }

  buf_set_keymap('n', '<leader>o', ':TSLspOrganize<CR>', opts)
  -- More keybindings (redacted)
  buf_set_keymap('n', '<leader>j', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
end

nvim_lsp.tsserver.setup { on_attach = on_attach, capabilities = lsp_status.capabilities }
```

Thanks for your plugins @jose-elias-alvarez!

**Comment by jose-elias-alvarez** [comment]
Looks like this is the same issue as #38. If I'm right, I think all you need to do is move `require("null-ls").setup {}` outside of `on_attach` and it should work. I'll see if I can figure out a way for the plugin not to break in this situation (or update the nvim-lsp-ts-utils readme with a warning if not).

**Comment by fnune** [comment]
That works!!! Thank you very much!
