### ISSUE TITLE
Add remark-cli to builtins

### ISSUE THREAD

**Issue by sarmong** [jose-elias-alvarez/null-ls.nvim#498]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Remark is an alternative to markdownlint for to  linting markdown files

https://github.com/remarkjs/remark/tree/main/packages/remark-cli

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by jose-elias-alvarez** [comment]
If you'd like to take a crack at this, you can take a look at the [markdownlint implementation](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/6fb80ae9a4b34c41316485351d5b31450959dcff/lua/null-ls/builtins/diagnostics/markdownlint.lua#L18) here. The basic idea is to spawn the linter with the correct arguments, then process the output using Lua pattern matching.

**Comment by Murderlon** [comment]
Hi, just so you are aware, remark was recently added to lspconfig: https://github.com/neovim/nvim-lspconfig/pull/1606. There is now a [unified-language-server](https://github.com/unifiedjs/unified-language-server) which is used in the official [remark-language-server](https://github.com/remarkjs/remark-language-server). 

AFAIK this project is for making non-LSP tools LSP compatible, so maybe this is no longer required?

**Comment by jose-elias-alvarez** [comment]
> Hi, just so you are aware, remark was recently added to lspconfig: [neovim/nvim-lspconfig#1606](https://github.com/neovim/nvim-lspconfig/pull/1606). There is now a [unified-language-server](https://github.com/unifiedjs/unified-language-server) which is used in the official [remark-language-server](https://github.com/remarkjs/remark-language-server).
> 
> AFAIK this project is for making non-LSP tools LSP compatible, so maybe this is no longer required?

There may be cases where a more modern solution is available but users don't have access to it due to restrictions on their environment, though I agree that an actual language server is always a better option.

**Comment by sarmong** [comment]
Nice, I will take a look!

@jose-elias-alvarez , what restrictions are you referring to?

**Comment by jose-elias-alvarez** [comment]
> Nice, I will take a look!
> 
> @jose-elias-alvarez , what restrictions are you referring to?

The example I have in mind is if your work IT department approves of a known tool (e.g. ESLint) but has not yet (or will not) approve an unknown tool (e.g. the ESLint language server). In those cases, having an option that uses the CLI might be useful. If you don't think that's relevant here, feel free to close this.

**Comment by sarmong** [comment]
I think if somebody needs this, the issue can be reopened.
