### ISSUE TITLE
Expose active / inactive status

### ISSUE THREAD

**Issue by jose-elias-alvarez** [jose-elias-alvarez/null-ls.nvim#501]
### Discussed in https://github.com/jose-elias-alvarez/null-ls.nvim/discussions/489

<div type='discussions-op-text'>

<sup>Originally posted by **vuki656** December 25, 2021</sup>
Hey,

is there any way to know if the plugin has invoked a formatter/linter and is doing something?

I'd really like to put a "loading" indicator to know if it's currently chewing something in my status bar since I'm mostly using `eslint_d` and sometimes it can take a second or two.

Similar to what I have in my [plugin](https://github.com/vuki656/package-info.nvim#loading-hook)

I don't need any UI, just a `true`/`false` or any way to figure out that `true`/`false`.</div>

This should be pretty simple to implement – we can set a flag on the global state when generators run and remove it when they're done / error out, then expose that.

**Comment by syphar** [comment]
I'm not sure if I fully understand the issue, but wouldn't supporting LSP [`$/progress`](https://microsoft.github.io/language-server-protocol/specification#progress) the correct thing to do here? 

Then plug-ins like https://github.com/arkav/lualine-lsp-progress/ would directly pick it up. 

I see `sumneko_lua` is using it for the initial workspace load, and `rust_analyzer` using is for the workspace load, but also for further linting calls after save.

**Comment by jose-elias-alvarez** [comment]
Yes, supporting progress would definitely be a more LSP-like solution. I'll look into what it would take to add support, though I'll mention that this isn't a feature I'll use myself.

**Comment by vuki656** [comment]
> I'm not sure if I fully understand the issue, but wouldn't supporting LSP [`$/progress`](https://microsoft.github.io/language-server-protocol/specification#progress) the correct thing to do here?
> 
> Then plugins like https://github.com/arkav/lualine-lsp-progress/ would directly pick it up.
> 
> I see `sumneko_lua` is using it for the initial workspace load, and `rust_analyzer` using is for the workspace load, but also for further linting calls after save.

That would cover the language server loading status. This would relate to the linter/formatter loading status aka the thing that `null-ls` handles. So if I run eslint --fix on a file, tsserver doesn't know anything about it. 

Also, not all language servers implemented the loading spec so that's a bummer.

**Comment by jose-elias-alvarez** [comment]
@vuki656 I have to review the spec but at a glance it seems that we could send arbitrary progress notifications to Neovim itself, which you'd then be able to get using a custom handler like lualine-lsp-progress or `vim.lsp.util.get_progress_messages` (there's an `LspProgressUpdate` event that would work well for a statusline).

**Comment by syphar** [comment]
rust-analyzer is using lsp progress for both workspace loading (like sumneko-lua, too) and linter status (clippy for example)

Progress then includes the source server and can also show abitary messages. 

I can imagine we could show the tool being run, if they have a readable name

**Comment by jose-elias-alvarez** [comment]
Small update: I prototyped `$progress` support today and it was pretty straightforward to implement. I'm waiting on #519, which changes how formatters run in a way that affects progress reporting. We should be able to report a (very rough) percentage as well as the source's name, which I imagine will be enough to close this issue.
