### ISSUE TITLE
Disable null-ls for specific buffers

### ISSUE THREAD

**Issue by jose-elias-alvarez** [jose-elias-alvarez/null-ls.nvim#502]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

null-ls should make it easy to disable functionality for a specific buffer.

### Help

Yes

### Implementation help

The simplest solution I can think of is to use a buffer-local variable, something like`b:null_ls_disabled`, and check for it in [`client.supports_method`](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/client.lua#L29) and [the diagnostics handler](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/diagnostics.lua#L119) to determine whether null-ls should do anything with that buffer. 

This is pretty simple – I'm opening the issue mostly as a reminder to myself, but if anyone happens to see this and wants to take care of it, feel free.

**Comment by ELLIOTTCABLE** [comment]
FWIW, I'd really like to disable *specific sources* for a given buffer. I'm not sure if that merits a separate Issue — in particular, for me, `eslint_d` / `eslint` are often unhelpful in certain circumstances.

**Comment by jose-elias-alvarez** [comment]
In the future, I'd like to restructure null-ls so that sources "attach" to a given buffer instead of being active all the time, which should make that a lot easier, but it's a pretty big change and it'll take some time for me to get around to it. In the meantime, you can toggle the availability of any source on demand using a command / function:

```lua
vim.cmd("command! ToggleEslint lua require('null-ls.sources').toggle('eslint')")
```

**Comment by jose-elias-alvarez** [comment]
I thought about this more and am not sure I see the use case for doing this vs. disabling sources, which will correctly handle things like clearing diagnostics.

**Comment by MattSPalmer** [comment]
Don't know if you'd consider re-opening this, but I have a use case that isn't really covered by disabling sources.

The [`octo.nvim`](https://github.com/pwntester/octo.nvim) plugin loads a diff view that preserves the original filetype, but the root finding always fails on the left hand buffer since it's not in the actual project - the buffer name is `octo://some/plugin/specific/stuff`.

If I could specify a custom `should_attach`, I could filter out `octo://` buffers with a small change. Currently (to the best of my knowledge), I have to go and define or modify a condition on every source to get the same effect.

**Comment by jose-elias-alvarez** [comment]
@MattSPalmer Sure, this is simpler than the feature I described originally since it would only cover attachment. We can either do a `should_attach()` callback or a buffer-local variable like `b:null_ls_skip_attach`, which you could then set up with an autocommand:

```vim
" I think this pattern works?
autocmd BufEnter octo://* let b:null_ls_skip_attach=1
```

I personally prefer the callback style, but it's a little more verbose. What do you think?

**Comment by MattSPalmer** [comment]
I prefer the callback style too. It may be more verbose but I like that it happens in Lua and that it hooks directly into the existing client lifecycle.

And this way we could check anything about the buffer if string matching the name wasn't enough.

**Comment by MattSPalmer** [comment]
I'd be happy to work up a PR for this if you haven't already started!

**Comment by jose-elias-alvarez** [comment]
Sure, feel free! I think a simple callback that takes the buffer number as an argument makes sense.
