### ISSUE TITLE
Run built-in sources only in the presence of specific file(s)

### ISSUE THREAD

**Issue by sQVe** [jose-elias-alvarez/null-ls.nvim#509]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

The `make_conditional_utils` are using `vim.loop.cmd()` https://github.com/jose-elias-alvarez/null-ls.nvim/blob/e13a1cadf720ecb8a27a022beaf4608778ca8fdc/lua/null-ls/utils.lua#L142

This is really confusing since `null-ls` allows one to configure the `root_dir` and it breaks `root_has_file` on complex setups like monorepos etc. As a user I'm heavily assuming that it's using the output of `root_dir`.

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I tried doing this like it's implemented on:
https://github.com/jose-elias-alvarez/null-ls.nvim/blob/1e131a0b3f52eb812c7c07f5e24aee90c0ee8967/lua/null-ls/client.lua#L66

But I got I got stumped since I don't have access to `fname` in the utility functions. Unsure how one best would implement this.

**Comment by jose-elias-alvarez** [comment]
The resolved `root_dir` is available on the client, and we could theoretically try to get `root_dir` from the client and fall back to `vim.loop.cwd()`, as in [these lines](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/helpers.lua#L260-L261). The issue is that in a typical config (registering a source on null-ls setup), the client won't yet be initialized at the point the sources are registered, so this won't work.

The conditional utils predate root directory configuration and don't quite match the current architecture. Ideally, the condition would be checked when the source first runs, which would give it access to the name of an attached buffer, but that would require significant restructuring. 

I'll try to see if I can think of a solution that doesn't add too much complexity, but ultimately built-ins and their associated options are meant to handle simple cases. Any more complex cases can be handled by manual registration using autocommand events.

**Comment by jose-elias-alvarez** [comment]
It's still a WIP but could you try #413? I tried to restructure things so that `condition` is checked on the source's first run, meaning that it will inherit `root_dir` from the client.

**Comment by sQVe** [comment]
@jose-elias-alvarez For sure. I'll test it out as soon as possible, probably in a couple of hours.

**Comment by jose-elias-alvarez** [comment]
Thanks! Let me know if the specific option works and if anything else is broken for you (I think it should be ready to merge).

**Comment by sQVe** [comment]
@jose-elias-alvarez Having the possibility to set `cwd` for specific built-ins are awesome since it will solve some complex conditionals (it would cover most ESLint cases for instance).

**Comment by sQVe** [comment]
I tried it out now and it correctly applies the conditional check but only for the first resolved `root_dir`. If I have a monorepo with:
```text
monorepo (git repo)
  packages
    package-using-eslint
      package.json (used to resolve root_dir)
    package-not-using-eslint
      package.json (used to resolve root_dir)
```

If I open `package-not-using-eslint` it now doesn't try to use `eslint` due to set `root_dir` and set `conditional`, but when opening a file on `package-using-eslint` it seems to not use the new `root_dir` but rather the one from `package-not-using-eslint` since it doesn't lint the file at all. It's consistent in the sense that it works the other way around - after opening `package-using-eslint` and then `package-not-using-eslint` it will try to lint both files.

This is the conditional function I have set for `eslint`:
```lua
condition = function(utils)
  return utils.root_has_file({
    '.eslintrc.cjs',
    '.eslintrc.js',
    '.eslintrc.json',
    '.eslintrc.yaml',
    '.eslintrc.yml',
  })
end,
```

**Comment by jose-elias-alvarez** [comment]
Right, `condition` is only meant to control whether a source is registered, meaning that after one check, it'll keep the same results. That's consistent with the old behavior, too. 

Yours is a more complicated case and I'm not sure we can handle it generically using `condition`, but you can try `runtime_condition` (I haven't tested this thoroughly but it should give you a good starting point):

```lua
local bufnr_cache = {}

local runtime_condition = function(params)
    -- you probably want to cache results to avoid checking again on every change
    if bufnr_cache[params.bufnr] ~= nil then
        return bufnr_cache[params.bufnr]
    end

    local has_eslint_config = require("lspconfig").util.root_pattern({
        ".eslintrc.cjs",
        ".eslintrc.js",
        ".eslintrc.json",
        ".eslintrc.yaml",
        ".eslintrc.yml",
    })(params.bufname) ~= nil

    bufnr_cache[params.bufnr] = has_eslint_config
    return has_eslint_config
end
```

**Comment by sQVe** [comment]
Is `runtime_condition` an option for the built-ins or should I use `condition` for it?

**Comment by jose-elias-alvarez** [comment]
You can set it in exactly the same way as `condition`, e.g.:

```lua
local sources = {
    null_ls.builtins.eslint_d.with({ runtime_condition = ... }),
}

**Comment by sQVe** [comment]
@jose-elias-alvarez That seems to work perfectly for my complicated case. 🎉

**Comment by jose-elias-alvarez** [comment]
Awesome, thanks for confirming. We can probably hijack the [`prefer_local / only_local` functionality](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/helpers/make_builtin.lua#L86) to do something similar:

```lua
local sources = {
    null_ls.builtins.eslint_d.with({
        -- need a better name :(
        run_if_root_has_file = {
            ".eslintrc.cjs",
            ".eslintrc.js",
            ".eslintrc.json",
            ".eslintrc.yaml",
            ".eslintrc.yml",
        },
    }),
}
```

**Comment by sQVe** [comment]
@jose-elias-alvarez This is what I ended up doing:

```lua
local starts_with = function(str, start)
  return string.sub(str, 1, #start) == start
end

local create_runtime_condition = function(config_name_list)
  local bufnr_cache = {}
  local config_path_cache = {}

  return function(params)
    if bufnr_cache[params.bufnr] ~= nil then
      return bufnr_cache[params.bufnr]
    else
      for _, cached_config_path in ipairs(config_path_cache) do
        if starts_with(params.bufname, cached_config_path) then
          bufnr_cache[params.bufnr] = true
          return true
        end
      end
    end

    local config_path = require('lspconfig').util.root_pattern(
      config_name_list
    )(params.bufname)

    local has_config = config_path ~= nil
    if has_config then
      table.insert(config_path_cache, config_path)
    end
    bufnr_cache[params.bufnr] = has_config

    return has_config
  end
end

local eslint_runtime_condition = create_runtime_condition({
  '.eslintrc.cjs',
  '.eslintrc.js',
  '.eslintrc.json',
  '.eslintrc.yaml',
  '.eslintrc.yml',
})
```

Keeping two caches, one for `bufnr` and one for `config_path` to keep the folder traversing to an absolute minimum. Works quite nicely so far - as far as I can tell. 👍🏼

**Comment by jose-elias-alvarez** [comment]
Very nice approach! I hope we can include something similar in null-ls core.

**Comment by jose-elias-alvarez** [comment]
It isn't quite as streamlined as some of the solutions here, but I added a generic caching mechanism in 490a09c0ccfc8da22f6840d6a03398ef5d1b3035 to make it easier for users to implement logic like this without killing performance. I also mentioned in #833 how we can use this as a default for built-in sources to help provide a better out-of-the-box experience.

**Comment by NullVoxPopuli** [comment]
I'm looking to implement a "runtime_condition" for prettierd, @jose-elias-alvarez -- how would your utils help with that? anyone have examples?

**Comment by sQVe** [comment]
@NullVoxPopuli What kind of `runtime_condition` do you want for `prettierd`?

I use this https://github.com/sQVe/dotfiles/blob/master/config/nvim/lua/sQVe/utils/lsp.lua#L18-L47 helper to create my runtime conditions. 

If you want to only run `prettierd` when there's a local `prettier` I would recommend this instead: https://github.com/sQVe/dotfiles/blob/master/config/zsh/zshenv#L42-L43
