### ISSUE TITLE
Support eslint as a formatter

### ISSUE THREAD

**Issue by ChristianChiarulli** [jose-elias-alvarez/null-ls.nvim#51]
seems like eslint_d is supported why not eslint?

**Comment by jose-elias-alvarez** [comment]
Vanilla ESLint can only format either by directly writing the file (which isn't desirable when editing it) or by outputting to JSON with the [`--fix-dry-run` flag](https://eslint.org/docs/user-guide/command-line-interface#--fix-dry-run). `eslint_d` can format directly to `stdout`, but `eslint` requires an additional step to parse JSON output and return the formatted content. It wouldn't be too hard to implement, though, so a PR would be welcome.

**Comment by jose-elias-alvarez** [comment]
Closed in 9cc156e82b7ad3e2a783668fd634df31391396a6 (though as I mention in the documentation, I really don't recommend using it if `eslint_d` is an option).
