### ISSUE TITLE
config is deprecated; use setup instead, Formatting key command not working 

### ISSUE THREAD

**Issue by melsiir** [jose-elias-alvarez/null-ls.nvim#525]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

6.0.0

### null-ls config

local ok, null_ls = pcall(require, "null-ls")

if not ok then
   return
end

local b = null_ls.builtins

local sources = {
	
      b.formatting.prettierd,
      b.formatting.eslint_d,
}

local M = {}

M.setup = function(on_attach)
   null_ls.config {
      sources = sources,
   }
   require("lspconfig")["null-ls"].setup { on_attach = on_attach }
end

return M

### Steps to reproduce

Just open any file

### Expected behavior

Formatting when using key shortcut

### Actual behavior

Nothing happened

### Debug log

null-ls.log                                   73 [WARN  Sat Jan  1 00:54:09 2022] ...m/site/pa     ck/packer/opt/null-ls.nvim/lua/null-ls/init.l     ua:39: lspconfig integration is deprecated; p     ass options to setup instead                   74 [WARN  Sat Jan  1 00:55:06 2022] ...m/site/pa     ck/packer/opt/null-ls.nvim/lua/null-ls/init.l     ua:61: config is deprecated; use setup instea     d                                              75 [WARN  Sat Jan  1 00:55:06 2022] ...m/site/pa     ck/packer/opt/null-ls.nvim/lua/null-ls/init.l     ua:39: lspconfig integration is deprecated; p     ass options to setup instead

### Help

No

### Implementation help

I recently switch to null-ls for formatting my js and css files 
I set it up to for formatte with key binding <leader> ft
But it didn't work I got some error message on start up 
When I open js file I got this error on startup:

Error executing vim.schedule lua callback: ...file
s/home/.config/nvim/lua/custom/plugins/lspconfig.l
ua:23: Expected lua table
stack traceback:
        [C]: in function 'nvim_buf_set_keymap'
        ...files/home/.config/nvim/lua/custom/plugins/lspconfig.lua:23: in function '_on_attach'
        ...pack/packer/opt/nvim-lspconfig/lua/lspconfig/configs.lua:276: in function '_setup_buffer'
                                                          ...pack/packer/opt/nvim-lspconfig/lua/lspconfig/configs.lua:187: in function 'cb'
        vim.lua:285: in function <vim.lua:285>    Press ENTER or type command to continue

And this:

config is deprecated; use setup instead

But when I open other files I just got this error :
config is deprecated; use setup instead

The formatting is working via
 lua vim.lsp.buf.formatting()

But not working via <leader>ft

My lspconfig :

local M = {}

M.setup_lsp = function(attach, capabilities)
   local lspconfig = require "lspconfig"

   local servers = { "html", "cssls", "pyright"}

   for _, lsp in ipairs(servers) do
      lspconfig[lsp].setup {
         on_attach = attach,
         capabilities = capabilities,
         flags = {
            debounce_text_changes = 150,
         },
      }
   end
   

 lspconfig.tsserver.setup {
      on_attach = function(client, bufnr)
         client.resolved_capabilities.document_formatting = false,
         vim.api.nvim_buf_set_keymap(bufnr, "n", "<space>ft", "<cmd>lua vim.lsp.buf.formatting()<CR>", opt)
      end,
   }

 lspconfig.tailwindcss.setup{}

--custom float diagnostics 

vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, {
      virtual_text = false,
      underline = true,
      signs = true,
 })

vim.cmd "autocmd CursorHold * lua vim.lsp.diagnostic.show_line_diagnostics()"
vim.cmd "autocmd CursorHoldI * silent! lua vim.lsp.buf.signature_help()"

end

return M

**Comment by kencx** [comment]
Try replacing this in your null-ls config

```
null_ls.config {
    sources = sources,
}
```
with this
```
null_ls.setup {
    sources = sources,
}
```
It should fix the warning: `config is deprecated; use setup instead`.

For your lspconfig, did you define `opt` anywhere before calling `nvim_buf_set_keymap()`? You can check [lspconfig](https://github.com/neovim/nvim-lspconfig#keybindings-and-completion) for how to define custom mappings.

**Comment by melsiir** [comment]
> Try replacing this in your null-ls config
> 
> ```
> null_ls.config {
>     sources = sources,
> }
> ```
> 
> with this
> 
> ```
> null_ls.setup {
>     sources = sources,
> }
> ```
> 
> It should fix the warning: `config is deprecated; use setup instead`.
> 
> For your lspconfig, did you define `opt` anywhere before calling `nvim_buf_set_keymap()`? You can check [lspconfig](https://github.com/neovim/nvim-lspconfig#keybindings-and-completion) for how to define custom mappings.

Thanks bro I replace the null-ls.config with null-ls.setup
And rempoved this line 

require("lspconfig")["null-ls"].setup { on_attach = on_attach }

Now no error
