### ISSUE TITLE
done() callback error

### ISSUE THREAD

**Issue by ranebrown** [jose-elias-alvarez/null-ls.nvim#54]
I'm seeing this error when opening a file with no diagnostic results (after vint merge #44)`Error executing vim.schedule lua callback: .../start/null-ls.nvim/lua/null-ls/builtins/diagnostics.lua:446: attempt to call local 'done' (a nil value)` [line 446](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/52286ee4d11016b3366481935c12211c44d43777/lua/null-ls/builtins/diagnostics.lua#L446)

Any idea what could be causing this? I copied this from one of the other builtins for the PR.

**Comment by jose-elias-alvarez** [comment]
Yep, I see the problem. Setting `format = "json"` means that the built-in should directly return a table of diagnostics, so it doesn't have access to `done()` (something I forgot myself). You're right that several other contributed built-ins have the same issue, but I guess they never entered the condition, so it never triggered. I'll fix it up, test it out, and push a fix.

**Comment by ShaunMWallace** [comment]
Im getting the same error except on line 325 of diagnostics.

**Comment by jose-elias-alvarez** [comment]
@ranebrown Should be fixed on the latest version, can you let me know?

@ShaunMWallace Not sure that this is the same issue, since the line I think you're referring to wasn't affected, but could you also try the latest version and open another issue if that doesn't fix it?

**Comment by ranebrown** [comment]
That seems to have fixed it. Thanks!
