### ISSUE TITLE
Use locally installed version of commands

### ISSUE THREAD

**Issue by sarmong** [jose-elias-alvarez/null-ls.nvim#557]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

This is the issue I have with `prettier`, but it probably applies to other builtins as well.

Prettier changes its formatting from version to version. For example, [here](https://prettier.io/blog/2021/05/09/2.3.0.html), you can see how many differences there are between 2.2 and 2.3.

**Problem**

If I have version 2.2 installed in my project, this version will be used to validate files on precommit hook and on CI pipeline.
But, neovim will format the file according to the globally available `prettier` version.

**Possible solution**

Run `npx prettier` to use prettier version from `myapp/node_modules/.bin`

The same approach could be used for `eslint` and all other JS tools.

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I can try to implement it, but I am not sure if there are no pitfalls.

**Comment by syphar** [comment]
To me it looks like you're searching for `prefer_local` or `only_local`, like [described in the BUILTINS docs](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#using-local-executables). 

Or am I missing something?

**Comment by jose-elias-alvarez** [comment]
As @syphar noted, we have a couple of options to handle this, and the specific case described here will become the default once #515 is merged. I don't know if using `npx` here is the right call, since I don't like that it will install the package if it's not available, but you can also modify a built-in source's command manually if you want to use it.

**Comment by nyngwang** [comment]
@jose-elias-alvarez: So I don't need to add `.with({ prefer_local = ... })` for each formatter now?

**Comment by jose-elias-alvarez** [comment]
@nyngwang It is the default for a few Node-based sources for now. It's a little unclear, but if [the documentation](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md) shows `from_node_modules`, you don't need to specifically set `prefer_local`.

**Comment by nyngwang** [comment]
@jose-elias-alvarez: Thanks :) it's very clear now! I think it would be helpful for new users if this is documented there.

**Comment by nyngwang** [comment]
@jose-elias-alvarez:

Could you support path with `*` in it? E.g.:

```
__pypackages__/**/lib/autopep8
```

**Comment by jose-elias-alvarez** [comment]
@nyngwang This would be pretty tricky and is not something I am likely to implement myself. Feel free to open a feature request for tracking and to see if anyone wants to step in.

**Comment by nyngwang** [comment]
For future readers: I kind of _resolved_ this in another thread https://github.com/jose-elias-alvarez/null-ls.nvim/issues/289#issuecomment-1054803013, so you will probably don't need/want to implement it.
