### ISSUE TITLE
checkhealth from this plugin may not always return a valid report

### ISSUE THREAD

**Issue by EdmundsEcho** [jose-elias-alvarez/null-ls.nvim#567]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@HMBRW-A-001-M1-004.local

### Operating System

macOS 12.1

### null-ls config

Apologies, I chose not to do this because I could not find exactly where the null-ls settings were.  I fully expect that somehow (see log), I have something to update in the settings to prevent the error.  However, this is not the main reason for my posting this issue.

What I am posting is that I witnessed a report generated by null-ls being responsible for crashing the `checkhealth` all-together.  The cause was that the report did not  return *anything*.  There is no guard for this scenario in the neovim infrastructure, so it crashed (see [PR #17012](https://github.com/neovim/neovim/pull/17012)).

### Steps to reproduce

run `:checkhealth null-ls`

### Expected behavior

It should return what the neovim `checkhealth` script expects when running through all of the scripts.

### Actual behavior

Crashes the script.  Nothing is returned from any of the tests.

### Debug log

```
[WARN  Sun Dec 12 18:33:49 2021] ...nd/.config/nvim/bundle/null-ls.nvim/lua/null-ls/init.lua:61: config is deprecated; use setup instead
[WARN  Sun Dec 12 18:33:49 2021] ...nd/.config/nvim/bundle/null-ls.nvim/lua/null-ls/init.lua:39: lspconfig integration is deprecated; pass options to setup instead
[WARN  Sun Dec 12 18:40:23 2021] ...nd/.config/nvim/bundle/null-ls.nvim/lua/null-ls/init.lua:61: config is deprecated; use setup instead
[WARN  Sun Dec 12 18:40:23 2021] ...nd/.config/nvim/bundle/null-ls.nvim/lua/null-ls/init.lua:39: lspconfig integration is deprecated; pass options to setup instead
[WARN  Sun Dec 12 18:53:55 2021] ...nd/.config/nvim/bundle/null-ls.nvim/lua/null-ls/init.lua:39: lspconfig integration is deprecated; pass options to setup instead
```

### Help

Yes

### Implementation help

It's more of a yes and no.  I looked at the check health code.  I'm not yet familiar enough with lua to see what the return value of the script is.  There are several clauses that end with `return`.  So, is it a side effect?  I could not see a global variable that was being updated either.  So, at first glance, I have more to learn before I can help.

**Comment by jose-elias-alvarez** [comment]
I think there's some confusion – health checks don't need to "return" anything, but I can see that if you run `:checkhealth null-ls` without any registered sources (meaning that the check runs but none of the `report` functions is called), you get the following output:

```
Running healthchecks...
Error detected while processing function health#check:
line   33:
E684: list index out of range: 0
```

Is that what you're referring to? I don't get a crash on either 0.6.1 or Neovim master, but it does prevent the rest of the `:checkhealth` output from filling the buffer, which isn't ideal. In my opinion, the right behavior from Neovim's end is to prevent an error in one health check from killing the entire check, 

Either way, I put together a fix in c62050977ca017ba9dc252ca82532ef94105b096. Let me know if that takes care of the issue.

**Comment by EdmundsEcho** [comment]
I understand your point.  Yes,  you got it... including what I meant by "crash".  The "returning nothing" causes all of the `checkhealth` tests to fail to report.  In the event "nothing is returned", I might provide a "dummy output" that describes the "no input result".

**Comment by jose-elias-alvarez** [comment]
I think this is okay from our end now so I'm going to close this. Thanks for the report!
