### ISSUE TITLE
vim.lsp.buf.formatting_sync: timeout When trying to use prettier.

### ISSUE THREAD

**Issue by hrqmonteiro** [jose-elias-alvarez/null-ls.nvim#572]
Simply doesn't work.

![print](https://user-images.githubusercontent.com/17055027/148868478-3f73b3cf-4887-4ac7-957a-d9bc1a8e8db1.png)
![print2](https://user-images.githubusercontent.com/17055027/148868480-83bdef57-f2b4-4f85-be23-55deb1ee916f.png)
![print3](https://user-images.githubusercontent.com/17055027/148868482-06717eb0-e56e-45f3-be9f-2d3729cf3e83.png)

**Comment by jose-elias-alvarez** [comment]
I added the issue template for a reason and will not provide support to users who can't be bothered to follow it.

**Comment by iDuuck** [comment]
@hrqmonteiro This seems to be an issue with the timeout neovim has implemented for the formatting_sync method. Try increasing it: `vim.lsp.buf.formatting_sync(nil, 2000)` (second param is time in ms)
