### ISSUE TITLE
Sonarlint

### ISSUE THREAD

**Issue by omaranbari** [jose-elias-alvarez/null-ls.nvim#574]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Thank you for the wonderful plugin.

Has anyone looked into the possibility of adding sonarlint as a formatter?

Looking forward to any feedback.

### Help

No

**Comment by jose-elias-alvarez** [comment]
According to [this thread](https://community.sonarsource.com/t/can-i-run-sonarlint-check-from-command-line-without-sonarqube/35896/9), SonarLint doesn't have a CLI, so it wouldn't be possible to add support here. I see that there is a [proper language server](https://github.com/SonarSource/sonarlint-language-server) as well as an [open PR](https://github.com/neovim/nvim-lspconfig/pull/1627) to add support to nvim-lspconfig, which should provide a better experience anyways.

**Comment by omaranbari** [comment]
Thank you Jose Elias
