### ISSUE TITLE
Null-ls uses old buffer diagnostics when nvim-cmp uses a native popup

### ISSUE THREAD

**Issue by bellini666** [jose-elias-alvarez/null-ls.nvim#576]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.7.0-dev+872-g70fe3ce00

### Operating System

Debian Unstable

### null-ls config

```lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir
if on_windows then
    temp_dir = vim.loop.os_getenv("TEMP")
else
    temp_dir = "/tmp"
end

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local flags = {
    debounce_text_changes = 0,
}

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = {
            null_ls.builtins.diagnostics.flake8,
        },
        flags = flags,
        debug = true,
    })
end

local lspconfig_config = function()
    local nvim_lsp = require("lspconfig")
    nvim_lsp.pyright.setup({
        flags = flags,
        settings = {
            disableorganizeimports = true,
        },
    })
end

local cmp_config = function()
    local cmp = require("cmp")
    cmp.setup({
        snippet = {
            expand = function(args)
                vim.fn["vsnip#anonymous"](args.body)
            end,
        },
        mapping = {
            ["<CR>"] = cmp.mapping.confirm({ select = true }),
        },
        sources = {
            { name = "nvim_lsp" },
            { name = "buffer" },
        },
        experimental = {
            -- native_menu = true,
        },
    })
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "jose-elias-alvarez/null-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },
            {
                "neovim/nvim-lspconfig",
                config = lspconfig_config,
            },
            {
                "hrsh7th/nvim-cmp",
                requires = {
                    "hrsh7th/cmp-buffer",
                    "hrsh7th/cmp-nvim-lsp",
                    "hrsh7th/vim-vsnip",
                    "neovim/nvim-lspconfig",
                },
                config = cmp_config,
            },
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end
```

### Steps to reproduce

https://user-images.githubusercontent.com/134025/149021792-521f49b7-18c3-490b-a58e-6564b7ae0cb7.mp4

and

https://user-images.githubusercontent.com/134025/149022259-e399a78b-72eb-4531-aab2-610e6a553cc7.mp4

The video shows it, but basically:

1) Start typing something that will open a completion menu (in this case, I started to type `None`, a valid python word)
2) Press "esc" instead of choosing the completion menu

Note that pyright did give the updated diagnostics in both cases (in the first video it was that `No` is not valid, in the second there shouldn't be a diagnostics issue)

### Expected behavior

Null-ls would use the current buffer info after leaving insert mode to provide updated diagnostics info

### Actual behavior

Old diagnostics is show

### Debug log

[TRACE ter 11 jan 2022 18:13:24] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:118: received LSP request for method textDocument/completion
[TRACE ter 11 jan 2022 18:13:24] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_COMPLETION
[DEBUG ter 11 jan 2022 18:13:24] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:24: no generators available
[DEBUG ter 11 jan 2022 18:13:24] ...ack/packer/start/null-ls.nvim/lua/null-ls/completion.lua:16: received no completion results from generators
[TRACE ter 11 jan 2022 18:13:24] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method textDocument/didChange
[TRACE ter 11 jan 2022 18:13:24] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG ter 11 jan 2022 18:13:24] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:334: spawning command [codespell] at /tmp with args { "-" }
[DEBUG ter 11 jan 2022 18:13:24] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:334: spawning command [flake8] at /tmp with args { "--format", "default", "--stdin-display-name", "/tmp/xxx.py", "-" }
[TRACE ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:223: error output: nil
[TRACE ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:224: output: nil
[TRACE ter 11 jan 2022 18:13:25] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:155: received diagnostics from source 1
[TRACE ter 11 jan 2022 18:13:25] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:156: {}
[TRACE ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:223: error output: nil
[TRACE ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:224: output: /tmp/xxx.py:1:1: F821 undefined name 'No'

[TRACE ter 11 jan 2022 18:13:25] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:155: received diagnostics from source 2
[TRACE ter 11 jan 2022 18:13:25] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:156: { {
    code = "F821",
    col = 0,
    end_col = 2,
    end_lnum = 0,
    lnum = 0,
    message = "undefined name 'No'",
    row = "1",
    severity = 3,
    source = "flake8"
  } }
[TRACE ter 11 jan 2022 18:13:25] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method textDocument/didChange
[TRACE ter 11 jan 2022 18:13:25] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:334: spawning command [codespell] at /tmp with args { "-" }
[DEBUG ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:334: spawning command [flake8] at /tmp with args { "--format", "default", "--stdin-display-name", "/tmp/xxx.py", "-" }
[TRACE ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:223: error output: nil
[TRACE ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:224: output: nil
[TRACE ter 11 jan 2022 18:13:25] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:155: received diagnostics from source 1
[TRACE ter 11 jan 2022 18:13:25] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:156: {}
[TRACE ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:223: error output: nil
[TRACE ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:224: output: /tmp/xxx.py:1:1: F821 undefined name 'Non'

[TRACE ter 11 jan 2022 18:13:25] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:155: received diagnostics from source 2
[TRACE ter 11 jan 2022 18:13:25] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:156: { {
    code = "F821",
    col = 0,
    end_col = 3,
    end_lnum = 0,
    lnum = 0,
    message = "undefined name 'Non'",
    row = "1",
    severity = 3,
    source = "flake8"
  } }
[TRACE ter 11 jan 2022 18:13:25] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method textDocument/didChange
[TRACE ter 11 jan 2022 18:13:25] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:334: spawning command [codespell] at /tmp with args { "-" }
[DEBUG ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:334: spawning command [flake8] at /tmp with args { "--format", "default", "--stdin-display-name", "/tmp/xxx.py", "-" }
[TRACE ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:223: error output: nil
[TRACE ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:224: output: nil
[TRACE ter 11 jan 2022 18:13:25] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:155: received diagnostics from source 1
[TRACE ter 11 jan 2022 18:13:25] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:156: {}
[TRACE ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:223: error output: nil
[TRACE ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:224: output: nil
[TRACE ter 11 jan 2022 18:13:25] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:155: received diagnostics from source 2
[TRACE ter 11 jan 2022 18:13:25] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:156: {}
[TRACE ter 11 jan 2022 18:13:25] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method textDocument/didChange
[TRACE ter 11 jan 2022 18:13:25] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:334: spawning command [codespell] at /tmp with args { "-" }
[DEBUG ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:334: spawning command [flake8] at /tmp with args { "--format", "default", "--stdin-display-name", "/tmp/xxx.py", "-" }
[TRACE ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:223: error output: nil
[TRACE ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:224: output: nil
[TRACE ter 11 jan 2022 18:13:25] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:155: received diagnostics from source 1
[TRACE ter 11 jan 2022 18:13:25] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:156: {}
[TRACE ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:223: error output: nil
[TRACE ter 11 jan 2022 18:13:25] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:224: output: /tmp/xxx.py:1:1: F821 undefined name 'N'

[TRACE ter 11 jan 2022 18:13:25] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:155: received diagnostics from source 2
[TRACE ter 11 jan 2022 18:13:25] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:156: { {
    code = "F821",
    col = 0,
    end_col = 1,
    end_lnum = 0,
    lnum = 0,
    message = "undefined name 'N'",
    row = "1",
    severity = 3,
    source = "flake8"
  } }

### Help

No

**Comment by jose-elias-alvarez** [comment]
So I'm not able to reproduce the specific issue, but I've seen similar issues recently and also use nvim-cmp. A few questions just to make sure:

1. Does the issue occur when you don't use nvim-cmp at all?
2. Does the issue occur when you set `native_menu = true`?

I suspect that nvim-cmp is not cleaning up its temporary buffers properly, which is causing a bad interaction with null-ls. After the completion menu opens, you can see stray `"[Scratch"]` buffers when running `:!ls` (which doesn't happen when `native_menu = true`).

**Comment by jose-elias-alvarez** [comment]
Strangely I *am* able to reproduce this with `native_menu = true`. The issue there is that while completing, `vim.api.nvim_get_mode().mode` returns `ic` instead of `i`. I tested this out before, so the change in behavior must have been caused by a recent change to nvim-cmp.

Again, I'm not able to replicate your precise issue, but I think c29feb54a02ca8731f7f09a5cafe7c7b76f4e54f may help (and should also improve performance when using nvim-cmp). Could you update and see if the new commit helps?

**Comment by bellini666** [comment]
Hey @jose-elias-alvarez . Yes, the issue happens specifically while using `native_menu = true`. Without it, or even without `nvim-cmp` the issue doesn't happen at all. It took me a while how to reproduce the issue with a minimal config =P.

And yes, that fixed the issue! At least I'm not able to reproduce the minimal example anymore. Will come back if I ever see it happening again!

IMO you can close the issue and consider it done.

**Comment by jose-elias-alvarez** [comment]
I see, I misunderstood the nature of the issue, then, but I'm glad to hear things seem to be working okay. Thanks for reporting this!
