### ISSUE TITLE
Shellcheck diagnostics enabled for PKGBUILDs

### ISSUE THREAD

**Issue by Shatur** [jose-elias-alvarez/null-ls.nvim#584]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.6.1

### Operating System

ArchLinux

### null-ls config

-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir
if on_windows then
    temp_dir = vim.loop.os_getenv("TEMP")
else
    temp_dir = "/tmp"
end

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = {
            null_ls.builtins.diagnostics.shellcheck,
            null_ls.builtins.code_actions.shellcheck,
        },
        debug = true,
    })
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "jose-elias-alvarez/null-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end

### Steps to reproduce

1. Download any PKGBUILD file: `curl 'https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=optimus-manager-qt' -o PKGBUILD`
2. Open in Neovim.

### Expected behavior

shellcheck is not used for PKGBUILD.

### Actual behavior

A lot of errors from shellcheck:
![изображение](https://user-images.githubusercontent.com/22453358/149566375-7dacd3ea-2d62-4fad-a11d-3cad8131915b.png)

### Debug log

[WARN  Вс 02 янв 2022 22:11:25] ...plugins/start/null-ls.nvim/lua/null-ls/builtins/init.lua:17: failed to load builtin shellcheck for method formatting; please check your config
[WARN  Вс 02 янв 2022 22:11:25] ...plugins/start/null-ls.nvim/lua/null-ls/builtins/init.lua:17: failed to load builtin gitsigns for method diagnostics; please check your config

### Help

No

**Comment by polyzen** [comment]
They're bash scripts, and N/Vim automatically recognizes them as such. Not sure if there's a way to configure/disable null-ls based on filename. Doesn't seem like shellcheck lets you globally configure based on filename, but one way to do so would be if this were implemented:
https://github.com/koalaman/shellcheck/issues/2128

If you install the `pacman-contrib` package, PKGBUILD files will be set to the `PKGBUILD` filetype:
https://gitlab.archlinux.org/pacman/pacman-contrib/-/blob/v1.4.0/src/vim/ftdetect/PKGBUILD.vim

If you would then find you'd like to use shellcheck for PKGBUILD's, you could configure null-ls like so (note you could also use `extra_filetypes` with shfmt):
https://github.com/polyzen/dotfiles/blob/58a7bf4b99d943fc0667b7e92dbc847310934101/base/.config/nvim/lua/lsp.lua#L82-L87

Unfortunately the `extra_args` function seems to be evaluated only on the first file open, but perhaps that can be resolved:
https://github.com/jose-elias-alvarez/null-ls.nvim/issues/587

**Comment by Shatur** [comment]
> If you install the pacman-contrib package, PKGBUILD files will be set to the PKGBUILD filetype:

Sorry, forgot to mention, but I have it installed and the filetype is recognized as PKGBUILD. But null-ls is still attached.

**Comment by Shatur** [comment]
> If you would then find you'd like to use shellcheck for PKGBUILD's, you could configure null-ls like so (note you could also use extra_filetypes with shfmt):
> Unfortunately the extra_args function seems to be evaluated only on the first file open, but perhaps that can be resolved:

Oh, I get it, thanks. Can I disable it for `PKGBUILD` temporary until #578 will be fixed?

**Comment by polyzen** [comment]
There's `disabled_filetypes`, but I don't think that would work in this situation:
https://github.com/jose-elias-alvarez/null-ls.nvim/commit/ff4d9169f25c23199cd2cdd5fce8fc99a88f2a0d

**Comment by Shatur** [comment]
> There's disabled_filetypes, but I don't think that would work in this situation:

Yes, I tried

```lua
local null_ls = require('null-ls')
null_ls.setup({
  sources = {
    null_ls.builtins.diagnostics.shellcheck.with({
      disabled_filetypes = { "PKGBUILD" },
    }),
  },
})
```

and it didn't work.

**Comment by jose-elias-alvarez** [comment]
I suspect the issue is that Neovim is setting the filetype to `sh` first, then setting it to `PKGBUILD`, meaning that null-ls attaches to the buffer and generates them once (which would also explain why `disabled_filetypes` doesn't work here). 

If I take the autocommand from the linked file and add the following line to the top level of the minimal config, everything seems to work, since only one `FileType` event is fired:

```lua
vim.cmd("au BufNewFile,BufRead PKGBUILD set filetype=PKGBUILD")
```

Does that work for you?

**Comment by Shatur** [comment]
> If I take the autocommand from the linked file and add the following line to the top level of the minimal config, everything seems to work, since only one FileType event is fired:

It works on buffer enter, but after `:e` I see null-ls diagnostics again.

**Comment by jose-elias-alvarez** [comment]
> > If I take the autocommand from the linked file and add the following line to the top level of the minimal config, everything seems to work, since only one FileType event is fired:
> 
> It works on buffer enter, but after `:e` I see null-ls diagnostics again.

To clarify, do you mean with the minimal config or with your own config? With the minimal config I'm not seeing this behavior.

**Comment by Shatur** [comment]
> To clarify, do you mean with the minimal config or with your own config? With the minimal config I'm not seeing this behavior.

Right, I it works with minimal configuration.

I think I can close this one in favor of #587.

**Comment by polyzen** [comment]
> Not sure if there's a way to configure/disable null-ls based on filename.

Seems like https://github.com/jose-elias-alvarez/null-ls.nvim/pull/613 would allow one to disable null-ls when the filename is `PKGBUILD`.
