### ISSUE TITLE
prettier is not formatting the code

### ISSUE THREAD

**Issue by jose4125** [jose-elias-alvarez/null-ls.nvim#594]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.6.0-dev+642-g07223fae5 Build type: Release LuaJIT 2.1.0-beta3

### Operating System

mac

### null-ls config

local null_ls = require('null-ls')
local formatting = null_ls.builtins.formatting

null_ls.setup({
  sources = {
    formatting.prettier.with({
      prefer_local = "node_modules/.bin",
    }),
    formatting.eslint.with({
      prefer_local = "node_modules/.bin",
    }),
    formatting.stylelint,
    formatting.prismaFmt,
    formatting.black,
    formatting.isort,
    formatting.cmake_format,
    formatting.dart_format,
    formatting.terraform_fmt,
    formatting.codespell,
  },
  -- you can reuse a shared lspconfig on_attach callback here
  on_attach = function(client)
      if client.resolved_capabilities.document_formatting then
          vim.cmd("autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()")
        -- vim.cmd([[
        --     augroup LspFormatting
        --         autocmd! * <buffer>
        --         autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()
        --     augroup END
        --     ]])
      end
  end,
})

### Steps to reproduce

1. open a js, ts or tsx file, add some linting error
![Screen Shot 2022-01-17 at 3 09 14 PM](https://user-images.githubusercontent.com/1216119/149831660-7bae698d-4d37-433f-a4c7-259f92d8d4e8.png)

### Expected behavior

when I save. should format the document

### Actual behavior

the linter is showing linters erros. when I  saved is not formatting the document

### Debug log

no errors

### Help

No

**Comment by jose-elias-alvarez** [comment]
The autocommands you are attempting to use are both broken, because you haven't specified a pattern (or rather, you are using `lua` as a pattern, which will not work). Using the one recommended in the README with your config works correctly. 

I'll also mention that using `eslint` and `prettier` together is not recommended. From your screenshot, it looks like you are already using eslint-plugin-prettier, so you should drop `prettier` and let `eslint` handle formatting.

**Comment by jose4125** [comment]
I remove eslint formmating and works. thanks

**Comment by bryant-the-coder** [comment]
how to remove the ^M thign after formatting on each line????

**Comment by nyngwang** [comment]
> I removed eslint formmating and works. thanks

You're wrong. You can use both `nvim-lspconfig`-`eslint` and `null-ls`-`prettier`. In my case:

**ESLint**:

```lua
M = {
  capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities()),
  autostart = true,
  on_attach = function (...)
    require('lsp_config.common_setup')(...)
    vim.cmd([[
      autocmd BufWritePre <buffer> lua vim.cmd('EslintFixAll')
    ]])
  end,
  settings = {
    packageManager = 'yarn'
  }
}

return M
```

**tsserver**:

```lua
M = {
  capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities()),
  autostart = true,
  on_attach = function (client, bufnr)
    client.resolved_capabilities.document_formatting = false
    client.resolved_capabilities.document_range_formatting = false
    require('lsp_config.common_setup')(client, bufnr)
    if vim.fn.getbufvar(bufnr, '&filetype') == 'html' then
      vim.lsp.handlers['textDocument/publishDiagnostics'] = function () end
    end
  end,
  filetypes = {
    'html',
    'javascript',
    'javascriptreact',
    'javascript.jsx',
    'typescript',
    'typescriptreact',
    'typescript.tsx'
  }
}

return M
```
