### ISSUE TITLE
[Error] Vim(bufdo):E37: No write since last change (add ! to override)

### ISSUE THREAD

**Issue by tamago324** [jose-elias-alvarez/null-ls.nvim#6]
Thank you for creating a very interesting plugin!
It did not work properly, so I will report it.

- `nvim --version`: NVIM v0.5.0-dev+1384-gf2906a466
- Operating system/version: Manjaro

**Describe the bug**

When I run `vim.lsp.buf.formatting()` without `set hidden`, I get the following error.

> Error executing vim.schedule lua callback: ...im/.plugged/plenary.nvim/lua/plenary/async_lib/async.lua:14: The coroutine failed with this message: ...ig/nvim/.plugged/null-ls.nvim/lua/null-ls/formatting.lua:63: Vim(bufdo):E37: No write since last change (add ! to override)

**To Reproduce using `nvim -u mini.vim -i NONE`**

```vim
set encoding=utf-8

filetype plugin indent on
if has('vim_starting')
  let s:pluin_manager_dir='~/.config/nvim/.plugged/vim-plug'
  execute 'set runtimepath+=' . s:pluin_manager_dir
endif
call plug#begin('~/.config/nvim/.plugged')
Plug 'neovim/nvim-lspconfig'
Plug 'nvim-lua/plenary.nvim'
Plug 'jose-elias-alvarez/null-ls.nvim'
call plug#end()

set nobackup
set nowritebackup
set noswapfile
set updatecount=0
set backspace=indent,eol,start
language messages en_US.utf8

lua << EOF

local servers = require'xlsp.servers'
require'lspconfig'.sumneko_lua.setup{
  cmd = servers.get_cmd('sumneko_lua'),
}

require'null-ls'.setup {
  sources = {
    null_ls.builtins.formatting.stylua,
  }
}

EOF
```

1. `nvim -u minvimrc -i NONE`
2. `:e sample.lua`
3. edit
4. `:w` (hook `BufWritePost`)
5. error

**Expected behavior**

format is executed and the file is saved without error.

---

Thank you!

**Comment by tamago324** [comment]
It worked properly when I set `set hidden`.

**Comment by jose-elias-alvarez** [comment]
Thanks for the detailed instructions. I can see that `set nohidden` breaks the save after formatting functionality, since it uses `bufdo`. 

I just pushed a simple fix that changes the command to `bufdo!`, which should take care of the problem. Could you update null-ls and see if that fixes it for you, too?

**Comment by tamago324** [comment]
I checked it, and it worked fine.
Thank you for your quick support!

**Comment by jose-elias-alvarez** [comment]
No problem, thanks for the bug report!
