### ISSUE TITLE
Feature Request: conditional formatting

### ISSUE THREAD

**Issue by vuki656** [jose-elias-alvarez/null-ls.nvim#60]
Would it be possible to select a formatter based on some conditions?

For example with `eslint` and `prettier`, a user could write a condition to check if there is `.eslintrc` present in the project, if yes, use `eslint`, if not use `prettier`. 

Awesome work on the plugin btw, its a breeze to set up compared to `efm`.

**Comment by jose-elias-alvarez** [comment]
Great to hear! This is something I've thought about, too. My idea would be to have a general-purpose conditional helper that would let you do something like this:

```lua
local null_ls = require("null-ls")
local sources = {
    -- we can set the metatable for conditionals so that accessing the generator will run the callback
    null_ls.conditional(function(utils)
        -- pass a utils object to conditionals to streamline common tasks
        return utils.root("package.json").has_file(".eslintrc") and null_ls.builtins.formatting.eslint_d
            or null_ls.builtins.formatting.prettier
    end),

    -- maybe we could even check if the command is successful?
    null_ls.conditional(function(utils)
        return utils.can_run(null_ls.builtins.formatting.eslint_d) or null_ls.builtins.formatting.prettier
    end),
}
```

This is just a sketch, but does that sound like it would solve this case?

**Comment by vuki656** [comment]
This looks really cool and simple to set up. Lot more user-friendly compared to what I had in mind. 

Regarding syntax, I would prefer the file checking since if for example `eslint` and `prettier` are both installed globally, the check would pass for `eslint` even if there is no `.eslintrc` file present.

**Comment by jose-elias-alvarez** [comment]
That's a good point – I was thinking specifically of ESLint's integration with Prettier, but you're right that it would pass. I think we can start with checking files and expand it later if it makes sense.

**Comment by bpinto** [comment]
@jose-elias-alvarez what about eslint + prettier? Where one needs to be executed after the other, is that possible?

**Comment by jose-elias-alvarez** [comment]
That case will be covered by #56 (though if you can modify your project's config, I really recommend setting up [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) and using `eslint_d` as a formatter).
