### ISSUE TITLE
Add support for ktlint

### ISSUE THREAD

**Issue by miki725** [jose-elias-alvarez/null-ls.nvim#600]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

[`ktlint`](https://github.com/pinterest/ktlint) is pretty poplar lint for kotlin. Will be great if it can be integrated to lint/format kotlin code with neovim LSP

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by jose-elias-alvarez** [comment]
The linter already has [an nvim-lint implementation](https://github.com/mfussenegger/nvim-lint/blob/187c70ffc6d1eb093bf1c9c102555565f53c100b/lua/lint/linters/ktlint.lua) so porting it here should be pretty simple. Generally, adding formatters isn't too tough, either, so anyone who wants to tackle this should find it pretty straightforward.
