### ISSUE TITLE
[Feature request] Add support for golangci-lint

### ISSUE THREAD

**Issue by tiannaru** [jose-elias-alvarez/null-ls.nvim#62]
Allow using golangci-lint as either formatter or linter.
This might turn out complicated, as golangci-lint is sometimes slow. This could be alleviated increasing concurrent threads via command line options.
It is also quite extensible, and it would need to be able to source a config file that is project specific.
I can also help, if this feature is deemed desirable.

**Comment by tiannaru** [comment]
If not too difficult, maybe it could be added in #53

**Comment by abzcoding** [comment]
I think it would be better to have it as a [linter](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics.lua)
[this](https://github.com/mfussenegger/nvim-lint/blob/master/lua/lint/linters/golangcilint.lua) might be helpful

**Comment by jose-elias-alvarez** [comment]
I don't know anything about this but am happy to help with a PR. The linked nvim-lint source looks like a good place to start. If the CLI output includes both diagnostics and formatting, we could cache the results to improve speed somewhat.
