### ISSUE TITLE
pydocstyle ignores config file discovery

### ISSUE THREAD

**Issue by stinovlas** [jose-elias-alvarez/null-ls.nvim#623]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.6.1

### Operating System

Linux 5.13.0-1028-oem Ubuntu

### Minimal config

```
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir
if on_windows then
    temp_dir = vim.loop.os_getenv("TEMP")
else
    temp_dir = "/tmp"
end

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = {
            null_ls.builtins.diagnostics.pydocstyle,
        },
        debug = true,
    })
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "jose-elias-alvarez/null-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end
```

### Steps to reproduce

Create `setup.cfg` with following content:
```ini
[pydocstyle]
add_ignore=D100,D101,D107
```
Create `example.py` with following content:
```python
class Class:
    def __init__(self):
        pass
```

Run `nvim --clean -u minimal_init.lua example.py`

### Expected behavior

No errors should be shown. When I run `pydocstyle example.py` the output is empty.

### Actual behavior

Errors are shown. Configuration in `setup.cfg` is ignored.

### Debug log

```
[TRACE Pá 28. ledna 2022, 10:33:44] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:92: starting null-ls client
[TRACE Pá 28. ledna 2022, 10:33:44] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:118: received LSP request for method initialize
[DEBUG Pá 28. ledna 2022, 10:33:44] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:147: unable to notify client for method textDocument/didOpen (client not active): {
  textDocument = {
    uri = "file:///home/jmusilek/test/example.py"
  }
}
[TRACE Pá 28. ledna 2022, 10:33:44] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method initialized
[TRACE Pá 28. ledna 2022, 10:33:44] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method textDocument/didOpen
[TRACE Pá 28. ledna 2022, 10:33:44] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Pá 28. ledna 2022, 10:33:44] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:335: spawning command [pydocstyle] at /home/jmusilek/test with args { "/tmp/lua_7HeUV1.py" }
[TRACE Pá 28. ledna 2022, 10:33:44] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:224: error output: nil
[TRACE Pá 28. ledna 2022, 10:33:44] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:225: output: /tmp/lua_7HeUV1.py:1 at module level:
        D100: Missing docstring in public module
/tmp/lua_7HeUV1.py:1 in public class `Class`:
        D101: Missing docstring in public class
/tmp/lua_7HeUV1.py:2 in public method `__init__`:
        D107: Missing docstring in __init__

[TRACE Pá 28. ledna 2022, 10:33:44] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:156: received diagnostics from source 1
[TRACE Pá 28. ledna 2022, 10:33:44] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:157: { {
    code = "D100",
    col = 0,
    end_col = 0,
    end_lnum = 1,
    lnum = 0,
    message = "Missing docstring in public module",
    row = 1,
    severity = 3,
    source = "pydocstyle"
  }, {
    code = "D101",
    col = 0,
    end_col = 0,
    end_lnum = 1,
    lnum = 0,
    message = "Missing docstring in public class",
    row = 1,
    severity = 3,
    source = "pydocstyle"
  }, {
    code = "D107",
    col = 0,
    end_col = 0,
    end_lnum = 2,
    lnum = 1,
    message = "Missing docstring in __init__",
    row = 2,
    severity = 3,
    source = "pydocstyle"
  } }
```

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I was able to get around this with providing explicit path to configuration file:
```
null_ls.setup({
    sources = {
        null_ls.builtins.diagnostics.pydocstyle.with({
            extra_args = { '--config', vim.loop.cwd() .. '/setup.cfg' },
        }),
    },
})
```
However, this is not a general solution since `pydocstyle` has extensive autodiscovery mechanism with inheritance and multiple possible configuration files. See https://www.pydocstyle.org/en/2.1.1/usage.html#configuration-files

I'd gladly submit PR to fix this in a better way and more permanent way, but I don't really know where to start. I have no clue why the `pydocstyle` auto discovery doesn't work as expected.

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
So I think the cause is that `pydocstyle` looks for a config file based on the path of the file passed as an argument, not the directory in which it's spawned. You can verify this by copying `example.py` to another directory, e.g. `/tmp`, and running `pydocstyle /tmp/example.py` from the directory that contains the config file. `pydocstyle` doesn't support `stdin` (though there is an [open issue](https://github.com/PyCQA/pydocstyle/issues/195), so we use a temp file. 

I'm not sure we have a good solution here. In the linked PR, they mention that even if `stdin` support is added, the linter won't resolve config files automatically, so you'd still have to manually specify the location. I haven't seen this kind of behavior before, and I think `pydocstyle` would ideally look for a config file in the current working directory, but that might be hard to implement and might break existing behavior.

**Comment by syphar** [comment]
thank you for explaining @jose-elias-alvarez , just wanted to write the same. 


@stinovlas sadly there is no other way currently. That's also why I [added an explanation and configuration example to the pydocstyle builtin docs](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#pydocstyle). 

- null-ls doesn't work directly on the file but formats the buffer, which is good :)  
- since pydocstyle doesn't support stdin, we have to use a temporary file to pass in the buffer content 
- pydocstyle config discovery ignores the CWD and start from the temporary file. 

The solution is probably to change pydocstyle and add a parameter to change this behavior. Then we can use this parameter in the null-ls config.

**Comment by stinovlas** [comment]
Thank you both for your comments. I'm totally new to `null-ls` (and nvim LSP client and Lua) and as it showed, I have little understanding of its principles. Of course it works over the buffers instead of files! The issue has to be resolved in pydocstyle, no doubt.

I also tried to use `pydocstyle` with multiple `--config` options so I could emulate its autodiscovery mechanism. Sadly, that doesn't work either, it uses just the last `--config` specified. I think that it would be possible to create the temporary file in the same directory as the actual file (if the buffer is tied to an open file, that is) – the autodiscovery would probably kick in, but I don't like this solution at all and I don't think that's something we should add to the `null-ls`.

Thank you for pointing up the documentation. I was looking for something like this, but couldn't find anything. Next time I'll be more thorough.
