### ISSUE TITLE
nvim-ts-autotag stops working after formatting the buffer.

### ISSUE THREAD

**Issue by kwkarlwang** [jose-elias-alvarez/null-ls.nvim#626]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.6.1 Release

### Operating System

macOS Big Sur 11.6.2 M1

### Minimal config

```lua
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir
if on_windows then
    temp_dir = vim.loop.os_getenv("TEMP")
else
    temp_dir = "/tmp"
end

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = {
            null_ls.builtins.formatting.prettier
        },
        debug = true,
    })
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "jose-elias-alvarez/null-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },{
                'nvim-treesitter/nvim-treesitter',
                run = ':TSUpdate'
            },{
                "windwp/nvim-ts-autotag",
                config = function ()
                    require('nvim-ts-autotag').setup()
                end
            }
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end
```

### Steps to reproduce

Before starting, I am not sure if this is a [nvim-ts-autotag](https://github.com/windwp/nvim-ts-autotag) or a `null-ls` problem (or prettier).

In short, nvim-ts-autotag does not close the tag after calling `lua vim.lsp.buf.formatting_sync()` **manully**.

1. After installing the plugins. Run `:TSInstall tsx`
2. Run the following command: `mkdir test && cd test && npm init -y` in terminal
3. Create a new file `nvim index.tsx` and paste the following content
```tsx
import React from 'react'
export const index = (props : {}) => {
    return;
}
```
4. Inside neovim, run `:lua vim.lsp.buf.formatting_sync()`.
5. In between `return` and `;`, type ` <div>`.

Here is a video to reproduce and demonstrate the problem.

https://user-images.githubusercontent.com/38927155/151673509-7fcc302c-3b90-45ac-addb-71502e66c382.mov

### Expected behavior

I expect the output to be the following after typing `<div>`, autotag should complete the `</div>`
```tsx
import React from "react";

export const index = (props : {}) => {
  return <div></div>;
}
```

### Actual behavior

The actual content is the following. Autotag has stopped working after calling `:lua vim.lsp.buf.formatting_sync()`
```tsx
import React from "react";

export const index = (props : {}) => {
  return <div>;
}
```

The strange thing is if I have the following null-ls.setup `on_attach`:
```lua
    on_attach = function(client)
        if client.resolved_capabilities.document_formatting then
            vim.cmd([[
            augroup LspFormatting
                autocmd! * <buffer>
                autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()
            augroup END
            ]])
        end
    end,
```
Then I can format on save and nvim-ts-autotag works as expected. Only when I call it manually with `:lua vim.lsp.buf.formatting_sync()` breaks the autotag function.

### Debug log

[TRACE Sat Jan 29 10:39:15 2022] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:92: starting null-ls client
[TRACE Sat Jan 29 10:39:15 2022] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:118: received LSP request for method initialize
[DEBUG Sat Jan 29 10:39:15 2022] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:147: unable to notify client for method textDocument/didOpen (client not active): {
  textDocument = {
    uri = "file:///Users/karl.wang/Desktop/test/index.tsx"
  }
}
[TRACE Sat Jan 29 10:39:15 2022] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method initialized
[TRACE Sat Jan 29 10:39:15 2022] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method textDocument/didOpen
[TRACE Sat Jan 29 10:39:15 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Sat Jan 29 10:39:15 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:24: no generators available
[TRACE Sat Jan 29 10:39:21 2022] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:118: received LSP request for method textDocument/formatting
[TRACE Sat Jan 29 10:39:21 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_FORMATTING
[DEBUG Sat Jan 29 10:39:21 2022] ...rt/null-ls.nvim/lua/null-ls/helpers/command_resolver.lua:18: attempting to find local executable node_modules/.bin/prettier
[DEBUG Sat Jan 29 10:39:21 2022] ...rt/null-ls.nvim/lua/null-ls/helpers/command_resolver.lua:40: Unable to resolve command [node_modules/.bin/prettier], skipping further lookups
[DEBUG Sat Jan 29 10:39:21 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:281: Using dynamic command for [prettier], got: prettier
[DEBUG Sat Jan 29 10:39:21 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:335: spawning command [prettier] at /Users/karl.wang/Desktop/test with args { "--stdin-filepath", "/Users/karl.wang/Desktop/test/index.tsx" }
[TRACE Sat Jan 29 10:39:22 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:224: error output: nil
[TRACE Sat Jan 29 10:39:22 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:225: output: import React from "react";

export const index = (props: {}) => {
  return;
};

[TRACE Sat Jan 29 10:39:26 2022] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method textDocument/didChange
[TRACE Sat Jan 29 10:39:26 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG Sat Jan 29 10:39:26 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:24: no generators available

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
This is a pretty tricky issue. Basically, null-ls formatting uses a temp buffer to minimize the number of changes made to the actual buffer. Once it's done, it [schedules deleting the temp buffer](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/2ae4a5e2e2b35716c44c104ef1afa35ecb40c444/lua/null-ls/formatting.lua#L44) to ensure it's deleted even if the handler throws an error. However, nvim-ts-autotag [catches the BufDelete event](https://github.com/windwp/nvim-ts-autotag/blob/32bc46ee8b21f88f87d97b976ae6674595b311b5/lua/nvim-ts-autotag.lua#L22), assumes that [the deleted buffer is the _current_ buffer](https://github.com/windwp/nvim-ts-autotag/blob/32bc46ee8b21f88f87d97b976ae6674595b311b5/lua/nvim-ts-autotag/internal.lua#L430), and detaches from the current buffer, which makes its functionality no longer work.

The following nvim-ts-autotag diff makes things work by correctly passing the number of the deleted buffer:

```diff
diff --git a/lua/nvim-ts-autotag.lua b/lua/nvim-ts-autotag.lua
index c1c3a2b..553fa72 100644
--- a/lua/nvim-ts-autotag.lua
+++ b/lua/nvim-ts-autotag.lua
@@ -19,7 +19,7 @@ function M.setup(opts)
   vim.cmd[[augroup nvim_ts_xmltag]]
   vim.cmd[[autocmd!]]
   vim.cmd[[autocmd FileType * call v:lua.require('nvim-ts-autotag.internal').attach()]]
-  vim.cmd[[autocmd BufDelete * call v:lua.require('nvim-ts-autotag.internal').detach()]]
+  vim.cmd[[autocmd BufDelete * lua require('nvim-ts-autotag.internal').detach(vim.fn.expand('<abuf>'))]]
   vim.cmd[[augroup end]]
 end

diff --git a/lua/nvim-ts-autotag/internal.lua b/lua/nvim-ts-autotag/internal.lua
index c9dae9e..a46408d 100644
--- a/lua/nvim-ts-autotag/internal.lua
+++ b/lua/nvim-ts-autotag/internal.lua
@@ -426,8 +426,8 @@ M.attach = function (bufnr,lang)
     end
 end

-M.detach = function ( )
-    local bufnr = vim.api.nvim_get_current_buf()
+M.detach = function (bufnr)
+    bufnr = tonumber(bufnr) or vim.api.nvim_get_current_buf
     buffer_tag[bufnr] = nil
 end
```

I don't have the bandwidth to put together a minimal reproduction for nvim-ts-autotag, but if I were you I would open up an issue or PR to handle these assumptions (at a glance there's a few more in the code).

**Comment by kwkarlwang** [comment]
Got it, thanks for the clear explanation! I will take the issue to nvim-ts-autotag then. For now, the format on save autocmd works just fine.

**Comment by jose-elias-alvarez** [comment]
I played around with this a bit more and have no idea why the autocommand works, but calling it manually doesn't (some kind of race condition, maybe?). I also wasn't able to put together a minimal reproduction but confirmed that the following diff fixes things on our end:

```diff
diff --git a/lua/null-ls/formatting.lua b/lua/null-ls/formatting.lua
index 838cb76..1b51867 100644
--- a/lua/null-ls/formatting.lua
+++ b/lua/null-ls/formatting.lua
@@ -42,7 +42,7 @@ M.handler = function(method, original_params, handler)

             -- schedule before calling handler in case handler throws
             vim.schedule(function()
-                api.nvim_buf_delete(temp_bufnr, { force = true })
+                vim.cmd(string.format("noautocmd %dbwipeout", temp_bufnr))
             end)

             handler(...)
```

I do think this should be handled upstream, though, since assuming that BufDelete events are fired _only_ when the deleted buffer is the active buffer seems off.
