### ISSUE TITLE
Ability to lower priority of null-ls code actions

### ISSUE THREAD

**Issue by axieax** [jose-elias-alvarez/null-ls.nvim#630]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Hi,
I find that for most language servers, null-ls code actions are where I want them to be towards the bottom of `vim.ui.select`. However, with the `gopls` language server, it seems that null-ls code actions come before gopls' ones (as shown below). Do you know if there is a way to force null-ls code actions to the end of the list (perhaps by configuring priority)?

![image](https://user-images.githubusercontent.com/62098008/151755842-764dee16-d0d5-4a66-8395-505d8f767aa1.png)

Thanks!

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by jose-elias-alvarez** [comment]
To my knowledge there is no concept of code action priority, so this isn't something we can handle. You'd need to write a custom function to request code actions, sort the returned code actions in whatever way you want, then display and select the one you want. The [Telescope code actions built-in](https://github.com/nvim-telescope/telescope.nvim/blob/3a3c9a3c8ba3fb14121ef5c50a87173dcb969416/lua/telescope/builtin/lsp.lua#L149) is a good example of how to do this.

**Comment by axieax** [comment]
Appreciate the help! After a bit of experimentation, I've finally managed to achieve this desired functionality: [https://github.com/axieax/dotconfig/blob/main/nvim/lua/lsp/code_actions.lua](https://github.com/axieax/dotconfig/blob/main/nvim/lua/lsp/code_actions.lua)

**Comment by emmanueltouzery** [comment]
if that helps anyone, I made it work now, assuming you display code actions using `vim.lsp.buf.code_action()` and that you have https://github.com/stevearc/dressing.nvim installed.
My config setting is: https://github.com/emmanueltouzery/nvim_config/commit/22fd1c39c3463ec6c64ab66243d7699c82a373ca

Basically ask dressing.nvim to use telescope for code action dialogs, and then override the telescope sorter.
