### ISSUE TITLE
Correctly handle extra diagnostic attributes

### ISSUE THREAD

**Issue by jose-elias-alvarez** [jose-elias-alvarez/null-ls.nvim#632]
This is a diagnostic created by the ESLint language server:

```
{ {
    bufnr = 1,
    col = 58,
    end_col = 58,
    end_lnum = 0,
    lnum = 0,
    message = "Insert `;`",
    namespace = 17,
    severity = 1,
    source = "eslint",
    user_data = {
      lsp = {
        code = "prettier/prettier",
        codeDescription = {
          href = "https://github.com/prettier/eslint-plugin-prettier#options"
        }
      }
    }
  } }
```

And this is the equivalent diagnostic created by the null-ls `eslint` source:

```
{ {
    bufnr = 1,
    code = "prettier/prettier",
    col = 58,
    end_col = 0,
    end_lnum = 1,
    end_row = 1,
    lnum = 0,
    message = "Insert `;`",
    namespace = 18,
    row = 1,
    severity = 1,
    source = "eslint"
  } }
```

I think we should change how null-ls handles these extra attributes. As a start, we could change the logic in [`make_diagnostic`](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/helpers/diagnostics.lua#L58) to directly assign top-level attributes and assign all others under a `user_data.null_ls` key. I'll open a separate issue.

_Originally posted by @jose-elias-alvarez in https://github.com/jose-elias-alvarez/null-ls.nvim/pull/622#issuecomment-1025948155_

This will be a breaking change, but our current behavior is not compliant with the API, so it's a good idea to fix it.

**Comment by wookayin** [comment]
One reference is `diagnostic_lsp_to_vim` in (code: https://github.com/neovim/neovim/blob/v0.6.0/runtime/lua/vim/lsp/diagnostic.lua#L92-L118).

[`Diagnostic` from the language server protocol](https://microsoft.github.io/language-server-protocol/specification#diagnostic) is translated to a neovim `diagnostic` per `:h diagnostic-structure`
```
A diagnostic is a Lua table with the following keys:                        
                                                                            
        bufnr: Buffer number                                                
        lnum: The starting line of the diagnostic                           
        end_lnum: The final line of the diagnostic                          
        col: The starting column of the diagnostic                          
        end_col: The final column of the diagnostic                         
        severity: The severity of the diagnostic vim.diagnostic.severity    
        message: The diagnostic text                                        
        source: The source of the diagnostic                                
        user_data: Arbitrary data plugins or users can add                  
```

```
/* Diagnostic from the standard LSP protocol */
interface Diagnostic {
  range
  severity
  code
  codeDescription
  source
  message
  tags
  relatedInformation
  data
}
```

So for example, `code` will go into `d.user_data.lsp.code`. I am not sure why neovim developers has decided to include code not as a top-level entry, but this is the correct convention we've got so far and all other LSP servers working in a neovim seem to be following this.

**Comment by wookayin** [comment]
I also would like to mention that if we move `code` away into `user_data.null_ls`, some plugins like [trouble.nvim](https://github.com/folke/trouble.nvim/blob/aae12e7b23b3a2b8337ec5b1d6b7b4317aa3929b/lua/trouble/util.lua#L177) will fail to extract the data because of the plugin-specific namespace (like `user_data.lsp` and `user_data.null_ls`). I am going to propose neovim should standarize `code` as a top-level entry in the diagnostic structure.

**Comment by jose-elias-alvarez** [comment]
> I also would like to mention that if we move `code` away into `user_data.null_ls`, some plugins like [trouble.nvim](https://github.com/folke/trouble.nvim/blob/aae12e7b23b3a2b8337ec5b1d6b7b4317aa3929b/lua/trouble/util.lua#L177) will fail to extract the data because of the plugin-specific namespace (like `user_data.lsp` and `user_data.null_ls`). I am going to propose neovim should standarize `code` as a top-level entry in the diagnostic structure.

This is an excellent point. Unless `code` is standardized, it's difficult for plugins to provide that data in a way that integrations can pick up on (unless they pretend to be LSP sources and reuse `user_data.lsp`). Let's see if there's any guidance from the Neovim maintainers on this before continuing.

**Comment by wookayin** [comment]
The `code` entry now has been standard in neovim, so we can keep the current behavior where `code` is set directly as a top-level field of `diagnostic` table structure.

**Comment by jose-elias-alvarez** [comment]
> The `code` entry now has been standard in neovim, so we can keep the current behavior where `code` is set directly as a top-level field of `diagnostic` table structure.

Great, thanks for opening the issue. I think the easiest way to ensure compatibility here is to have a list of specifically approved top-level fields, so I or someone else can put together a PR with that approach whenever.

**Comment by jose-elias-alvarez** [comment]
I'm reviewing this issue again, and now that `code` has been standardized, I'm not sure whether this would actually be a change for the better. Non-standard top level attributes don't specifically cause any issues, and the UX of digging into `diagnostic.user_data.null_ls.my_custom_attribute` is quite a bit worse than just accessing `diagnostic.my_custom_attribute`. It's also more transparent for built-in authors who may otherwise wonder where their custom attribute went. 

Given that this isn't actually causing any problems, I don't think it justifies a breaking change / a (small) amount of added complexity, and so I'm going to close this issue and merge the original PR that inspired it as-is. I'll revisit this as an option if the situation changes.
