### ISSUE TITLE
Formatting sync will timeout when formatter errors

### ISSUE THREAD

**Issue by marcelbeumer** [jose-elias-alvarez/null-ls.nvim#64]
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no issues already open with the same problem.

### Neovim Version

NVIM v0.6.0-dev+61-g6f48c018b

### Steps to reproduce

I would guess there are more ways to reproduce this, but this is mine.

- Setup vim to format on save sync: `autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()`
- Config a formatter, in my case `deno fmt` or `prettier` that will give exit code `>0` and stderr on syntax errors:

```
  local deno_fmt = {
    method = null_ls.methods.FORMATTING,
    filetypes = {"typescript", "typescriptreact" },
    generator = null_ls.formatter({
      command = "deno",
      args = { "fmt", "-"},
      to_stdin = true
      -- command = "prettier",
      -- args = { "--stdin-filepath", "$FILENAME" },
      -- to_stdin = true,
    }),
  }
  null_ls.config {
    debounce = 150,
    save_after_format = false,
    sources = { deno_fmt }
  }
```

(I'm using TypeScript code, but I guess use anything else)
- Change code to have a syntax error
- Save the file
- Notice it takes a long time (vim freezes for a bit)
- `:messages`: you'll see it timed out `vim.lsp.buf.formatting_sync: timeout`

### Expected behavior

I would expect no timeout / delay 

### Actual behavior

Delay / timeout :)

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by marcelbeumer** [comment]
Additional info: I'm not having this issue on `efm-langserver`

**Comment by jose-elias-alvarez** [comment]
Thanks for the reproduction steps! I can see the timeout error on my end, too and it seems to be specific to `buf.formatting_sync()`, which means we're most not responding properly to `buf_request_all`. I'll look into this tomorrow and let you know.

Out of curiosity: why use `buf.formatting_sync` over the built-in `save_after_format` option?

**Comment by marcelbeumer** [comment]
Thanks @jose-elias-alvarez! 

I'm using `formatting_sync()` because I want to avoid multiple writes to a file, that could potentially impact scripts hooked into file watchers for example. I didn't even test async, it was more of a "intuitive" thing to do "to avoid trouble and complexity". As `deno fmt` is quite fast, sync works well for me.

**Comment by jose-elias-alvarez** [comment]
Nope, I think you're right – you'll get one write from the original `:w` command and an additional write from `:update` afterwards, though I haven't seen any bad behavior from file watchers as a result (I assume most would do some form of debouncing). Either way, I think 4e9060ec1a44d6a635df9cf6347ab80c3f9d7f41 should take care of the issue, so let me know.

**Comment by marcelbeumer** [comment]
Yes https://github.com/jose-elias-alvarez/null-ls.nvim/commit/4e9060ec1a44d6a635df9cf6347ab80c3f9d7f41 fixes it, thanks a lot! 

Off topic:
I'm really excited about null-ls, I took some time to properly read through the docs and check some of the code yesterday, so cool it's now a same-process-in-mem lsp server (!), and especially with the helper API's, it unlocks thinking of LSP as something we can script into our workflows, instead of seeing it as these mysterious and complex servers you can hopefully configure to get them to work ;) I guess I just wanted to say, thanks for making nvim even better!

**Comment by jose-elias-alvarez** [comment]
Thank you for the kind words! One of my main goals was to make it simple for users to make their own integrations (I used diagnostic-languageserver for a while and still never figured it out) so I'm glad we are getting there.
