### ISSUE TITLE
Black only works on one buffer

### ISSUE THREAD

**Issue by PCesteban** [jose-elias-alvarez/null-ls.nvim#640]
### Discussed in https://github.com/jose-elias-alvarez/null-ls.nvim/discussions/638

<div type='discussions-op-text'>

<sup>Originally posted by **PCesteban** February  3, 2022</sup>
When I use black to format my python code only works on one buffer. If I open another file and I use black, it doesn't do anything, I have to quit neovim and go to the other file I want to format again to make it work. however with autopep8 and yapf the formatting works just fine. How can I make black work properly inside my neovim session? 

Update:
It seems that the problem is that the files aren't in the same directory, but why this doesn't happen with other formatters?</div>

### Debug trace:
```
[TRACE Thu Feb  3 17:45:11 2022] ...ocal/share/nvim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:118: received LSP request for method textDocument/formatting
[TRACE Thu Feb  3 17:45:11 2022] ...are/nvim/plugged/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_FORMATTING
[DEBUG Thu Feb  3 17:45:11 2022] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:335: spawning command [black] at /home/esteban-pc/ormuco-test with args { "--stdin-filename", "/home/esteban-pc/Documents/Money/Higia/Scripts/HIGIA_main.py", "--quiet", "--quiet", "-" }                                           
[TRACE Thu Feb  3 17:45:11 2022] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:224: error output: nil
[TRACE Thu Feb  3 17:45:11 2022] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:225: output: nil
```
The error appears when I open neovim, then open a file and format it using black and then go to another file in another folder and try to do the same, but nothing happens.

I don't know much about it but the reason may be that **in this specific case** black is tied to a folder but I want to run it in a file that is not in that folder (third line from debug trace):
```
spawning command [black] at /home/esteban-pc/ormuco-test with args { "--stdin-filename", "/home/esteban-pc/Documents/Money/Higia/Scripts/HIGIA_main.py", "--quiet", "--quiet", "-" }
```
the folder to which it is "tied" corresponds to the folder where the first file I open after logging in to neovim is located. If I try to format another file that is in the same folder, black works correctly. The same procedure was done with other formatters (yapf, autopep8) and both worked correctly in all cases.

### Versions
- Neovim = 0.6.1
- black = 22.1.0

### Language server
- pyright

### Null-ls config
```
require("null-ls").setup({                                                                                                                                          
      sources = {
          require("null-ls").builtins.formatting.black.with({ extra_args = { "--quiet" } })
          },
       on_attach = function(client)
          if client.resolved_capabilities.document_formatting then
             vim.cmd([[
             augroup LspFormatting
                autocmd! * <buffer>
                autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()
            augroup END
            ]])
         end
      end,
  })
```

**Comment by jose-elias-alvarez** [comment]
I was curious about this, so I put together a "project" with the following structure:

```lua
./
├── test1/
│  ├── .git/
│  └── sample.py
└── test2/
   ├── .git/
   └── sample.py
```

Starting from the root, I ran the following commands:

```
cd test1
cat ../test2/sample.py | black --stdin-filename ../test2/sample.py --quiet -
````

And received the following error:

```
Traceback (most recent call last):
  File "/Users/jose/.pyenv/versions/3.10.0/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/Users/jose/.pyenv/versions/3.10.0/lib/python3.10/site-packages/black/__init__.py", line 1373, in patched_main
    main()
  File "/Users/jose/.pyenv/versions/3.10.0/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jose/.pyenv/versions/3.10.0/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/jose/.pyenv/versions/3.10.0/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jose/.pyenv/versions/3.10.0/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jose/.pyenv/versions/3.10.0/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jose/.pyenv/versions/3.10.0/lib/python3.10/site-packages/black/__init__.py", line 456, in main
    sources = get_sources(
  File "/Users/jose/.pyenv/versions/3.10.0/lib/python3.10/site-packages/black/__init__.py", line 538, in get_sources
    normalized_path = normalize_path_maybe_ignore(p, root, report)
  File "/Users/jose/.pyenv/versions/3.10.0/lib/python3.10/site-packages/black/files.py", line 144, in normalize_path_maybe_ignore
    normalized_path = abspath.resolve().relative_to(root).as_posix()
  File "/Users/jose/.pyenv/versions/3.10.0/lib/python3.10/pathlib.py", line 816, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/Users/jose/test/test2/sample.py' is not in the subpath of '/Users/jose/test/test1' OR one path is relative and the other is absolute.
```

However, the following command works:

```
cat ../test2/sample.py | black --quiet -
```

Basically, it looks like when you use the `--stdin-filepath` option, `black` throws an error if the path isn't in the subpath of the current working directory. 

As I understand from the [PR that added `--stdin-filepath`](https://github.com/psf/black/pull/1780), the option may not be strictly necessary in every case. That means a simple solution would be to modify `args` to leave it out:

```lua
local black = null_ls.builtins.formatting.black.with({
    args = { "--quiet", "-" },
})
```

You could also use the [`cwd`](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#spawn-directory) option to always spawn `black` in the directory of the current buffer. 

Separately, the fact that null-ls completely discarded `stderr` in this case (without even logging it) made it harder than it should have been to track down the cause of the issue, so that's something I want to improve, too.

**Comment by PCesteban** [comment]
I see, thank you, it works perfectly now.

**Comment by ram02z** [comment]
I am currently having a similar issue with black. I have tried the proposed solution to no avail. Its strange because it has stopped working on a large file but works fine on a smaller file in the same directory. Running black directly from the terminal does format the file just fine,

**Comment by jose-elias-alvarez** [comment]
@ram02z Your description makes it sound like it could be due to a timeout. See [here](https://github.com/jose-elias-alvarez/null-ls.nvim#i-am-seeing-a-vimlspbufformatting_sync-timeout-error-message) for a potential solution. Otherwise, please open another issue.

**Comment by ram02z** [comment]
> @ram02z Your description makes it sound like it could be due to a timeout. See [here](https://github.com/jose-elias-alvarez/null-ls.nvim#i-am-seeing-a-vimlspbufformatting_sync-timeout-error-message) for a potential solution. Otherwise, please open another issue.

Timeout wasn't the solution sadly. Ill open an issue.
