### ISSUE TITLE
zsh diagnostics source

### ISSUE THREAD

**Issue by andrewferrier** [jose-elias-alvarez/null-ls.nvim#641]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I have a custom diagnostic source which basically uses `zsh -n $FILENAME` to syntax check a zsh file (the `-n` option parses the file, but does not execute it, which means it has the nice side-effect of syntax checking it - although it typically only finds the first syntax issue).

This is not a full zsh linter - AFAIK such a thing does not exist - but I use it as a substitute which is better than nothing.

Would you be interested in incorporating this as a builtin? If so, I can prep a pull req, similar to [my checkmake one](https://github.com/jose-elias-alvarez/null-ls.nvim/pull/636) recently.

### Help

Yes

### Implementation help

No help needed, just the go-ahead it would be worth merging!

**Comment by jose-elias-alvarez** [comment]
Sure, I think as long as we explain the caveats in the documentation, this could be useful.

**Comment by andrewferrier** [comment]
Pull request ready for this now: https://github.com/jose-elias-alvarez/null-ls.nvim/pull/653
