### ISSUE TITLE
Diagnostics source for trailing space

### ISSUE THREAD

**Issue by andrewferrier** [jose-elias-alvarez/null-ls.nvim#655]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I have created a custom diagnostics source which fires a warning on lines that have trailing space on them. There are obviously various ways to highlight this in Vim/NeoVim - some folks prefer the `list`/`listchars` option for example - but I like this to be integrated with the diagnostics option.

It's relatively simple, but is pure lua - I don't use any external tools. I've also built up a list of `disabled_filetypes` which I include because they already have linters available through `null-ls` which warn of this anyway - not sure whether I should/would include this in a default list of `disabled_filetypes` for the builtin.

Anyway, if you think this would be a valuable inclusion, I can prep a pull req.

### Help

Yes

### Implementation help

None, just approval it would be worthwhile!

**Comment by jose-elias-alvarez** [comment]
Sure, this sounds like a reasonable addition. I'd say we can enable it for all filetypes and leave customizations to the user, which is consistent with the current whitespace formatters.

**Comment by andrewferrier** [comment]
Got it, that makes more sense. I'll take a look at the gitsigns code action and steal some of the ideas from there.
