### ISSUE TITLE
View 'raw' output of the last run of a diagnostic source.

### ISSUE THREAD

**Issue by IndianBoy42** [jose-elias-alvarez/null-ls.nvim#661]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Sometimes I think it would be helpful to see the raw output of the command run as part of a diagnostic source. Probably by opening it in a new buffer/split/window.

### Help

Yes

### Implementation help

I think this should be fairly simple, just save the output from when a command is run, and then provide an api function/command to open a buffer with that output. First I want to gauge whether people consider that to be a desirable feature?

**Comment by jose-elias-alvarez** [comment]
It's currently possible to see the output in a log file by [enabling debug mode](https://github.com/jose-elias-alvarez/null-ls.nvim#how-do-i-enable-debug-mode-and-get-debug-output) or within Neovim by [configuring log settings](https://github.com/jose-elias-alvarez/null-ls.nvim#how-do-i-enable-debug-mode-and-get-debug-output). Does that solve this?

**Comment by IndianBoy42** [comment]
debug mode has a performance impact though right? It logs a lot more than just the command output and doesn't provide a clean way of getting just what I want (only the output of the last invocation of one source)

**Comment by jose-elias-alvarez** [comment]
It does have a performance impact, but is this something you would use regularly (beyond figuring out why something is not working)? What use case do you have in mind?

**Comment by jose-elias-alvarez** [comment]
It seems like a pretty niche use case. I don't think I'd want to support this "natively" with a specific command but am open to capturing and exposing the information.

**Comment by jose-elias-alvarez** [comment]
I implemented something similar to what (I think) you were looking for in 2e96fb682d2ba770e1a3d81259ce751b00786624. Combined with [the source API](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/SOURCES.md), you can now effectively query a given source's last output with a single command:

```
:lua print(vim.inspect(require("null-ls.sources").get("markdownlint")[1].generator.opts._last_output))
```

It should be easy to compose it into a command if that's still something you're interested in.
