### ISSUE TITLE
Improve behavior of :NullLsInfo

### ISSUE THREAD

**Issue by jose-elias-alvarez** [jose-elias-alvarez/null-ls.nvim#664]
### Discussed in https://github.com/jose-elias-alvarez/null-ls.nvim/discussions/663

<div type='discussions-op-text'>

<sup>Originally posted by **filipekiss** February  9, 2022</sup>
First of all, thank for all the hard work you put in this plugin. It really saves a lot of time when trying to configure non-LSP sources.

I was first setting up the plugin and I did a simple call to `require('null-ls').setup()` and things worked as expected (as in I got no errors).

I understand that, by default, NullLs doesn't attach to the buffers, which makes sense, but, at the same time, it renders the command a little bit useless.

So I was thinking that maybe the command `:NullLsInfo` could be improved in a way that, by default, if no sources are configured for the current buffer, it would detect the filetype and show me the available sources from the builtins.

That way, I can open a file for a language and run `:NullLsInfo` and I'll have a list of all available sources that I can use, making discoverability for builtins a lot better.

I haven't looked at the source code yet so I'm not sure how difficult it would be to implement something like this, but I think it would greatly improve the overall experience of using and configuring NullLs, especially for new comers.

Once again, thanks for all  your hard work and let me know if I can help in any way :)</div>

@filipekiss I converted this into an issue. Implementing this actually wouldn't be hard, but there are probably some edge cases I'm not seeing right now. I'll work on it when I have time (or anyone else who happens to see this and wants to work on it can pick it up).

**Comment by filipekiss** [comment]
Thanks for the quick reply! I'll take a look at the source later, see if I can come up with something. If you have any directions on where I should look, that might help.

I have just recently started writing lua, so there are a few quirks that I still don't get 😅

**Comment by jose-elias-alvarez** [comment]
Sure, you can see that [this line](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/info.lua#L65) is what prevents the window from showing when the buffer isn't attached. To implement this, you'd probably want to save it and conditionally render the info based on whether the buffer is attached (for example, active sources no longer makes sense).
