### ISSUE TITLE
support for django linting and formatting using djLint

### ISSUE THREAD

**Issue by shaeinst** [jose-elias-alvarez/null-ls.nvim#681]
### Issues

- [x] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

djLint is definitely good option to format django files. i am aware of djhtml but djLint is more smart than it 
github: https://github.com/Riverside-Healthcare/djLint

### Help

No

**Comment by ObserverOfTime** [comment]
Linting implemented in #752

**Comment by jose-elias-alvarez** [comment]
Closed by #752. Thanks @shaeinst and @ObserverOfTime for handling this!
