### ISSUE TITLE
Allow to merge a builtin's generator options instead of overriding them

### ISSUE THREAD

**Issue by 13k** [jose-elias-alvarez/null-ls.nvim#692]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

## Issue

Currently, if I setup a diagnostics source like this:

```lua
null_ls.builtins.diagnostics.some_builtin.with({
  filetypes = { "another_ft" },
  generator_opts = { ignore_stderr = true },
})
```

It will completely override the builtin's `generator_opts`. With the config above, it effectively creates an empty generator.

This happens because [user options completely override the builtin's options](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/3059dc761b27c4c836f88879c460cd7a989caa47/lua/null-ls/helpers/make_builtin.lua#L98) in `with()`.

## Proposed solution

To implement this, is it as simple as changing from `vim.tbl_extend` to `vim.tbl_deep_extend` in `with()`?

Looks like the behavior of `tbl_deep_extend()` is to merge map-like tables, and ONLY map-like tables. Lists are overridden, which is the current behavior. Behavior for scalar values is also the same.

It shouldn't break user configs, since if they are already passing a full set of `generator_opts` (or other map-like key for that matter), it would get merged anyway.

## Workaround

A dirty workaround is to do this:

```lua
local builtin = null_ls.builtins.diagnostics.some_builtin

local generator_opts = vim.tbl_deep_extend("force", builtin._opts, {
  ignore_stderr = true
})

builtin.with({
  filetypes = { "another_ft" },
  generator_opts = generator_opts,
})
```

Which is very bad (not because of the extra steps, but because `_opts` is obviously a private/internal key, which is transformed internally and could have invalid values for `make_builtin`. It just so happens that it doesn't).

### Help

Yes

**Comment by jose-elias-alvarez** [comment]
This is actually a deliberate decision–it used to be possible to arbitrarily override generator options, but since there was so much confusion about generators vs. built-ins, I wanted to clarify which options were valid to override (for example, `from_stderr` is probably not an option that a user should need to override, since that would essentially require a new source). I'm open to adding more options but am not sure that I would want to just merge any options.

**Comment by 13k** [comment]
That's fair enough.

How could I configure the generator to ignore stderr then? By adding a new `ignore_stderr` option to `with()` ?

**Comment by jose-elias-alvarez** [comment]
Yes, we'd have to add a new option. What's the use case you have in mind? If ignoring `stderr` is something you want to do, it may be best to change the built-in itself.

**Comment by 13k** [comment]
That's kinda complicated. I had a new issue drafted up but changed my mind, since it involves changing the behavior of error checking.

I'm using rubocop, which may or may not be started by [spring](https://github.com/rails/spring), depending on the project I'm working on. TLDR on how it works: it's a pre-loader that caches code and makes boot times faster (which is perfect for the linter use-case) and can "hijack" executables by writing binary shims that load `spring` first then runs the command.

The problem is that `spring` generates output to stderr, a harmless informative message saying it's starting the rubocop process, and can safely be ignored:

> Running via Spring preloader in process [PID]

So this instance is the case where the process is successful, but prints to stderr.

The current error checking logic will consider any output to stderr as error, regardless of the exit code. I know it's implemented around stderr output because (the majority of) linters exit with non-zero in case linting errors are found, but the zero exit code + stderr case is considered an error.

I could configure `spring` to be quiet, but it's a "global" config and I don't want to lose the message when I'm executing commands in the terminal directly. It also requires changing application code.

I could also configure `spring` to be quiet depending on an environment variable, then change my null-ls config to pass an env var to the generator, but also requires changing app code and, worse, adding an env var that has nothing to do with app logic.

So I opted for ignoring stderr, which has less impact on the projects I'm working on.

A second use case is when rubocop's configuration is outdated but is valid. rubocop will output to stderr, warning about new rules being available and not configured, but will execute successfully and exit with zero (if no linting errors were found). These messages can also be ignored.

So my first proposed change for that abandoned issue was that error checking should only consider `check_exit_code()`. But I'm sure some generators would break with this change and could not be possible to be implemented like this.

The second change I proposed was to refactor the whole error-checking logic and consolidate everything in a single point of failure function that receives a result triplet (exit_code, stdout, stderr) and returns an error message. If this message is `nil`, it's a success, otherwise it's an error. It would be called by the generator's handler, leaving `loop.spawn()` to only execute processes and capture their result triplet. A default implementation could be the same existing logic and generators could then override the error-checking function as an option. Then I could configure the rubocop generator to only check the exit code (if <= 1, it's always success).

**Comment by jose-elias-alvarez** [comment]
I see, it's a pretty complicated situation but I think I understand. I'm not opposed to improving error-checking in general, but as you noted it's likely to break things. For now, I think a simple PR to allow configuring `ignore_stderr` sounds like a good option.

**Comment by jose-elias-alvarez** [comment]
I'm cleaning out some old issues, and I think that the case you described is justifiable, so I added the option to override `ignore_stderr` in 52212d0f86e9a58f2c0d146881947eb01400b12d.
