### ISSUE TITLE
Formatting and moving buffers will replace them

### ISSUE THREAD

**Issue by tamago324** [jose-elias-alvarez/null-ls.nvim#7]
- `nvim --version`: NVIM v0.5.0-dev+1384-gf2906a466
- Operating system/version: Manjaro

**Describe the bug**

If I move to another buffer while it is being formatted, there is a problem with the buffer being replaced.

**To Reproduce**

```vim
set encoding=utf-8

filetype plugin indent on
if has('vim_starting')
  let s:pluin_manager_dir='~/.config/nvim/.plugged/vim-plug'
  execute 'set runtimepath+=' . s:pluin_manager_dir
endif
call plug#begin('~/.config/nvim/.plugged')
Plug 'neovim/nvim-lspconfig'
Plug 'nvim-lua/plenary.nvim'
Plug 'jose-elias-alvarez/null-ls.nvim'
call plug#end()

set nobackup
set nowritebackup
set noswapfile
set updatecount=0
set backspace=indent,eol,start
language messages en_US.utf8

lua << EOF

local null_ls = require'null-ls'

null_ls.setup {
  on_attach = function(client)
    vim.cmd([[autocmd BufWritePost <buffer> lua vim.lsp.buf.formatting()]])
  end,
  sources = {
    null_ls.builtins.formatting.stylua,
  }
}

EOF
```

1. `nvim -u minvimrc -i NONE`
2. `:e sample.lua`
5. `:new | wincmd w` (Create a buffer and move on to the previous buffer)
3. edit lua file
4. `:w | wincmd w` (hook `BufWritePost`)
5. The buffer created in 5 will be deleted and replaced with the buffer opened in 2.

**Expected behavior**

I hope the buffer will not be replaced.

**Screenshots**

https://user-images.githubusercontent.com/16581287/121055519-4944e200-c7f8-11eb-9578-c2103e0508c9.mp4

Thank you!

**Comment by tamago324** [comment]
It might be a problem with `vim.lsp.buf.formatting()` in Neovim's built-in lsp client, as I had the same problem with another language server (`kotlin_language_server`)...

**Comment by jose-elias-alvarez** [comment]
Wow, thanks for the video – very clear. I think it's another issue caused by `bufdo`, but I just pushed a commit that fixes your test case. Let me know if that takes care of the problem.

**Comment by tamago324** [comment]
Confirmed. It was working perfectly.
It's perfect!
Thank you!
