### ISSUE TITLE
Diagnostics source is not set correctly

### ISSUE THREAD

**Issue by stephan-hesselmann-by** [jose-elias-alvarez/null-ls.nvim#73]
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.6.0-dev

### Steps to reproduce

Use builtin diagnostics
```
    require("null-ls").config({ sources = {builtins.diagnostics.hadolint} })
```

### Expected behavior

The diagnostics source is displayed as `hadolint` (defaults to generator command).

### Actual behavior

The diagnostics source is displayed as `null-ls`.

### Debug log

see explanation below

### Help

Yes

### Implementation help

The problem is that `index` in https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/diagnostics.lua#L22 refers to generators that are added to `params` (after matching filetype), however when the function is called`index` refers to all generators (not matched by filetype) https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/generators.lua#L37. This then leads to `generators` being `nil`, and the code defaults to `null-ls` rather than taking the command configured in the generator.

Possible fixes would be to
1. pass the relevant `generator` directly to `postprocess` instead of relying on an index, or
2. pass the correct index for the table of filetype matched generators, or
3. select from all generators in https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/diagnostics.lua#L22.

I would prefer option 1. because I find the index passing a bit convoluted and I don't see any reason for it. But I also haven't looked at much of the rest of the code, so maybe there's a reason.

**Comment by jose-elias-alvarez** [comment]
Thanks for catching this and for investigating! This should be fixed by 6141eefe5a17c6f070046f16d98b86b20da896a3. You're right that passing the index is a little more complicated than necessary for this case, but I plan on using `params.generators` for a couple of pending features, so I thought it would make sense to re-use it here (though I might change it in the future).

**Comment by stephan-hesselmann-by** [comment]
Thanks for the fix. Can confirm that it works with master

**Comment by stephan-hesselmann-by** [comment]
@jose-elias-alvarez There is another issue with the index when there are multiple linters for one filetype. In this case the index that is passed now always points to the last generator, because the increment is executed before the future. Should I create a separate issue for that?

**Comment by jose-elias-alvarez** [comment]
Whoops! I took your first suggestion and simply passed the generator directly to `postprocess` in 2ad9c76ca161d2c4da70f15fcdd9d58bc31663eb, which (I think!) should take care of this, and I added a test to check the sources of multiple diagnostics so we can catch this in the future.

**Comment by stephan-hesselmann-by** [comment]
Yes that seems to do the trick. Thanks!
