### ISSUE TITLE
Add luacheck

### ISSUE THREAD

**Issue by ChristianChiarulli** [jose-elias-alvarez/null-ls.nvim#74]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Add luacheck as a linter

### Help

No

### Implementation help

If I find some time I will add this, but if someone wants to beat me to it, I would appreciate it.

**Comment by vuki656** [comment]
On the off note, isn't luacheck pretty much dead? The last commit was in 2018.

**Comment by abzcoding** [comment]
> On the off note, isn't luacheck pretty much dead? The last commit was in 2018.

yeah people use `selene` nowadays but it is a good linter in its own right :sweat_smile:

**Comment by vuki656** [comment]
Oh cool, will look into adding it to null-ls.

**Comment by abzcoding** [comment]
> Oh cool, will look into adding it to null-ls.

it is already supported by null-ls :cold_sweat:

**Comment by vuki656** [comment]
True, but nothing in the BUILTINS.md, so I guess I should add that instead :smile:

**Comment by jose-elias-alvarez** [comment]
Good point – the `selene` built-in was part of a much larger commit, so we overlooked it.
