### ISSUE TITLE
Add ability to use basename when `to_temp_file` option used.

### ISSUE THREAD

**Issue by arslanmaj** [jose-elias-alvarez/null-ls.nvim#757]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I have come across an issue integrating in 'mlint' into null-ls that may require some changes to core null-ls. 

mlint is a linter for Matlab files and it does not accept stdin inputs. Instead, it needs to use the `to_temp_file` generator factory option.

mlint can be run using the command `mlint $FILENAME`. Part of what the linter does is validate the filename. When `to_temp_file` is used, `params.temp_file` is of the form `/tmp/null-ls_xxxxxx.m` and this form is unacceptable to the linter for multiple reasons. First, it contains a hyphen in the name - an invalid character to the linter. Additionally, if the file contained a class or function, then the linter would expected that $FILENAME matches the class or function name. 

The easiest way that `to_temp_file` can work for mlint would be to have the temp file's basename match that of the file being linted. 

For example, if "/home/foo/hello.m" is the file I am working on, then `mlint /tmp/hello.m` would be the best temporary filename.

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I am not sure of what the best way to implement this feature would be. However, I would be happy to help if I could receive some guidance. First thing I am unsure of - is it even alright to use the file's basename when creating the temp_file? Second, it would be best to get some more detailed implementation guidance on this issue.

**Comment by arslanmaj** [comment]
Ok I found out another idea that might be a lot easier. 

Is it possible to include a config file as part of the linter command and then to also include a default config file to help spawn the command?

i.e. 
`mlint -confg null-ls-config.txt`

where null-ls-config.txt is a config file that ignores file-name resulting errors and sits somewhere in the null-ls ecosystem?

**Comment by jose-elias-alvarez** [comment]
Hm, that option is definitely a lot easier but is also something we don't currently do. We could use `stdpath("data")` to create and store a config file and add its path to the built-in's default arguments. 

My concern would then be for users who want to override the argument and point to a config file of their own. Does `mlint` have any support for passing config arguments inline so we can tell it to ignore the rule without a dedicated config file?

**Comment by arslanmaj** [comment]
mlint does not have support for inline config args :(

Unfortunately, even with a config file, (I tried this out today) bad filenames sent to mlint (i.e. /tmp/null-ls-xxxxxx.m) cannot be checked. The linter does not support bypassing that particular error. 

The only two options I see:

1. Use DIAGNOSTICS_ON_SAVE which does not replace $FILENAME with temp_file.

OR: 

2. If we are allowed the ability to pass in 'unusable temp_filename chars' to the null-ls generator options and then have null-ls create temp file-names so that they don't contain the 'unusable temp_filename chars', then mlint can be easily hooked up to null-ls. 

I.e. if null-ls is given 'unusuable temp_filename chars' = { '-', '@' }, then 
 "/tmp/null-ls-x@bceF" would be replaced with "/tmp/null_ls-x_bceF"

Option 1 is easiest to integrate. Option 2 would be a lot of changes.

**Comment by jose-elias-alvarez** [comment]
Option 1 is probably okay for now, since we already have a few linters that for various reasons can only run on save. Option 2 would require us to handle temp file creation on our own, in which case we could think of ways for linters to define a pattern. Definitely not opposed to it, and I don't think it should be a huge change.

**Comment by arslanmaj** [comment]
Added mlint pull request as result of this with DIAGNOSTICS_ON_SAVE option
