### ISSUE TITLE
Overriding resolved capabilities will not work as a way to disable formatting after I merge a PR

### ISSUE THREAD

**Issue by mjlbach** [jose-elias-alvarez/null-ls.nvim#778]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

See: https://github.com/neovim/neovim/pull/17814

I am going to remove `resolved_capabilities` in favor of using the original server capabilities. Just a heads up.

### Help

No

**Comment by jose-elias-alvarez** [comment]
Really appreciate the heads-up! I'll subscribe to the PR and see what we need to do to adapt. Out of curiosity, will there be a new recommended approach for users to handle multiple servers with formatting capabilities?

**Comment by mjlbach** [comment]
You would use the new nested keys (resolved_capabilities.documentFormattingProvider or server_capabilities.documentFormattingProvider depending on what I do), although as I mentioned in https://github.com/jose-elias-alvarez/null-ls.nvim/pull/703 I don't think the appropriate solution is to disable this at the buf_request level (by disabling capabilities), an interface we're considering dropping anyways.

**Comment by axieax** [comment]
Hi, I'm currently using `client.request_sync("textDocument/formatting", params, nil, bufnr)` for formatting through an autocmd. This works for LSP formatting but not for `null-ls` for some reason. Previously I was using `vim.lsp.buf.formatting_sync` and manually disabling certain client formatting using `resolved_capabilities`. However, after migrating to `server_capabilities`, it seems that `client.server_capabilities.documentFormattingProvider = false` cannot "disable" formatting anymore for a specific client anymore, resulting in `vim.lsp.buf.formatting_sync` displaying a menu to select from multiple sources for formatting.

**Comment by mjlbach** [comment]
1. I highly recommend people don't do `client.server_capabilities.documentFormattingProvider = false`, `null-ls` should expose an API that requests only null-ls formatting, or you can write the request yourself
2. I haven't merged the PR that would make this disable formatting, if you look at the PR linked in the issue

**Comment by axieax** [comment]
Ahh I see thanks for getting back to me! I just realised `resolved_capabilities` works atm so I'll just stick with that for now and keep posted for future changes :))

**Comment by mjlbach** [comment]
Thinking about solving this a different way.

https://github.com/neovim/neovim/pull/18193/files

**Comment by jose-elias-alvarez** [comment]
Now that the PR was merged and I fixed a couple of issues in b66946a792f40822fe540a79e98764cb5922eedf, I think this is all set. Thanks again for the heads-up on this!

**Comment by bmulholland** [comment]
When this sort of coordination happens, it affects no one and so it can go unappreciated. I know it takes real effort and thought, though, so I want to thank both of you @mjlbach and @jose-elias-alvarez for coordinating to keep everything working smoothly. Much appreciated!
