### ISSUE TITLE
Could you please adjust the formatting indent value to match the "indent" require by neovim's folding ?

### ISSUE THREAD

**Issue by FireSK7** [jose-elias-alvarez/null-ls.nvim#779]
### Issues

- [x] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I just want to fold my code using "za" with null-ls's formatting mechanism.  And I find that  [it can't behave well  ](https://ibb.co/QcbRFwP) until I use the neovim's formatting way, “gg V G =” ( you know that ), to format the code then I was able to [fold the code by indent.](https://ibb.co/7kQ0r6X) I wonder if you can provide some solution about this?

**Comment by FireSK7** [comment]
I have solved the problem by adjusting the "tab" length.

**Comment by jose-elias-alvarez** [comment]
If I understand, the issue is that the formatter is changing the indentation, right? You'll need to configure the formatter's arguments to make sure it's using the indentation value you want, though it sounds like you've figured it out already.
