### ISSUE TITLE
How to enable ansible-lint?

### ISSUE THREAD

**Issue by briandipalma** [jose-elias-alvarez/null-ls.nvim#781]
I have installed and enabled ansible-lint yet I don't see the errors it complains about when I run it on the CLI:

https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#ansiblelint

I'm guessing it's a filetype issue, does `Filetypes: { "yaml.ansible" }` mean I have to do something special with the files to get them checked?

**Comment by jose-elias-alvarez** [comment]
I think you're right, we don't have support for "dotted" filetypes at the generator level. I was able to get it working with this diff, but let me know if this makes sense @IamTheFij:

```diff
diff --git a/lua/null-ls/builtins/diagnostics/ansiblelint.lua b/lua/null-ls/builtins/diagnostics/ansiblelint.lua
index d51f338..d961b9a 100644
--- a/lua/null-ls/builtins/diagnostics/ansiblelint.lua
+++ b/lua/null-ls/builtins/diagnostics/ansiblelint.lua
@@ -10,7 +10,7 @@ return h.make_builtin({
         description = "Linter for Ansible playbooks, roles and collections.",
     },
     method = DIAGNOSTICS,
-    filetypes = { "yaml.ansible" },
+    filetypes = { "yaml", "ansible" },
     generator_opts = {
         command = "ansible-lint",
         to_stdin = true,
@@ -42,7 +42,7 @@ return h.make_builtin({
                     col = col,
                     message = message.check_name,
                     severity = severities[message.severity],
-                    filename = message.location.path,
+                    filename = require("null-ls.utils").path.join(params.root, message.location.path),
                 })
             end
             return params.messages
```

**Comment by IamTheFij** [comment]
So, there should be nothing special about a filetype with a dot in it, such as `yaml.ansible`. The filetype I used, `yaml.ansible`, is the one set by [this Ansible plugin](https://github.com/pearofducks/ansible-vim) which offers some filetype detection for Ansible files. This, to me, seemed preferable to enabling for `yaml`, because there are a _lot_ of places folks edit YAML files and this linter spits out a bunch of errors in those cases.

**Comment by briandipalma** [comment]
OK, so when I set the filetype to `yaml.ansible` with `:set ft=yaml.ansible` and make an edit to the file it seems to work as I expect. Sorry I didn't understand what the documentation meant, thanks for the help.

**Comment by jose-elias-alvarez** [comment]
@IamTheFij Thanks for the quick feedback!
