### ISSUE TITLE
Clang-format not accepting style options

### ISSUE THREAD

**Issue by kylechui** [jose-elias-alvarez/null-ls.nvim#782]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+1328-gfb5587d2b

### Operating System

Xubuntu 20.04 LTS

### Minimal config

```lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir
if on_windows then
    temp_dir = vim.loop.os_getenv("TEMP")
else
    temp_dir = "/tmp"
end

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = {},
        debug = true,
    })
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "jose-elias-alvarez/null-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end

-- ADDITIONAL CONFIGURATION BELOW
local nl = require("null-ls")
nl.setup({
    sources = {
        nl.builtins.formatting.clang_format.with({
            extra_args = { "--style='{IndentWidth: 4}'" }
        });
    }
})
```

### Steps to reproduce

1. `nvim --clean -u minimal_init.lua`
2. `:e test.cpp` (provided below)
3. `:lua vim.lsp.buf.formatting()`
```cpp
// test.cpp
#include <bits/stdc++.h>
using namespace std;

int main() {
	
    int N;
        cin >> N;
                vector<int> arr(N);

for (size_t i = 0; i < N; i++) {

                cin >> arr[i];
}
}
```

### Expected behavior

The code should be formatted with an indent size of 4.

### Actual behavior

The code is not formatted at all.

### Debug log

```
[WARN  Sat 26 Mar 2022 08:14:53 AM PDT] .../packer/start/null-ls.nvim/lua/null-ls/builtins/init.lua:17: failed to load builtin clangd for method formatting; please check your config
```

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
Your minimal config isn't working because you are setting up null-ls twice, once inside `null_ls_config()` and then again at the bottom. If I move your config into `null_ls_config()` and enable debug mode, I see the following error output:

```
[TRACE Mon Mar 28 18:26:02 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:217: error output: Invalid value for -style
```

I think that's probably a good place to start debugging, but this doesn't seem like an issue on our end. I tried changing the extra arguments to this and it seems to be working:

```lu

**Comment by kylechui** [comment]
Ah that works perfectly, thanks so much for your help! I wasn't entirely sure how to mimic the `extra_args` from the documentation files, and thought copying the arguments exactly as a string would suffice. TIL that the `=` just becomes a split between two elements in the table! Thanks again and I'll be closing this thread
