### ISSUE TITLE
Hadolint Doesn't Update On Insert

### ISSUE THREAD

**Issue by barrett-ruth** [jose-elias-alvarez/null-ls.nvim#785]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+1275-g00effff56 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Operating System

arch

### Minimal config
```lua
local function join_paths(...)
    local path_sep = '/'
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local null_ls_config = function()
    local null_ls = require 'null-ls'
    -- add only what you need to reproduce your issue
    null_ls.setup {
        sources = { null_ls.builtins.diagnostics.hadolint },
        debug = true,
update_in_insert = true
    }
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require('packer').startup {
        {
            'wbthomason/packer.nvim',
            {
                'jose-elias-alvarez/null-ls.nvim',
                requires = { 'nvim-lua/plenary.nvim' },
                config = null_ls_config,
            },
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    }
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
    load_plugins()
    require('packer').sync()
else
    load_plugins()
    require('packer').sync()
end
```

### Steps to reproduce

Firstly, I'm not sure if this is a null-ls problem or hadolint problem.

`nvim --clean -u minimal_unit.lua <Dockerfile>`

Dockerfile can be any Dockerfile with any sort of error (e.g. complete jibberish) - fixing such error with `update_in_insert` set on still does nothing.

The file correctly displays the new errors only after saving and re-reading the file ((e.g. have to `:w | :e`))

### Expected behavior

Dockerfile lints updates on live changes as you type

### Actual behavior

It only updates on save and re-reading

### Debug log

[TRACE Sun 27 Mar 2022 01:31:39 PM CDT] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:92: starting null-ls client
[TRACE Sun 27 Mar 2022 01:31:39 PM CDT] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:118: received LSP request for method initialize
[DEBUG Sun 27 Mar 2022 01:31:39 PM CDT] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:147: unable to notify client for method textDocument/didOpen (client not active): {
  textDocument = {
    uri = "file:///home/bruth/.config/nvim/Dockerfile"
  }
}
[TRACE Sun 27 Mar 2022 01:31:39 PM CDT] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method initialized
[TRACE Sun 27 Mar 2022 01:31:39 PM CDT] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method textDocument/didOpen
[TRACE Sun 27 Mar 2022 01:31:39 PM CDT] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Sun 27 Mar 2022 01:31:39 PM CDT] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:344: spawning command "hadolint" at /home/bruth/.config/nvim with args { "--no-fail", "--format=json", "/home/bruth/.config/nvim/Dockerfile" }
[TRACE Sun 27 Mar 2022 01:31:39 PM CDT] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:217: error output: nil
[TRACE Sun 27 Mar 2022 01:31:39 PM CDT] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:218: output: [{"code":"DL1000","column":1,"file":"/home/bruth/.config/nvim/Dockerfile","level":"error","line":4,"message":"unexpected 'a'\nexpecting '#', '\\', ADD, ARG, CMD, COPY, ENTRYPOINT, ENV, EXPOSE, FROM, HEALTHCHECK, LABEL, MAINTAINER, ONBUILD, RUN, SHELL, STOPSIGNAL, USER, VOLUME, WORKDIR, a pragma, at least one space, or end of input"}]
[TRACE Sun 27 Mar 2022 01:31:39 PM CDT] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:162: received diagnostics from source 1
[TRACE Sun 27 Mar 2022 01:31:39 PM CDT] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:163: { {
    code = "DL1000",
    col = 0,
    end_col = 0,
    end_lnum = 4,
    lnum = 3,
    message = "unexpected 'a'\nexpecting '#', '\\', ADD, ARG, CMD, COPY, ENTRYPOINT, ENV, EXPOSE, FROM, HEALTHCHECK, LABEL, MAINTAINER, ONBUILD, RUN, SHELL, STOPSIGNAL, USER, VOLUME, WORKDIR, a pragma, at least one space, or end of input",
    row = 4,
    severity = 1,
    source = "hadolint"
  } }
[TRACE Sun 27 Mar 2022 01:32:30 PM CDT] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:118: received LSP request for method shutdown
[TRACE Sun 27 Mar 2022 01:32:30 PM CDT] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method exit
[TRACE Sun 27 Mar 2022 01:32:33 PM CDT] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:92: starting null-ls client
[TRACE Sun 27 Mar 2022 01:32:33 PM CDT] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:118: received LSP request for method initialize
[DEBUG Sun 27 Mar 2022 01:32:33 PM CDT] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:147: unable to notify client for method textDocument/didOpen (client not active): {
  textDocument = {
    uri = "file:///home/bruth/.config/nvim/Dockerfile"
  }
}
[TRACE Sun 27 Mar 2022 01:32:33 PM CDT] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method initialized
[TRACE Sun 27 Mar 2022 01:32:33 PM CDT] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method textDocument/didOpen
[TRACE Sun 27 Mar 2022 01:32:33 PM CDT] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Sun 27 Mar 2022 01:32:33 PM CDT] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:344: spawning command "hadolint" at /home/bruth/.config/nvim with args { "--no-fail", "--format=json", "/home/bruth/.config/nvim/Dockerfile" }
[TRACE Sun 27 Mar 2022 01:32:33 PM CDT] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:217: error output: nil
[TRACE Sun 27 Mar 2022 01:32:33 PM CDT] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:218: output: [{"code":"DL1000","column":1,"file":"/home/bruth/.config/nvim/Dockerfile","level":"error","line":4,"message":"unexpected 'a'\nexpecting '#', '\\', ADD, ARG, CMD, COPY, ENTRYPOINT, ENV, EXPOSE, FROM, HEALTHCHECK, LABEL, MAINTAINER, ONBUILD, RUN, SHELL, STOPSIGNAL, USER, VOLUME, WORKDIR, a pragma, at least one space, or end of input"}]
[TRACE Sun 27 Mar 2022 01:32:33 PM CDT] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:162: received diagnostics from source 1
[TRACE Sun 27 Mar 2022 01:32:33 PM CDT] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:163: { {
    code = "DL1000",
    col = 0,
    end_col = 0,
    end_lnum = 4,
    lnum = 3,
    message = "unexpected 'a'\nexpecting '#', '\\', ADD, ARG, CMD, COPY, ENTRYPOINT, ENV, EXPOSE, FROM, HEALTHCHECK, LABEL, MAINTAINER, ONBUILD, RUN, SHELL, STOPSIGNAL, USER, VOLUME, WORKDIR, a pragma, at least one space, or end of input",
    row = 4,
    severity = 1,
    source = "hadolint"
  } }

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
Yep, looks like the linter was misconfigured and wasn't using `stdin`. e90dc2f9b7d3e1beb7222aacb5895d08f29ad3c4 should take care of the issue, so could you try updating the plugin and let me know?

**Comment by barrett-ruth** [comment]
Awesome! Thanks for the response and amazing plugin that (for me) blows EFM out of the water.
