### ISSUE TITLE
Understanding `should_attach`

### ISSUE THREAD

**Issue by barrett-ruth** [jose-elias-alvarez/null-ls.nvim#791]
Let's say I want to disable null-ls eslint_d source from running if there is no .eslintrc file.
I think this is something within reason to request - opening a miscellaneous script shouldn't have to be met with an error.

How could I do this leveraging `should_attach` or another null-ls feature?

**Comment by jose-elias-alvarez** [comment]
For cases like this, you'll want to use [a condition](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md#conditional-sources). There are a few helpers to handle common cases like checking for the presence of a file at the project's root, but you can use whatever method you want to determine whether a source should be active or not.
