### ISSUE TITLE
Add npm-groovy-lint as a builtin

### ISSUE THREAD

**Issue by sseneca** [jose-elias-alvarez/null-ls.nvim#801]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

https://github.com/nvuillam/npm-groovy-lint

It would be nice to have this configured through null-ls while editing Groovy files. It lints and at a glance it looks like it can also be a formatter.

There is a VS Code plugin that wraps around it: https://marketplace.visualstudio.com/items?itemName=NicolasVuillamy.vscode-groovy-lint

### Help

No

**Comment by vladdoster** [comment]
My [PR](https://github.com/jose-elias-alvarez/null-ls.nvim/commit/5b745e5fa2a18a2c0df8966080f4321fad4f42d7
) adding npm-groovy-lint has been merged. 

My Jenkinsfiles and shared-lib are so pretty now :^).

**Comment by jose-elias-alvarez** [comment]
Thanks for the callout @vladdoster, closing this.

**Comment by BonaBeavis** [comment]
Maybe this should be opened again: npm-groovy-lint, also gives diagnostics, which null-ls could use.

**Comment by jose-elias-alvarez** [comment]
@BonaBeavis Can you open a separate issue to track this?
