### ISSUE TITLE
Eslint_d does not stop after close nvim

### ISSUE THREAD

**Issue by expoure** [jose-elias-alvarez/null-ls.nvim#802]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.6

### Operating System

Linux

### Minimal config

Any config should be able to reproduce this issue

### Steps to reproduce

1- Set linter to eslint_d
2- open a javascript based file
3- close nvim
4- open htop or another system monitor and search for eslint 

### Expected behavior

Eslint should stop after exit nvim

### Actual behavior

Eslint does not stop after exit nvim

### Debug log

No log

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

This problem seems to be related... after closing lvim (it also happens in nvim using the null-ls plugin) eslint_d keeps running on the system

https://user-images.githubusercontent.com/12136268/162046300-982a0d80-f03f-49c3-aa36-6565d6f9a57f.mp4

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
This is how `eslint_d` works and is not related specifically to null-ls. If you want to stop it, you can run `eslint_d` stop from the command line, though I think it's pretty pointless since it hardly uses any resources. I'll add a note of this to the documentation, since this isn't the first time the question has come up.

**Comment by expoure** [comment]
Here eslint_d keep using around 1GB of ram... but i can make a script to resolve it. Thanks!
