### ISSUE TITLE
no generators availabe, module 'gitsigns' not found

### ISSUE THREAD

**Issue by juniway** [jose-elias-alvarez/null-ls.nvim#813]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+954-g530c65b17

### Operating System

macOS 12.3 Monterey, Ubuntu 21.04

### Minimal config

```
curl -fLO https://raw.githubusercontent.com/jose-elias-alvarez/null-ls.nvim/main/scripts/minimal_init.lua
```

with this simple addition:

```
local null_ls_config = function()
	local null_ls = require("null-ls")
	-- add only what you need to reproduce your issue
	null_ls.setup({
		sources = {
			null_ls.builtins.code_actions.gitsigns,
		},
		debug = true,
	})
end
```

### Steps to reproduce

open a go file or maybe any other file with a recognizable filetype in nvim with this command:

```
nvim --clean -u minimal_init.lua main.go
```

#### Explain
I have `go` in system and lang server `gopls` installed, so I open a `main.go` with `minimal_init.lua` config like above.

Move the cursor to any line in main.go, and type `:lua vim.buf.lsp.code_action()`, it shows `No code actions available`

### Expected behavior

Should display correct `code_actions`, e.g.

``
Code actions:
1: Blame line
```



### Actual behavior

it shows `No code actions available`

### Debug log


```
...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:24: no generators available
.../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:118: received LSP request for method textDocument/codeAction
...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_CODE_ACTION
...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:78: failed to run generator: ...l-ls.nvim/lua/null-ls/builtins/code_actions/gitsigns.lua:16: module 'gitsigns' not found:
        no field package.preload['gitsigns']
        no file './gitsigns.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/gitsigns.lua'
        no file '/usr/local/share/lua/5.1/gitsigns.lua'
        no file '/usr/local/share/lua/5.1/gitsigns/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/gitsigns.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/gitsigns/init.lua'
...
```


### Help

No

### Implementation help

_No response_

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
You need to install [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim) for the built-in to work.

**Comment by juniway** [comment]
@jose-elias-alvarez 
1. Maybe there some confusion about the meaning of `builtin`, I thought `builtin` is by its name builtin, and I didn't find related docs about this. 

3. I installed `gitsigns.nvim`, but it still doesn't work

```
local function load_plugins()
  require("packer").startup({
  ...
  function(use)
  use({
      "jose-elias-alvarez/null-ls.nvim",
      requires = { "nvim-lua/plenary.nvim", "lewis6991/gitsigns.nvim" },
      config = null_ls_config,
  })
  ...
  end,
})
```

**Comment by fgheng** [comment]
> @jose-elias-alvarez
> 
> 1. Maybe there some confusion about the meaning of `builtin`, I thought `builtin` is by its name builtin, and I didn't find related docs about this.
> 2. I installed `gitsigns.nvim`, but it still doesn't work
> 
> ```
> local function load_plugins()
>   require("packer").startup({
>   ...
>   function(use)
>   use({
>       "jose-elias-alvarez/null-ls.nvim",
>       requires = { "nvim-lua/plenary.nvim", "lewis6991/gitsigns.nvim" },
>       config = null_ls_config,
>   })
>   ...
>   end,
> })
> ```

I had the same problem.

I use lazy.nvim as plugin manager and I write gitsings.nvim in null-ls dependencies the problem is also occurred

**Comment by jose-elias-alvarez** [comment]
@fgheng null-ls does absolutely nothing special here - it just requires `gitsigns` when the user has registered the code action source and requests code actions. Does this command run in Neovim without erroring?

```vim
:lua print(vim.inspect(require("gitsigns")))
```

If not, then the issue is with your plugin manager's setup.
