### ISSUE TITLE
minimal_init.lua doesn't work for lsp

### ISSUE THREAD

**Issue by juniway** [jose-elias-alvarez/null-ls.nvim#814]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+954-g530c65b17

### Operating System

macOS 12.3 Monterey, Ubuntu 21.04

### Minimal config

```
curl -fLO https://raw.githubusercontent.com/jose-elias-alvarez/null-ls.nvim/main/scripts/minimal_init.lua
```

with below simple addition:
```
local on_attach = function(client, bufnr)
	local function buf_set_keymap(...)
		vim.api.nvim_buf_set_keymap(bufnr, ...)
	end
	local function buf_set_option(...)
		vim.api.nvim_buf_set_option(bufnr, ...)
	end

	buf_set_option("omnifunc", "v:lua.vim.lsp.omnifunc")

	local opts = { noremap = true, silent = true }
	buf_set_keymap("n", "gD", "<Cmd>lua vim.lsp.buf.declaration()<CR>", opts)
	buf_set_keymap("n", "gd", "<Cmd>lua vim.lsp.buf.definition()<CR>", opts)
	buf_set_keymap("n", "K", "<Cmd>lua vim.lsp.buf.hover()<CR>", opts)
end

local lspconfig_config = function()
	local lspconfig = require("lspconfig")
	lspconfig.gopls.setup({
		on_attach = on_attach,
	})
end

local function load_plugins()
	-- only add other plugins if they are necessary to reproduce the issue
	require("packer").startup({
		{
			{ "wbthomason/packer.nvim" },
			{
				"jose-elias-alvarez/null-ls.nvim",
				requires = { "nvim-lua/plenary.nvim" },
				config = null_ls_config,
			},
			{
				"neovim/nvim-lspconfig",
				config = lspconfig_config,
			},
		},
		config = {
			package_root = package_root,
			compile_path = compile_path,
		},
	})
end
```

also, I have Go in my environment and `gopls` already installed in `/usr/lcoal/bin/gopls`, `:LspInfo` also displays the correct lsp server info.

### Steps to reproduce

open `main.go` (or any other recognized filetypes) with `minimal_init.lua`

```
nvim --clean -u minimal_init.lua main.go
```

### Expected behavior

key maps should work, basically, everything in the `on_attach` callback should work.

### Actual behavior

none of things in `on_attach` works

### Debug log

```
...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:92: starting null-ls client
.../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:118: received LSP request for method initialize
...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:147: unable to notify client for method textDocument/didOpen (client not active): {
  textDocument = {
    uri = "file:///Users/juniway/dev/go/coredns/coredns.go"
  }
}
...
```

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
I think there may be some confusion here - null-ls is not an LSP plugin, and getting the minimal init file to work with anything other than null-ls is not a goal. If you're trying to debug issues related to nvim-lspconfig, you can try using [their minimal init](https://raw.githubusercontent.com/neovim/nvim-lspconfig/master/test/minimal_init.lua).
