### ISSUE TITLE
sqlfluff now require a mandantory flags "--dialect"

### ISSUE THREAD

**Issue by milanglacier** [jose-elias-alvarez/null-ls.nvim#815]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.7.0

### Operating System

macOS

### Minimal config

It is the problem of sqlfluff.
Now sqlfluff requires '--dialect` as mandantory.

```
            null_ls.builtins.formatting.sqlfluff.with {
                args = { 'fix', '--dialect', 'mysql', '--disable_progress_bar', '-f', '-n', '-' },
            },
            null_ls.builtins.diagnostics.sqlfluff.with {
                args = { 'lint', '--dialect', 'mysql', '-f', 'github-annotation', '-n', '--disable_progress_bar', '-' },
            },

```

This default config will raise a error, and now my config will work.

### Steps to reproduce

No need.

### Expected behavior

No need.

### Actual behavior

The `sqlfluff` is worked now. But it is still a buggy plugin. sometimes the formatter will fail (i.e cannot format the file), sometime it will give surprisingly diagnostics like

```
L:  12 | P:  30 | L003 | Expected 7 indentations, found 7 [compared to line 09]
L:  13 | P:  30 | L003 | Expected 7 indentations, found 7 [compared to line 09]
L:  14 | P:  30 | L003 | Expected 7 indentations, found 7 [compared to line 09]
L:  15 | P:  30 | L003 | Expected 7 indentations, found 7 [compared to line 09]
L:  16 | P:  30 | L003 | Expected 7 indentations, found 7 [compared to line 09]
L:  17 | P:  30 | L003 | Expected 7 indentations, found 7 [compared to line 09]
```
What do you mean by that? Expected 7 indentations and I have 7. Why do  you give me a warning/error?

(it is not the problem of null-ls, I just want to remind users who want to give sqlfluff a try what the user experience is).

### Debug log

no need

### Help

Yes

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by syphar** [comment]
IMO null-ls cannot magically figure out the dialect, 

so this should just be part of the documentation: 

https://github.com/jose-elias-alvarez/null-ls.nvim/pull/816

**Comment by jose-elias-alvarez** [comment]
I think #816 closes this, since it should now be clear in the documentation that this argument is needed.
