### ISSUE TITLE
Adding $FILEEXT var

### ISSUE THREAD

**Issue by vanhtuan0409** [jose-elias-alvarez/null-ls.nvim#83]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Adding $FILEEXT var which will be interpolated into file extensions (eg `json` when filename is `foo.json`)
This will help with formatters which require type hint like `deno fmt --ext`

### Help

No

**Comment by jose-elias-alvarez** [comment]
I'm also seeing more sources that use the file extension, and it's an easy change, so I'll add this soon.

**Comment by jose-elias-alvarez** [comment]
Closed in 8517ae37f3b4aba29285d020d7425289731e9321.
