### ISSUE TITLE
gitsigns codeaction broken on nightly

### ISSUE THREAD

**Issue by rebelot** [jose-elias-alvarez/null-ls.nvim#839]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.8.0-dev+91-g0344736aa

### Operating System

Mac OS 12.2.1

### Minimal config

```lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir
if on_windows then
    temp_dir = vim.loop.os_getenv("TEMP")
else
    temp_dir = "/tmp"
end

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = { null_ls.builtins.code_actions.gitsigns },
        debug = true,
    })
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "jose-elias-alvarez/null-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },
            "lewis6991/gitsigns.nvim",
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end
```

### Steps to reproduce

run gitsigns-provided code action in any versioned file

### Expected behavior

gitsigns code action is executed

### Actual behavior

The following error is thrown after selecting the code action
```
Error executing vim.schedule lua callback: vim/shared.lua:0: attempt to index a boolean value
stack traceback:
        vim/shared.lua: in function 'tbl_get'
        ...zi/usr/src/neovim/share/nvim/runtime/lua/vim/lsp/buf.lua:650: in function 'on_choice'
        ...aurenzi/usr/src/neovim/share/nvim/runtime/lua/vim/ui.lua:54: in function 'select'
        ...zi/usr/src/neovim/share/nvim/runtime/lua/vim/lsp/buf.lua:671: in function 'on_code_action_results'
        ...zi/usr/src/neovim/share/nvim/runtime/lua/vim/lsp/buf.lua:690: in function 'callback'
        ...urenzi/usr/src/neovim/share/nvim/runtime/lua/vim/lsp.lua:1554: in function 'handler'
        ...urenzi/usr/src/neovim/share/nvim/runtime/lua/vim/lsp.lua:1043: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Debug log

-

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

-

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
For whatever reason, I can't replicate this, but based on the trace, this is similar to the situation in #837 where Neovim assumes an incorrect type. In this case, it looks like it's assuming that `codeActionProvider` is a table, but the spec lets it be a boolean, too:

![Screen Shot 2022-04-30 at 4 56 35 PM](https://user-images.githubusercontent.com/54108223/166122399-197df646-81a0-4ca9-9ffe-e5e5274283cc.png)

I'd recommend reporting this upstream. A similar situation was just resolved in neovim/neovim#18332, and just like that issue I imagine this affects actual LSP servers and not just null-ls.
