### ISSUE TITLE
null-ls resolves to wrong root_dir if nested in a git repo

### ISSUE THREAD

**Issue by MurdeRM3L0DY** [jose-elias-alvarez/null-ls.nvim#841]
When I first open neovim and `<C-o>` into a previous lua file, null-ls doesn't seem to register conditional stylua.
This problem only happens in symlinked directories. 

https://user-images.githubusercontent.com/95099980/166156974-d4bd78ba-057b-47ff-bfb7-38653d9f52a9.mp4

**Comment by jose-elias-alvarez** [comment]
Can't really help with this unless you follow the issue template and provide the requested information.

**Comment by MurdeRM3L0DY** [comment]
I think I may have figured out why this happens:
The `root_dir` in `client.config` doesn't match up with the actual root_dir which is why `has_root_dir` doesn't register stylua
In my case `client.config.root_dir` returns `$HOME/dotfiles/` instead of `$HOME/dotfiles/roles/nvim/files/`
`:pwd` returns the expected root_dir

**Comment by MurdeRM3L0DY** [comment]
I get what's going on now. null-ls defaults the root_dir to the root of the git repo. Closing as this doesn't seem to be a bug with null-ls

**Comment by jose-elias-alvarez** [comment]
FYI, you can use [condition](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md#condition) to have finer control over when a source registers.

**Comment by MurdeRM3L0DY** [comment]
That doesn't work because the `.git` is located in `$HOME/dotfiles` while my neovim config root(which is not a git repo) is located at `$HOME/dotfiles/roles/nvim/files` and since null-ls client defaults to `.git` as root_dir, the condition would match against `$HOME/dotfiles/.stylua.toml` instead of `$HOME/dotfiles/roles/nvim/files/.stylua.toml`. Maybe you could allow users to resolve root_dir per source? wdyt?

**Comment by jose-elias-alvarez** [comment]
`condition` can match against anything - it's not limited to `root_dir`. The conditional utils are there for convenience and are not meant to handle every case.

**Comment by jose-elias-alvarez** [comment]
I disagree - you can [change how `root_dir` behaves](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/CONFIG.md#root_dir-function) to handle specific cases like the one you describe. The idea of a per-source `root_dir` would likely help with this specific issue but would also add a lot of complexity, which I think is unnnecessary given how many other mechanisms we have to change how sources behave.

**Comment by MurdeRM3L0DY** [comment]
Right, please ignore the suggestion about adding root_dir per source. When I made that suggestion, I was under the impression that the issue was from stylua source. But I later realized that this issue originally stems from the way null-ls client resolves the root dir. It makes sense for null-ls to default to a git repo but I think it should only do so if the git repo is located in the cwd and should fallback to the cwd otherwise. wdyt?

**Comment by jose-elias-alvarez** [comment]
I think that's reasonable as a local modification but am not sure if it makes sense to push it as a breaking change to all users. For example, you can see in [the default options](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/CONFIG.md#options) that null-ls will look for a `.null-ls-root` file. If a user changes to a nested directory and opens a file (setting that file's directory as the `cwd`), would they expect the search to stop there?

I think the current behavior makes more sense as a default and is more consistent with how nvim-lspconfig works. Again, we have mechanisms in place for you to change this if you feel like it doesn't work for you.

**Comment by MurdeRM3L0DY** [comment]
Yeah. I'm currently using `.null-ls-root` to detect root_dir.
Hmm, weird. nvim-lspconfig resolves to the correct root_dir though

**Comment by jose-elias-alvarez** [comment]
The underlying logic is exactly the same, but assuming you're talking about lua-language-server, the difference in behavior is most likely due to the fact that [the config uses a different `root_dir` by default](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#sumneko_lua).

**Comment by MurdeRM3L0DY** [comment]
Got it. Thanks.
