### ISSUE TITLE
Format on save fails after updating to the latest version of null-ls

### ISSUE THREAD

**Issue by chrisdavies** [jose-elias-alvarez/null-ls.nvim#844]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.7.0

### Operating System

Fedora 35

### Minimal config

```
require("null-ls").setup({
  sources = {
    require("null-ls").builtins.formatting.prettier,
    require("null-ls").builtins.formatting.goimports,
  }
})
```

### Steps to reproduce

Open up a `.go` file or a `.ts` file in a properly configured project (e.g. projects that successfully formatted on save prior to updating null-ls).

Save the file.

### Expected behavior

The file formats.

### Actual behavior

The file does not format, and I see the following error in neovim:

```
Error detected while processing BufWritePost Autocommands for "<buffer=3>":
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/lsp.lua:122: Expected Lua number
stack traceback:
        [C]: in function 'nvim_buf_get_option'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:122: in function 'buf_get_line_ending'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:281: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:302: in function 'text'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1134: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:164: in function 'for_each_buffer_client'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1130: in function '_text_document_did_save_handler'
        [string ":lua"]:1: in main chunk
```

### Debug log

```
[TRACE Tue 03 May 2022 02:34:53 PM EDT] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:106: starting null-ls client
[TRACE Tue 03 May 2022 02:34:53 PM EDT] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method initialize
[TRACE Tue 03 May 2022 02:34:53 PM EDT] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method initialized
[TRACE Tue 03 May 2022 02:34:53 PM EDT] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didOpen
[TRACE Tue 03 May 2022 02:34:53 PM EDT] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Tue 03 May 2022 02:34:53 PM EDT] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:24: no generators available
```

### Help

No

### Implementation help

I don't know enough about LUA to be able to put together a PR in a reasonable amount of time. I'm happy to hop on Zoom, or whatever you prefer and screenshare to help repro the issue, though.

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
I'm going to need a full minimal reproduction here (using the file from the issue template) because I can't replicate this. Your error indicates that this is coming from an autocommand, which isn't in your minimal config.

**Comment by chrisdavies** [comment]
I've narrowed my config down to just this (still reproduces):

```
-- .config/nvim/init.lua
require('plugins')

require("null-ls").setup({
  sources = {
    require("null-ls").builtins.formatting.prettier,
    require("null-ls").builtins.formatting.goimports,
  },
})
```

```
-- .config/nvim/lua/plugins.lua
return require('packer').startup(function()
  use 'wbthomason/packer.nvim'

  -- Format on save and other code actions
  use {
    'jose-elias-alvarez/null-ls.nvim',
    requires = {
      'nvim-lua/plenary.nvim',
    },
  }

  -- Language server integration and autocomplete
  use 'neovim/nvim-lspconfig'

end)
```

There's nothing else except the packer compiled files.

**Comment by jose-elias-alvarez** [comment]
That config doesn't have formatting on save, do you see the error when you run `vim.lsp.buf.formatting_sync()`?

**Comment by jose4125** [comment]
neovim version NVIM v0.8.0-dev+1577-g4df11463b
```
local null_ls = require('null-ls')
local formatting = null_ls.builtins.formatting

null_ls.setup({
  sources = {
    formatting.prettier.with({
      filetypes = { "javascript", "javascriptreact", "typescript", "typescriptreact", "vue", "css", "scss", "less", "html", "json", "jsonc", "yaml", "markdown", "graphql", "handlebars", "svelte" },
      only_local = "node_modules/.bin",
    }),
    formatting.stylelint,
    formatting.prismaFmt,
    formatting.black,
    formatting.isort,
    formatting.cmake_format,
    formatting.dart_format,
    formatting.terraform_fmt,
    formatting.codespell,
  },
  -- you can reuse a shared lspconfig on_attach callback here
  on_attach = function(client)
    if client.supports_method("textDocument/formatting") then
        vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
        vim.api.nvim_create_autocmd("BufWritePre", {
            group = augroup,
            buffer = bufnr,
            -- on 0.8, you should use vim.lsp.buf.format instead
            callback = vim.lsp.buf.format,
        })
    end
  end,
})

```
the format on save is not formatting the code

**Comment by jose-elias-alvarez** [comment]
These are snippets from *your* configs, not self-contained minimal configs. When you open a new issue, you'll see the steps required to set up a minimal config so we can isolate this and verify if it is actually a null-ls issue. Otherwise, there's too many factors involved, so I can't investigate further.

**Comment by chrisdavies** [comment]
`vim.lsp.buf.formatting_sync()` does work. The config I specified above is (I think) as minimum as I can make it. I really don't want to waste your time, though, so feel free to close, and I'll get format on save working using another mechanism!

**Comment by jose-elias-alvarez** [comment]
If you post what you're using to format on save, I can take a look at it, but yeah, sounds like this is an issue with the autocommand and not null-ls.

**Comment by chrisdavies** [comment]
OK. Here's the self-contained, minimal config:

```
require('packer').startup(function()
  use 'wbthomason/packer.nvim'

  use {
    'jose-elias-alvarez/null-ls.nvim',
    requires = {
      'nvim-lua/plenary.nvim',
    },
  }
end)

local augroup = vim.api.nvim_create_augroup("LspFormatting", {})
require("null-ls").setup({
  sources = {
    require("null-ls").builtins.formatting.prettier,
  },
  on_attach = function(client, bufnr)
    if client.supports_method("textDocument/formatting") then
      vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
      vim.api.nvim_create_autocmd("BufWritePre", {
        group = augroup,
        buffer = bufnr,
        callback = vim.lsp.buf.formatting_sync,
      })
    end
  end,
})

```

**Comment by jose-elias-alvarez** [comment]
> OK. Here's the self-contained, minimal config:
> 
> ```
> require('packer').startup(function()
>   use 'wbthomason/packer.nvim'
> 
>   use {
>     'jose-elias-alvarez/null-ls.nvim',
>     requires = {
>       'nvim-lua/plenary.nvim',
>     },
>   }
> end)
> 
> local augroup = vim.api.nvim_create_augroup("LspFormatting", {})
> require("null-ls").setup({
>   sources = {
>     require("null-ls").builtins.formatting.prettier,
>   },
>   on_attach = function(client, bufnr)
>     if client.supports_method("textDocument/formatting") then
>       vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
>       vim.api.nvim_create_autocmd("BufWritePre", {
>         group = augroup,
>         buffer = bufnr,
>         callback = vim.lsp.buf.formatting_sync,
>       })
>     end
>   end,
> })
> ```

Not exactly what I meant, but does this config fail for you? It works for me on 0.7 and 0.8.

**Comment by chrisdavies** [comment]
Yes. It does format, but it gives the error every time I save. It also gives the error on save, even if I don't have the `on_attach` part. Basically, if I `require("null-ls")` in my config at all, I get an error on save.

I'm on 0.7:

```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az316-460
```

I've got a workaround for now, so it's not a big deal. If no one else is hitting it, it must be something odd with some other part of my system, but it's strange because it was all working until I did a `PackerSync` and got an update to `null-ls` yesterday.

**Comment by olacin** [comment]
@chrisdavies I encountered the same issue, but this does not comes from null_ls.

In fact, neovim `client.server_capabilities` does not have the same structure in 0.8 as in 0.7. You probably can fix it when creating your autocmd like I did:
```diff
local ok, null_ls = pcall(require, "null-ls")
if not ok then
    return
end

local formatting = null_ls.builtins.formatting
local diagnostics = null_ls.builtins.diagnostics
local code_actions = null_ls.builtins.code_actions

null_ls.setup({
    sources = {
        -- Python
        diagnostics.flake8.with({ extra_args = { "--max-line-length", "88" } }),
        formatting.black.with({ extra_args = { "--fast" } }),
        formatting.isort.with({ extra_args = { "--profile", "black" } }),
        -- Typescript
        diagnostics.eslint_d,
        code_actions.eslint_d,
        formatting.prettier,
        -- Lua
        formatting.stylua,
        -- Go
        formatting.gofmt,
    },
    on_attach = function(client, bufnr)
-        if client.server_capabilities.document_formatting then
+        if client.server_capabilities.documentFormattingProvider then
            local group = vim.api.nvim_create_augroup("LspFormatting", { clear = true })
            vim.api.nvim_create_autocmd(
                "BufWritePre",
                { buffer = bufnr, callback = vim.lsp.buf.formatting_sync, group = group }
            )
        end
    end,
})

```

**Comment by par4m** [comment]
Working for me on NVIM v0.8.0-dev+95-g07660193a3
```lua
local null_ls_status_ok, null_ls = pcall(require, "null-ls")
if not null_ls_status_ok then
	return
end

-- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/formatting
local formatting = null_ls.builtins.formatting
-- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/diagnostics
local diagnostics = null_ls.builtins.diagnostics

local lsp_formatting = function(bufnr)
	vim.lsp.buf.format({
		-- filter = function(clients)
		-- filter out clients that you don't want to use
		-- return vim.tbl_filter(function(client)
		-- return client.name ~= "tsserver"
		-- end, clients)
		-- end,
		bufnr = bufnr,
	})
end

local augroup = vim.api.nvim_create_augroup("LspFormatting", {})

null_ls.setup({
	debug = false,
	sources = {
		formatting.prettier.with({ extra_args = { "--no-semi", "--single-quote", "--jsx-single-quote" } }),
		formatting.black.with({ extra_args = { "--fast" } }),
		formatting.stylua,
		-- diagnostics.flake8
	},
	on_attach = function(client, bufnr)
		if client.supports_method("textDocument/formatting") then
			vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
			vim.api.nvim_create_autocmd("BufWritePre", {
				group = augroup,
				buffer = bufnr,
				callback = function()
					lsp_formatting(bufnr)
				end,
			})
		end
	end,
}
```

**Comment by chrisdavies** [comment]
Ah. Sorry, everyone. I've switched my configs up and am using a different plugin now for format-on-save. I think if no one else is having the error, you should just close the issue! No idea what is going on on my system.
