### ISSUE TITLE
eslint working directories

### ISSUE THREAD

**Issue by joshmedeski** [jose-elias-alvarez/null-ls.nvim#846]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Add the ability to specify the working directories to run eslint in a monorepo.

Here is an example of a yarn monorepo using the [`coc-eslint`](https://github.com/neoclide/coc-eslint).

```json
{
  "eslint.workingDirectories": [
    "atlas-functions",
    "docs",
    "server",
    "web",
    "web-e2e",
    "mobile"
  ]
}
```

There is a different `eslintrc` file in each of these directories, I want null-ls to be able to make this differentiation.

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

Is there a way to have a `null-ls` configuration per project?

**Comment by jose-elias-alvarez** [comment]
This is not a feature that we can implement using the ESLint CLI, which is what null-ls uses. I don't know off the top of my head if it supports the specific feature, but I would look into using [the ESLint language server](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#eslint), which is closer to coc-eslint in that it uses the ESLint Node API.

**Comment by joshmedeski** [comment]
Thanks, @jose-elias-alvarez, that makes sense. I'll give the LSP a go!
