### ISSUE TITLE
flake8 doesn't respect local `.flake8` configs

### ISSUE THREAD

**Issue by dhleong** [jose-elias-alvarez/null-ls.nvim#848]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.6.1

### Operating System

macOS

### Minimal config

Probably just

```lua
require'null-ls'.setup{
  sources = {
    require('null-ls').builtins.diagnostics.flake8,
  }
}
```

### Steps to reproduce

- Create a mono-repo with a root .flake8 file
- Create a sub-project in this repo with its own .flake8 file
- Open a python file in the sub-repo
- Write something lint-y that is not permitted by the root `.flake8`, but is ignored by the sub-project's `.flake8`

### Expected behavior

The lint is ignored, due to the project-local config

### Actual behavior

The lint is reported

### Debug log

There is no output from this repro

### Help

Yes

### Implementation help

If I simply run `!cat % | flake8`, it works as expected. It looks like we're passing the file's text to `flake8` via stdin; perhaps we can simply run `flake8` with the current file's directory as its cwd and things would work as expected?

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by dhleong** [comment]
I wonder whether my proposed fix would also help with #722

**Comment by jose-elias-alvarez** [comment]
See #289 for discussion of this exact issue. You can use [`prefer_local`](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md#using-local-executables) to find the nearest `.flake8` config file and use that as the `cwd` of the spawned process. You can also provide a callback to `cwd` for finer control.

**Comment by dhleong** [comment]
Ah, `prefer_local` is for the executable, which I don't need to change, but that did lead me to the `with { cwd = ... }` config which I totally missed, and which works perfectly for my use case:

```lua
    require('null-ls').builtins.diagnostics.flake8.with {
      cwd = function(params)
        return vim.fn.fnamemodify(params.bufname, ':h')
      end,
    },
```

Thank you for your help and sorry for not reading the docs more thoroughly!
