### ISSUE TITLE
nvim_buf_get_name error

### ISSUE THREAD

**Issue by xaotag** [jose-elias-alvarez/null-ls.nvim#849]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.8.0-dev+127-g3ec93ca92c

### Operating System

arch 

### Minimal config

```lua
local null_ls = require "null-ls"

local formatting = null_ls.builtins.formatting
local diagnostics = null_ls.builtins.diagnostics

local async_formatting = function(bufnr)
    bufnr = bufnr or vim.api.nvim_get_current_buf()

    vim.lsp.buf_request(bufnr, "textDocument/formatting",
                        {textDocument = {uri = vim.uri_from_bufnr(bufnr)}},
                        function(err, res)
        if err then
            local err_msg = type(err) == "string" and err or err.message
            -- you can modify the log message / level (or ignore it completely)
            vim.notify("formatting: " .. err_msg, vim.log.levels.WARN)
            return
        end

        -- don't apply results if buffer is unloaded or has been modified
        if not vim.api.nvim_buf_is_loaded(bufnr) or
            vim.api.nvim_buf_get_option(bufnr, "modified") then return end

        if res then
            vim.lsp.util.apply_text_edits(res, bufnr)
            vim.api.nvim_buf_call(bufnr, function()
                vim.cmd("silent noautocmd update")
            end)
        end
    end)
end

-- https://github.com/prettier-solidity/prettier-plugin-solidity
augroup = vim.api.nvim_create_augroup("LspFormatting", {})
local null_ls = require("null-ls")

null_ls.setup({
    debug = false,
    sources = {formatting.lua_format, formatting.prettier},
    on_attach = function(client, bufnr)
        if client.supports_method("textDocument/formatting") then
            vim.api.nvim_clear_autocmds({group = augroup, buffer = bufnr})
            vim.api.nvim_create_autocmd("BufWritePost", {
                group = augroup,
                buffer = bufnr,
                callback = function(bufnr)
                    async_formatting(bufnr)
                end
            })
        end
    end
})

```

### Steps to reproduce

:w 

### Expected behavior

format

### Actual behavior

处理 BufWritePost 自动命令 "<buffer=1>" 时发生错误:
Error executing lua callback: /usr/share/nvim/runtime/lua/vim/uri.lua:84: Expected Lua number
stack traceback:
        [C]: in function 'nvim_buf_get_name'
        /usr/share/nvim/runtime/lua/vim/uri.lua:84: in function 'uri_from_bufnr'
        /home/aiden/.config/nvim/lua/null_ls/init.lua:10: in function 'async_formatting'
        /home/aiden/.config/nvim/lua/null_ls/init.lua:45: in function </home/aiden/.config/nvim/lua/null_ls/init.lua:44>

### Debug log

[TRACE 2022年05月06日 星期五 12时57分56秒] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:97: starting null-ls client
[TRACE 2022年05月06日 星期五 12时57分56秒] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method initialize
[TRACE 2022年05月06日 星期五 12时57分56秒] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method initialized
[TRACE 2022年05月06日 星期五 12时57分56秒] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didOpen
[TRACE 2022年05月06日 星期五 12时57分56秒] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG 2022年05月06日 星期五 12时57分56秒] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:24: no generators available
[TRACE 2022年05月06日 星期五 12时57分56秒] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didSave
[TRACE 2022年05月06日 星期五 12时57分56秒] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_SAVE
[DEBUG 2022年05月06日 星期五 12时57分56秒] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:24: no generators available

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
I mentioned this on the wiki, but the snippet in question is not part of null-ls. Still, there's two legitimate issues in the snippet, so here is the fix:

```lua
local null_ls = require("null-ls")

local formatting = null_ls.builtins.formatting
local diagnostics = null_ls.builtins.diagnostics

local async_formatting = function(bufnr)
    bufnr = bufnr or vim.api.nvim_get_current_buf()

    vim.lsp.buf_request(
        bufnr,
        "textDocument/formatting",
        { textDocument = { uri = vim.uri_from_bufnr(bufnr) } },
        function(err, res, ctx)
            if err then
                local err_msg = type(err) == "string" and err or err.message
                -- you can modify the log message / level (or ignore it completely)
                vim.notify("formatting: " .. err_msg, vim.log.levels.WARN)
                return
            end

            -- don't apply results if buffer is unloaded or has been modified
            if not vim.api.nvim_buf_is_loaded(bufnr) or vim.api.nvim_buf_get_option(bufnr, "modified") then
                return
            end

            if res then
                local client = vim.lsp.get_client_by_id(ctx.client_id)
                vim.lsp.util.apply_text_edits(res, bufnr, client and client.offset_encoding or "utf-16")
                vim.api.nvim_buf_call(bufnr, function()
                    vim.cmd("silent noautocmd update")
                end)
            end
        end
    )
end

local augroup = vim.api.nvim_create_augroup("LspFormatting", {})

null_ls.setup({
    debug = false,
    sources = { formatting.lua_format, formatting.prettier },
    on_attach = function(client, bufnr)
        if client.supports_method("textDocument/formatting") then
            vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
            vim.api.nvim_create_autocmd("BufWritePost", {
                group = augroup,
                buffer = bufnr,
                callback = function()
                    async_formatting(bufnr)
                end,
            })
        end
    end,
})
```

Once you verify that this works for you, I'll update the wiki.

**Comment by xaotag** [comment]
ty,no problem ,you can update the wiki

**Comment by xaotag** [comment]
but ,format js,ts,jsx.tsx failed
```
log 
formatting: Request textDocument/formatting failed with message: Cannot read properties of undefined (reading 'insertSpaces')
```

**Comment by jose-elias-alvarez** [comment]
That looks like it's coming from the formatter, not from null-ls. What happens when you run the formatter from the command line? If it only happens with null-ls, please open another issue with reproduction steps (including a specific file / project where you see the error).
