### ISSUE TITLE
Builtin clang-format formatter not working because of missing filename argument

### ISSUE THREAD

**Issue by PasiBergman** [jose-elias-alvarez/null-ls.nvim#85]
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.5

### Steps to reproduce

Open a file with filetype "c", "cpp", "cs" or "java" and try to use builtin clang_format (clang-format) to format the current buffer. Buffer does not get formatted, because the `-assume-filename` option value does not get set.

### Expected behavior

Buffer content gets formatted using `clang-format`

### Actual behavior

Buffer content does not get formatted.

### Debug log

error: empty filenames are not allowed
Error: clang-format exited with exit code 1.

### Help

Yes

**Comment by jose-elias-alvarez** [comment]
Closed by #86.
