### ISSUE TITLE
Allow calling `setup()` multiple times

### ISSUE THREAD

**Issue by AlxHnr** [jose-elias-alvarez/null-ls.nvim#859]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Most other lua plugins have a `setup()` function which can be called multiple times. This feature is really nice because it allows reloading your `init.lua` at runtime just by running `:so %`. But with null-ls I have to restart neovim on every change I want to try. Each time I want to enable a new linter, or change my existing null-ls settings, I have to restart again and again.

Adding this feature would make null-ls more consistent with the rest of neovim and its ecosystem. Every neovim setting and almost every other plugin can be configured at runtime without a restart.

### Help

No

**Comment by AlxHnr** [comment]
I see, the source API solves my problem. Not sure why I couldn't find it at first glance. Is there a reason why null-ls doesn't ship a vim-help page?

**Comment by AlxHnr** [comment]
If you want to keep `setup()` only callable once, feel free to close this issue. Its up to you to decide on the design philosophy.

For anyone else who insists on hot-reloading their `init.lua`, and happens to stumble upon this discussion, I've pasted a solution below. That way they can for example comment out a linter, run `:so %` and its gone.

```lua
-- init.lua
local null_ls = require('null-ls')
null_ls.setup()
null_ls.disable{}
null_ls.reset_sources()
null_ls.register(null_ls.builtins.diagnostics.shellcheck)
```

`on_attach` could be redefined at runtime by registering a wrapper lambda.

**Comment by jose-elias-alvarez** [comment]
I think what you've posted is a good workaround. As I said, I'm not totally opposed to reviewing a PR that accomplishes this without adding complexity, so I'll keep this open in case anybody wants to pick it up.

**Comment by jose-elias-alvarez** [comment]
I'm closing this since I don't plan to work on it, but anybody who's really interested and is willing to put in the work should feel free to open a PR.
