### ISSUE TITLE
bad argument #1 to 'unpack'

### ISSUE THREAD

**Issue by bercly0b** [jose-elias-alvarez/null-ls.nvim#860]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.8.0-dev

### Operating System

Ubuntu 18.04.6 LTS

### Minimal config

Sorry guys, I didn't figure out the `minimal_init.lua` config trick because I don't use packer..
Here are pieces of my nvim config
https://github.com/bercly0b/dotfiles/blob/master/lua/plugins/lsp.lua
https://github.com/bercly0b/dotfiles/blob/master/lua/plugins/null-ls.lua

### Steps to reproduce

I use `tsserver` as main language server and `null-ls` for diagnostic.
A few days ago I've update `null-ls` and I started to get an error when I trying to use some lsp commands, like:
`vim.lsp.buf.definition`
`vim.lsp.buf.code_action`
`vim.lsp.buf.hover`

I tried to checkout to [this](https://github.com/jose-elias-alvarez/null-ls.nvim/commit/3dbded7cfaf0591157280bc97d11407eeaef3ea9) commit and I got the same error
And then I checkout to [this](https://github.com/jose-elias-alvarez/null-ls.nvim/commit/d871b418c67867a11a43eb1412a1a21aee888ae3) commit and it's works well.

### Expected behavior

I don't get error)

### Actual behavior

I get error when I use some lsp commands
```
E5108: Error executing lua ...otfiles/.vim/plugged/null-ls.nvim/lua/null-ls/client.lua:39: bad argument #1 to 'unpack' (table expected, got string)
stack traceback:
        [C]: in function 'unpack'
        ...otfiles/.vim/plugged/null-ls.nvim/lua/null-ls/client.lua:39: in function 'capability_is_disabled'
        ...otfiles/.vim/plugged/null-ls.nvim/lua/null-ls/client.lua:50: in function 'supports_method'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1470: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:164: in function 'for_each_buffer_client'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1469: in function 'request'
        /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:61: in function 'hover'
        [string ":lua"]:1: in main chunk
```

### Debug log

```
[TRACE Thu 12 May 2022 03:38:09 PM MSK] ...otfiles/.vim/plugged/null-ls.nvim/lua/null-ls/client.lua:106: starting null-ls client
[TRACE Thu 12 May 2022 03:38:09 PM MSK] ...f/dotfiles/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method initialize
[TRACE Thu 12 May 2022 03:38:09 PM MSK] ...f/dotfiles/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method initialized
[TRACE Thu 12 May 2022 03:38:09 PM MSK] ...f/dotfiles/.vim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didOpen
[TRACE Thu 12 May 2022 03:38:09 PM MSK] ...les/.vim/plugged/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Thu 12 May 2022 03:38:09 PM MSK] ...ed/null-ls.nvim/lua/null-ls/helpers/command_resolver.lua:35: attempting to find local executable node_modules/.bin/eslint_d
[DEBUG Thu 12 May 2022 03:38:09 PM MSK] ...ed/null-ls.nvim/lua/null-ls/helpers/command_resolver.lua:41: Unable to resolve command [node_modules/.bin/eslint_d], skipping further lookups
[DEBUG Thu 12 May 2022 03:38:09 PM MSK] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:284: Using dynamic command for [eslint_d], got: "eslint_d"
[DEBUG Thu 12 May 2022 03:38:09 PM MSK] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:344: spawning command "eslint_d" at /home/%replace%/ with args { "-f", "json", "--stdin", "--stdin-filename", "/home/%replace%/src/utils/getReadbleNum.ts" }
[TRACE Thu 12 May 2022 03:38:09 PM MSK] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:217: error output: nil
[TRACE Thu 12 May 2022 03:38:09 PM MSK] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:218: output: [{"filePath":"/home/%replace%/src/utils/getReadbleNum.ts","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[{"ruleId":"valid-jsdoc","replacedBy":[]}]}]
[TRACE Thu 12 May 2022 03:38:09 PM MSK] ...es/.vim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:169: received diagnostics from source 1
[TRACE Thu 12 May 2022 03:38:09 PM MSK] ...es/.vim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:170: {}
```

### Help

Yes

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by bercly0b** [comment]
I guess the problem is here somewhere
https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/client.lua#L39

**Comment by jose-elias-alvarez** [comment]
Rebuild from the latest Neovim master and this problem should be solved.

**Comment by bercly0b** [comment]
> Rebuild from the latest Neovim master and this problem should be solved.

Thank you! this fixed my problem 👍
