### ISSUE TITLE
Deregistering a source leaves its diagnostics dangling around forever

### ISSUE THREAD

**Issue by AlxHnr** [jose-elias-alvarez/null-ls.nvim#862]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.7.0

### Operating System

Fedora 35

### Minimal config

Only change to the provided config:
```diff
-         sources = {},
+         sources = {null_ls.builtins.diagnostics.shellcheck},
```

### Steps to reproduce

```sh
# install shellcheck, e.g. `sudo apt install shellcheck`
nvim --clean -u minimal_init.lua
```

Create a new file in a split, named `/tmp/foo.sh` with the following content:

```sh
unused="foo"
```

This will give you some warnings. Then deregister shellcheck:

```vim
:lua require('null-ls').deregister{}
```

### Expected behavior

Diagnostics disappear. Similar to how nvim-lspconfig is handling comparable situations gracefully.

### Actual behavior

Diagnostics are orphaned and will stick around forever. Even when shellcheck is registered again, it will just add new diagnostics on top of the ones that already exist.

### Debug log

```conf
[WARN  Tue May  3 23:04:51 2022] ...d-party/start/null-ls.nvim/lua/null-ls/builtins/init.lua:17: failed to load builtin dictionay for method hover; please check your config
[TRACE Thu May 12 19:21:05 2022] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:106: starting null-ls client
[TRACE Thu May 12 19:21:05 2022] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method initialize
[TRACE Thu May 12 19:21:05 2022] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method initialized
[TRACE Thu May 12 19:21:05 2022] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didOpen
[TRACE Thu May 12 19:21:05 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Thu May 12 19:21:05 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:344: spawning command "shellcheck" at /home/user with args { "--format", "json1", "--source-path=/tmp", "--external-sources", "-" }
[TRACE Thu May 12 19:21:05 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:217: error output: nil
[TRACE Thu May 12 19:21:05 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:218: output: {"comments":[{"file":"-","line":1,"endLine":1,"column":1,"endColumn":1,"level":"error","code":2148,"message":"Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.","fix":null}]}

[TRACE Thu May 12 19:21:05 2022] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:169: received diagnostics from source 1
[TRACE Thu May 12 19:21:05 2022] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:170: { {
    code = 2148,
    col = 0,
    end_col = 0,
    end_lnum = 1,
    end_row = 1,
    lnum = 0,
    message = "Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.",
    row = 1,
    severity = 1,
    source = "shellcheck"
  } }
[TRACE Thu May 12 19:21:14 2022] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didChange
[TRACE Thu May 12 19:21:14 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG Thu May 12 19:21:14 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:344: spawning command "shellcheck" at /home/user with args { "--format", "json1", "--source-path=/tmp", "--external-sources", "-" }
[TRACE Thu May 12 19:21:14 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:217: error output: nil
[TRACE Thu May 12 19:21:14 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:218: output: {"comments":[{"file":"-","line":1,"endLine":1,"column":1,"endColumn":1,"level":"error","code":2148,"message":"Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.","fix":null},{"file":"-","line":1,"endLine":1,"column":1,"endColumn":7,"level":"warning","code":2034,"message":"unused appears unused. Verify use (or export if used externally).","fix":null}]}

[TRACE Thu May 12 19:21:14 2022] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:169: received diagnostics from source 1
[TRACE Thu May 12 19:21:14 2022] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:170: { {
    code = 2148,
    col = 0,
    end_col = 0,
    end_lnum = 1,
    end_row = 1,
    lnum = 0,
    message = "Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.",
    row = 1,
    severity = 1,
    source = "shellcheck"
  }, {
    code = 2034,
    col = 0,
    end_col = 6,
    end_lnum = 0,
    end_row = 1,
    lnum = 0,
    message = "unused appears unused. Verify use (or export if used externally).",
    row = 1,
    severity = 2,
    source = "shellcheck"
  } }
[TRACE Thu May 12 19:23:33 2022] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didChange
[TRACE Thu May 12 19:23:33 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS
... [repeats a few hundred times] ...
```

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
Using [the `disable` method](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/dcad76eb1abb80cf3a27208823becbf62547abf8/lua/null-ls/sources.lua#L144) will erase diagnostics from disabled sources (and is the right tool to use if you plan on potentially enabling the source again). 

This probably isn't the clearest separation of concerns, but my idea in designing the API was that `disable` and `toggle` should handle cases where users want to disable sources they themselves have registered, whereas `deregister` is more of a blunt tool for integrations to make sure that sources are completely wiped out. I see that this isn't mentioned at all in the documentation, so I'll update that.

**Comment by AlxHnr** [comment]
Why shouldn't `deregister()` do a cleanup? Imo deregister is a superset of disable.

**Comment by jose-elias-alvarez** [comment]
That's debatable - again, since it's intended for consumption by integrations, the idea was to give them finer control about what to do with diagnostics. For example, I can imagine an integration that wants to run once, leave diagnostics in the buffer, and then deregister itself. 

Either way, changing its behavior would be a breaking change, and since we already have a tool to handle this situation, I'd be hesitant to change it without additional justification.

**Comment by AlxHnr** [comment]
> I can imagine an integration that wants to run once, leave diagnostics in the buffer

I can't. At this point the diagnostics are stuck and won't go away by fixing them. This is beta software, so breakage is implied. Maybe we should rerename the function to something more aggressive sounding? Right now it sounds like a cleanup-routine which doesn't clean up. Having to `disable()` + `deregister()` just to wipe some warnings is not intuitive in my view.

**Comment by jose-elias-alvarez** [comment]
Why do you need to run `deregister`? `disable` alone will both wipe out diagnostics and prevent the source from running again until you specifically enable it.

**Comment by AlxHnr** [comment]
> Why do you need to run `deregister`?

To deregister a source and hopefully clean up all states. What else is this function for? My concern here is that the API isn't clear enough if I have to read its implementation every time something is ambiguous. If the API is supposed to be rather low-level, it should be made more obvious. E.g. by naming. I assume `reset_sources()` doesn't wipe the diagnostics either? I would expect this from something that has `reset()` in its name.

**Comment by AlxHnr** [comment]
Even tough the actual use case could be debated, I just want a clean and obvious counterpart to `register_sources()`, to teardown proberly in a clean way what was setup before. This is what an api should provide in my opinion.

**Comment by jose-elias-alvarez** [comment]
I still don't get it - if what you want is to disable a source and hide its diagnostics, that's what `disable` does. It seems like we're mixing up two separate issues here:

1. Users want ways to modify how sources run dynamically, including preventing them from running and hiding any output. This was the goal of implementing the source API in the first place, and that specific use case is handled by `disable`.
2. The `deregister` function doesn't do what you expect. I agree that reading the implementation is not ideal and will update the documentation to clarify its intended usage and make it clear that `disable` is the right solution for what you want to do.

As long as we're handling the use case of disabling sources and are doing a better job of conveying how to do that to users, I'm happy. It's true that null-ls is still in beta, but I'd still rather avoid breaking changes unless their impact justifies the cost. I'm not really interested in bikeshedding beyond that point.

**Comment by AlxHnr** [comment]
A documentation update is good enough for me. As long as the design decisions are conveyed properly and there is no ambiguity in what the API's goals are, I'm happy. Feel free to close this issue.

**Comment by jose-elias-alvarez** [comment]
I updated the documentation in 30400da991deb6e8535ba8874ac715efa6ea1bd0 to help clarify the distinction between different methods.
