### ISSUE TITLE
Disable null-ls on 'terminal' buftype

### ISSUE THREAD

**Issue by michaelb** [jose-elias-alvarez/null-ls.nvim#864]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.7.0

### Operating System

Linux

### Minimal config

Config-independent

### Steps to reproduce

1. Open a new (or existing) file
2. type `:term` 
3. observe how there is a 'gutter' (signcolumn may be a better term?) on the left of the windows

### Expected behavior

null-ls shouldn't create an extra useless column for buftypes 'terminal'

### Actual behavior

![Screenshot_103](https://user-images.githubusercontent.com/44144536/168145460-bcc9b033-13bf-46ef-abc2-d5417fc6c5d8.png)

any terminal (see right vsplit) has this additionnal signcolumn that takes up space at the left. In my case, it breaks the formatting of another plugin (sniprun), but it actually happens on every terminal.

I've seen https://github.com/jose-elias-alvarez/null-ls.nvim/issues/49 but the discussion diverged too much to the issue

### Debug log

[WARN  dim. 19 déc. 2021 10:24:09] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:39: failed to run generator: ...e/pack/packer/start/null-ls.nvim/lua/null-ls/helpers.lua:171: command stylua is not executable (make sure it's installed and on your $PATH)
[ERROR mar. 01 févr. 2022 19:48:19] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:178: command stylua is not executable (make sure it's installed and on your $PATH)
[ERROR lun. 18 avril 2022 15:38:34] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:180: command stylua is not executable (make sure it's installed and on your $PATH)

(note that I don't care about having actual signs in the signcolumn, I'm actually debugging my plugin's user)

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
I'm having a hard time understanding what this has to do with null-ls. This is controlled by the `signcolumn` option and is trivially replicated by running Neovim with no plugins using the command `nvim --clean +'set signcolumn=yes' +'term'`.

**Comment by michaelb** [comment]
Hmmm you're right. 

That'll teach me to partially skip the form, since the minimal config doesn't reproduce this without your cli option. I guess in my and my user' case, null-ls was the only thing requiring the signcolumn so I might have jumped on the gun too soon. 
Sorry!
