### ISSUE TITLE
tsserver declaration no work

### ISSUE THREAD

**Issue by xaotag** [jose-elias-alvarez/null-ls.nvim#866]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.8.0-dev+203-g9e4286294f 

### Operating System

arch 5.17.6-arch1-1

### Minimal config

```lua 
init.lua 
local null_ls = require("null-ls")
local format = require("null_ls.source").prettier

local augroup = vim.api.nvim_create_augroup("LspFormatting", {})

null_ls.setup({
  debug = true,
  sources = format,
  on_attach = function(client, bufnr)
    local callback = function()
      vim.lsp.buf.format({
        bufnr = bufnr,
        filter = function(clients)
          return vim.tbl_filter(function(client)
            return client.name == "null-ls"
          end, clients)
        end
      })
    end
    if client.supports_method("textDocument/formatting") then
      vim.api.nvim_clear_autocmds({group = augroup, buffer = bufnr})
      vim.api.nvim_create_autocmd("BufWritePost", {
        group = augroup,
        buffer = bufnr,
        -- need to ignore callback argument, which is a table
        callback = function() callback() end
      })
    end
  end
})
----------
source.lua 
----------
local M = {}

local null_ls = require("null-ls")
local formatting = null_ls.builtins.formatting
local diagnostics = null_ls.builtins.diagnostics

-- LuaFormatter off
M.prettier = {
	formatting.prettier,
	formatting.lua_format.with({
		extra_args = {
			"--indent-width", "2",
			"--no-use-tab",
		}
	})
}
-- LuaFormatter on
return M

```

### Steps to reproduce

 Lspsaga preview_definition

### Expected behavior

![image](https://user-images.githubusercontent.com/40427877/168461964-197c3601-26ab-4d51-81bb-3e58926c454f.png)

### Actual behavior

no work 

### Debug log

```
[TRACE 2022年05月15日 星期日 14时55分18秒] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:97: starting null-ls client
[TRACE 2022年05月15日 星期日 14时55分18秒] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method initialize
[TRACE 2022年05月15日 星期日 14时55分18秒] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method initialized
[TRACE 2022年05月15日 星期日 14时55分18秒] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didOpen
[TRACE 2022年05月15日 星期日 14时55分18秒] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG 2022年05月15日 星期日 14时55分18秒] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:24: no generators available

```

### Help

Yes, but I don't know how to start. I would need guidance

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
I don't think I understand. Your minimal config isn't even setting up null-ls at all, and I'm not sure what's the issue here. Are you saying that null-ls is making it so that lspsaga's `preview_definition` doesn't work? Does it work when you disable null-ls? I'm going to need a working minimal config and more details about the issue to investigate.

**Comment by xaotag** [comment]
If I close the null-ls formatter,  lspsaga `preview_definition` will work properly

**Comment by xaotag** [comment]
The problem is solved
![image](https://user-images.githubusercontent.com/40427877/168931551-f76c4f62-2c89-4196-8a9d-a9d8a1a92a31.png)
