### ISSUE TITLE
Rubocop doens`t work when unexpected output comes together

### ISSUE THREAD

**Issue by otavioschwanck** [jose-elias-alvarez/null-ls.nvim#869]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.7

### Operating System

mac

### Minimal config

local h = require("null-ls.helpers")
local methods = require("null-ls.methods")

local DIAGNOSTICS = methods.internal.DIAGNOSTICS

local handle_rubocop_output = function(params)
    if params.output and params.output.files then
        local file = params.output.files[1]
        if file and file.offenses then
            local parser = h.diagnostics.from_json({
                severities = {
                    info = h.diagnostics.severities.information,
                    refactor = h.diagnostics.severities.hint,
                    convention = h.diagnostics.severities.warning,
                    warning = h.diagnostics.severities.warning,
                    error = h.diagnostics.severities.error,
                    fatal = h.diagnostics.severities.fatal,
                },
            })
            local offenses = {}

            for _, offense in ipairs(file.offenses) do
                table.insert(offenses, {
                    message = offense.message,
                    ruleId = offense.cop_name,
                    level = offense.severity,
                    line = offense.location.start_line,
                    column = offense.location.start_column,
                    endLine = offense.location.last_line,
                    endColumn = offense.location.last_column + 1,
                })
            end

            return parser({ output = offenses })
        end
    end

    return {}
end

local rubocop_fixed =  h.make_builtin({
    name = "rubocop",
    meta = {
        url = "https://rubocop.org/",
        description = "The Ruby Linter/Formatter that Serves and Protects.",
    },
    method = DIAGNOSTICS,
    filetypes = { "ruby" },
    generator_opts = {
        command = "bundle",
        args = { "exec", "rubocop", "-f", "json", "--stdin", "$FILENAME", "RUBYOPT='-W0'" },
        to_stdin = true,
        format = "json",
        check_exit_code = function(code)
            return code <= 1
        end,
        on_output = handle_rubocop_output,
    },
    factory = h.generator_factory,
})

local null_ls = require("null-ls")

null_ls.setup({
    sources = {
      require("null-ls").builtins.diagnostics.eslint,
      rubocop_fixed -- is preferable to use bundle instead rubocop directly. see args.
  }
})

### Steps to reproduce

Open a rails project with upgraded rubocop version

### Expected behavior

Show diagnostics

### Actual behavior

Diagnostics doen't appears

### Debug log

https://pastebin.com/iRuT49t3

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
I'm not 100% sure what's going on in your minimal config, since the formatting got broken, but it sounds like you're trying to set up Rubocop with custom arguments, right? This is not guaranteed to work and not something I can really support, especially since I'm not at all familiar with Ruby. Your debug log is also gigantic, but judging from this line at the very end, it looks like the linter isn't accepting the arguments you are passing in (maybe it doesn't want anything to come after the filename?):

```
-s/--stdin requires exactly one path, relative to the root of the project. RuboCop will use this path to determine which cops are enabled (via eg. Include/Exclude), and so that certain cops like Naming/FileName can be checked.
```

I would start by making sure that your version works from the command line, then work on porting it to null-ls, but beyond that I can't really help here.

**Comment by otavioschwanck** [comment]
> I'm not 100% sure what's going on in your minimal config, since the formatting got broken, but it sounds like you're trying to set up Rubocop with custom arguments, right? This is not guaranteed to work and not something I can really support, especially since I'm not at all familiar with Ruby. Your debug log is also gigantic, but judging from this line at the very end, it looks like the linter isn't accepting the arguments you are passing in (maybe it doesn't want anything to come after the filename?):
> 
> ```
> -s/--stdin requires exactly one path, relative to the root of the project. RuboCop will use this path to determine which cops are enabled (via eg. Include/Exclude), and so that certain cops like Naming/FileName can be checked.
> ```
> 
> I would start by making sure that your version works from the command line, then work on porting it to null-ls, but beyond that I can't really help here.

@jose-elias-alvarez the same version works on coc and emacs.  On coc i execute in this way:

```
{
            "command": "bundle",
            "sourceName": "rubocop",
            "debounce": 100,
            "args": [
              "exec",
              "rubocop",
              "--format",
              "json",
              "--force-exclusion",
              "--stdin",
              "%filepath"
            ],
            "parseJson": {
              "errorsRoot": "files[0].offenses",
              "line": "location.start_line",
              "endLine": "location.last_line",
              "column": "location.start_column",
              "endColumn": "location.end_column",
              "message": "[${cop_name}] ${message}",
              "security": "severity"
            },
            "securities": {
              "fatal": "error",
              "error": "error",
              "warning": "warning",
              "convention": "info",
              "refactor": "info",
              "info": "info"
            }
          }
          ```

**Comment by jose-elias-alvarez** [comment]
Those arguments don’t look the same as the one in your original post - I don’t see `RUBYOPT='-W0'` there (and if I had to guess from the error message, that’s the one that’s giving you trouble).

**Comment by otavioschwanck** [comment]
@jose-elias-alvarez i putted that arg because i try to do some tests to see if works.

Here is the results without the RUBYOPT:

https://pastebin.com/zTuHqmwU

**Comment by jose-elias-alvarez** [comment]
I apologize, but I really can't help with this beyond what I mentioned in #764. Fundamentally, this is a question about configuring a custom source and not an issue with null-ls itself, and as I mentioned I have no experience with Ruby.

One workaround that was mentioned in a past issue was to use a [binstub](https://bundler.io/man/bundle-binstubs.1.html). I don't know anything about this, but it looks like the goal is to condense what would otherwise require a `bundle exec` command into a single script, which may work better with null-ls.

**Comment by otavioschwanck** [comment]
I managed to configure with diagnosticls:

```
lspconfig.diagnosticls.setup {
  filetypes = { "ruby" },
  init_options = {
    linters = {
      rubocop = {
        command = "bundle",
        sourceName = "rubocop",
        debounce = 100,
        args = { "exec",
          "rubocop",
          "--format",
          "json",
          "--force-exclusion",
          "--stdin",
          "%filepath"
        },
        parseJson = {
          errorsRoot = "files[0].offenses",
          line = "location.start_line",
          endLine = "location.last_line",
          column = "location.start_column",
          endColumn = "location.end_column",
          message = "[${cop_name}] ${message}",
          security = "severity"
        },
        securities = {
          fatal = "error",
          error = "error",
          warning = "warning",
          convention = "info",
          refactor = "info",
          info = "info"
        }
      },
      shellcheck = {
        command = "shellcheck",
        debounce = 100,
        args = { "--format=gcc", "-"},
        offsetLine = 0,
        offsetColumn = 0,
        sourceName = "shellcheck",
        formatLines = 1,
        formatPattern = {
          "^[^:]+:(\\d+):(\\d+):\\s+([^:]+):\\s+(.*)$",
          {
            line = 1,
            column = 2,
            message = 4,
            security = 3
          }
        },
        securities = {
          error = "error",
          warning = "warning",
          note = "info"
        }
      },
      languagetool = {
        command = "languagetool",
        debounce = 200,
        args = {"-"},
        offsetLine = 0,
        offsetColumn = 0,
        sourceName = "languagetool",
        formatLines = 2,
        formatPattern = {
          "^\\d+?\\.\\)\\s+Line\\s+(\\d+),\\s+column\\s+(\\d+),\\s+([^\\n]+)\nMessage:\\s+(.*)$",
          {
            line = 1,
            column = 2,
            message = { 4, 3 }
          }
        }
      }
    },
    formatters = {
      dartfmt = {
        command = "dartfmt",
        args = { "--fix" }
      },
      rubocop = {
        command = "bundle",
        args = { "exec",
          "rubocop",
          "-a",
          "%filepath",
          ">",
          "tmp/rubocop"
        }
      }
    },
    filetypes = {
      sh = "shellcheck",
      email = "languagetool",
      ruby = "rubocop"
    },
    formatFiletypes = {
      dart = "dartfmt",
      ruby = "rubocop"
    }
  }
}
```
