### ISSUE TITLE
bad argument #1 to 'unpack' (table exp expected, got string)

### ISSUE THREAD

**Issue by winkee01** [jose-elias-alvarez/null-ls.nvim#871]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.8.0-dev+10-ge73ef5c09

### Operating System

macOS Montery 12.3

### Minimal config

curl -fLO https://raw.githubusercontent.com/jose-elias-alvarez/null-ls.nvim/main/scripts/minimal_init.lua

### Steps to reproduce

nvim --clean -u minimal_init.lua

### Expected behavior

no error

### Actual behavior

Error executing vim.schedule lua callback: ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:39: bad argument #1 to 'unpack' (table expected, got string)
stack traceback:
        [C]: in function 'unpack'
        ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:39: in function 'capability_is_disabled'
        ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:50: in function 'supports_method'
...

### Debug log

NONE

### Help

No

### Implementation help

the error is caused by **line #39** from `null-ls/client.lua`

```
local on_init = function(new_client, initialize_result)
    local capability_is_disabled
    if u.has_version("0.8") then
        capability_is_disabled = function(method)
            -- TODO: extract map to prevent future issues
            local required_capability = lsp._request_name_to_capability[method]                   -- Line #37
            return not required_capability
                or vim.tbl_get(new_client.server_capabilities, unpack(required_capability)) == false  -- Line #39
        end
    else
        capability_is_disabled = function(method)
            return new_client.resolved_capabilities[methods.request_name_to_capability[method]] == false
        end
    end
```

I inspected NeoVim's runtime source code, which is `$RUNTIME/lua/lsp/lsp.lua`, the function **`_request_name_to_capability`** is this:

```
lsp._request_name_to_capability = {
  ...
  ['textDocument/prepareCallHierarchy'] = 'call_hierarchy';
  ...
}
```

clearly, function **`_request_name_to_capability`** returns a string, not a table, therefore, there is a false calling in Line #39 of `null-ls/client.lua`

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by Mephistophiles** [comment]
this issue is a duplicate of #860

**Comment by Mephistophiles** [comment]
@winkee01 try to rebuild neovim from the latest master
@jose-elias-alvarez what do you think about adding it to the FAQ?

**Comment by winkee01** [comment]
> @winkee01 try to rebuild neovim from the latest master @jose-elias-alvarez what do you think about adding it to the FAQ?

no problem with it, I will try to rebuild neovim.

**Comment by winkee01** [comment]
@Mephistophiles I rebuilt neovim and the problem is fixed, the version is `NVIM v0.8.0-dev+227-g6613f58ce`. Thanks a lot

**Comment by jose-elias-alvarez** [comment]
Thanks @Mephistophiles! I'll add this to the FAQ if I see the same issue again (hopefully most users on Neovim master will have rebuilt soon).

**Comment by winkee01** [comment]
FYI, neovim changed its api on Apirl 30, 2022, the commit hash is `#c618b314c6`.

<img width="1052" alt="CleanShot 2022-05-18 at 12 02 10@2x" src="https://user-images.githubusercontent.com/49930785/168954707-6abb4465-8ea2-47de-b1dc-c0d67d25f093.png">

**Comment by MaxVerevkin** [comment]
I use latest master and I'm still getting this error.

**Comment by jose-elias-alvarez** [comment]
> I use latest master and I'm still getting this error.

I can almost guarantee you that this is not the same issue if you are on the latest version of null-ls and the latest Neovim master (`NVIM v0.8.0-dev+300-ge5490b38b` as of my writing this). If you are able to reproduce this on the *very latest* master (not something provided by a package manager or similar), please open a separate issue.

**Comment by jose-elias-alvarez** [comment]
> > I can almost guarantee you that this is not the same issue if you are on the latest version of null-ls and the latest Neovim master (NVIM v0.8.0-dev+300-ge5490b38b as of my writing this).
> 
> Just to verify before I open a new issue, I'm getting this (I cant find a single difference...):
> 
> ![image](https://user-images.githubusercontent.com/34583604/170125576-8ef1ea29-dc32-4941-b7d4-c60c17392a5d.png)
> 
> > $ vi --version
> > NVIM v0.8.0-dev+300-ge5490b38b
> > Build type: Release
> > LuaJIT 2.1.0-beta3
> > Compiled by maxv

It looks like there something wrong with your runtime files - if you look at [line 474 in buf.lua](https://github.com/neovim/neovim/blob/e5490b38b720d04a3361fd83f50099f3a71dd6c1/runtime/lua/vim/lsp/buf.lua#L474), you'll see that it doesn't match your trace. I also don't know how you are calling `document_highlight`,  which could be another source of issues.

Please try cleaning your runtime files, rebuilding again, and then open an issue with a minimal `init.lua` if you're still having problems.

**Comment by MaxVerevkin** [comment]
Oh, I forgot I have stable neovim installed on my system too, and new neovim (installed in ~.local/) used incorrect runtime files. Thanks for pointing this out!

**Comment by DanCardin** [comment]
Fwiw, I was hitting this problem, then realized had previously installed/enabled `lewis6991/impatient.nvim` and required an `LspCacheClear`. In case anyone else runs into the same thing

**Comment by kahnclusions** [comment]
I had the same issue as above, installing latest master wasn't enough, I also had to `brew uninstall neovim` because I had an older stable install on my machine and that was causing runtime conflicts.

**Comment by jose-elias-alvarez** [comment]
@shaeinst Can you please update to the latest Neovim master and follow the instructions in the issue template here to make sure this is isolated? I cannot reproduce this.

**Comment by shaeinst** [comment]
```bash
# nvim --version:
NVIM v0.8.0-dev+436-g279bc71f3-dirty
```
```bash
# Operating System 
Linux IL 5.18.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 09 Jun 2022 16:14:10 +0000 x86_64 GNU/Linux

```
My minimal null-ls config
```lua



local builtins = require("null-ls.builtins")
local formatting = builtins.formatting
local sources = {}
local load = false

-- for Lua
if vim.fn.executable("lua-format") == 1 then
	load = true
	sources[#sources+1] = formatting.lua_format.with({
		command = "lua-format",
		args = {
			"--indent-width",
			"1",
			"--tab-width",
			"4",
			"--use-tab",
			"--chop-down-table",
			"--extra-sep-at-table-end",
		},
	})
end

if load then
	require("null-ls").setup({
		sources = sources
	})
end

local keymap = vim.api.nvim_set_keymap
keymap('n', '<Space>fm', '<ESC>:lua vim.lsp.buf.formatting()<CR>', {noremap = true, silent = true})
```
Degu Log:
```lua
[WARN  Mon 06 Jun 2022 01:00:10 PM +0545] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:58: error in formatting handler: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:483: Expected 2 arguments
[WARN  Thu 09 Jun 2022 12:40:35 AM +0545] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:58: error in formatting handler: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:483: Expected 2 arguments
[WARN  Fri 10 Jun 2022 12:51:31 AM +0545] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:58: error in formatting handler: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:483: Expected 2 arguments
[WARN  Fri 10 Jun 2022 12:51:37 AM +0545] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:58: error in formatting handler: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:483: Expected 2 arguments
[WARN  Fri 10 Jun 2022 12:51:40 AM +0545] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:58: error in formatting handler: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:483: Expected 2 arguments
```
Error on formatting with null-ls
```lua
E5108: Error executing lua ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:39: bad argument #1 to 'unpack' (table expected
, got string)
stack traceback:
        [C]: in function 'unpack'
        ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:39: in function 'capability_is_disabled'
        ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:50: in function <...te/pack/packer/start/null-ls.nvim/lua/null-ls/
client.lua:48>
        vim/shared.lua: in function 'tbl_filter'
        /usr/local/share/nvim/runtime/lua/vim/lsp/buf.lua:124: in function 'select_client'
        /usr/local/share/nvim/runtime/lua/vim/lsp/buf.lua:156: in function 'formatting'
        [string ":lua"]:1: in main chunk
```

tested it  without any other config (just null-ls config) and neovim latest master
