### ISSUE TITLE
prettier-standard is abandonned, can be replaced with prettier-eslint

### ISSUE THREAD

**Issue by yanovich** [jose-elias-alvarez/null-ls.nvim#877]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.8

### Operating System

ubuntu

### Minimal config

local null_ls_status_ok, null_ls = pcall(require, "null-ls")
if not null_ls_status_ok then
  return
end

local formatting = null_ls.builtins.formatting
local diagnostics = null_ls.builtins.diagnostics

null_ls.setup({
  debug = false,
  sources = {
    formatting.prettier_standard,
    diagnostics.standardjs,
    formatting.black.with({ extra_args = { "--fast" } }),
    diagnostics.flake8,
    formatting.stylua.with({ extra_args = { "--indent-type", "Spaces", "--indent-width", "2" } }),
    formatting.clang_format,
  },
})

### Steps to reproduce

yarn add --dev prettier-statndard

### Expected behavior

found 0 vulnerabilities

### Actual behavior

3 vulnerabilities found - Packages audited: 894

### Debug log

n/a

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

prettier-eslint-cli package works from cli as expected.

I've tried to create a built-in in place in the null-ls plugin dir, but it doesn't work

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
I'm confused by this issue - if the issue is that `prettier-standard` depends on outdated / vulnerable packages, that's not really related to null-ls. There hasn't been a new version in a while, but since there are projects in the wild that rely on it, I don't think it makes sense to completely remove support here.

I also don't know what this has to do with the issue, but we don't support `prettier-eslint-cli`. If you'd like to add support, you can open a PR and I can help out.

**Comment by yanovich** [comment]
```
$ yarn audit
yarn audit v1.22.18
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ critical      │ Prototype Pollution in minimist                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.2.6                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ prettier-standard                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ prettier-standard > prettierx > minimist                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1067342                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Regular Expression Denial of Service in postcss              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ postcss                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=7.0.36                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ prettier-standard                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ prettier-standard > prettierx > postcss-less > postcss       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1070012                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Regular Expression Denial of Service in trim                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ trim                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.0.3                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ prettier-standard                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ prettier-standard > prettierx > remark-parse > trim          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1070259                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
```
`prettier-standard` has a critical vulnerability. it's easy to fix, but it's not been fixed for a year. `prettier-eslint-cli` is fine. `standard.js` uses `eslint` so it just works.

**Comment by jose-elias-alvarez** [comment]
It's likely that we support other sources that are abandoned or have vulnerabilities, but I still don't think it makes sense for us to remove them. This case is pretty clear-cut, but there are others where it would be harder to make a judgment. For example, if a repo hasn't been updated in 5 years, does that mean that the package is completely stable or that it's abandoned? Other package managers also don't have these types of warnings, so it's unrealistic to investigate every case.

In my experience, many projects in the JS ecosystem rely on older packages, so users don't really have a choice. I'd support adding a warning to the documentation, but I don't plan on removing the source completely.

**Comment by jose-elias-alvarez** [comment]
Closing this as I don't plan on acting on this issue.
