### ISSUE TITLE
Export from_pattern/from_patterns/from_json from diagnostics module

### ISSUE THREAD

**Issue by andrewferrier** [jose-elias-alvarez/null-ls.nvim#88]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Thanks for your great work on null-ls. It's a great idea and I'm already using some of the built-in diagnostic helpers.

However, when building my own, I'm a bit surprised that the `from_pattern`/`from_json` functions from the `null-ls.builtins.diagnostics` module are not exported. To me, these functions are both really useful, and kind of essential to match simple regex-style patterns that many linters output. For example, this is typically how you parse responses when using EFM as a language server, for example.

It would be great if these functions were available for custom diagnostic helpers, as well as the built-in ones.

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

Recommendation / opinion on where / how to expose it.

**Comment by jose-elias-alvarez** [comment]
Exporting the helpers would be simple, and I'm not at all opposed to it. I'd say if there's a reason we don't currently do so, it's to encourage people to contribute built-ins. In this case, is it a source you'd want to contribute?

**Comment by andrewferrier-ibm** [comment]
Yeah, I'd like to contribute built-ins for `checkmake` and `mdl` at least. You'll take pull requests I assume?

**Comment by andrewferrier-ibm** [comment]
(I still think there's value in exporting the helpers by the way, can be very useful for people who maybe have local custom setup/wrappers around linters, also helpers when developing new built-ins, there's a bunch of reasons....)

**Comment by jose-elias-alvarez** [comment]
PRs are very welcome! And I can see that it would be useful, so the next time I'm working on the plugin, I'll move the helpers and expose them from `"null-ls.helpers"`.

**Comment by jose-elias-alvarez** [comment]
Closed by 1724d220448a327de92be556e2edb2b3cf2117c1.
