### ISSUE TITLE
Max Severity of diagnostics

### ISSUE THREAD

**Issue by AnonymusRaccoon** [jose-elias-alvarez/null-ls.nvim#881]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Null-ls should have an option to limit the severity of diagnostic to a value. Lint/Format diagnostic should be differentiable from compile error or warnings. Right now, indents or missing semicolon are highlighted as error by ESLint, so it'shard to see real errors.

### Help

No

**Comment by jose-elias-alvarez** [comment]
I don't agree with the core premise here, I think many projects use linters to catch errors that may cause crashes / compilation errors. Either way, ESLint specifically lets you configure its diagnostics to whatever level you want, and null-ls lets you arbitrarily modify diagnostics using the [diagnostics-postprocess](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md#diagnostics-postprocess) hook.

**Comment by AnonymusRaccoon** [comment]
I don't think that ESLint levels should be reduced, I want ESLint errors to show as errors when I ask for a lint, but when I am typing in my IDE, I don't want to prioritize those issues. Having the option to reduce the max level would fix this issue.

Diagnostics-postprocess could work but I since someone who wants to reduce the max level of one linter would probably want that for all linters, it could be a good option to add.

**Comment by jose-elias-alvarez** [comment]
> since someone who wants to reduce the max level of one linter would probably want that for all linters

Again, I'm not sure I agree with the premise. I think this is a pretty niche use case, and it should already be possible to replicate the functionality by (for example) loading your sources into a table and mapping over each entry to apply a shared `diagnostics_postprocess`. I don't think this is necessary as a core option.

**Comment by jose-elias-alvarez** [comment]
Here's a more concrete example of what I meant:

```lua
local null_ls = require("null-ls")

local sources = {
    null_ls.builtins.diagnostics.markdownlint,
    null_ls.builtins.diagnostics.eslint,
}

null_ls.setup({
    sources = vim.tbl_map(function(source)
        return source.with({
            diagnostics_postprocess = function(diagnostic)
                if diagnostic.severity == vim.diagnostic.severity.ERROR then
                    diagnostic.severity = vim.diagnostic.severity.WARN
                end
            end,
        })
    end, sources),
})
```

I think this is a pretty solid way to compose our existing config features to achieve the result you're looking for, and I don't think the use case is common enough to justify adding another option.
