### ISSUE TITLE
Support for `sca2d`

### ISSUE THREAD

**Issue by MaxVerevkin** [jose-elias-alvarez/null-ls.nvim#885]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

[`sca2d`](https://gitlab.com/bath_open_instrumentation_group/sca2d) is a linter for [OpenSCAD](https://openscad.org/).

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by jose-elias-alvarez** [comment]
I should really document this, but to give you a rough description of the general process for contributing a new linter if you want to give it a shot:

1. Examine the linter's options and see what it takes to output diagnostics in a structured format from the command line. JSON is best if it's supported, followed by plain lines that contain row and column numbers. Everything else will require additional work. You can also try to determine if the linter is using `stderr`, though you could also save that for the testing phase.
2. See if the linter supports `stdin` - if not, investigate if the linter works when reading the same content from a temporary file so we can use (the to_temp_file option)[https://github.com/jose-elias-alvarez/null-ls.nvim/blob/af192263b33764fa91d3fa578abd9e674a1984c7/doc/HELPERS.md#L210]. If neither works, then we'll have to run the linter on save only, which is a worse experience.
3. Find other existing built-ins that you can use as an example. [vint](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics/vint.lua) is a good example for a JSON linter, and [markdownlint](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics/markdownlint.lua) is a good example of a linter that parses lines. By this point, we have a good variety, so it should be possible to find an example for most situations, including manually parsing output, but if not you can open a draft PR for feedback.
4. Fork null-ls and start testing your source locally. For diagnostics, we want to make sure that it shows diagnostics accurately, doesn't error out on unexpected output, and updates when there are changes made to the buffer (unless the linter can only run on save for the reasons described above.) Enable debug mode and make sure the linter is getting spawned with the correct arguments and providing the output you expect.
5. Consider adding code coverage - this can prevent issues when the linter is updated and can also help you test additional cases.
