### ISSUE TITLE
[Bug] Cursor position in another window is not restored

### ISSUE THREAD

**Issue by tamago324** [jose-elias-alvarez/null-ls.nvim#9]
- `nvim --version`: NVIM v0.5.0-dev+1384-gf2906a466
- Operating system/version: Manjaro

**Describe the bug**

When a buffer is displayed in multiple windows and formatting is executed, there is a issue that the cursor position of the buffer in the window other than the current buffer becomes the first position.

**To Reproduce**

```vim
set encoding=utf-8

filetype plugin indent on
if has('vim_starting')
  let s:pluin_manager_dir='~/.config/nvim/.plugged/vim-plug'
  execute 'set runtimepath+=' . s:pluin_manager_dir
endif
call plug#begin('~/.config/nvim/.plugged')
Plug 'neovim/nvim-lspconfig'
Plug 'nvim-lua/plenary.nvim'
Plug 'jose-elias-alvarez/null-ls.nvim'
call plug#end()

set number
set nobackup
set nowritebackup
set noswapfile
set updatecount=0
set backspace=indent,eol,start
language messages en_US.utf8

lua << EOF

local null_ls = require'null-ls'

null_ls.setup {
  on_attach = function(client)
    vim.cmd([[autocmd BufWritePost <buffer> lua vim.lsp.buf.formatting()]])
  end,
  sources = {
    null_ls.builtins.formatting.stylua,
  }
}

EOF
```

<details><summary>sample.lua</summary><div>

```lua
function func1(a, b)
  local x = a + b
  local y = [[








































  ]]

  return x
end

function func2(a, b)
  local x = a + b

  return x
end
```

</div></details>

1. `nvim -u minivimrc -i NONE`
2. `:e sample.lua`
3. `:normal! G3o` (Edit buffer)
4. `:vsplit | normal! Gzz` (Split and move the cursor)
5. `:wincmd w`
6. `:write` (Format)

The cursor position of the window opened with 3 is the first line.
This issue also affects windows in other tabs.

**Expected behavior**

Cursor positions in all window buffers will be displayed at their original positions.

**Screenshots**

https://user-images.githubusercontent.com/16581287/122045716-08148980-ce19-11eb-99de-9499256dfcc8.mp4

Thank you!

**Comment by jose-elias-alvarez** [comment]
This is actually a bug with `vim.lsp.buf.formatting`, which is itself caused by `nvim_buf_set_lines` (see [this issue](https://github.com/neovim/neovim/issues/14645)). I hope that Neovim can improve this, but in the meantime, 3a84ee5dc69539dfcb424f30d7198734ce661a82 should take care of it. Could you update the plugin and see if that works for you?

**Comment by tamago324** [comment]
Thank you for your quick response!
I see, it's a bug in neovim itself. So it can't be helped.
I checked it, and it behaves a little strange.
You may need to restore the topline that can be obtained with `winsaveview()`.

https://user-images.githubusercontent.com/16581287/122198555-3905c480-ced4-11eb-955e-443d8937f0be.mp4

**Comment by jose-elias-alvarez** [comment]
Thanks for the suggestion! I just pushed a commit that uses `windo winsaveview`, which should ensure that everything is saved and restored. Let me know if that works.

**Comment by tamago324** [comment]
Confirmed.
The issue has been resolved.
Thank you very much!
