### ISSUE TITLE
 bad argument #1 to 'unpack' (table expected , got string)

### ISSUE THREAD

**Issue by shaeinst** [jose-elias-alvarez/null-ls.nvim#919]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.8.0-dev+436-g279bc71f3-dirty

### Operating System

Linux IL 5.18.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 09 Jun 2022 16:14:10 +0000 x86_64 GNU/Linux

### Minimal config

```lua
local builtins = require("null-ls.builtins")
local formatting = builtins.formatting
local sources = {
	formatting.lua_format.with({
			command = "lua-format",
			args = { "--indent-width", "1", "--tab-width", "4", "--use-tab", "--chop-down-table", },
		})
}
require("null-ls").setup({
	sources = sources
})

```

### Steps to reproduce

``` lua
E5108: Error executing lua ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:39: bad argument #1 to 'unpack' (table expected
, got string)
```
as you can clearly see, [this line](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/ff40739e5be6581899b43385997e39eecdbf9465/lua/null-ls/client.lua#L39) complaining  about ```string and table```. That's why ```unpack``` causing error because it got string instead of table. 
i tried with removing ```unpack``` from that line and every thing worked fine as expected.

### Expected behavior

formatting with null-ls should work on latest neovim v0.8 as it working with v0.7

### Actual behavior

formatting with null-ls should does not work with latest neovim v0.8 but it works fine with v0.7

### Debug log

``` lua
E5108: Error executing lua ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:39: bad argument #1 to 'unpack' (table expected
, got string)
stack traceback:
        [C]: in function 'unpack'
        ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:39: in function 'capability_is_disabled'
        ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:50: in function <...te/pack/packer/start/null-ls.nvim/lua/null-ls/
client.lua:48>
        vim/shared.lua: in function 'tbl_filter'
        /usr/local/share/nvim/runtime/lua/vim/lsp/buf.lua:124: in function 'select_client'
        /usr/local/share/nvim/runtime/lua/vim/lsp/buf.lua:156: in function 'formatting'
```

``` lua
[TRACE Fri 17 Jun 2022 09:30:10 AM +0545] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:106: starting null-ls client
[TRACE Fri 17 Jun 2022 09:30:10 AM +0545] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method initialize
[DEBUG Fri 17 Jun 2022 09:30:10 AM +0545] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:161: unable to notify client for method textDocument/didOpen (client not active): {
  textDocument = {
    uri = "file:///home/uselay/codeDNA/ws/lab/Experiment/lua.lua"
  }
}
[TRACE Fri 17 Jun 2022 09:30:10 AM +0545] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method initialized
[TRACE Fri 17 Jun 2022 09:30:10 AM +0545] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didOpen
[TRACE Fri 17 Jun 2022 09:30:10 AM +0545] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Fri 17 Jun 2022 09:30:10 AM +0545] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:24: no generators available

```

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by griffenliu** [comment]
I have the same problem.

**Comment by jose-elias-alvarez** [comment]
I can't replicate this. Your issue is almost definitely outdated runtime files - looking at the error trace, it points at [this line](https://github.com/jose-elias-alvarez/neovim/blob/901fde60c6a4679648e9c0bd714a0c6dac97fe31/runtime/lua/vim/lsp/buf.lua#L124) followed by [this line](https://github.com/jose-elias-alvarez/neovim/blob/901fde60c6a4679648e9c0bd714a0c6dac97fe31/runtime/lua/vim/lsp/buf.lua#L156), neither one of which actually corresponds to the referenced function. You can verify by running `:lua print(vim.inspect(vim.lsp._request_name_to_capability))`. If this prints a list with string values (not table values) your runtime files don't correspond to the version of Neovim you're using.

If that's the case, all I can suggest is to clean out your runtime files, rebuild from source (or use whatever method you used in the first place), and make sure you don't have any other versions of Neovim installed.

**Comment by shaeinst** [comment]
output of ``` :lua print(vim.inspect(vim.lsp._request_name_to_capability))```
```lua
{
  ["codeLens/resolve"] = "code_lens_resolve",
  ["textDocument/codeAction"] = "code_action",
  ["textDocument/codeLens"] = "code_lens",
  ["textDocument/completion"] = "completion",
  ["textDocument/declaration"] = "declaration",
  ["textDocument/definition"] = "goto_definition",
  ["textDocument/documentHighlight"] = "document_highlight",
  ["textDocument/documentSymbol"] = "document_symbol",
  ["textDocument/formatting"] = "document_formatting",
  ["textDocument/hover"] = "hover",
  ["textDocument/implementation"] = "implementation",
  ["textDocument/prepareCallHierarchy"] = "call_hierarchy",
  ["textDocument/prepareRename"] = "rename",
  ["textDocument/rangeFormatting"] = "document_range_formatting",
  ["textDocument/references"] = "find_references",
  ["textDocument/rename"] = "rename",
  ["textDocument/signatureHelp"] = "signature_help",
  ["textDocument/typeDefinition"] = "type_definition",
  ["workspace/executeCommand"] = "execute_command",
  ["workspace/symbol"] = "workspace_symbol"
}
```
let me try with clean neovim

**Comment by shaeinst** [comment]
@jose-elias-alvarez you're correct. My runtime files were corrupted. But, i tried by uninstalling and reinstalling neovim, i was still getting that error. after deleting ~/.local/share/nvim and reinstalling, it get fixed.
Thanks.

**Comment by shaeinst** [comment]
and now i understand why, because i have installed nevim-0.7 using My distoro's package manager (pacman) and that's why  ```~/.local/share/nvim``` belonged to ```neovim-0.7```. so, whenever i ran ```nevim-0.8```, it's was using ```nevim-0.7```'s runtime files.
