### ISSUE TITLE
BufWritePost Error -- `eslint_d` still properly working

### ISSUE THREAD

**Issue by wildbeard** [jose-elias-alvarez/null-ls.nvim#931]
### FAQ

- [x] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.7.1-dev+66-ge820c6d7c

### Operating System

Pop_OS! 22.04

### Minimal config

Note: with this config I can't seem to get `null_ls` to attach to any file type (js or vue). Volar and tsserver are attaching properly. I added Volar config as I figured it might be related to the issue.

```lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
  local path_sep = on_windows and "\\" or "/"
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir
if on_windows then
  temp_dir = vim.loop.os_getenv("TEMP")
else
  temp_dir = "/tmp"
end

local attachFn = function(isVolar)
  local attach = function(client, bufnr)
    -- LSP Keybinds

    if isVolar then
      client.resolved_capabilities.document_formatting = false
    elseif client.resolved_capabilities.document_formatting then
      vim.cmd([[
          augroup LspFormatting
              autocmd! * <buffer>
              autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()
          augroup END
        ]])
    end
  end

  return attach
end

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
  local null_ls = require("null-ls")
  -- add only what you need to reproduce your issue
  null_ls.setup({
    sources = {
      null_ls.builtins.diagnostics.eslint_d.with({
        diagnostics_format = "#{m} (#{s}: #{c})"
      }),
      null_ls.builtins.code_actions.eslint_d,
      null_ls.builtins.formatting.eslint_d,
    },
    on_attach = attachFn(false),
    debug = true,
  })
end

local function load_plugins()
  -- only add other plugins if they are necessary to reproduce the issue
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "jose-elias-alvarez/null-ls.nvim",
        module = 'lspconifg',
        requires = { "nvim-lua/plenary.nvim" },
        config = null_ls_config,
      },
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  })
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
  load_plugins()
  require("packer").sync()
else
  load_plugins()
  require("packer").sync()
end

```

### Steps to reproduce

Note: My primary config uses `nvim-lsp-installer` for the LUA, PHP, and Typescript lang servers. This config works w/out issue on my MB running Catalina 10.15.6. It uses Vim Plug instead of Packer, and I don't think null-ls had been updated in a ~month. This issue started to occur once I switched to a Linux machine running Pop_OS! 22.04.

* Edit any javascript type file (`ts`, `js`, `vue`)
* File correctly shows `eslint_d` warnings and errors
* File saves and cleans up formatting correctly (ie: a missing `;` at the end of the line shows an error, and when saved it is added)
* Receive the following `BufWritePost` error:
```
Error detected while processing BufWritePost Autocommands for "<buffer=15>":
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/lsp.lua:122: Expected Lua number
```
* I did disable `null-ls` to check if the error was coming from the plugin and the error stopped showing itself

### Expected behavior

I do not receive the following error:
```
Error detected while processing BufWritePost Autocommands for "<buffer=15>":
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/lsp.lua:122: Expected Lua number
```

### Actual behavior

I receive the following error:
```
Error detected while processing BufWritePost Autocommands for "<buffer=15>":
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/lsp.lua:122: Expected Lua number
```

### Debug log

Output in nvim's `messages`
```
"File.vue" 281L, 7703B written                                                                                                                                                                           
Error detected while processing BufWritePost Autocommands for "<buffer=15>":
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/lsp.lua:122: Expected Lua number
stack traceback:
        [C]: in function 'nvim_buf_get_option'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:122: in function 'buf_get_line_ending'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:281: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:302: in function 'text'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1134: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:164: in function 'for_each_buffer_client'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1130: in function '_text_document_did_save_handler'
        [string ":lua"]:1: in main chunk
```

`null-ls` debug log. `null-ls` is showing `command eslint_d is not executable` but proceeds to show errors/warnings from `eslint_d`.
```
  [ERROR Thu 23 Jun 2022 04:15:34 PM MDT] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:180: command eslint_d is not executable (make sure it's installed and on your $PATH)    
  [TRACE Mon 27 Jun 2022 07:54:47 AM MDT] ...l/share/nvim/plugged/null-ls.nvim/lua/null-ls/client.lua:106: starting null-ls client    
  [TRACE Mon 27 Jun 2022 07:54:47 AM MDT] ...ocal/share/nvim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method initialize    
  [TRACE Mon 27 Jun 2022 07:54:47 AM MDT] ...ocal/share/nvim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method initialized    
  [TRACE Mon 27 Jun 2022 07:54:47 AM MDT] ...ocal/share/nvim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didOpen    
  [TRACE Mon 27 Jun 2022 07:54:47 AM MDT] ...are/nvim/plugged/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN    
  [DEBUG Mon 27 Jun 2022 07:54:47 AM MDT] ...ed/null-ls.nvim/lua/null-ls/helpers/command_resolver.lua:35: attempting to find local executable node_modules/.bin/eslint_d    
  [DEBUG Mon 27 Jun 2022 07:54:47 AM MDT] ...ed/null-ls.nvim/lua/null-ls/helpers/command_resolver.lua:41: Unable to resolve command [node_modules/.bin/eslint_d], skipping further lookups    
  [DEBUG Mon 27 Jun 2022 07:54:47 AM MDT] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:286: Using dynamic command for [eslint_d], got: "eslint_d"    
  [DEBUG Mon 27 Jun 2022 07:54:47 AM MDT] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:346: spawning command "eslint_d" at /home/ph/projects/project with args { "-f", "json", "--stdin", "--stdin-file  name", "/home/ph/projects/project/File.vue" }
  [TRACE Mon 27 Jun 2022 07:54:47 AM MDT] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:217: error output: nil    
  [TRACE Mon 27 Jun 2022 07:54:47 AM MDT] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:218: output: [{"filePath":"/home/ph/projects/project/File.vue","messa  ges":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[{"ruleId":"lines-around-directive","replacedBy":["padding-line-between-statements"]},{"ruleId":"no-spaced-func","replacedBy  ":["func-call-spacing"]},{"ruleId":"global-require","replacedBy":[]},{"ruleId":"no-buffer-constructor","replacedBy":[]},{"ruleId":"no-new-require","replacedBy":[]},{"ruleId":"no-path-concat","replacedBy":[]}]}]
  [TRACE Mon 27 Jun 2022 07:54:47 AM MDT] ...re/nvim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:169: received diagnostics from source 1    
  [TRACE Mon 27 Jun 2022 07:54:47 AM MDT] ...re/nvim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:170: {}    
  [TRACE Mon 27 Jun 2022 07:54:49 AM MDT] ...ocal/share/nvim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method textDocument/formatting    
  [TRACE Mon 27 Jun 2022 07:54:49 AM MDT] ...are/nvim/plugged/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_FORMATTING    
  [DEBUG Mon 27 Jun 2022 07:54:49 AM MDT] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:346: spawning command "eslint_d" at /home/ph/projects/sockeye with args { "--fix-to-stdout", "--stdin", "--stdin-filename", "/home/ph/projects/project/File.vue" }
  [TRACE Mon 27 Jun 2022 07:54:49 AM MDT] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:217: error output: nil    
  [TRACE Mon 27 Jun 2022 07:54:49 AM MDT] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:218: output: <template>
  ... the entire Vue file output ends up here
```

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
Can you pare down the config so that it *only* includes null-ls-related code, verify that the issue still occurs, and then edit the issue?

**Comment by jose-elias-alvarez** [comment]
Hmm, I can't replicate this with 0.7.2. A similar issue came up in #844, though we never resolved it. 

One thing I notice from your error trace is that the line numbers are off - on 0.7, [_text_document_did_save_handler](https://github.com/neovim/neovim/blob/44d0c6572b60233ded9bd73915636f8e00841dff/runtime/lua/vim/lsp.lua#L1189) has a different line number. Have you ever tried building / installing Neovim from the master branch? If so, I wonder if you have an issue with your runtime files. There is a mention of a similar issue in [this PR](https://github.com/neovim/neovim/pull/18591).

**Comment by wildbeard** [comment]
Rebuilt w/version v0.7.2 and receiving the same error using my standard config and the minimal config.
```
± % nvim --version
NVIM v0.7.2
Build type: Release
```

**Comment by jose-elias-alvarez** [comment]
Do you get the same issue with an actual language server that supports formatting? Nothing in the error trace is specific to null-ls.

**Comment by wildbeard** [comment]
I don't believe so. I modified my standard config to disable null-ls and turn volar's formatting back on. Volar formats my vue files just fine without that error.

**Comment by jose-elias-alvarez** [comment]
No worries, just wanted to rule that out. Does this *only* occur when you set up the formatting autocommand, or do you always get the error when null-ls is attached? You might want to try wiping out your runtime files and running `make distclean` before rebuilding just to make sure there's no interference there.

Otherwise, I'm having a hard time wrapping my head around the issue. The autocommand that's throwing the error is [set up here](https://github.com/neovim/neovim/blob/44d0c6572b60233ded9bd73915636f8e00841dff/runtime/lua/vim/lsp.lua#L1238), which causes [this line](https://github.com/neovim/neovim/blob/44d0c6572b60233ded9bd73915636f8e00841dff/runtime/lua/vim/lsp.lua#L1197) to throw. The error strongly indicates that `bufnr` is `nil` at that point, but I don't see how that's possible, since the autocommand specifically passes in a buffer number (and even if it were `nil`, the `resolve_bufnr` helper would make sure it's defined). 

If you don't mind digging into the relevant runtime file (which should be located at `/usr/share/nvim/runtime/lua/vim/lsp.lua` according to your trace) and adding some `print` statements around the relevant variables, we can maybe try to figure out what's going on, but otherwise I don't think I can help more, since the cause of the problem is not clear and I cannot replicate it locally.

**Comment by wildbeard** [comment]
I did run `make distclean` after pulling the 0.7.2 tag and before building.

I modified `/usr/share/nvim/runtime/lua/vim/lsp.lua` and added `print` on lines 122 (`buf_get_line_ending`) and 1131 (`lsp._text_document_did_save_handler`).

And here is the output when saving:
```
buf_get_line_ending 12                                                                                                                                                                                                                               
buf_get_line_ending 12
buf_get_line_ending 12
"pages/wild-salmon-delivered.vue" 361L, 15305B written
_text_document_did_save_handler 12
buf_get_line_ending nil
Error detected while processing BufWritePost Autocommands for "<buffer=12>":
```

**Comment by jose-elias-alvarez** [comment]
Very strange - I have no idea how `bufnr` could be defined in the save handler but not in `buf_get_line_ending`. 

One thing that jumps out at me again is that the line numbers you mentioned do not match the line numbers in [the corresponding version of `lsp.lua`](https://github.com/neovim/neovim/blob/release-0.7/runtime/lua/vim/lsp.lua). Are you sure that you're rebuilding in a way that cleans existing runtime files, or could you try deleting them manually? Other than that I don't think there's much more I can suggest.

**Comment by jose-elias-alvarez** [comment]
Glad you figured it out!
