### ISSUE TITLE
Selene diagnostic not using configuration file

### ISSUE THREAD

**Issue by craigmac** [jose-elias-alvarez/null-ls.nvim#933]
### Discussed in https://github.com/jose-elias-alvarez/null-ls.nvim/discussions/932

<div type='discussions-op-text'>

<sup>Originally posted by **craigmac** June 27, 2022</sup>
When I run `selene init.lua` I get no errors, but when it runs in nvim (HEAD), it keeps marking `vim` as both `warning[unscoped_variables]` and `error[undefined_variable]` (wording from the null-ls.log). Is it missing a flag that I can configure when setting it up? I've checked the issues, wiki, and faq, and ended up here before filing as a bug in case I'm missing the obvious. `selene init.lua` defaults to looking for a `selene.toml` in the current directory when used on the CLI, and doesn't report any errors for init.lua. I'm using a `selene.toml` and `neovim.toml` that I've copied from the base of the nvim-lspconfig repo here: https://github.com/neovim/nvim-lspconfig</div>

**Comment by unphased** [comment]
Thanks. I was so close to trying this myself and yeah all it needed was the selene.toml in repo root (in my case `~/.vim`. I kept testing it first placing them in `~/.vim/nvim` (that dir being symlinked to `~/.config/nvim`)
