### ISSUE TITLE
Deno Lint

### ISSUE THREAD

**Issue by jukefr** [jose-elias-alvarez/null-ls.nvim#939]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Deno (https://deno.land/) has a built in linter, `deno lint`.

It would be nice to have it supported in null-ls.

I looked around the code a bit but I am not familiar at all with vim tooling but I think it could look something like

```lua
{
        command = "deno lint",
        args = { "--json", "-" },
        to_stdin = true,
        format = "json_raw",
        check_exit_code = function(code)
	        return code <= 1
        end,
        filetypes = { "typescript", "typescriptreact", "javascript", "javascriptreact" },
        condition = function(utils)
	        return utils.root_has_file({ "import_map.json" })
        end,
},
```

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

- need to figure out proper command to run linter (`deno lint --json - | cat file`) is what was shown in help of command
- need to parse the output maybe ? (i am not sure how this part all works yet)

**Comment by kaiuri** [comment]
@jukefr, I've created an `autocommand` for formatting files with Deno on my `init.lua` a while ago, it might be of help to you:

```lua
command('DenoFormat', function()
    local ft = vim.o.filetype
    local filename = vim.api.nvim_buf_get_name(0)
    local supported_ft = {
        ts = 'typescript',
        tsx = 'typescriptreact',
        json = 'json',
        jsonc = 'jsonc',
    }
    for stdin_type, v in pairs(supported_ft) do
        if v == ft then
            vim.cmd(string.format('silent !deno fmt --ext %s %s', stdin_type, filename))
        end
    end
end, {})
```

**Comment by sigmaSd** [comment]
deno lsp already does linting and formatting. denols and coc-deno both uses this.

**Comment by kaiuri** [comment]
@sigmaSd i think this is for cases were the user doesn't use a **lsp** client

**Comment by jose-elias-alvarez** [comment]
null-ls is fundamentally a compromise between external non-LSP tooling and LSP functionality in Neovim, so if an LSP option exists, that's always going to be the best, both from a user perspective and in terms of keeping the project maintainable. 

If there's a compelling reason not to use the LSP client, I'm happy to revisit this, but I'm going to close it for now.
