### ISSUE TITLE
attempt to call field 'os_environ' (a nil value)

### ISSUE THREAD

**Issue by dhleong** [jose-elias-alvarez/null-ls.nvim#945]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.6.1

### Operating System

Ubuntu 18.04

### Minimal config

```lua
require 'null_ls'.setup {
  sources = {
    require 'null_ls'.builtins.diagnostics.eslint.with({
      env = { ANY_VAR = 'value' },
    })
  }
}
```

### Steps to reproduce

Just open any file that would use the linter with custom env vars

### Expected behavior

It should work and pass the env vars to the linter

### Actual behavior

An error occurs:

```
|| [null-ls] [WARN  15:42:40] ...nfig/nvim/bundle/null-ls.nvim/lua/null-ls/generators.lua:78: failed to run generator: ...rd/.config/nvim/bundle/null-ls.nvim/lua/null-ls/loop.lua:33: attempt to call field 'os_environ' (a nil value)
```

### Debug log

```
[WARN  Fri Jul  8 15:41:38 2022] /home/discord/git/null-ls.nvim/lua/null-ls/generators.lua:78: failed to run generator: /home/discord/git/null-ls.nvim/lua/null-ls/loop.lua:33: attempt to call field 'os_environ' (a nil value)
```

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

Is it safe to just use an empty table to start with `os_environ` doesn't exist?

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
null-ls doesn't officially support versions below the current stable version (0.7.2 as of now) so I'd recommend upgrading. [This issue](https://github.com/neovim/neovim/issues/18393) indicates that `os_environ` should be available in recent versions of Neovim.

Interestingly, I found that [paq.nvim](https://github.com/savq/paq-nvim/blob/b3c7d047e29792f306626bf87430a2b0c92e5aad/lua/paq.lua#L18) uses `vim.fn.environ` as a fallback for versions before 0.6... which implies that 0.6 should have support, too, so I'm not sure what's going on in your case. Either way, I would try upgrading first.

**Comment by dhleong** [comment]
https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable doesn't have 0.7 yet but the unstable ppa (0.8) is fine. I guess we can close this
