### ISSUE TITLE
Is format working with windows 10

### ISSUE THREAD

**Issue by maxxnino** [jose-elias-alvarez/null-ls.nvim#95]
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.5.0 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Steps to reproduce

https://user-images.githubusercontent.com/34153891/128631976-8ec3ea29-b983-49d0-a76f-f690658dbc3e.mp4

### Expected behavior

`:w` or using `<cmd>lua vim.lsp.buf.formatting()<cr>` will format the file. I have prettier installed global. Can use `prettier -w file.js` to manually format. Old neoformat is working ok. The same with stylua and yapf too

### Actual behavior

It not formatting

### Debug log
`:message`
![message](https://user-images.githubusercontent.com/34153891/128631988-0d74f721-39f6-4e2b-9870-903bff5cf6d2.jpg)

`:LspInfo`
![lspinfo](https://user-images.githubusercontent.com/34153891/128632295-bce55c89-7cc9-46bb-b307-a405ab479307.jpg)

### Help

No

**Comment by jose-elias-alvarez** [comment]
This is really tricky for me to debug, since I know nothing about Windows and don't currently have access to a Windows setup. Based on your description and debug output, it looks like your config is fine, but something is going wrong with either spawning the process or capturing the output of the process.

Could you first tell me what you get when you run `:echo executable("prettier")` in Neovim? That'll let us rule out `$PATH`-related issues.

If that output is fine (it should be `1`), could you try using [this branch](https://github.com/jose-elias-alvarez/null-ls.nvim/tree/fix-windows-path) of the plugin and see if that makes a difference? The fix there is an educated guess based on [this nvim-lspconfig issue](https://github.com/neovim/neovim/issues/13911).

If that doesn't work, there's not much more I can do for now unless you or another Windows user is willing to dig around in the code and figure out what's going on.

**Comment by maxxnino** [comment]
The output is `1` and i tried fix-window branch. Sadly, It doesn't work :(. The language server like tsserver, i nedd to add `.cmd` to the end config path `typescript-language-server.cmd`. But i think this is not the case, because stylua is and executable, and it isn't working either

**Comment by maxxnino** [comment]
Actually, I got new message error from prettier, The stylua is the same as above
![Untitled](https://user-images.githubusercontent.com/34153891/128633222-a2478c18-cae3-4a20-9393-6c214f08fa74.jpg)

**Comment by jose-elias-alvarez** [comment]
Hmm, I see. It looks like we may be dealing with multiple issues at the same time, interestingly. I just pushed an update to the fix-windows branch to add some additional debug logs – could you try updating and post the output again?

**Comment by maxxnino** [comment]
It's show less that before, only the init stuff and sometime it crash my nvim. and I scroll the mouse wheel it's show some garbage to my terminal too
![image](https://user-images.githubusercontent.com/34153891/128633672-bac367f0-3718-4509-9e43-d9254aed5e00.png)

**Comment by jose-elias-alvarez** [comment]
That's really strange! The only change in the latest commit was to add some logs, so I can't imagine how that alone is crashing Neovim. One thing that I see is that your file contains some Unicode characters, which [can have issues with Neovim](https://github.com/neovim/neovim/issues/15128). Could you try formatting a file that doesn't contain them and see if that makes a difference?

**Comment by maxxnino** [comment]
You can check my [file](https://github.com/maxxnino/tree-sitter-zig/blob/main/grammar.js) here, i think it don't contain any unicode character in it

**Comment by jose-elias-alvarez** [comment]
Yep, I saw your ligatures and thought they were Unicode characters, but I can see that they're not. I'm able to format the file without any issues on my end, so something else is going on. 

Thanks for your patience – I'm going to ask in the Neovim Matrix chat to see if anybody has any experience dealing with Windows. but other than that, until I have access to a Windows computer again, we'll have to depend on someone seeing this issue and pitching in.

**Comment by maxxnino** [comment]
Thank you, hope to see some good new in the future

**Comment by Dulanjala007** [comment]
this happened to me as well. the issue was some garbage characters were added to the beginning of the input/stdin which stops prettier and others from working correctly.
I tried replacing uv.spawn with plenary.nvim job that fixed the issue...
also needed to add the ".cmd" to the end of the cmd.

**Comment by jose-elias-alvarez** [comment]
@Dulanjala007 Could you give me some more information about your changes? As far as I can tell Plenary doesn't do anything special with `stdin`, but that's very promising. I think we can take care of the second issue by using `vim.fn.exepath` too.

**Comment by Dulanjala007** [comment]
@jose-elias-alvarez found it... 😊

in loop.lua,

line 86
    `local stdin = uv.new_pipe(true)`    =>   `local stdin = uv.new_pipe(false)`

line 111
     `handle = uv.spawn(cmd,`   =>  `handle = uv.spawn(vim.fn.exepath(cmd), `

**Comment by jose-elias-alvarez** [comment]
@Dulanjala007 Great, thank you so much for looking into this! The changes are simple and don't seem to make any difference on Unix.

 @maxxnino I just pushed the changes to the `fix-windows-path` branch, so when you get a chance could you check if that fixes it for you too?

**Comment by Dulanjala007** [comment]
@jose-elias-alvarez yeah! `fix-windows-path` branch work...

**Comment by maxxnino** [comment]
I tested with yafp, stylua, prettier. it's working flawlessly. Let's go baby!, You are the best

**Comment by jose-elias-alvarez** [comment]
Thanks for confirming! I've just merged the fix, so I'm going to close this for now. Thank you again for figuring this out, @Dulanjala007!
