### ISSUE TITLE
buildifier builtin formatter overwriting invalid BUILD file with garbage

### ISSUE THREAD

**Issue by alexcepoi** [jose-elias-alvarez/null-ls.nvim#955]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.7.2

### Operating System

Debian

### Minimal config

```
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir
if on_windows then
    temp_dir = vim.loop.os_getenv("TEMP")
else
    temp_dir = "/tmp"
end

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = { null_ls.builtins.formatting.buildifier },
        debug = true,
    })
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "jose-elias-alvarez/null-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end
```

### Steps to reproduce

Download BUILD file: https://gist.github.com/alexcepoi/57067117afc6080ebc9e44ae3deaa986

$ vi -u minimal_init.lua BUILD
$ :PackerCompile
$ :lua vim.lsp.buf.formatting_sync()

### Expected behavior

Contents remain unchanged and an error message is pasted presented to the user.

### Actual behavior

Contents of the file are replaced with (<snip> is the absolute directory path):

<snip>/BUILD # reformat

### Debug log

[TRACE Sun 17 Jul 2022 23:26:03 UTC] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_FORMATTING
[DEBUG Sun 17 Jul 2022 23:26:03 UTC] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:346: spawning command "buildifier" at <snip> with args { "-path=<snip>/BUILD" }
[TRACE Sun 17 Jul 2022 23:26:04 UTC] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:217: error output: <snip>/BUILD:2:18: unexpected newline in string

[TRACE Sun 17 Jul 2022 23:26:04 UTC] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:218: output: <snip>/BUILD # reformat

[TRACE Sun 17 Jul 2022 23:26:04 UTC] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:222: ignoring stderr due to generator options

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
Based on the log, I think I see what's happening, but I can't replicate this on my end. When I run `buildifier` on the sample file, I get the same error output, but the formatter's output is empty, so nothing happens (and it works correctly when the file is fixed). 

Not sure what's going on - perhaps a version incompatibility? I installed the command using [the method recommended here](https://github.com/bazelbuild/buildtools/blob/master/buildifier/README.md#setup).

**Comment by alexcepoi** [comment]
Yep, probably an odd binary version.

Installed per your instructions and it works just fine.
