### ISSUE TITLE
Prettier and Prettierd timed out, formatting stuck at the begining.

### ISSUE THREAD

**Issue by patya3** [jose-elias-alvarez/null-ls.nvim#966]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.7.2

### Operating System

Windows 10 pro

### Minimal config

local present, null_ls = pcall(require, "null-ls")

if not present then
   return
end

local b = null_ls.builtins

local sources = {

   b.formatting.prettier.with({
     prefer_local = "node_modules/.bin",
     timeout = 15000,
   }),
}

null_ls.setup {
   debug = true,
   sources = sources,
}

### Steps to reproduce

Setup prettier or prettierd with or without config, with global or local config.

### Expected behavior

Null-ls formats ts document on **:lua vim.lsp.buf.formattin()**

### Actual behavior

Null-ls stuck at formating.
All global executable found, but when running it, the formating stucks at the begining, and timeout after the timeout duration i set in the config.

:checkhealth display that prettier is OK

### Debug log

[TRACE 7/21/2022 10:13:17 PM] ...site\pack\packer\opt\null-ls.nvim/lua/null-ls/client.lua:106: starting null-ls client
[TRACE 7/21/2022 10:13:17 PM] ...ta\site\pack\packer\opt\null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method initialize
[DEBUG 7/21/2022 10:13:17 PM] ...site\pack\packer\opt\null-ls.nvim/lua/null-ls/client.lua:161: unable to notify client for method textDocument/didOpen (client not active): {
  textDocument = {
    uri = "file:///D:/........../src/app.ts"
  }
}
[TRACE 7/21/2022 10:13:17 PM] ...ta\site\pack\packer\opt\null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method initialized
[TRACE 7/21/2022 10:13:17 PM] ...ta\site\pack\packer\opt\null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didOpen
[TRACE 7/21/2022 10:13:17 PM] ...\pack\packer\opt\null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG 7/21/2022 10:13:17 PM] ...\pack\packer\opt\null-ls.nvim/lua/null-ls/generators.lua:24: no generators available
[TRACE 7/21/2022 10:13:19 PM] ...ta\site\pack\packer\opt\null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method textDocument/formatting
[TRACE 7/21/2022 10:13:19 PM] ...\pack\packer\opt\null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_FORMATTING
[DEBUG 7/21/2022 10:13:19 PM] ...pt\null-ls.nvim/lua/null-ls/helpers/command_resolver.lua:35: attempting to find local executable node_modules/.bin\prettier
[TRACE 7/21/2022 10:13:19 PM] ...pt\null-ls.nvim/lua/null-ls/helpers/command_resolver.lua:39: resolved dynamic command for [node_modules/.bin\prettier] with cwd=D:\............-service
[DEBUG 7/21/2022 10:13:19 PM] ...t\null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:286: Using dynamic command for [prettier], got: "D:\\..........\\node_modules\\.bin\\prettier"
[DEBUG 7/21/2022 10:13:19 PM] ...t\null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:346: spawning command "D:\\.......\\node_modules\\.bin\\prettier" at D:\..........-service with args { "--stdin-filepath", "D:\..........\\src\\app.ts" }
[DEBUG 7/21/2022 10:13:34 PM] ...a\site\pack\packer\opt\null-ls.nvim/lua/null-ls/loop.lua:154: command [D:\.......\node_modules/.bin\prettier] timed out after 15000 ms

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
What happens when you run the local executable from the command line using the same arguments as null-ls? For example (I see you're on Windows so I have no idea how to adapt this, but hopefully it illustrates the idea):

```sh
cat src/app.ts | ./node_modules/.bin/prettier --stdin-filepath src/app.ts
```

**Comment by patya3** [comment]
Everything is working and fine outside null-ls, even null-ls find the executables at the right place whether the exec is local or global. But when starts formatting the file the exec just time out without any error and progress.

**Comment by jose-elias-alvarez** [comment]
Hard to say, no issues on my end with `prettier` or `prettierd`. Have you tried raising the timeout?

**Comment by patya3** [comment]
It just started working after some plugin updates! Windows things...

Thanks for the amazing plugin it is fast and snappy even in Windows powershell!
