### ISSUE TITLE
log vim.inspect-ed object on demand

### ISSUE THREAD

**Issue by haolian9** [jose-elias-alvarez/null-ls.nvim#990]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

```
logger:trace(vim.inspect(obj))
logger:debug(string.format(..., vim.inspect(obj))
```
those usage can be seen everywhere, it's a avoidable overhead when logger:level is higher than trace or debug.

i failed to find a way to implement a custom format option for string.format, let's say `%r` for repr or `%i` for inspect, so that we can do something like this: `logger:debug("hello world! %i", obj_to_be_inspected)`

IMO, another simple implementation would be making logger:{trace,debug,...}'s first param be `function|string` type, when it's function

**Comment by haolian9** [comment]
i think plenary.log might be a good solution.

**Comment by jose-elias-alvarez** [comment]
I think the simplest solution would be to allow passing in a function that returns a string. That would add the least amount of complexity, and it would be the most straightforward option to work with, in my opinion. 

Do we have any idea how much overhead this actually adds, though? There's only a few places where we use `vim.inspect`, and the only one that's called frequently is [when we log diagnostic results](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/9caa5d6d19e4d0bc8782c2a75988af0c20eed59e/lua/null-ls/diagnostics.lua#L170). I tried to use `vim.loop.now()` to measure how long that particular `vim.inspect` call took, but I had to create thousands of diagnostics before it went over 1ms (at which point the editor itself became too laggy to work with). 

> i think plenary.log might be a good solution.

`plenary.log` theoretically supports "lazy logging" by passing in a function, but the last time I tried it, it didn't work at all (see #355 for discussion). Looking at [the commit history](https://github.com/nvim-lua/plenary.nvim/commits/master/lua/plenary/log.lua), it doesn't look like there's been any fixes either. At this point we're only using it for file logging, so if we're going to move ahead with this, we'd want to do it ourselves (it'd be just a few lines of code, anyway).

**Comment by haolian9** [comment]
well, i actually haven't do a benchmark before opening this issue, and overstated its impact, it's not `anywhere`. i should be sorry for that.

> a function that returns a string
this way is flexable enough, but i think a wrapper of string.format is good for convenience.

```lua
local function log(fmt_or_fn, ...)
  if type(fmt_or_fn) == "function" then
    msg = fmt_or_fn()
  else
    local args = {}
    for i = 1, select("#", ...) do
      local arg = select(1, ...)
      if type(arg) == "table" then
        table.insert(args, vim.inspect(arg))
      else
        table.insert(args, arg)
      end
    end
    msg = string.format(fmt_or_fn, unpack(args))
  end

  vim.notify(msg)
end

log("hello world!")
log("hello %s", "world!")
log("hello %s", { "world", "!" })
log(function()
  return "hello world!"
end)
```

**Comment by haolian9** [comment]
speak of overhead, it might not be noticed since it's just several cpu clocks and memory allocations. but it's still a waste, and cleaning it do make me happier, haha.

**Comment by jose-elias-alvarez** [comment]
The only reason I'd be against adding a wrapper is because (in my opinion) it's not immediately clear how it works without reading the implementation (especially with tables). We also don't have that many log statements in the codebase (I found 52) and don't add new ones frequently.

I agree that dumping objects that we never log is a waste and would be happy to review a PR adding "lazy logging" using functions, but I don't think this is enough of a problem to justify putting in anything more complicated than that.

**Comment by jose-elias-alvarez** [comment]
If you like, feel free to put in a PR and I can review it when I have the time!

**Comment by haolian9** [comment]
i think it's time to close this issue. i tried to learn lua's meta programming pattern several times, sadly it is too magic to me.
